### ISSUE TITLE
How to build mucommnader?

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#10]
How to build mucommnader?

the https://github.com/mucommander/mucommander/blob/master/compile.txt file seems totally outdated, as mucommander does not seem to depend on ANT anymore.

**Comment by ahadas** [comment]
Indeed, it is one of the missing things in the wiki..

Anyway, you can simply build and run mucommander using the scripts in the root folder of the repository.
Depending on the operating system you're using you can either build it using:
windows: gradle.bat buid
other: ./gradlew build
or run it using:
windows: gradle.bat run
other: ./gradlew run
