### ISSUE TITLE
[Bug] Cannot Install version 130 in debian does not recognize zst compression

### ISSUE THREAD

**Issue by jlschwartz** [mucommander/mucommander#1000]
### Description

When I try to install version 130 in Debian 11 it gives an error as it does not recognize zst compression.  

### Steps to reproduce

dpkg-deb: error: archive '/home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1

### Expected behavior

It should install in debian.

### Actual behavior

It does not install in debian 11.

### Screenshots?

dpkg-deb: error: archive '/home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/jlschwartz/Downloads/mucommander_1.3.0-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1

### muCommander version

130

### Java version

java 11

### Operating System type and version

Debian 11

**Comment by ahadas** [comment]
@jlschwartz thanks for reporting this, I've added what I wrote in https://github.com/mucommander/mucommander/issues/771#issuecomment-1627728620 as a known issue in the readme file
