### ISSUE TITLE
[Enhancement] Please make the list of hard drives sorted alphabetically

### ISSUE THREAD

**Issue by Saratxe** [mucommander/mucommander#1010]
### Description

I work with many external hard drives mounted at the same time. When I want to access a specific hard drive, I always have to search for the corresponding drive. Therefore, I would like to have the possibility to display the list of hard drives sorted alphabetically.

**Comment by ahadas** [comment]
@Saratxe on which operating system?

**Comment by Saratxe** [comment]
macOS Sonoma 14.5

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)

**Comment by Saratxe** [comment]
I can confirm this on my system, it has been fixed. Thank you!
