### ISSUE TITLE
[Bug] mucommander customizing command bar not working [Fedora]

### ISSUE THREAD

**Issue by dotbanana** [mucommander/mucommander#1020]
### Description

I installed rpm on Fedora System with Gnome through downloading from your website and installing with dnf.   
Unfortunately the customization of the command bar does not work.  
I use mucommander on other systems with Debian for example where the buttons can be arranged. 
On Fedora nothing happens. The buttons cannot be changed. 

### Steps to reproduce

Go to Customize command bar window either through Menu - View - Customize Command bar or through right click on a command bar button and choosing "Customize command bar".

### Expected behavior

Expected behaviour is that the buttons can be rearranged. 

### Actual behavior

Nothing happens when trying to rearrange buttons.  
You can see the blue line that should indicate where a button moves when releasing the mouse but it does not do it. 

### muCommander version

muCommander
Version: 1.3.0
Build date: 2023/07/08
Build number: dddabaf

### Java version

Java
Runtime version: 20.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 20.0.1+9
VM vendor: Eclipse Adoptium

### Operating System type and version

OS
Name: Linux
Version: 6.4.4-200.fc38.x86_64
Architecture: amd64

Fedora 38

**Comment by ahadas** [comment]
@dotbanana thanks for reporting this! it easily reproduced on my machine

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
