### ISSUE TITLE
UX Issue/Enhancement - Conditions for suppressing auto file/directory resync of panes currently displayed

### ISSUE THREAD

**Issue by mj162** [mucommander/mucommander#1031]
#### Expected Behaviour
When any of the menus are active or the path entry text box is active:-
* Auto updating/syncing of the file browser panes is suspended until neither is active

When the path entry text box is active:-
* Keyboard accelerators are disabled

#### Actual Behaviour
When any of the menus are active or the path entry box is active:
* Auto updating/syncing of the file browser panes removes focus and destroys the state of editing of the path entry box; as a result one's typing into the path entry box has to be started over with this being particularly irksome when entering long or hard to remember paths

When the path entry box is active:-
* Keyboard accelerators may be inadvertently invoked while typing a pathlist; as a result, one can accidentally select and damage files

See for example: [zTRzTajW4j]( https://pastebin.com/ZBxevxAy)

Thanks.

**Comment by pskowronek** [comment]
@mj162 hm, that paste bin contains a link to download a gif... could you simply attach screenshots to this PR?

**Comment by mj162** [comment]
Sure, done. :)

**Comment by mj162** [comment]
![screen_recording_2023-08-07_14-42](https://github.com/mucommander/mucommander/assets/64870692/a62f0733-e437-44c8-be72-b95258c6e8bd)
Thanks for continuing to maintain and improve MuCommander -- I use it on Solaris/SPARC and Linux/X64 every day.

Attached is a GIF showing the issue:  In the RHS, the user is trying to type-in a long path `/media/home/michael/doc/sysadm/config` but unsuccessfully, because the auto file/directory resync runs resetting the pathlist box with the directory the user is still in.  The change requests that you suspend the auto file/directory re-synchroniser while the pathlist box is either selected (the cursor is in the pathlist box), or the pathlist in the pathlist box has changed owing to user input.

The benefit to users of this suggested improvement is better usability, particularly when running over remote ssh -X sessions.

Thank you.

**Comment by mj162** [comment]
[Thanks for the head-up that GitHub supported inline GIF animations]

**Comment by ShayArtzi** [comment]
@mj162 TBH I'm having hard time understanding the scenario you are describing. Could you please describe exactly what you are doing step by step?

**Comment by ahadas** [comment]
> #### Actual Behaviour
> When any of the menus are active or the path entry box is active:
> 
> * Auto updating/syncing of the file browser panes removes focus and destroys the state of editing of the path entry box; as a result one's typing into the path entry box has to be started over with this being particularly irksome when entering long or hard to remember paths

I understand this part, you can reproduce it by:
1. trigger the following: `sleep 5; touch <presented-folder-path>/newfile`
2. in muCommander, start typing something in the location textfield
3. after ~5 sec, a change is detected and when we update the folder panel, the text is the location textfield is overridden with the path of the presented folder

so the request here is not to refresh the folder panel when menu items or the location textfield is active

> When the path entry box is active:-
> 
> * Keyboard accelerators may be inadvertently invoked while typing a pathlist; as a result, one can accidentally select and damage files

however, this part is not clear to me - @mj162 can you please give an example of a keyboard shortcut that the issue you refer to is reproduced with?

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
