### ISSUE TITLE
[Bug] ToolBar and CommandBar shortcut description not updated after change in Preferences

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

When changing shortcut for an action that is either present in ToolBar or CommandBar their description is not updated in the UI (the shortcut works, so it is only visual aspect).

### Steps to reproduce

- Go to Preferences and change shortcut for Copy action
- Apply the change

### Expected behavior

- the action description should be updated in the UI

### Actual behavior

- In Command Bar copy button still shows Copy [F5] - the same applies to an action from tool bar.

### muCommander version

1.3.0 and the current master

### Java version

doesn't matter

### Operating System type and version

macOS Catalina

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
