### ISSUE TITLE
[Bug] Error message when running gradlew  run

### ISSUE THREAD

**Issue by fr43nk** [mucommander/mucommander#1052]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I want du start the mucommander from source and started the command

`./gradlew run`

This shows an error message

```bash
> Task :createOsgiRuntime FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createOsgiRuntime'.
> Invalid syntax for version: 4a450b0
```

I have installed jdk 20 with the provided installer. 

### Steps to reproduce

- Clone the repository
- run `./gradlew run`

### Expected behavior

It should finish without an error

### Actual behavior

Error message
```bash
> Task :createOsgiRuntime FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createOsgiRuntime'.
> Invalid syntax for version: 4a450b0
```

### muCommander version

Latest from github

### Java version

javac 20.0.2

### Operating System type and version

Mac OS 14.0
MacBookPro M1Pro (arm64)

**Comment by pskowronek** [comment]
`pkill -f GradleDaemon -9` and re-try?

**Comment by fr43nk** [comment]
I found somewhere:

`./gradlew clean creOsgi`

This helped to resolve the issue.
