### ISSUE TITLE
Error while executing DMG job

### ISSUE THREAD

**Issue by fr43nk** [mucommander/mucommander#1053]
Hi,

on my Mac I tried to execute the `./gradlew dmg` command.
But this one throws an error with the following message:

```bash
> Task :macAppImage FAILED
java.nio.file.NoSuchFileException: 
mucommander/build/muCommander.app/Contents/runtime/Contents/Home/lib

FAILURE: Build failed with an exception.
```

My Platform is as follows:
- MacOS 14.0
- M1 Pro CPU
- Java 20.0.2
- code base latest clone from github

**Comment by pskowronek** [comment]
does `./gradlew clean dmg` help to solve the problem?

**Comment by pskowronek** [comment]
Try: `./gradlew clean dmg --info` or `--stacktrace`

**Comment by pskowronek** [comment]
and you may try `git submodule update --remote` (`jre` directory is submodule)

**Comment by ahadas** [comment]
closing due to insufficient information
