### ISSUE TITLE
v0.9.2 - damaged on MacOS

### ISSUE THREAD

**Issue by dmitriynet** [mucommander/mucommander#106]
After update -  v0.9.2 on startup said "muCommander damaged and cannot be opened"

**Comment by alexey-lysiuk** [comment]
Check #64 or any related issue closed recently.

**Comment by poetcsw** [comment]
Same - and tried everything I could think to try. 

Java is latest Oracle release, attributes for gatekeeper applied. Annoying - shouldn't be so difficult to use the Java apps, but it is.
