### ISSUE TITLE
Can't run DMG: muCommander is corrupted and cannot be opened.

### ISSUE THREAD

**Issue by VincentVolmer** [mucommander/mucommander#1060]
This morning I downloaded and installed muCommander 1.3.0-1 but I can't run it. When I do, I get the error: muCommander is corrupted and cannot be opened. Tried github and muCommander website, browser is Firefox.

macOS Catalina 10.15.7

btw 
muCommander-1.2.0-2.dmg runs fine. Went back to this version.

**Comment by pskowronek** [comment]
Pls search closed issues. Thanks!

**Comment by pskowronek** [comment]
Pls re-open if you think this is a different issue.
