### ISSUE TITLE
[Bug] sftp: location bar does not use ssh key

### ISSUE THREAD

**Issue by weberjn** [mucommander/mucommander#1062]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

If you are connected to a server with an ssh key, and append a subdirectory in the location bar, muCommander shows a login prompt. Instead it should just change to the subdirectory.

### Steps to reproduce

append a subdirectory in the location bar and press enter

### Expected behavior

enter sub dir

### Actual behavior

show login prompt

### muCommander version

Version: 1.3.0 (Portable)
Build date: 2023/07/08
Build number: dddabaf

### Java version

Runtime version: 11.0.18

### Operating System type and version

Windows 11

**Comment by ShayArtzi** [comment]
I was able to reproduce that and I'm working on a PR to address the issue, I'll post it here once it is ready for review

**Comment by ShayArtzi** [comment]
PR: https://github.com/mucommander/mucommander/pull/1104

**Comment by ahadas** [comment]
@ShayArtzi why do we need special handling for SFTP with a private key? I would expect that we use the credential for the remote server also in case of password authentication and also for other protocol, no?

**Comment by ShayArtzi** [comment]
seems to me you are 100% right but I since I'm not super familiar with all of the different use cases I figured I'd minimize the change. I'm actually not sure if we have more protocols that support PK authentication, but LMK if you want me to take out the protocol check

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
