### ISSUE TITLE
Can't write to application content folder

### ISSUE THREAD

**Issue by prounlocks** [mucommander/mucommander#1077]
Hello! I just want to replace one file inside of one app container, but MU commander doesnt allow to do this and didnt ask to enter password. Is it possible to fix?

**Comment by pskowronek** [comment]
More details please - ideally the ones asked for: https://github.com/mucommander/mucommander/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml

**Comment by ahadas** [comment]
closing due to insufficient information
