### ISSUE TITLE
Foregoing submodules in git repository

### ISSUE THREAD

**Issue by holograph** [mucommander/mucommander#11]
Honestly, they're just unnecessarily complicated and I've run into several issues working with them. For example, I had to fork `mucommander-commons-file` to its own fork, and now I can't issue pull requests back to master without overriding the submodule URL, which is obviously not what I meant to do.

Is there any reason not to have these as straightforward subdirectories (+subprojects in Gradle)?

**Comment by ahadas** [comment]
No, I agree that having them as subdirectories and subprojects in Gradle is better

**Comment by ahadas** [comment]
The submodules have been merged as subdirectories in the 'mucommander' repository

**Comment by holograph** [comment]
:+1:
