### ISSUE TITLE
Missing "DATE" stuff in batch renaming?

### ISSUE THREAD

**Issue by soder82** [mucommander/mucommander#111]
I'm on 0.9.2 and I think there in prev. versions was options in batch renaming for adding date (Day, Month, Year). It's not there for me now. It still works, but I can't see  the info about adding D, M and Y...

/Söder

**Comment by soder82** [comment]
[http://imgur.com/Mm0sI1b](url)

**Comment by soder82** [comment]
What do you mean with a "PR"?

**Comment by ahadas** [comment]
@soder82  Pull Request, basically to submit a patch that adds the missing buttons.

**Comment by soder82** [comment]
Aha, I can't do any code at all. I'm just a heavy consumer. ;)

Den ons 12 dec. 2018 15:06 skrev Arik Hadas <notifications@github.com>:

**Comment by ahadas** [comment]
@soder82 Ah ok :)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
