### ISSUE TITLE
MacOS warning

### ISSUE THREAD

**Issue by paulvi** [mucommander/mucommander#113]
Can the Mac version be somehow signed?
<img width="601" alt="screen shot 2017-07-04 at 7 00 33 pm" src="https://user-images.githubusercontent.com/1614482/27827722-44659f7c-60eb-11e7-9ac0-d31fcbaa43be.png">

**Comment by thomasuebel** [comment]
I think becoming an identified Apple developer to get a certificate to sign your application, you'd need to join Apple's Developer Programme for about $99 a year. It's not impossible, but I assume since this is an open source application, no one's going to pay Apple to do this.

Do you have problem actually installing the application, or is the notification just a nuisance to you? Because I think there are ways installing an unsigned application with a Mac.

**Comment by paulvi** [comment]
well, I played extra secure, and decided not to change OS settings, and not to install the application.

Besides, I don't know where to configure this.

Maybe README should warn about this aspect and ask for donation.

**Comment by thomasuebel** [comment]
Hi @paulvi,

I don't have a make, so I can't verify it. Would you be willing to help out? I need to verify:

1. The application can be opened by "control-clicking". So, holding CTRL and clicking to bring up the context menu and then selecting "open" should allow opening the application.

2. Changing the security settings on your mac to allow installation of unsigned applications. 
- Click the apple icon on your desktop,
- Select "System Preferences"
- Next open "Security & Privacy"
- Click the padlock symbol and authenticate to be able to make changes
- Change "Allow applications downloaded from:" to "Anywhere" and confirm the change

If either change works, I think we could put that information in the Readme for Mac Users.
What do you think?

**Comment by paulvi** [comment]
Oh, actually the first is better, just open once from browsing Application.

<img width="488" alt="screen shot 2017-07-14 at 2 00 20 pm" src="https://user-images.githubusercontent.com/1614482/28200191-1bf530b6-689d-11e7-966e-f87341d25ebf.png">

Second is riskier

<img width="673" alt="screen shot 2017-07-14 at 1 59 00 pm" src="https://user-images.githubusercontent.com/1614482/28200196-26a12f10-689d-11e7-80cb-027913aab419.png">

Yes, this warning and 2 choices should be visible for users.


Also you don't need to ask for donation, if you find somebody who already is Apple's Developer Programme member. The same readme would be nice place to invite.
