### ISSUE TITLE
[Question] About the internal text editor

### ISSUE THREAD

**Issue by iahung3** [mucommander/mucommander#1134]
Is it a stripped down version of JEdit?

**Comment by pskowronek** [comment]
_Just an overall kind remark: can you repeat bug titles into issues' descriptions elaborating a little more? It is really hard to read when going thru email notifications._

Text editor & viewer are in-house implementations, both use https://github.com/bobbylight/RSyntaxTextArea for syntax highlighting etc.

**Comment by iahung3** [comment]
> Text editor & viewer are in-house implementations, both use https://github.com/bobbylight/RSyntaxTextArea for syntax highlighting etc.

It looks strikingly similar to JEdit.
