### ISSUE TITLE
RFE: Add a solarized dark/light theme to muCommander

### ISSUE THREAD

**Issue by thomasuebel** [mucommander/mucommander#114]
The solarized theme by Ethan Schoonover is already found in many tools developers use on a daily basis. While working late at night the colors of Solarized Dark are a lot easier on the eyes and at day the inverted Solarized Light colors are a soothing experience, yet are easy to read.

As a tool, muCommander could gain a lot by providing this more modern theme. 
The color scheme, and hex codes can be found at http://ethanschoonover.com/solarized. Maybe also an application specific repository can be opened at https://github.com/altercation/solarized.

**Comment by ahadas** [comment]
+1
Nice idea!
Would you like to implement it?

**Comment by thomasuebel** [comment]
Yeah, I'd give it a try.

**Comment by ahadas** [comment]
👍

**Comment by sirolf2009** [comment]
I've started a solarized dark theme. The panels are colored, but the toolbars aren't: https://gist.github.com/sirolf2009/196803ae2ede270491c2148b2a7a925c

**Comment by ahadas** [comment]
@sirolf2009 thanks for this contribution! could you please check it on the master branch?

**Comment by sirolf2009** [comment]
Sure, I'll make a light version as well and I'll try and upload them this weekend
