### ISSUE TITLE
[Enhancement]  Show the items of all subfolders

### ISSUE THREAD

**Issue by Pavel00x** [mucommander/mucommander#1147]
### Description

Hello,
I have a main folder and several subfolders in it.
Is it possible to show the items of all subfolders please?
Without displaying those subfolders.
Thank you

**Comment by ahadas** [comment]
@Pavel00x yes, it's possible to achieve this using file search: search for all files (File names = `*`), within a certain folder (by specifying the path to that folder in "Search path"), and select "Search in subfolders" and deselect "Search for folders"
