### ISSUE TITLE
Add FISH protocol for easily connecting to remote NIX servers

### ISSUE THREAD

**Issue by BobbyTBS** [mucommander/mucommander#115]
The FISH protocol (FIles transferred over SHell) allows the user to connect to a remote Linux/Mac/Unix server via SSH, even when the server doesn't enable SFTP, SCP, or Samba shares.

It was originally developed for Midnight Commander and has also been implemented in KDE's Krusader twin panel file manager

As Krusader does not yet install on the latest Mac OS, and no other Mac-based twin panel file manager (that I can find) supports this protocol, I think it will be a useful addition to the mucommander toolkit.

As I understand, it works by opening a SSH session and uploading a small Perl program to handle file operations. More information can be found below:

https://github.com/KDE/kio-extras/tree/master/fish

https://techbase.kde.org/Development/Tutorials/Debugging/Debugging_IOSlaves/Debugging_kio_fish

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
