### ISSUE TITLE
[Bug] Cannot build mucommander on Mac with Apple silicon

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I cannot build muCommander on my Mac with Apple silicon.

### Steps to reproduce

In terminal.app, enter the following command:

`git clone --recurse-submodules git@github.com:mucommander/mucommander.git && cd mucommander && ./gradlew dmg -Parch=aarch64`

### Expected behavior

mucommander.dmg will be built.

### Actual behavior

mucommander.dmg will not be built.

See build.log for error message.

[build.log](https://github.com/mucommander/mucommander/files/15141543/build.log)

### muCommander version

b3e3855c111e9819ac81c9a2e65295175afe2d71

### Java version

```
% java --version     
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment Homebrew (build 21.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.2, mixed mode, sharing)
```

### Operating System type and version

Name: Mac OS X
Version: 14.4.1
Architecture: aarch64

### Relevant log output

```shell
see build.log
```

**Comment by ahadas** [comment]
yeah, that's because of the work-in-progress to sign the dmg also as part of the nightly build

**Comment by ahadas** [comment]
> @ahadas, It still doesn't work.
> 
> [build.log](https://github.com/mucommander/mucommander/files/15142603/build.log)

ok, so you'll need to drop [two lines from the build.gradle file](https://github.com/mucommander/mucommander/blob/master/build.gradle#L420-L421) in order to produce an unsigned dmg

**Comment by ahadas** [comment]
> @ahadas, It still doesn't work.
> 
> [build.log](https://github.com/mucommander/mucommander/files/15143065/build.log)

@Andreas0602 did you remove the last characters from the line before (comma and slash)?

**Comment by ahadas** [comment]
> > @Andreas0602 did you remove the last characters from the line before (comma and slash)?
> 
> @ahadas, No, but I did it just now, and it still doesn't work.
> 
> [build.log](https://github.com/mucommander/mucommander/files/15143210/build.log)

it looks like you're not using the latest code since the 'dmg' task no longer signs the dmg, I believe that once you'll rebase you will be able to create an unsigned dmg locally. but why do you create a dmg locally in the first place? you can install the dmg from the latest [nightly build](https://github.com/mucommander/mucommander/actions/workflows/nightly.yml) instead

**Comment by ahadas** [comment]
> > > @Andreas0602 did you remove the last characters from the line before (comma and slash)?
> > 
> > 
> > @ahadas, No, but I did it just now, and it still doesn't work.
> > [build.log](https://github.com/mucommander/mucommander/files/15143210/build.log)
> 
> it looks like you're not using the latest code since the 'dmg' task no longer signs the dmg, I believe that once you'll rebase you will be able to create an unsigned dmg locally

actually, it could be that you're using the latest code but more advanced version of Java (later than 18) and that's why you see that issue, I switched the nightly build action to Java 18 as a temporary workaround..

**Comment by ahadas** [comment]
> Yes, I have Java 21 installed on my machine. (I wrote that already in my initial bug report.)

ack, I removed my comment about that because I looked at it again and I don't see why `codesign` would be called at all..

> Yes, the nightly builds are fine

thanks for the confirmation!

> (by the way, you need to update the link on the mucommander home page)

yeah, will do

>, but I would also like to be able to build from a branch. But if it's too much work for you to support this, it's also okay. Don't worry.

I'll look at it but I'm still changing that part, so once it stabilizes

**Comment by ahadas** [comment]
> > Yes, I have Java 21 installed on my machine. (I wrote that already in my initial bug report.)
> 
> ack, I removed my comment about that because I looked at it again and I don't see why `codesign` would be called at all..

ok, it reproduces on my machine with Java 21, I'm getting:
```bash
> Task :dmg FAILED
java.io.IOException: Command [/usr/bin/codesign, -s, -, -vvvv, --force, /var/folders/1j/n6gk9yxx66n6cb8ccrsz4t6c0000gn/T/jdk.jpackage2638180645781310320/images/image-8809667923087310463/muCommander.app] exited with 1 code
```

it is similar to what I saw few days ago - that Java missed passing the `--deep` argument to `codesign` so it fails on signing the app folder. we can use this issue for tracking this issue but it will take some time for me to get to this - in the meantime, Java 18 (or lower I suppose) is required for creating a dmg

> > (by the way, you need to update the link on the mucommander home page)
> 
> yeah, will do

[done](https://github.com/mucommander/mucommander.github.io/pull/17)
