### ISSUE TITLE
[Bug] Open With - disappeared icons

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1162]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Open With context menu had icons, but in 1.3.0 and 1.4.0 they don't show up anymore.

Might be related to recent changes in macOS?

### Steps to reproduce

Go to a file, right click on it, in menu choose Open With.

### Expected behavior

Something like this (this is screenshot from #917): 

![obraz](https://github.com/mucommander/mucommander/assets/360665/6db26994-7a50-49b1-8fd6-61fbc92c02dd)

### Actual behavior

Normally icons should appear for each app, but they don't.

![obraz](https://github.com/mucommander/mucommander/assets/360665/4f10ca30-83d9-4991-9e48-bfa3131d854d)

### Screenshots?

Above.

### muCommander version

1.4.0 & 1.3.0

### Java version

23-internal & 20

### Operating System type and version

Ventura 13.6.6

**Comment by pskowronek** [comment]
Might be a problem with my OCLP Ventura - apparently `mdfind` (used to get path for an app) is not cooperating...

**Comment by ahadas** [comment]
yeah, it also works well for me with macOS Monterey (12.7.4)

**Comment by pskowronek** [comment]
Ok, found it. `mdfind` is yet another command that requires spotlight to be enabled :(

To enable spotlight run this: `sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist`

Closing the issue, will try to find alternative for `mdfind` in the meantime.

**Comment by pskowronek** [comment]
FYI, trying to convince authors of `duti` to implement a nice thing that would help muC :)
