### ISSUE TITLE
[Enhancement] Click "Name" to always sort files from A to Z

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1165]
### Description

When clicking the "Name" column header, files should be sorted in alphabetical ascending order. Currently, this does not always occur. Here's a scenario in which muCommander does not behave as desired:

1. Make sure that the files are sorted by date in descending order (topmost file is newest).
2. Click the "Name" column header.

**Desired result:** Files are sorted in alphabetical ascending order (topmost file is aaaaaa.txt).
**Actual result:** Files are sorted in alphabetical descending order (topmost file is zzzzzz.txt). Only after clicking "Name" a second time, the sort order will be as desired.

It is not good that the sort order after clicking "Name" depends on the previous sort order of "Date".

**Comment by ShayArtzi** [comment]
I can see the issue. Basically, once a sort order was established, we retain it until a reverse operation happens. Let me create a PR to address this
