### ISSUE TITLE
[Bug] Debug console should also display stack traces (if present)

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

When opening muC debug console and if error was logged with stacktrace, then no stacktrace is included.
Additionally, debug log dialog is modal (it would be better if it was not modal).

See log output for this bug: https://github.com/mucommander/mucommander/issues/1169 - in console there's only entry with no stacktrace - one needs to go to mucommander.log to get the stacktrace, it makes bug reporting harder and additional user input is required while investigating a problem.

### Steps to reproduce

Open Debug console.

### Expected behavior

- it should display also stacktraces 
- shouldn't be modal dialog, ideally you could place log console behind muC while trying to reproduce the problem

### Actual behavior

- stacktraces not displayed
- it is modal, cannot go back to muC, one needs to close the dialog

### Screenshots?

![obraz](https://github.com/mucommander/mucommander/assets/360665/af5b7772-73c0-4e08-ac90-5c757e233a07)

### muCommander version

1.4.0 (the same behavior also was in previous versions)

### Java version

N/D

### Operating System type and version

macOS Ventura

**Comment by ahadas** [comment]
Version 1.4.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.1-1)
