### ISSUE TITLE
[Bug] 'Report a bug' in Menu sometimes has icon, most often it doesn't

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Report a bug' in Menu sometimes has icon, most often it doesn't.

Very strange :)

### Steps to reproduce

Open muCommander and navigate to Menu -> Help - observe whether 'Rpeort a bug' has an icon.
Re-launch muCommander a couple of times - sometimes it has it, sometimes not - most often it doesn't have it.

### Expected behavior

Consistent display of that icon.

### Actual behavior

Randomness.

### Screenshots?

It is when it has it:
![mc_icon_bug](https://github.com/mucommander/mucommander/assets/360665/81bd4a0f-a3c2-4e27-9f61-28d87c605c6a)

### muCommander version

1.4.0, in 1.3.0 I don't see this icon either.

### Java version

as provided by DMG

### Operating System type and version

macOS Ventura (OCLP)

**Comment by pskowronek** [comment]
This is caused by Menu item and Tool bar items being loaded in simultaneously in parallel here:
https://github.com/mucommander/mucommander/blob/eb26d7a445a71d81125d66b8cfbc806ae1f7bf2e/mucommander-core/src/main/java/com/mucommander/ui/main/MainFrame.java#L199-L210

The following line nullifies icons in Menu, but apparently it can be overridden by Toolbar loading thread: https://github.com/mucommander/mucommander/blob/eb26d7a445a71d81125d66b8cfbc806ae1f7bf2e/mucommander-commons-util/src/main/java/com/mucommander/commons/util/ui/helper/MenuToolkit.java#L194
When this line is commented out, then Menu contains pretty nice icons in the menu - the question is whether such UX we would like to have:

![obraz](https://github.com/mucommander/mucommander/assets/360665/19adeb4c-dd2f-4a06-84b3-7818166b8dbb)


![obraz](https://github.com/mucommander/mucommander/assets/360665/6c42394e-f1cf-4c29-bdbe-b511f58f9cc7)

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
