### ISSUE TITLE
[Bug] Erratic behavior

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Please see the attached video.

**Bug 1 (at 00′12″ in the video):** All main menu items except "muCommander" are missing. When changing from the Downloads directory in the left pane to the root directory in the right pane, the missing menu items appear.

**Bug 2 (at 00′41″ in the video):** When switching to "Custom folder", the appearance changes undesirably from FlatLaf to CDE/Motiv. FlatLaf is unavailable.

Log file: removed

https://github.com/mucommander/mucommander/assets/79788982/bf95c09b-046c-4cc2-b4fa-591ea1503d9b

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### muCommander version

Version: 1.5.0
Build date: 2024/05/08
Build number: 54524da

### Java version

Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-0081ac197a656cdc0d88d5a5e2a0f399ee023654
VM vendor: Oracle Corporation

### Operating System type and version

Name: Mac OS X
Version: 14.4.1
Architecture: aarch64

**Comment by pskowronek** [comment]
(@Andreas0602 - that video is in terrible format, I'm having a problem watching it both in Firefox and VLC - it looks like nothing happens until you scroll and only then the video content gets updated)

**Comment by pskowronek** [comment]
> It's a mp4 file encoded with H.264 ... should be quite a common format. Anyway, I've just converted it to webm VP8 with a reduced resolution of 1920 x 1080. How about that one?
> Demo.webm

H.264 but something wasn't good in it. This one works great.

**Comment by pskowronek** [comment]
@Andreas0602 ad Bug 2 - do you reproduce that always? Is it only for Downloads or for other folders you have the same problem?

**Comment by pskowronek** [comment]
I cannot produce bug 2. Could you change log level to finest and provide logs? Maybe this will give us some hint.

**Comment by pskowronek** [comment]
ad bug 1 - I'm able to reproduce using debugger

ad bug 2 - I don't see anything obvious (you may remove te loge above now as it contains some internal IPs and names). I set the same L&F and still nothing. However, I see this in your logs:
```
2024-05-08 22:53:32.270 [WT-EventQueue-0] DEBUG com.mucommander.ui.theme.ThemeReader:934 - Unexpected start of element executable, ignoring.                     
2024-05-08 22:53:32.270 [WT-EventQueue-0] DEBUG com.mucommander.ui.theme.ThemeReader:158 - Ignoring element: normal                                              
2024-05-08 22:53:32.270 [WT-EventQueue-0] DEBUG com.mucommander.ui.theme.ThemeReader:158 - Ignoring element: selected                                            
2024-05-08 22:53:32.270 [WT-EventQueue-0] DEBUG com.mucommander.ui.theme.ThemeReader:934 - Unexpected start of element file_groups, ignoring.                    
2024-05-08 22:53:32.270 [WT-EventQueue-0] DEBUG com.mucommander.ui.theme.ThemeReader:158 - Ignoring element: group1
```

I don't see anything similar in my logs. So, I have a hunch that it might be somehow related to Custom theme you have there. Can you open theme by Edit (you may first export it and provide it here):

![obraz](https://github.com/mucommander/mucommander/assets/360665/5da772e8-d0d2-46ae-86a8-b592336176a3)

This tells me, that probably changing anything in preferences might trigger defaulting to CDE/Motif - have you checked that?

**Comment by pskowronek** [comment]
After importing your theme I can reproduce the behavior:
![obraz](https://github.com/mucommander/mucommander/assets/360665/7613b214-b88a-487f-8276-7a1f3412adad)

**Comment by pskowronek** [comment]
> After importing your theme I can reproduce the behavior:

But only once and no more :)

**Comment by ahadas** [comment]
Version 1.4.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.1-1)
