### ISSUE TITLE
muCommander often crash on my mac 10.11.6

### ISSUE THREAD

**Issue by tokist** [mucommander/mucommander#118]
Hi, thanks for muCommander product. It's most helpful.

Recently muCommander often(per 2day) crash on background.
This is a crash report.

-----------------------
Environment:
muCommander version: 0.9.2
mac book pro: memory 16GB
mac os version: 10.11.6
java version: java update 141

Error detail:
[hs_err_pid37139.zip](https://github.com/mucommander/mucommander/files/1192519/hs_err_pid37139.zip)

**Comment by mrserb** [comment]
Looks line the bug in jdk, if you have a complete steps to reproduce you can report it here: https://bugs.java.com/bugdatabase/

**Comment by tokist** [comment]
This crash not occurred after I upgraded mac os to 10.13.6 and java version to 8.151. I think this crash is resolved. Thanks a lot for your help!
