### ISSUE TITLE
[Bug] connect to server menu does not work but key [command] & [k] works on MacOS 14.4.1 (aarm64)

### ISSUE THREAD

**Issue by maiemi** [mucommander/mucommander#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Clicking the menu "goto" and "connect to server" will appear the menu but it is not possible to fill the fields.
using the key combination [command ] & [k] will appear the menu, too and here it is possible to fill the fields.
MacOS 14.4.1 (Apple Silicon, aarm64) and muCommander 1.4.0

### Steps to reproduce

start muCommander
click in the menubar on "goto"
click on "connect to server"
try to fill in the fields
=> does not work

instead of click in the menubar on "goto", use the keys [command] & [k]
try to fill in the fields
=> works fine

### Expected behavior

the fields have to be filled

### Actual behavior

The tabs (SFTP, SMB and the others) can be chosen, but the fields cannot be filled

### muCommander version

1.4.0
Location: German

### Java version

Java
Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-0081ac197a656cdc0d88d5a5e2a0f399ee023654
VM vendor: Oracle Corporation

### Operating System type and version

OS
Name: Mac OS X
Version: 14.4.1
Architecture: aarch64

**Comment by ahadas** [comment]
Version 1.4.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.1-1)
