### ISSUE TITLE
[Bug] Undesired beep and undesired character when leaving terminal by pressing F12

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

There's an undesired beep and an undesired `~` character when leaving the terminal by pressing F12.

### Steps to reproduce

1. Start muCommander
2. Press F12
3. Press F12 again

### Expected behavior

After step 3, there's no beep and no undesired character in the terminal.

### Actual behavior

After step 3, there's an undersired beep and there is the undesired character `~` in the terminal.

### muCommander version

Version: 1.5.0
Build date: 2024/05/08
Build number: 54524da

### Java version

Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-0081ac197a656cdc0d88d5a5e2a0f399ee023654
VM vendor: Oracle Corporation

### Operating System type and version

Name: Mac OS X
Version: 14.4.1
Architecture: aarch64

### Relevant log output

```shell
none
```

**Comment by pskowronek** [comment]
> When I turn it on, the problem does not occur.

on or off? And what KB settings you have, DE?

**Comment by pskowronek** [comment]
remember to restart muC after changing the settings :) and pls provide final observations and steps to reproduce (like DE keyboard etc). I will try to provide the fix for your scenario.

**Comment by pskowronek** [comment]
@Andreas0602 you were right, it is kinda randomish - happened to me on both settings.
Can you check this PR #1188 ? With this fix it doesn't happen to me anymore.
