### ISSUE TITLE
File dates inside zip file all show as 1/1/80

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#1203]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

When I look at the contents of a zip file recently downloaded from Google Drive, muCommander (wrongly) shows all file dates as 1/1/80, and this date is transferred across if I copy the files inside muCommander.

### Steps to reproduce

I just downloaded some files from Google Drive. Google zipped them and saved them in a zip file on my local disk. 

When I click on the zip file inside muCommander to view the contents, all the file dates inside the zip file show up as 1/1/80, and if I copy them to another directory, the resulting files are also dated 1/1/80. In reality, all the files are dated 5/28/24, and this date shows up if I list the archive contents using ```unzip -l```. 

I also tested the archive using ```unzip -t``` and it reports no errors.

This didn't happen with a  simple manually created zip file just now, so let me know if you would like a copy of the zip file in question.

### Expected behavior

The file dates should display and copy correctly.

### Actual behavior

File dates display and are copied as 1/1/80.

### muCommander version

1.4.0

### Java version

Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-0081ac197a656cdc0d88d5a5e2a0f399ee023654
VM vendor: Oracle Corporation

### Operating System type and version

Name: Mac OS X
Version: 12.7.5
Architecture: x86_64

**Comment by ShayArtzi** [comment]
Hi @rhstanton, it would be helpful if you could attach an example file. Thanks!

**Comment by rhstanton** [comment]
Sure. I just uploaded two small text files to Google Drive then downloaded them both, creating a zip file with the exact same issue, which I've attached.

[Test-20240531T050145Z-001.zip](https://github.com/user-attachments/files/15508509/Test-20240531T050145Z-001.zip)

**Comment by ShayArtzi** [comment]
Thanks - that helps. I was able to reproduce the issue on my machine and diagnose the cause. When muC parses a zip file to list its content, is refers to the classic modification time and date fields for each file. However, in some cases those (now legacy) fields are not being used. Instead, the header includes an `extra field` (`0x5455`) which stores an extended timestamp.

In this case, the legacy date/time fields defaults to 1980-01-01 (this is MS-DOS formats which stores date as an offset from 1980).

here is a [good reference for pkzip file header structure](https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html).

I would like to try and fix this - hopefully I will get some time next week to further look into it.

**Comment by ShayArtzi** [comment]
@rhstanton FYI the fix for this issue is now included in the nightly build

**Comment by ahadas** [comment]
Version 1.4.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.1-1)

**Comment by rhstanton** [comment]
Thanks! It works fine on my Mac, but no windows open when I try and run the new version on my Ubuntu machine.

**Comment by pskowronek** [comment]
> but no windows open when I try and run the new version on my Ubuntu machine.

can you provide logs?

**Comment by rhstanton** [comment]
It doesn't seem to generate a log file. This seems to be same issue as #1194. In particular, I *can* run muCommander if I use the command 

```
java -jar /opt/mucommander/lib/app/mucommander-1.4.1.jar
```
