### ISSUE TITLE
Localization fallback in 0.9.1

### ISSUE THREAD

**Issue by zlobjc** [mucommander/mucommander#121]
I don't know how to reproduce that.
Some times localization just fallback to OS localization
![mucommander](https://user-images.githubusercontent.com/5018132/29360486-d1899dba-828b-11e7-81c4-789acb84760c.png)

switching to en_GB fix that
![mucommander-good](https://user-images.githubusercontent.com/5018132/29360490-d85e89c0-828b-11e7-9c89-54910dd38391.png)

**Comment by ahadas** [comment]
@zlobjc thanks for reporting this. I believe it was [fixed](https://github.com/mucommander/mucommander/commit/286230e2602e5b980f3434e0bcdcf749b2201b04) in 0.9.2. any reason not to upgrade to 0.9.2?

**Comment by ahadas** [comment]
Closing as it is probably a duplicate. Feel free to reopen if that is not the case.
