### ISSUE TITLE
[Bug] Portable version execution error

### ISSUE THREAD

**Issue by kolanp** [mucommander/mucommander#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

When I downloaded and ran the portable version, I got a JAVA error.
![mucommander error](https://github.com/mucommander/mucommander/assets/10550691/fcece8b2-fdcd-45a7-8b6f-f0ecc04a7a88)

### Steps to reproduce

When running the mucommander.exe file

### Expected behavior

Java virtual machine launcher failed.

### Actual behavior

java launcher error message is appeared.

### Screenshots?

![mucommander error](https://github.com/mucommander/mucommander/assets/10550691/4b7d9089-1807-4fb1-89d1-2abeaab976a7)

### muCommander version

v1.4.1-1

### Java version

Java version: 8.411(Build 1.8.0_411-b09)

### Operating System type and version

Win 11 (23H2 Build 22631.3737)

### Relevant log output

```shell
The software cannot run and therefore cannot generate a log file.
```

**Comment by pskowronek** [comment]
Tried to run on Win 10 and had no problem (I've of course extracted the zip first).
Silly question (just checking), have you extracted the zip and run the .exe from it? Or directly run from Windows' view of that zip file?

**Comment by hajdam** [comment]
As stated on website, Java 11 or later is required to run muCommander and you listed Java 8, so that might be the issue here...

**Comment by kolanp** [comment]
OK, I think it didn't run because I didn't install Java 11.
