### ISSUE TITLE
[Bug] Image Preview [F3] complains about too large file

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Image Preview [F3] complains about too large file

### Steps to reproduce

- Navigate to JPEG file having ~10MB or more
- try to hit F3 (Preview)

### Expected behavior

- image preview is rendered without showing a message box that file is too large

### Actual behavior

- Message box appears that file is too large (probably the same one as if it was text file too large) - see screenshot
- Another problem is that even if one clicks `Cancel`, the preview is still shown (probably the behavior originates from text files when Binary Viewer is used in such a case).

### Screenshots?

![obraz](https://github.com/mucommander/mucommander/assets/360665/92305c82-fb54-459a-be48-f1f2af52e5cf)

### muCommander version

1.4.1

### Java version

23-internal
OpenJDK 64-Bit Server VM
23-internal-ahadas-0081ac197a656cdc0d88d5a5e2a0f399ee023654
Oracle Corporation

### Operating System type and version

Mac OS X
13.6.7
x86_64

### Relevant log output

```shell
N/A
```

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
