### ISSUE TITLE
The application “muCommander” can’t be opened.

### ISSUE THREAD

**Issue by detroitechno** [mucommander/mucommander#122]
Updated from a previous version on osx 10.11.5

The application “muCommander” can’t be opened.

I have open from anywhere selected in system settings. That's not the problem, it just won't open with that simple error message.

**Comment by ahadas** [comment]
Hi @detroitechno , 
So did you try to open the application that was already installed prior to the upgrade or to open the dmg file?

**Comment by detroitechno** [comment]
I had a previous version installed... I hadn't run the program in a while. 

When I ran it I got a notification that  *new version* was available. So I figured I would download it rather than being pestered by the notification every time I opened the program.

I now have: mucommander-0.9.2.dmg

With JRELoadError.

**Comment by ahadas** [comment]
You could switch off the notification of the availability of a new version, but it is better to upgrade since some useful functionality was added.

What version of Java are you using?

**Comment by detroitechno** [comment]
Updated Java to Version 8 Update 144 and it works. Thanks.
