### ISSUE TITLE
Mac OS Sonoma 14.4.1 Owner Group column selectors greyed out

### ISSUE THREAD

**Issue by jimocallaghan** [mucommander/mucommander#1225]
Hello, the Owner and Group column selectors do not appear to be active in Mac OS, muCommander version 1.4.1 Build number 5c94b3d - is this a java restriction or something the re is a workaround for?  Thanks.

**Comment by ahadas** [comment]
@jimocallaghan the owner and group are currently not retrieved for local files, regardless of the operating system. I think the reason for this is that in older versions of Java there was no way to get it from the JRE but [as from Java 7 it is possible](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#getOwner-java.nio.file.Path-java.nio.file.LinkOption...-) , see:

![image](https://github.com/mucommander/mucommander/assets/6020068/b2e443fb-2ff7-4f5a-b130-588f08fc2250)

so this seems like a reasonable enhancement

**Comment by jimocallaghan** [comment]
Thanks for the feedback @ahadas .
