### ISSUE TITLE
[Enhancement] Populate Owner and Group file details columns

### ISSUE THREAD

**Issue by jimocallaghan** [mucommander/mucommander#1228]
### Description

Being able to see the file attributes would be very helpful - may be achievable since Java 1.7, as indicated [here](https://github.com/mucommander/mucommander/issues/1225)

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
