### ISSUE TITLE
Mac version is said to be damaged when trying to install

### ISSUE THREAD

**Issue by jonelhai** [mucommander/mucommander#123]
I have Mac OS 10.12.6. When installing Mucommander 0.9.1 or 0.9.2 (dmg files), after dragging the application to the Applications folder, and opening it from that folder, I see a message saying "mucommander is damaged and can't be opened. You should move it to the Trash."

**Comment by pavel-sakun** [comment]
@jonelhai Use "sudo spctl --master-disable" to enable apps from anywhere. More details in this post: http://www.tech-recipes.com/rx/45404/mac-downloaded-app-is-damaged-and-cant-be-opened-error-solved/

**Comment by jonelhai** [comment]
@pavel-sakun - the sudo command worked. Thank you so much!!!

**Comment by ahadas** [comment]
@pavel-sakun thanks!

**Comment by Dan-Essin** [comment]
Mac OS X: "muCommander damaged and cannot be opened" may appear after downloading muCommander from the browser. This
  can be solved by executing: xattr -d com.apple.quarantine <jar_name>.jar

This command has two problems:
first, it doesn't specify what should be put in <jar_name>
second, trying all of the obvious alternatives - none of the them affect the error message.
