### ISSUE TITLE
[Bug] Nightly builds for Mac not working since several weeks

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Nightly builds for Mac are not working since several weeks.

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Screenshots?

![Nightly](https://github.com/user-attachments/assets/573216eb-587b-4fc2-b96e-5ce2369e20c5)

### muCommander version

-

### Java version

-

### Operating System type and version

-

**Comment by ahadas** [comment]
thanks @Andreas0602 , that's fixed
