### ISSUE TITLE
[Bug] Setting a keyboard shortcut clears another 

### ISSUE THREAD

**Issue by affe42** [mucommander/mucommander#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I'm trying to setup keyboard shortcuts like this:
CTRL-B : explore bookmarks
CTRL-SHIFT-B : add bookmark

While in the Preferences -> Shortcuts editor, both settings co-exist normally, but when I save/exit the Preferences, the other shortcut always gets cleared.

### Steps to reproduce

Just setup shortcuts like described above and exit the Preferences editor.

### Expected behavior

CTRL-B and CTRL-SHIFT-B should co-exist and launch the corresponding functions.

### Actual behavior

After exiting the editor, the shurtcut defined first does not work and is cleared out.

### muCommander version

1.4.1

### Java version

23-internal
OpenJDK 64-Bit Server VM
23-internal-ahadas-22e68b4be09cb27d2b8d6c4df79104b9ce55a14b
Oracle Corporation

### Operating System type and version

Windows 11
10.0
amd64

### Relevant log output

```shell
[✂]

[✂]
```

**Comment by ShayArtzi** [comment]
I tried reproducing the issue on a win11 machine and was not able to (I was able to follow the described scenario and it worked fine on my machine). Could you please check what L&F you are using by going to File -> preferences -> appearance? a screenshot might be helpful as well

**Comment by ahadas** [comment]
I managed to reproduce it on Fedora so I'll take it

**Comment by ahadas** [comment]
Version 1.5.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.5.0-1)
