### ISSUE TITLE
[Bug] Issue Title : " A Java Exception has occurred " is displayed when install muCommander 

### ISSUE THREAD

**Issue by doradora2222** [mucommander/mucommander#1244]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

  Detected Device Group : Galaxy book4 360 5g
  Network info.: Wifi only or not
(if not, need info for supported newtwork info with details.)
  OS & Version : Win 11 24H2 build 26100.712
  Memory:16G / 512GB
  Result with other device:Pass with Galaxy book 4 or other x86/x64 machine

-Issue Procedure
Access this link : '''https://www.mucommander.com/> Download and install muCommander> Observer

-Expected Result
App installation should be completed and able to run.

-Log & comment
When try to install and running app, java exception pop up appeared.

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-

### Screenshots?

-

### muCommander version

-

### Java version

-

### Operating System type and version

-

### Relevant log output

```shell
-
```

**Comment by pskowronek** [comment]
muC version? Screenshot with this exception?

**Comment by ahadas** [comment]
closing due to insufficient information, feel free to reopen once more information can be provided

**Comment by doradora2222** [comment]
@charset "UTF-8";/*! cafe note v2.3.31.4 | Copyright 2014, S-Core, Inc. All Right Reserved. */body,html{overflow:visible!important;height:auto}html{height:auto}body{display:block;margin-left:24px;margin-right:20px;margin-top:16px}body ol,body ul{margin:0;padding-left:40px}body li,body p{line-height:1.9;margin:0 auto}body .cui-quote{margin-left:4px;margin-bottom:20px;padding-left:6px;border-left:4px solid #ccc}body .cui-quote h1,body .cui-quote h2,body .cui-quote h3,body .cui-quote h4,body .cui-quote h5,body .cui-quote h6,body .cui-quote li,body .cui-quote p{margin-bottom:4px}table.cui-div{display:block}table.cui-div>tbody{display:block}table.cui-div>tbody>tr{display:block}table.cui-div>tbody>tr>td,table.cui-div>tbody>tr>th{display:block}figure.cui-og,figure.cui-temp-og{margin:0;display:block;margin-inline-start:0;margin-inline-end:0}.cui-og-container{display:inline-flex}.cui-og-container .cui-og-button-close{display:none;width:20px;height:20px;cursor:pointer;border:none;border-radius:4px;background-color:#fff;background-position:center;background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAI5JREFUOE+9lLEVgDAIRC8b6Tw0Opk2zKMj+XjPApUABTFtLj9wXNJQvFoxD+OBzDwR0Zmp3NI+KhQBgAPASkS7B2XmBcAGYNYFfFpWwi7U05geegeiC7tDsQ5GMLHInbIG3H6KZ66/YWwUVJjhsP4FlrZcOpTS2GSikQ72qKdX9zlkfphIE+YwArz3y4EXDCF2FapWr4IAAAAASUVORK5CYII=");position:relative;top:10px;left:-30px;z-index:1}.cui-og-container .cui-og-button-close.cui-state-focus{display:block}table.cui-pasted-table h1,table.cui-pasted-table h2,table.cui-pasted-table h3,table.cui-pasted-table h4,table.cui-pasted-table h5,table.cui-pasted-table h6,table.cui-pasted-table li,table.cui-pasted-table p,table.cui-pasted-table td,table.cui-pasted-table th{line-height:normal}div[data-cui-alt-image],img[data-cui-alt-image]{background:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABYAAAAUCAYAAACJfM0wAAABH0lEQVQ4jbXU26qEIBQGYF+wtxLMgg4QdGdBREUhFEFBBx/tn6sGpcPezTTCAi/0Q11rSQghhDGGJ4P8An3j20QIgSzLvookSfawUgrrukIp9VVcwkIIcM7h+z66rnsGbprGeCvf95+B8zw3YM75M/A4jnAcB3pS9Y3zPKPv+0vYKDf9jcdxRJ7naJrG2DRNE8IwBGMMZVkewmQbOnwVy7IgiqL3TWzbRtu2x+gVnKYpXNdF27ZY1xVxHO+awHVdDMMAKaWJnsFZlhkn8zzvtMOCIACl1No8Sqm1S55SCkVR3GrdI3QH13V9/7PRxmG5SSlh2/bHKGMMVVXtYc75bZRSaunX1w92+9vUT6mju3WfJuqvv/zf8FmZXq7/BfoCA1VRsvK4AfgAAAAASUVORK5CYII=") no-repeat center #c1c1c1}body::-webkit-scrollbar{opacity:.08;width:6px;height:6px}body::-webkit-scrollbar-thumb{background-color:rgba(0,0,0,.15);border-radius:7px;width:6px}.cui-knoxtaskinput-line{height:150px}.cui-customtask-card{width:560px;height:68px;border-radius:8px;border:solid 1px #dbdbdb;background-color:#fff;border-spacing:0px;table-layout:fixed;margin-bottom:20px}.cui-customtask-card td{margin:0;padding:0;border:0}.cui-customtask-card td>p{width:422px;margin-left:0;text-overflow:ellipsis;white-space:nowrap;overflow:hidden}.cui-customtask-card .cui-customtask-card-cell{text-overflow:ellipsis;white-space:nowrap;overflow:hidden}.cui-customtask-card .cui-customtask-card-image{width:40px;height:40px;margin:0 15px 0 15px;border-radius:22px;background-color:#e96b6b;vertical-align:middle}.cui-customtask-card .cui-customtask-card-content-task{font-size:15px;font-weight:700;font-stretch:normal;font-style:normal;letter-spacing:normal;text-align:left;color:#000;line-height:20px;height:100%}.cui-customtask-card .cui-customtask-card-content-asignee{font-size:12px;font-weight:400;font-stretch:normal;font-style:normal;letter-spacing:normal;line-height:20px;text-align:left;color:rgba(0,0,0,.9)}.cui-taskcard-wrapper{display:block;height:72px;margin-bottom:20px}.cui-taskcard-wrapper .cui-taskcard-more{width:32px;height:32px;padding:0;border:0;background-image:url("./cafe/knox/2.3.31.4/skins/default-knox/images/ic_more_horizontal_normal.png");background-size:16px 16px;background-repeat:no-repeat;background-position:center;background-color:transparent;border-radius:16px}.cui-taskcard-wrapper .cui-taskcard-more-hover{background-image:url("./cafe/knox/2.3.31.4/skins/default-knox/images/ic_more_horizontal_active.png");background-color:rgba(0,0,0,.06)}.cui-taskcard-wrapper-menu{width:122px;height:80px;border-radius:8px;box-shadow:0 3px 4px 0 rgba(0,0,0,.08);border:solid 1px #dbdbdb;background-color:#fff;position:absolute;top:46px;left:516px}.cui-taskcard-wrapper-menu .cui-taskcard-wrapper-menu-ul{margin:8px;padding:0;list-style:none}.cui-taskcard-wrapper-menu .cui-taskcard-wrapper-menu-item{position:relative;width:106px;height:32px;border-radius:4px;list-style-image:url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");margin:0 auto}.cui-taskcard-wrapper-menu .cui-taskcard-wrapper-menu-item-hover{border-radius:4px;background-color:rgba(0,0,0,.06)}.cui-taskcard-wrapper-menu .cui-taskcard-wrapper-menu-icon{width:20px;height:20px;margin:0 0 6px 0;position:absolute;top:4px;left:8px}.cui-taskcard-wrapper-menu .cui-taskcard-delete{background-image:url("./cafe/knox/2.3.31.4/skins/default-knox/images/ic_memo_delete.png")}.cui-taskcard-wrapper-menu .cui-taskcard-update{background-image:url("./cafe/knox/2.3.31.4/skins/default-knox/images/ic_edit.png");background-repeat:no-repeat;background-position:center}.cui-taskcard-wrapper-menu .cui-taskcard-wrapper-menu-text{width:52px;height:19px;font-family:"Malgun Gothic","맑은 고딕",Dotum,"돋움",Gulim,"굴림","Apple SD Gothic Neo","Segoe UI WPC","Segoe UI",Helvetica,sans-serif;font-size:13px;font-weight:400;font-stretch:normal;font-style:normal;line-height:2.15;letter-spacing:normal;text-align:left;color:rgba(0,0,0,.9);position:absolute;left:34px}.cui-mention.cui-mention-edited{padding:1px 4px;border-radius:4px;background-color:rgba(187,187,187,.19)!important;color:#2a82f0!important;font-weight:400!important;font-style:normal!important;font-family:"맑은 고딕"!important;text-decoration:none!important;line-height:normal}.cui-mention.cui-mention-editing{padding:1px 4px;border-radius:4px;background-color:rgba(0,0,0,.06);color:rgba(0,0,0,.9)}

body {margin: 10px; font-size: 10pt; font-family:'맑은 고딕',sans-serif; line-height:1.9;}
p {line-height:1.9;}
body,body p,body li,body h1,body h2, body h3,body h4,body h5,body h6 {font-family:'맑은 고딕',sans-serif; line-height:1.9;}

 
Greetings.
This is Eunyoung from Samsung Electronics Application Quality Assurance team.
 
We contacted you because we have the following issues during the test regarding the compatibility of PC app.
For more details, Please find the following report.


SAMSUNG
General info 
 
  Company
Samsung
  Electronics, Application Quality Assurance Team
  Date
2024-07-19
  Issue Number
P240718-07068
  Application Name
muCommander
  Download Path
https://www.mucommander.com/
  ISV(개발사)
muCommander
  Contact
  info.
-
  Package Name (optional)
-
  Application Version
-
  Priority
Mid
Issue info
Issue
  Title : " A Java Exception has occurred " is displayed when install
  muCommander 
  Frequency of Occurrence
Always
  Detected Device Group
Galaxy
  book4 360 5g
  Full
  model name
　
  Network
  info.
Wifi
  only or not
    (if not, need info for supported newtwork info with details.)
  CPU
  info.
-
  OS & Version
Win
  11 24H2 build 26100.712
  GPU
  info.
-
  Memory
16G
  / 512GB
  Display
  size
16"
  Result
  with other device
Pass
  with Galaxy book 4 or other x86/x64 machine
  Expected cause
-
  PIC in
  Samsung RnD
Jaedeok
  Choi
Detailed issue info.
Issue
  Procedure
Access this link : '''https://www.mucommander.com/>
  Download and install muCommander> Observer
Expected Result
App installation should be completed and able to run.
Log & comment
When try to install and running app,
  java exception pop up appeared.

Thank you very much for your time.
 
Best Regards,
Samsung Electronics Application Quality Assurance team
--------- Original Message ---------
Sender : Piotr Skowronek ***@***.***>
Date   : 2024-07-23 00:35 (GMT+9)
Title  : Re: [mucommander/mucommander] [Bug] Issue Title : " A Java Exception has occurred " is displayed when install muCommander  (Issue #1244)
 
muC version? Screenshot with this exception?
