### ISSUE TITLE
SFTP don't work on Linux in 0.9.2 version, but working well on Windows, v0.9 work well in both OS 

### ISSUE THREAD

**Issue by harp077** [mucommander/mucommander#127]
Good day !

First of all - thank you very VERY MUCH for excellent portable cross-platform 
file-manager !!!
SFTP don't work on Linux in 0.9.2 version, but working well on Windows, v0.9 work well in both OS,
 i am sorry.

With best regards and respect
Roman Koldaev aka harp07

**Comment by ahadas** [comment]
SFTP works with v1.0.0 on both Linux and Windows
