### ISSUE TITLE
[Bug] Terminal doesn't start on 1.5.1 on macOS Sequoia 

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#1281]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I was trying to open Terminal (via keyboard or icon) and Terminal opens but it gets stuck - it requires a couple of minutes to appear.

Re-installed a previous version (1.5.0) - and it works normally.

### Steps to reproduce

- Open Terminal

### Expected behavior

Shell prompt appears in seconds and it works

### Actual behavior

No shell prompt, terminal appears to be stuck - and after a couple of minutes it appears correctly

### Screenshots?

<img width="771" alt="image" src="https://github.com/user-attachments/assets/2d01dfc2-4566-464d-b81a-3208e9f54f97">

### muCommander version

1.5.1

### Java version

24-ea%0AOpenJDK 64-Bit Server VM%0A24-ea%2B15-1658%0AOracle Corporation (<- it is another problem, wrong escape characters)

### Operating System type and version

Mac OS X%0A15.0%0Aaarch64 (Sequoia, 15.0)

### Relevant log output

```shell
%5B%E2%9C%82%5D%0A%5B2024-09-30 01%3A05%3A32.151%5D INFO DefaultSchemeParser.java%23parse%2C292 Warning%3A path should not be empty%2C url%3Dhttp%3A%2F%2F192.168.1.66%3A80%0A%5B2024-09-30 01%3A05%3A32.151%5D INFO DefaultSchemeParser.java%23parse%2C292 Warning%3A path should not be empty%2C url%3Dhttp%3A%2F%2F192.168.1.30%3A8080%0A%5B2024-09-30 01%3A05%3A32.151%5D INFO DefaultSchemeParser.java%23parse%2C292 Warning%3A path should not be empty%2C url%3Dhttp%3A%2F%2F192.168.1.30%3A8080%0A%5B2024-09-30 01%3A05%3A34.645%5D INFO TerminalIntegration.java%23showTerminal%2C126 Going to show Terminal...%0A%5B2024-09-30 01%3A05%3A34.679%5D INFO OSXDesktopAdapter.java%23getMacOsUserShell%2C262 Going to use the following shell%3A %2Fbin%2Fbash%0A%0A%5B%E2%9C%82%5D
```

**Comment by ahadas** [comment]
@pskowronek the only change that might be relevant is the newer JRE that is used by 1.5.1, right?

**Comment by pskowronek** [comment]
> @pskowronek the only change that might be relevant is the newer JRE that is used by 1.5.1, right? I actually checked the terminal with a recent build but yeah, now it gets stuck on my machine (with Sonoma 14.6.1) as well..

I don't see anything related, except for JRE. Checked on old macbook with Ventura and intel, Terminal in v1.5.1 also "hangs".

**Comment by pskowronek** [comment]
When running via `./gradlew run`, it works as expected. 

JRE:
```
Runtime version: 22.0.2
VM name: OpenJDK 64-Bit Server VM
VM version: 22.0.2+9
VM vendor: Eclipse Adoptium
```

**Comment by pskowronek** [comment]
@ahadas btw, why JRE 24 EA (early access)?

**Comment by pskowronek** [comment]
<img width="483" alt="image" src="https://github.com/user-attachments/assets/904527b6-5282-427b-918c-e5bc66ccf5d8">
:/

**Comment by pskowronek** [comment]
Can be also reproduced on JRE 23:
```
Runtime version: 23
VM name: OpenJDK 64-Bit Server VM
VM version: 23+37-2369
VM vendor: Oracle Corporation
```

**Comment by pskowronek** [comment]
When running on jre 23, using the following command in `build/osgi` folder:
`/Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java -Djava.library.path=/usr/local/lib --add-exports java.desktop/com.apple.laf=ALL-UNNAMED --add-exports java.desktop/com.apple.eio=ALL-UNNAMED --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.transaction.xa/javax.transaction.xa=ALL-UNNAMED --add-opens java.management/javax.management=ALL-UNNAMED --add-opens java.rmi/java.rmi=ALL-UNNAMED --add-opens java.security.jgss/org.ietf.jgss=ALL-UNNAMED --add-opens java.sql/java.sql=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED -cp system-libs/mucommander-1.6.0.jar com.mucommander.main.muCommander`

In Activity Monitor I see `mucommander` process only and no `java`, `ps aux | grep java` shows 1 java indeed:
```
user            44712   0.2  2.7 421156064 503216 s004  S+    9:11PM   0:11.99 /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java -Djava.library.path=/usr/local/lib --add-exports java.desktop/com.apple.laf=ALL-UNNAMED --add-exports java.desktop/com.apple.eio=ALL-UNNAMED --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.transaction.xa/javax.transaction.xa=ALL-UNNAMED --add-opens java.management/javax.management=ALL-UNNAMED --add-opens java.rmi/java.rmi=ALL-UNNAMED --add-opens java.security.jgss/org.ietf.jgss=ALL-UNNAMED --add-opens java.sql/java.sql=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED -cp system-libs/mucommander-1.6.0.jar com.mucommander.main.muCommander
```

When I click Terminal, `java` appears in Activity monitor with 100% cpu, sampling the process via Activity Monitor shows:

<img width="887" alt="image" src="https://github.com/user-attachments/assets/0168a1e5-5f21-4725-b5a7-659109cfc008">

`ps aux` also shows 2 java processes:
```
user            44985 100.0  0.0 420844208   3008 s003  Rs+   9:18PM   0:03.07 /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java -Djava.library.path=/usr/local/lib --add-exports java.desktop/com.apple.laf=ALL-UNNAMED --add-exports java.desktop/com.apple.eio=ALL-UNNAMED --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.transaction.xa/javax.transaction.xa=ALL-UNNAMED --add-opens java.management/javax.management=ALL-UNNAMED --add-opens java.rmi/java.rmi=ALL-UNNAMED --add-opens java.security.jgss/org.ietf.jgss=ALL-UNNAMED --add-opens java.sql/java.sql=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED -cp system-libs/mucommander-1.6.0.jar com.mucommander.main.muCommander
user            44712   1.8  2.7 421202320 508176 s004  S+    9:11PM   0:13.70 /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home/bin/java -Djava.library.path=/usr/local/lib --add-exports java.desktop/com.apple.laf=ALL-UNNAMED --add-exports java.desktop/com.apple.eio=ALL-UNNAMED --add-exports java.desktop/com.apple.eawt=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.transaction.xa/javax.transaction.xa=ALL-UNNAMED --add-opens java.management/javax.management=ALL-UNNAMED --add-opens java.rmi/java.rmi=ALL-UNNAMED --add-opens java.security.jgss/org.ietf.jgss=ALL-UNNAMED --add-opens java.sql/java.sql=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED -cp system-libs/mucommander-1.6.0.jar com.mucommander.main.muCommander
```
That second process runs 100% for couple of minutes, then prompt shows correctly and the second java process disappears.

I had no luck with VisualVM (doesn't report any high cpu usage).

**Comment by pskowronek** [comment]
I've bumped JediTerm and its deps to the newest - it appears it fixes the problem.

**Comment by pskowronek** [comment]
@ahadas I've just checked muC v1.5.2 on apple silicon (macOS Sequoia & Sonoma) and the problem is still there - Terminal does not open, in logs just:
```
[2024-10-18 19:49:30.094] INFO TerminalIntegration.java#showTerminal,126 Going to show Terminal...
```

**Comment by pskowronek** [comment]
Apparently, it was caused by old `java` process that was hanging which originated from the previous muC version. This mysteriously caused Terminal in new muC version to refuse to work (!) - after executing `killall java` the Terminal now opens properly in the newest version of muC. 

Checked only on one macbook. Closing for now as false positive.
