### ISSUE TITLE
Bonjour should be default off

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#129]
Please turn off Bonjour service as default.

Thank you.

**Comment by ahadas** [comment]
@aadrian why disabling a feature by default?

**Comment by ahadas** [comment]
@aadrian I see. The risk is that people will just miss that feature but as the `Bonjour service` option appears in both the `Go` menu and the drive popup menu also when it's disabled, I think it's ok to disable it.

**Comment by aadrian** [comment]
@ahadas thank you for the update.

**Comment by ahadas** [comment]
@aadrian np, and thank you for reporting this :) btw, I remember you pushing for having a plug-in architecture (on gitter), right? so there's a [progress on that](https://github.com/ahadas/mucommander/tree/osgi), I hope to be able to introduce something consumable soon

**Comment by aadrian** [comment]
@ahadas Thank you for the info. This sounds good!

I was using lately https://github.com/pf4j/pf4j as a very simple plug-in solution for some in house JVM based projects, and except for a few issues with the latest JDK 11, it's quite a robust framework I must say :) .

**Comment by ahadas** [comment]
@aadrian interesting, thanks, I'll check that out :)
