### ISSUE TITLE
[Enhancement] Java Requirements: please update Readme.txt

### ISSUE THREAD

**Issue by d0vgan** [mucommander/mucommander#1299]
### Description

At first, I want to say I love muCommander, especially when I'm under Linux or MacOS. Thank you so much for muCommander!
Now I'd like to point your attention to the Java Requirements mentioned by muCommander.
It says:
```
Java Runtime Environment (JRE) version 11 or later is required to run muCommander.
```
The truth is: it is not quite correct.

When I try to run muCommander on a machine without Java at all, it indeed proposes to install the Java Runtime Environment.
But! Once JRE has been installed, an attempt to run muCommander (I'm referring to a portable version of muCommander) gives this very understandable message (this example is from Windows):
```
A Java Exception has occurred.
```

In fact, muCommander requires _both_ JRE ( https://www.java.com/en/download/manual.jsp ) and JDK ( https://www.oracle.com/java/technologies/downloads/ ).
Once _both_ have been installed, muCommander runs as expected.

Please update the documentation by mentioning both these requirements. It would be great to include the URLs as well. For example:
```
Java Runtime Environment (JRE) version 11 or later and JDK Development Kit are required to run muCommander.
Get JRE here: https://www.java.com/en/download/manual.jsp
Get JDK here: https://www.oracle.com/java/technologies/downloads/
```

**Comment by ahadas** [comment]
@d0vgan I suspect you faced this issue because you downloaded Java 8 from https://www.java.com/en/download/manual.jsp
I've just installed the JRE of Java 11 from [here ](https://adoptium.net/temurin/archive/?version=11) and muCommander started properly with it
btw, the JRE is contained within the JDK so you don't need both, you can alternatively install just the JDK but that would install extra things that you don't have to have in order to run muCommander
please reopen the issue if needed

**Comment by d0vgan** [comment]
I don't agree this can be closed without any modifications to the documentation!
You mentioned some third-party URL https://adoptium.net/temurin/archive/?version=11 that has nothing in common with the official way of installing Java!
At least this fact must be explicitly mentioned in the documentation!

**Comment by ahadas** [comment]
@d0vgan what would be the proposed change in light of the above?

**Comment by d0vgan** [comment]
As an end-user, I described a solution that worked for me.
Frankly, I don't know what is the difference between Java 8 and Java 11 and why Java 11 is not available on the official site.
So I'd propose the following changes to the documentation:
```
To run muCommander, you need exactly Java 11, which is different from the official Java 8 that is available on
  https://www.java.com/en/download/manual.jsp
If you don't know where to get Java 11, please download it here:
  https://adoptium.net/temurin/archive/?version=11 
Alternatively, you may install both Java 8 and JDK, it will also work:
  https://www.java.com/en/download/manual.jsp
  https://www.oracle.com/java/technologies/downloads/
```
Please feel free to rewrite this text to make it more correct. (As I mentioned, I know nothing about the Java world).

**Comment by ahadas** [comment]
@d0vgan yeah, IIRC Java was made more modular around Java 11 and when that happened, the distinction between JDK and JRE blurred as users are supposed to create a runtime-environment from the JDK by picking the required modules

anyway, back to muCommander - I'd prefer not to get to this level of details about how to install Java, could you please take a look at [the changes I've made to the Requirements section](https://github.com/mucommander/mucommander/pull/1301/files) and tell if they make this more accurate (it seems to me that what confused you is the term "JRE" as Java 11+ worked for you, but couldn't found JRE 11)

**Comment by d0vgan** [comment]
Thank you for the update!
Speaking about myself, I'd prefer this updated section to have a direct link to Java 11+ in the end of the section.
You see, each time I add muCommander to a new machine (that happens rarely, maybe once per 1 or 2 years, depending on my activities), I figure out that the standard Java Runtime (JRE) is not enough to run muCommander, so I try to recall what additional components I need.
As I said, I'm far from Java world, so the term "Java 11+" itself is what confuses me. Once I discover it is not JRE, I try to guess:
- is it related to JDK? https://www.oracle.com/java/technologies/downloads/
- is it related to Java SE? https://www.oracle.com/java/technologies/downloads/archive/
- is it related to something else?
Please understand me: I'm not trying to be "smart ass" or taunting. I really don't know the meaning of "Java 11+". When I google for it, I get such explanations as "Java 11 has new and updated features with the latest LTS version". OK, it's a newer version. But where can I download this newer version and why is it not present on the official page that I'm getting by googling for "Java download"?
As I mentioned, googling for "Java 11 download" gives me links to Java SE 11 and JDK 11, but I have no idea whether it is what I am looking for or not...

**Comment by ahadas** [comment]
@d0vgan you wrote that you use the portable version on Windows, right? why don't you use the msi installer?

**Comment by d0vgan** [comment]
I always prefer portable versions of programs to installers because with portable versions I have full control of what what I unpack to my computer and where I unpack it to. Whereas you never know what additional work is done by installers.
Also, some software just blindly updates old dependencies with newer ones, removing the old ones - and sometimes it leads to problems with other software that still depends on the old libraries (that have been removed by the installer). I'm not saying it is the case with muCommander - but I never know.

By the way, it might be a good point to mentioned in the documentation. I mean, if the installer solves all the problems with dependency on Java 11+ (whatever it is), you might mention: "You should prefer the muCommander installer to the portable version because the installer automatically resolves all the external dependencies of muCommander. While the portable version is recommended to experts who have the knowledge to resolve all the dependencies manually".

**Comment by ahadas** [comment]
yeah, the installer includes (a recent version of) Java so one doesn't need to bother installing Java separately as implied by the aforementioned changes to the Requirements section.
thanks for the feedback @d0vgan! I'd be more explicit about recommending to use installers but I won't point to Oracle or any other vendor of Java, this would be left for "advanced" users to figure out

**Comment by d0vgan** [comment]
OK, digging into the Java world with a help of neural networks, I've discovered the following facts:
- JRE exists only for Java 8. Java 8 is still popular, though it's legacy.
- From Java 9 and higher (in terms of muCommander, we are interested in Java 11+), Java exists only in a form of JDK that includes both runtime and development tools.

Basically, this is the exact additional information I wanted to see in muCommander's Readme. For example::
```
muCommander requires Java 11+ (Java JDK)
```
That's it! By seeing "JDK", I explicitly understand I need some implementation of JDK, not JRE!

Surely, there are different implementations such as OpenJDK, Amazon Corretto, Eclipse Temurin and so on - but when you visit their pages, they explicitly mention they are either "JDK" or "OpenJDK".
Not just "Java", but "JDK"!

I mean, probably it's obvious in Java world - but for me just an explicit presence of a word "JDK" (or "Java JDK") would be a clear sign that this is something different from just "Java" aka "Java 8".

**Comment by ahadas** [comment]
@d0vgan I'd prefer to avoid writing JDK there since even though the distinction between JRE and JDK blurred [as I mentioned before](https://github.com/mucommander/mucommander/issues/1299#issuecomment-2481106804), some vendors like adoptium still produce JRE which can be significantly more lightweight than a complete JDK (see [here](https://adoptium.net/en-GB/temurin/nightly/) for instance), and the JRE would be sufficient. that's why I think just saying Java would be best here,
