### ISSUE TITLE
New MacOS release

### ISSUE THREAD

**Issue by dragos** [mucommander/mucommander#13]
The current binary release for Max OS (on http://www.mucommander.com/) is broken (probably the Java stub launcher is outdated). Please issue a new binary release.

**Comment by zlobjc** [comment]
binary from github
“muСommander-0.9.0.app” is damaged and can’t be opened. You should move it to the Trash.

guys are you alive?

**Comment by ahadas** [comment]
@zlobjc , ack

**Comment by personalaccount** [comment]
I've put compiled a fresh stable build for OS X. Feel free to download it at http://itcreativelabs.com/mucommander.zip

**Comment by ahadas** [comment]
Thanks @personalaccount .
Note that this installation is bigger than it used to be (33mb instead of less than 10mb) because the current build process lacks the shrink phase (using proguard) - that's what blocks me from publishing nightly build releases. But yeah, fat installation is better than nothing for the time being.

**Comment by personalaccount** [comment]
Don't mention it @ahadas, I'm glad to help :) 
To be honest, I neglected to notice the size increase. With that said, I understand where you coming from when speaking about not willing to publish the uncompressed version :).

**Comment by ITfee** [comment]
Is there no official version/download for Mac?

**Comment by ahadas** [comment]
@ITfee, the official release is 0.9.0 that is available in the releases page (https://github.com/mucommander/mucommander/releases) and on mucommander.com
There is no 'official' nightly build/development version at the moment

**Comment by zlobjc** [comment]
If you saying about that:

> @ahadas released this on Aug 4, 2012 mucommander-0_9_0.dmg
> “muCommander.app” is damaged and can’t be opened. You should move it to the Trash.

It doesn't work on Mac OS 10.11.5

**Comment by ahadas** [comment]
Guys,
I've just uploaded a [nightly-build version to bintray] (https://bintray.com/mucommander/mucommander-mac/download_file?file_path=mucommander-0.9.1-nightly.dmg).
Please check it out

**Comment by ahadas** [comment]
New dmg that is part of 0.9.1rc is published:
https://github.com/mucommander/mucommander/releases/tag/0.9.1rc

**Comment by dragos** [comment]
Could you please update the webpage? Now that the ticket is closed nobody can actually find this release anyway.

**Comment by ahadas** [comment]
soon. I didn't find a proper way to release nightly builds yet. I'll update the webpage with 0.9.1 once it is published.

**Comment by ahadas** [comment]
@dragos , FYI the website has been updated with version 0.9.1
