### ISSUE TITLE
[Bug] "Unknown" folder in Windows Start menu

### ISSUE THREAD

**Issue by Neustradamus** [mucommander/mucommander#1306]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

Since a long time, there is a "Unknown" folder in Windows Start menu with muCommander link into.
- C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Unknown

It will be nice to have a "muCommander" folder instead of "Unknown".

Of course the installer needs to remove the bad folder too.

### Steps to reproduce

Install the latest muCommander version (1.5.2) and look Windows Start menu.

### Expected behavior

"muCommander" folder instead of "Unknown"

### Actual behavior

"Unknown" folder

### muCommander version

1.5.2

### Java version

*

### Operating System type and version

*

**Comment by ShayArtzi** [comment]
I was able to reproduce the issue and I'm working on a fix
