### ISSUE TITLE
Hang when open a file for view/edit (Mac OS X 10.10.5)

### ISSUE THREAD

**Issue by Awak00m** [mucommander/mucommander#131]
MUCommander hangs every time I try to open a file having very long line(s) inside. It shows a blank window of extremely big width with continuously spinning progress indicator.
Crash log file is attached.
[mu-bug.txt](https://github.com/mucommander/mucommander/files/1366723/mu-bug.txt)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
