### ISSUE TITLE
In tree view, the hidden right pane comes into view after resizing window (Windows 7)

### ISSUE THREAD

**Issue by danuvian** [mucommander/mucommander#132]
In tree view, I have hidden the right side of the pane by pressing the right triangle putton. So it looks similar to Windows Explorer at this point.

However, if I resize the application window, the right pane becomes visible again. It should stay hidden. This is the issue.

This occurs on Windows 7.

On the latest MacBook Pro, it works as expected (after resizing the window, the right pane stays hidden).

Thank you.

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
