### ISSUE TITLE
Large file copy btw. to smb's (Win 10 and Linux Mint)

### ISSUE THREAD

**Issue by phhemberg** [mucommander/mucommander#136]
First of all. Thanx for a great peace of CROSS-PLATFORM sofware. I'm having an issue though when trying to copy a file between to smb drives. Progressbar AND speedindicator doesn't show anything. It's a minor thing BUT it takes for ever to copy files between smb drives. No matter if i'm on Linux or Windows. Normaly (with other software as Multicommander) i'll get about 60-70 mb/sek in transferspeed. But with mucommander i'll get perhaps 16-17 mb/sek. Is this a Java thing? When i'll try to abort the copy process mucommander continous in bacground,

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
