### ISSUE TITLE
Removal of sun.misc.Sort and sun.misc.Compare in Java 8

### ISSUE THREAD

**Issue by personalaccount** [mucommander/mucommander#14]
The existing code (i.e. in file NfsURLConnection.java) uses currently deprecated versions of sun.misc.Sort and sun.misc.Compare.

It is advised by sun to use the sort() method of java.util.Arrays and java.util.Comparator respectively.

**Comment by ahadas** [comment]
Fixed by https://github.com/mucommander/mucommander-commons-file/commit/803a3be44207357142414a8e78e98decb5652faa

**Comment by ahadas** [comment]
I see that the fix has been merged before you opened the ticket, so maybe the mucommander-commons-file submodule was not up-to-date. I just merged the submodules into the 'mucommander' repository so it would be easier to build the project.
