### ISSUE TITLE
Shortcut not working correctly Pack files...

### ISSUE THREAD

**Issue by vskladany** [mucommander/mucommander#141]
The shortcut not working correctly for macOS, OSX 10.10, etc. since muCommander v0.9.1.

Example: control+I (Pack files...) after press the cursor focus to the path line.

Best regards.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
