### ISSUE TITLE
Batch rename files, reads wrong month with [M]. It reads it M-1 instead.

### ISSUE THREAD

**Issue by soder82** [mucommander/mucommander#142]
I got a Sony camera, and I use my Mac with a SD card reader to transfer the photos and videos to a home server. The video files are in a file format called .MTS and are only name 00000.MTS, 000001.MTS and I want them to be named with the date there are taken.

I transfer the files with muCommander from the Mac to the server, and then use the Batch rename function in muCommander with [YMD]-[N4-5].[E] or [Y][M][D]-[N4-5].[E] to get the date in front and then only keep the last to digits from the old file name.

Yesterday I noticed that the files are getting the wrong month this way, but the Year and Day are correct. If the month is december, 12, then the file is named 11. The file 00004.MTS taken 2017 december 24 gets the file name 20171124-04.MTS

I also checked the files I've transfers earlier, and I found that files that was taken in january got the file name like 20170013-04.MTS. January, first month, 01, is name 00 in the file name.

Using 0.92 in Mac Os High Sierra 10.13.2

/Söder

**Comment by soder82** [comment]
Any updates about this?

**Comment by ahadas** [comment]
Thanks for reporting this!
The fix is simple. Unfortunately, we have no nightly builds at the moment so it needs to wait for the next release. However, you could [build it from source](https://github.com/mucommander/mucommander/blob/master/README.md) if you like until then.
