### ISSUE TITLE
Message Properties with single quotes

### ISSUE THREAD

**Issue by systemsplanet** [mucommander/mucommander#149]
**MessageFormat requires two 's** as seen in this example:

public static void main(String... a) {
        System.out.println(MessageFormat.format("This folder doesn't exist or is not available.", (Object[]) null));
        System.out.println(MessageFormat.format("This folder doesn''t exist or is not available.", (Object[]) null));
    }

**Output**
This folder doesnt exist or is not available.
This folder doesn't exist or is not available.

**Comment by ahadas** [comment]
@systemsplanet fixed, thanks!
