### ISSUE TITLE
AppleScriptTest.java breaks compileTestJava

### ISSUE THREAD

**Issue by systemsplanet** [mucommander/mucommander#150]
mucommander\src\test\java\com\mucommander\ui\macosx\AppleScriptTest.java:66: 
  error: unmappable character for encoding Cp1252

**Fix is to edit build.gradle, add to dependencies:**
    compileJava.options.encoding = 'UTF-8'
    compileTestJava.options.encoding = 'UTF-8'

**Comment by ahadas** [comment]
I didn't see it happening locally or on travis-ci, yet I've added `compileTestJava.options.encoding = 'UTF-8'` just to be on the safe side. Thanks for reporting this.
