### ISSUE TITLE
compileJava warnings: deprecated API

### ISSUE THREAD

**Issue by systemsplanet** [mucommander/mucommander#151]
Error:
:compileJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: E:\ProgramFiles\nc\mucommander\src\main\java\com\mucommander\ui\quicklist\item\QuickListDataList.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Fix:
Add to build.gradle
    compileJava.options.compilerArgs += '-Xlint:-deprecation'

**Comment by ahadas** [comment]
@systemsplanet thanks for reporting this. I think the right way to handle this is by addressing the deprecations rather than hiding the warning, so it's better to keep them reported.
