### ISSUE TITLE
GeneralPanel.java hasChanged() will never be true

### ISSUE THREAD

**Issue by systemsplanet** [mucommander/mucommander#152]
com.mucommander.ui.dialog.pref.general.GeneralPanel
   constructor public GeneralPanel(PreferencesDialog parent)
   public boolean hasChanged() {

equals comparison compares a Locale to a String.
Locale equals implementation returns false if the object is not a LocaleKey.
            
Change to:
lang = languages.get(getSelectedIndex()).toString(); 
!lang.equals(MuConfigurations.getPreferences().getVariable(MuPreference.LANGUAGE));

**Comment by ahadas** [comment]
@systemsplanet thanks for catching and reporting that!
