### ISSUE TITLE
Opening a 7z archive locks it so it cant be deleted until mucommander is closed

### ISSUE THREAD

**Issue by systemsplanet-zz** [mucommander/mucommander#153]
finally has commented out the sevenZipFile.close(). 
Uncommenting, fixes the issue:

```java
com.mucommander.commons.file.archive.sevenzip.SevenZipArchiveFile.java
 public ArchiveEntryIterator getEntryIterator() throws IOException {
...
finally {
 try {
         sevenZipFile.close(); 
       }
  catch (IOException e) {
   }
}
```

**Comment by tikomir** [comment]
This problem also applies for RAR files.
Tested for v0.9.1-v0.9.3 on a Windows platform.

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
