### ISSUE TITLE
List remote shared folders over smb

### ISSUE THREAD

**Issue by klayman** [mucommander/mucommander#156]
Please add functionality to list available shared folders on a remote Windows machine when connecting to `\\servername`.

Currently muCommander can connect to `\\servername\share\` but throws the error message "This folder doesnt exist or is not available" when connecting to just `\\servername`.

This functionality is available in Far Manager and Explorer (it's possible to go one level up from any shared folder). Shared folders also can be listed with the `net view servername` command.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by Usernameisalreadytaken5** [comment]
https://www.youtube.com/watch?v=4Ebwvabn6Cs

That mean is only support SMB v1

**Comment by ahadas** [comment]
> Any news on it?

It will be fixed in v1.1.0

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)

**Comment by Neustradamus** [comment]
@ahadas: Nice, good job, thanks!
