### ISSUE TITLE
Linked content is deleted instead of a symlink on Windows.

### ISSUE THREAD

**Issue by klayman** [mucommander/mucommander#163]
I'm using muCommander for about 10 years now (Mac and Linux) and recently I installed it on a Windows workstation. I used to work with symlinks as some kind of files pointing to some resource, so when I delete a symlink only the link is deleted and the linked content in untouched. But this is not true for muCommander under Windows - I had a lot of trouble when some files on a production server were deleted after I accidentally deleted a symlink pointing to a network resource. I think this is wrong and very dangerous behavior that should be fixed.

**Comment by ahadas** [comment]
Hi @klayman ,

I agree.
It used to be problematic to identify symlinks on Windows through Java so [we decided long ago to ignore them] (https://github.com/mucommander/mucommander/blob/master/mucommander-commons-file/src/main/java/com/mucommander/commons/file/protocol/local/LocalFile.java#L610-L615). Need to check whether it is still the case or whether there's a third party tool that allows this.

How do you create symlinks on Windows?

**Comment by klayman** [comment]
Hi @ahadas ,
Thanks for your reply. I used FAR manager to create that symlink (alt + F6 there), but it's also possible with the `mklink /d` command.
Actually, muCommander does report the junctions and symlinks as links, but only in the deletion confirmation dialog (in the `1 File(s)` listing, which is hidden by default). Perhaps, some kind of external file listing is used there. At least, the windows `dir` command displays the type of files and folders correctly.

**Comment by ahadas** [comment]
> Actually, muCommander does report the junctions and symlinks as links, but only in the deletion confirmation dialog (in the 1 File(s) listing, which is hidden by default). Perhaps, some kind of external file listing is used there.
Exactly, we ask Java's Swing for the icon in that place.
That's good because it means that there a good chance we will be able to detect this using Files#isSymbolicLink. I'll try to test it today on a Windows.

**Comment by ahadas** [comment]
Quick update: symlinks on Windows are detected properly by muCommander with Files#isSymbolicLink. However, some further work is required as File#getCanonicalPath doesn't seem to point to the target of such links. Needs to investigate it a bit further.

**Comment by kousalik** [comment]
Hi @ahadas, can you please explain what is the issue with File#getCanonicalPath? Why do you need it to return path to the linked target? I believe it correctly returns the path of the link itself. Also LocalFile#isSymLink has return false hardcoded for Windows so it actually ignores symlinks which could potentially be detected correctly. The explaining comment seems wrong to me. I was hoping to provide a fix but this confuses me.

**Comment by ahadas** [comment]
Hi @kousalik , honestly, it's a bit hard for me to recall :)
Regarding the explaining comment, you are correct - note that it was written 9 years ago, before I change the lower part of this method to use Files#isSymbolicLink that was introduced in Java 7.
I think that in my previous comment I tried to say "By dropping the hard-coded `false` for Windows in LocalFile#isSymlink, the detection works but some other flow(s) that uses File#getCanonicalPath uniformly on all files in a folder then breaks". It's unfortunate that I didn't explain better what I found back then - can you try playing with that and see if it works for you for things like opening a linked file with the viewer editor, entering a linked directory, copying a directory that contains a symlink, etc?

**Comment by kousalik** [comment]
I'm actually a Mac+Linux user but I've set it up in a VM. I'll drop the hard coded `false` and give it a go.

**Comment by klayman** [comment]
Bump. This is a very dangerous issue. I've just faced it again. Some files were copied from a server to a PC and there were some symlinks among them (these files and symlinks were presumably copied with FAR manager). When the containing folder was renamed on the PC with muCommander, the linked files got deleted from the server.

**Comment by klayman** [comment]
Thank you!
