### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by shepelevstas** [mucommander/mucommander#164]
Trying to install mucommander following instructions from here http://apt.mucommander.com/:
after `apt update` getting this error:
```
W: GPG error: http://apt.mucommander.com stable InRelease: The following signatures were invalid: KEYEXPIRED 1530198815 KEYEXPIRED 1530198815 KEYEXPIRED 1530198815
```
Is it safe to install anyway?

**Comment by ahadas** [comment]
Note that recent versions of muCommander were not published on that repository.
You should rather use the package published [on the github page](
https://github.com/mucommander/mucommander/releases/download/0.9.2/mucommander_0.9.2_all.deb)

**Comment by FlorianZipser** [comment]
Could you then remove the link to http://apt.mucommander.com/: from the homepage http://www.mucommander.com/ ? Ran into the same issue.

**Comment by ahadas** [comment]
> Could you then remove the link to http://apt.mucommander.com/: from the homepage http://www.mucommander.com/ ? Ran into the same issue.

Already done
