### ISSUE TITLE
Compatibility with Java 11

### ISSUE THREAD

**Issue by kachkaev** [mucommander/mucommander#166]
After running `brew cask upgrade` yet another time I noticed that muCommander stopped working. All it did was showing `JRELoadError` alert on start. As it turned out, the cause was the shift from java 10  to java 11.

Here's what worked for me on macOS: 

```
brew cask uninstall java
brew cask install java10
```

How feasible would it be to support Java 11?

**Comment by zlobjc** [comment]
Have same issue, rollback to Java8 doesn't work for me.

**Comment by ahadas** [comment]
We should definitely support it.
There's [an on-going effort to use OSGI](https://github.com/mucommander/mucommander/pull/171) which hopefully render some of the dependencies that are hard to upgrade to new Java versions redundant and then it would be easier to fix this.

**Comment by zlobjc** [comment]
9.3 still there

**Comment by wzhliang** [comment]
Seeing same thing with 0.9.3

`java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
`
macOS 10.13.6

**Comment by mrserb** [comment]
You can try to use jpackager/jlink to pack the application on top of jdk11.

**Comment by ahadas** [comment]
Solved in 0.9.4 by bundling the JRE.
