### ISSUE TITLE
"no graphical environment detected" on Fedora with cinnamon

### ISSUE THREAD

**Issue by glurmito** [mucommander/mucommander#167]
Hello.

I've found that I cannot launch mucommander 0.9.2 on my Fedora 28 with cinnamon.

When I try to start it from the command line I get the following error: Error: no graphical environment detected.

It seems that GraphicsEnvironment.isHeadless()  is returning true although it's running in a graphical environment (DISPLAY=:0.0)

Probably there's something with my environment that's preventing java to detect the graphic environment.

Any clue?

Thanks for your help.

**Comment by ahadas** [comment]
Hi @glurmito ,

By default Fedora 28 with cinnamon comes with java-1.8.0-openjdk-headless, so you'll need to install the non-headless version `dnf install java-1.8.0-openjdk` for muCommander to work.

**Comment by glurmito** [comment]
Thank you for your reply.

Installing the proper version of java made it work. There's still a problem with Fedora dependencies in repo https://fedora.pkgs.org/26/rpm-sphere/mucommander-0.8.5-12.1.noarch.rpm.html as it won't install java correctly (but that's a different issue for a different forum),

Thanks again :-D
