### ISSUE TITLE
Run as administrator

### ISSUE THREAD

**Issue by ahadas** [mucommander/mucommander#173]
Administrators are prevented from, e.g., removing certain files from within muCommander due to lack of permissions ([see here](https://github.com/mucommander/mucommander/issues/109#issuecomment-438879717)).

One way to solve this is to run muCommander with the highest level of privileges that is available for the user ([as described here](https://stackoverflow.com/questions/19037339/run-java-file-as-administrator-with-full-privileges/49665793#49665793)). Alternatively, users can be asked to confirm on a per-operation basis whether or not to execute it as admin (like running a command with `sudo`).

**Comment by zsercsi** [comment]
Hi
I have same problem on Mac OS Mojave 10.14.1.
Deleting files to trash not working, but i can delete without trash.
Thank you for your help!

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
