### ISSUE TITLE
Deleting to Trash not working On Mac Os Mojave

### ISSUE THREAD

**Issue by zsercsi** [mucommander/mucommander#175]
MacOs Mojave 10.14.1
Deleting files to trash not working, but i can delete without trash.
Thank you for your help!

**Comment by ahadas** [comment]
@zsercsi did we chat on facebook about this? if not, did you grant muCommander permission to control Finder and what's the error you see in the debug console?

**Comment by zsercsi** [comment]
Hi. 
<img width="428" alt="kepernyofoto 2018-11-19 - 5 48 44" src="https://user-images.githubusercontent.com/45074431/48686901-e00c0d80-ebbe-11e8-9b62-0b9b0fbdc7d8.png">


Yes, i give permission

<img width="745" alt="kepernyofoto 2018-11-19 - 5 36 06" src="https://user-images.githubusercontent.com/45074431/48686948-2d887a80-ebbf-11e8-8af9-afab471f28f3.png">

Intresting, but i can delete without using trash.

**Comment by zsercsi** [comment]
Hi. Thank you for your help!   Yes, i give permission. Intresting, but i can delete without using trash. I send you 2 pictures. Thanks.  
>

**Comment by ahadas** [comment]
@zsercsi Thanks. Can you please check with [this version](https://www.dropbox.com/s/vbuch8jc3pjfl9d/mucommander-0.9.3.1.dmg?dl=0)?

**Comment by zsercsi** [comment]
Ok.
I check, but the same problem. I can't delete to trash, same error message. Without trash i can delete, again!

Thanks.

**Comment by ahadas** [comment]
> Ok.
> I check, but the same problem. I can't delete to trash, same error message. Without trash i can delete, again!
> My settings are ok in the sent pictures?

Yes, those settings are correct.

> 
> The 0_9_2 is perfect.

And 0.9.3 is even better :)

That issue was also reported by another user.
I wonder what's the problem because it works fine on my MacBook and with another MacBook I tested this on. Can you please take a screenshot of the Java section in the 'About muCommander' dialog?

**Comment by zsercsi** [comment]
Hi. Of Course. 

<img width="599" alt="kepernyofoto 2018-11-19 - 18 38 46" src="https://user-images.githubusercontent.com/45074431/48724827-9d801a80-ec2a-11e8-816d-cbc00e2fbc62.png">

I use now 0.9.2, because i must delete a lot.... :-)
I use 2017 Imac 27' 5 K, but this does not matter, i think!

**Comment by ahadas** [comment]
This means that we're also using the same version of Java... The good side though is that it almost proves that there's no bug in the code:
1. 0.9.3 worked on several machines that I tested with and doesn't work on your machine.
2. 0.9.3.1 that doesn't contain the change that is the prime suspect for breaking the interaction with the trash works on my machine and doesn't work on your machine.
It seems like something specific to some machines but without access to those machines, it is very difficult to investigate this.
So I'll publish the 0.9.3.1 version to fix other issues that were reported in 0.9.3. Any help from the community in investigating why this fails on particular machines is welcome.

**Comment by zsercsi** [comment]
Ok
Thank you for your help, and work!

PS: I willingly give you my mac, if you come to Hungary.  :-)

**Comment by ahadas** [comment]
Finally, managed to understand what's going on :)
It happens on machines that were installed with a previous version and then upgraded to 0.9.3.
The access to `Finder`is blocked due to the privacy settings that don't hold for the new version.
So a workaround for this is to invoke: `tccutil reset AppleEvents`
Note that it will clear all the `Automation` settings so you'll need to approve each application that was defined before. Unfortunately, resetting a particular application (bundle) doesn't seem to work.

@zsercsi , can you please give it a try?

**Comment by zsercsi** [comment]
Hi. I tried. 
I delete all Automation. When i open the 9.0.3, the app does not ask for access to finder, and i can't setting it. Everything works just like before, i can't delete to trash.
When i go back to 9.0.2 the app requests access automatically to finder, and it works!!! I can delete, everything!

**Comment by ahadas** [comment]
@zsercsi bummer :/ 
So 0.9.3 is not that different compared to 0.9.2 on macOS so you won't lose that much by staying with 0.9.2. But 0.9.4 is going to include some cool stuff so I hope someone from the community that experiences this issue could come up with a fix or that it will be resolved by some operating system update.

**Comment by zsercsi** [comment]
Hi.
I hope so too! Thank you for your work, and please write me, if you have an idea! 

Thanks.

**Comment by ahadas** [comment]
@zsercsi Please check out [the latest update of 0.9.3](https://github.com/mucommander/mucommander/releases) that provides a fix - thanks for reporting this and for your cooperation!

**Comment by zsercsi** [comment]
Hi Arik Thank you for dealing with my error. I tried the new version, but i am sorry, but the same problem! Not working The Trash! The same error message!I am sorry.......   
Arik Hadas <notifications@github.com> írta:

**Comment by ahadas** [comment]
@zsercsi , Hi, can you please paste here the **muCommander** section in the muCommander->About dialog?

**Comment by zsercsi** [comment]
Hi    
Arik Hadas <notifications@github.com> írta:

**Comment by ahadas** [comment]
@zsercsi Can you please enter the #mucommander IRC channel? you can do that [via the browser](https://webchat.freenode.net)

**Comment by zsercsi** [comment]
Arik Hadas <notifications@github.com> írta:
