### ISSUE TITLE
"Run in Current Folder" does not work on Mac OS-X

### ISSUE THREAD

**Issue by twhimes** [mucommander/mucommander#178]
mucommander does recognize any Unix commands, running on a Mac OS-X 10.12.6.
"find . -iname "*jpl*.docx"  
find . -iname "*jpl*.docx": No such file or directory.

This functionality used to work in past versions.

**Comment by ahadas** [comment]
@twhimes Hi, from the description above it seems that the command works but couldn't find this file (jpl.docx). What's the output of 'pwd' or 'ls'?

**Comment by twhimes** [comment]
Same:
pwd: No such file or directory.

ls: No such file or directory.

This functionality used to work, a long time ago. I think your app needs to spawn or fork
a shell, to execute commands.  But then you would have to redirect STDOUT/STDERR to
get it into the windo.


"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment]
@twhimes Thanks for checking this. I'm not sure whether you do it correctly as this part didn't change for quite a while and works fine on my machine. Would you be kind enough to look at [this video](https://youtu.be/ZrFjtd0qsWE) and tell what you are doing differently?

**Comment by twhimes** [comment]
Arik,

I watched the video. It is exactly what I am doing. Pretty straight forward. It must be something in the setup.
I did play with “preferences” to see this that made any difference. It didn’t.

Any other thoughts?

Terry



"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment]
@twhimes What does the log say? Try executing a command and then in `Help->Debug Console` find the line with `Shell.java#execute` and see what's the command that is actually being executed and whether or not there is an error afterward.

**Comment by twhimes** [comment]
“Debug Console”  is always blank.  Also, you cannot keep the Debug Console open while running commands.
But it is always blank after running any command.

Terry


"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by twhimes** [comment]
Finally got the “Debug Console” to work.  Here is the ERROR message after I
tried to run a command;
[2018-11-27 22:00:20.294] WARNING BonjourDirectory.java#setActive,95 Could not instantiate jmDNS, Bonjour not enabled
Terry


"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment]
@twhimes , That error is unrelated - you can disable Bonjour services discovery by unchecking that in the Preferences->Misc dialog.

What is the log level that is set at the bottom of the Debug console dialog? Try changing it to FINE and then you're supposed to see the Shell and ShellHistory printings

**Comment by ahadas** [comment]
@twhimes , Can you please tell what's configured in Preferences->Misc->Run command?

**Comment by twhimes** [comment]
Hope this come thru…

[cid:image001.png@01D48CB6.C770C520]



"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment]
@twhimes I'm afraid it's not :) you can use something like [imgur](https://imgur.com/upload) or to send it to mucommander@gmail.com

**Comment by twhimes** [comment]
Arik,

I think I found the problem.  Under Permissons/Misc/Use Custom Shell I have always used tcsh.
We used tcsh in Flight Ops.

When I switch to use Permissons/Misc/Use Default, it works.  I didn’t try other shell’s (like bash)
but it might not work for them either.

Terry



"A Purple Heart proves you were smart enough to hatch a plan,
 stupid enough to try it and lucky enough to survive!"

Terry W. Himes
JPL Jet Propulsion Laboratory
Dawn Spacecraft Team
Juno Systems & Software Team
TGO Sequence Lead
Phone: (818) 393-6261
Cell:     (818) 653-8213
thimes@jpl.nasa.gov<mailto:thimes@jpl.nasa.gov>
🇺🇸

**Comment by ahadas** [comment]
@twhimes Glad to see that it works for you now! Note that you can set the custom shell to `/bin/tcsh -c` if you like tcsh and it should work. The bash shell also works for me. So great, now that we realize that it's not a regression, I can proceed with releasing 0.9.3.1 :)

**Comment by twhimes** [comment]
Ah. Ok I'll test that



Sent from planet earth.


-------- Original message --------
