### ISSUE TITLE
link in impressum is broken

### ISSUE THREAD

**Issue by FlorianZipser** [mucommander/mucommander#179]
See the link in your impressum to "Maxence Bernard" is broken. I guess you should fix that for legal issues.
on http://www.mucommander.com/ see:
© 2002-2018 Maxence Bernard. All rights reserved.

**Comment by ahadas** [comment]
@FlorianZipser Thanks for reporting this, let me check this with @m4xence

**Comment by ahadas** [comment]
Removed the copyright.
