### ISSUE TITLE
An error prevented muCommander from starting (MacOS) -- reopen

### ISSUE THREAD

**Issue by ddj3o3** [mucommander/mucommander#182]
This is the capture from TERMINAL with JAVA -JAR solution:
Last login: Sun Nov 25 11:55:22 on ttys001
Restored session: Dom 25 Nov 2018 11:58:23 CET
MacBook:~ DDJ$ java -jar /Users/DDJ/Downloads/mucommander.jar 
11:59:20.374 [main] INFO com.mucommander.commons.runtime.OsFamily - Current OS family: Mac OS X
11:59:20.971 [main] INFO com.mucommander.commons.runtime.JavaVersion - Current Java version: 1.8
11:59:20.971 [main] INFO com.mucommander.commons.runtime.JavaVersion - Current JVM architecture: x86_64
Could not load snapshot: Character reference "&#3" is an invalid XML character.. Using default values.
Could not load custom commands: /Users/DDJ/Library/Preferences/muCommander/commands.xml (No such file or directory). Using default values.
Could not load custom associations: /Users/DDJ/Library/Preferences/muCommander/associations.xml (No such file or directory). Using default values.
[2018-11-25 11:59:23.346] SEVERE muCommander.java#run,547 Startup failed
Exception in thread "com.mucommander.ShutdownHook" java.lang.NoClassDefFoundError: Could not initialize class com.mucommander.core.GlobalLocationHistory
	at com.mucommander.conf.MuSnapshot.setGlobalHistory(MuSnapshot.java:648)
	at com.mucommander.conf.MuSnapshot.write(MuSnapshot.java:614)
	at com.mucommander.conf.MuConfigurations.saveSnapshot(MuConfigurations.java:86)
	at com.mucommander.ShutdownHook.performShutdownTasks(ShutdownHook.java:85)
	at com.mucommander.ShutdownHook.run(ShutdownHook.java:69)
MacBook:~ DDJ$

**Comment by ddj3o3** [comment]
Tried via Cross-Platform (JAVA WEB) but NO certification is present for MuCommander ... no way to open it

**Comment by ahadas** [comment]
@ddj3o3 hi, can you please share your snapshot.xml file? it resides in `~/Library/Preferences/muCommander`

**Comment by ddj3o3** [comment]
not found ... file not present into my HD

**Comment by ddj3o3** [comment]
in terminal mode:
MacBook-Pro:~ DDJ$ ls Library/Preferences/muCommander/
action_keymap.xml	command_bar.xml		preferences.xml		snapshot.xml
bookmarks.xml		extensions		shell_history.xml	themes

**Comment by ddj3o3** [comment]
@ahadas please tell me the instructions to share snapshot.xml

**Comment by ahadas** [comment]
Please send it to mucommander@gmail.com

**Comment by ddj3o3** [comment]
Found solution: JUST delete mucommander directory into Library/Preferences/
then RUN mucommander 
and now works it fine !!!!
thx @ahadas for support ... and me for solution too :-)

**Comment by ahadas** [comment]
Closing, please feel free to reopen if you have the problematic configuration files.
