### ISSUE TITLE
Support new versions of hadoop

### ISSUE THREAD

**Issue by RickIFWX** [mucommander/mucommander#184]
I'm trying to connect to hadoop 2.6 and receiving an error -  IPC version 9 cannot communicate with client version 3.  I'm guessing this is a version problem and I don't see anywhere to update the Hadoop client within mucommander.

**Comment by ahadas** [comment]
@RickIFWX hi, yeah, seems that it's a version issue and the library we use is indeed pretty old by now. on the bright side though, it would be easier to upgrade it with the upcoming plugin support

**Comment by RickIFWX** [comment]
Bummer,  no plans to update the libraries ?

**Comment by ahadas** [comment]
@RickIFWX , I didn't say that :) That's something that can certainly be a part of the next version

**Comment by lbendig** [comment]
@RickIFWX Couple of years ago I patched mucommander to support any Hadoop version, I always plan to clean up this and create a PR: https://github.com/lbendig/mucommander

**Comment by ahadas** [comment]
@lbendig such a contribution would be great, especially now. on the master most of the protocol and archive formats were converted to OSGi bundles as a step toward having a pluggable architecture and during the process the support for Hadoop and S3 protocols got broken. so it would be an awesome timing to implement their plugins in a way newer versions are supported.

**Comment by lbendig** [comment]
@ahadas Great to hear that there's an OSGi support. I try to find time to start working on it in the near future.

**Comment by ahadas** [comment]
@lbendig cool :) let me know if I can help

**Comment by pskowronek** [comment]
> @ahadas Great to hear that there's an OSGi support. I try to find time to start working on it in the near future.

Any hope? :)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
