### ISSUE TITLE
Version 0.9.3-1 for Windows is not an install file?

### ISSUE THREAD

**Issue by SGvagon** [mucommander/mucommander#185]
Hello,

before two days I saw, that you released new version 0.9.3-1 , but when I downloaded it (on Windows 7 x64bit) and run it (exe file) , it not show any installation, only start MuCommander like a portable.

Is it bug or some new feature on Windows?

**Comment by ahadas** [comment]
@SGvagon Hi, thank you for raising it up! That's a bug - apparently, I've uploaded the wrong file.. Replaced it with the right one (the installer). Please feel free to reopen if you find any issue with the new file.

**Comment by RoyiAvital** [comment]
Is there a portable version for Windows?

**Comment by ahadas** [comment]
@RoyiAvital , yes, the [portable version](https://github.com/mucommander/mucommander/releases/download/0.9.3-3/mucommander-0.9.3-portable.tar.gz) is provided with an exe file for Windows
