### ISSUE TITLE
Strange SFTP problem with the latest 0.9.3

### ISSUE THREAD

**Issue by neilyoung** [mucommander/mucommander#187]
I'm noticing a strange speed problem with the latest 0.9.3 update if it does SFTP upload to a remote server. My branch copies a 12 M file in several seconds. The latest internet 0.9.3 uploads in peeks and counts the speed in bytes/s

**Comment by ahadas** [comment]
@neilyoung does it still happen?

**Comment by neilyoung** [comment]
No, issue fixed with 0.9.3 of today :)

**Comment by ahadas** [comment]
Cool, thanks!

**Comment by neilyoung** [comment]
@neilyoung I'm sorry, I need to reopen this again. Copying a file of 14 MB using mucommander is announced to last for more than 22 minutes, while FileZilla just needs seconds.

There is (again?) an issue here :/

**Comment by ahadas** [comment]
@neilyoung ack, thanks for the update, reopenning

**Comment by neilyoung** [comment]
@ahadas You're the best. Let me know, if I can assist

**Comment by accuware** [comment]
@ahadas Hi Arik, any progress here? I'm starting to get used to Filezilla. That's not good :)

**Comment by ahadas** [comment]
@accuware , Hi, unfortunately not yet. It will take me some time to get to this...

**Comment by neilyoung** [comment]
Closing this. I don't believe it will be addressed soon. Thanks

**Comment by kousalik** [comment]
Not addressed soon is not a reason to close issue.

**Comment by ahadas** [comment]
> Closing this. I don't believe it will be addressed soon. Thanks

@neilyoung , I wonder - you previously wrote `Copying a file of 14 MB using mucommander is announced to last for more than 22 minutes` but how much did it actually take to copy it?

**Comment by neilyoung** [comment]
With the latest version it is not even possible to connect to the SFTP server anymore. So, it is a no-issue anymore
@kousalik Thanks for teaching me. I was looking for a way to leave this repo and it's unrelated (for me) announcements.

**Comment by neilyoung** [comment]
@ahadas Sorry, either I have missed something or things have changed. I _can_ SFTP. But a 3 MB file is announced to need > 6 minutes. I have a 50 MBit/s upstream. The bitrate display is most the time 0 B/s

Sorry for the confusion

**Comment by LeChatNoir666** [comment]
I have exact the same problem as shown in the picture above me...
I counter checked it with WinSCP and Filezilla. 
Both runs with max speed but muCommander have problems...
