### ISSUE TITLE
4K Screens

### ISSUE THREAD

**Issue by gentisle** [mucommander/mucommander#188]
Have Windows 10 on a 4K screen, and I was able to play around with the fonts and improve the look, but so far, all of the dialogs are too small to read. Would be nice to see a version that deals with the 4K screen issues. Thanks.

**Comment by mrserb** [comment]
Note HiDPI screens are supported by the JDK 9+

**Comment by ahadas** [comment]
Closing, should be fixed in v0.9.4. Please feel free to reopen if needed.

**Comment by gentisle** [comment]
OK, thanks. I tried it, but first have to install Java 11 according to the dialog that popped up.

**Comment by ahadas** [comment]
> OK, thanks. I tried it, but first have to install Java 11 according to the dialog that popped up. Love that "Red Hat" you have.

Note that you can also download a package that is bundled with JRE:
https://github.com/mucommander/mucommander/releases/download/0.9.4-2/mucommander-0.9.4-2-bundled.exe
