### ISSUE TITLE
Java SE 6

### ISSUE THREAD

**Issue by Dan-Essin** [mucommander/mucommander#192]
Hello,
Security issues aside, don't you think that it's time to recompile with an up to date JDK?

**Comment by ahadas** [comment]
Hi @Dan-Essin ,
You mention Java 6 in the title - note that the latest version is compiled with Java 8.
As for moving to a newer version of Java, we faced some issues with libraries we use internally and deployment issues on macOS. But yeah, that's definitely one of the tasks for the next version(s).
