### ISSUE TITLE
internal text editor adds ï»¿ at the beginning of text file, UTF-8 encoding, macOS

### ISSUE THREAD

**Issue by wwwguru-eu** [mucommander/mucommander#193]
Internal text editor adds 3 unwanted characters/bytes "ï»¿" at the beginning of the file, UTF-8 encoding, macOS.

To replicate: copy the empty (0 Bytes) file to somewhere, edit from muCommander, set encoding to UTF-8, type something: "asdfg", save.

Open it again (F4) and change the encoding to ISO-8859-1 (or any other ANSI encoding) and you see three unwanted bytes at the beginning of the text file:
ï»¿
it is: 0xef 0xbb 0xbf (hexdump ef bb bf 61 73 64 66 67 0a)

**Comment by ahadas** [comment]
Hi @wwwguru-eu ,
We intentionally write these bytes at the beginning of the stream. This is a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) we write at the beginning of the text stream in order to be able to detect exact UTF encoding when reading the content of the file. But you're right that they should not appear when switching to a non-UTF encoding.

**Comment by wwwguru-eu** [comment]
Hi Arik,

Thank you very much for your info.

This causes the problems - for example I have edited some php file, switched to UTF-8 encoding and after uploading to the web server this script stopped to work (showed these three bytes as some unexpected data instead of <?php at the beginning of this file). It took me some time to investigate that the source of the problem was MuCommander (when edited with vi this script worked fine)...

On macOS and other unixes I think there is some info about the file encoding and file type stored in the file system (try cat > a, type some ASCII like aaa and ctrl.c, then file a will show info it is ASCII file, then vi a a type some UTF-8 chars, :wq and file a will show it is UTF-8 encoded file), so I would suggest to delete these three bytes in macOS (linux) versions of MuCommander and instead of putting these bytes into the file gather the file encoding info from the filesystem.

On Windows I do not care - I do not use Windows since 2006...

I expect the same result no matter if I edit some file using MuCommander or vi or PhpStorm or anything else: only UTF-8 characters should be there, but no additional bytes at the beginning o the file (to help to identify the file encoding).

I hope you could be able to fix this annoying bug/feature as soon as possible.

Have a great day
Miroslav

**Comment by ahadas** [comment]
@wwwguru-eu , if that disturbs your work I can suggest how to disable that - but you'll need to run mucommander from source, would you be interested in that?
I think we can maybe save the BOM as part of the file's extended attributes once we have #194 in.

**Comment by wwwguru-eu** [comment]
Hi Arik,

Thank you.

For me - I have stopped to use MuCommander for editing UTF-8 files, I have just reported that bug to help you to make better product.

Have a nice day
Miroslav

**Comment by ahadas** [comment]
@wwwguru-eu , note that you can also replace the integrated editor in muCommander with another one that better fits your need. You'll need to create a [custom commands file](https://github.com/mucommander/mucommander/wiki/Custom-Commands) like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="edit"    value="emacs $f"            type="system"/>
    <command alias="view"    value="emacs $f"            type="system"/>
</commands>
```
This example uses emacs but you can replace it with the one you wish to use.

**Comment by jamazurak** [comment]
I think that you should give a choice to the user. I didn't know about that and had troubles with decrypted secrets that were saved within muCommander editor. And I was wondering why 36-byte long text occupies 39 bytes. After switching to another encoding I realized that there were extra characters. When I watched an error log I still didn't see those extra characters.
Personally, I hate any hidden data out of my control in the files.
![зображення](https://user-images.githubusercontent.com/25476873/159462462-6ca668b7-a1b7-46c0-b7d3-c2426a7acef9.png)
![зображення](https://user-images.githubusercontent.com/25476873/159462505-0f993366-204f-4134-85ef-a93a2ae98774.png)

**Comment by pskowronek** [comment]
If it is still an issue please re-open (there were some improvements regarding Text Editor and UTF-8).
