### ISSUE TITLE
[REQUEST] Space = show folder size recursively

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mucommander/mucommander#198]
When press "Space" show selected folder size recursively like Total Commander doing this..

**Comment by olivierpaul** [comment]
A work around is to do : File -> Properties (or Alt + Enter)
This will open a popup with the requested information

**Comment by ashlinchak** [comment]
This is a very important feature for a file manager. Looking forward to it.

**Comment by bgbruno** [comment]
cannot find any shortcut - for "folder size"

Q exist any ?

**Comment by ahadas** [comment]
The 'view' operation (defaults to F3) now (as from 0.9.6) calculates the size of selected directories and show it on the grid
