### ISSUE TITLE
macbook restarts when tried to view attached file

### ISSUE THREAD

**Issue by wwwguru-eu** [mucommander/mucommander#199]
Hi,

this is some strange bug: when I view (unpacked) attached file in muCommander, my macbook restarts immediately. MacOs version High Sierra 10.13.3.

[test.zip](https://github.com/mucommander/mucommander/files/3043011/test.zip)

**Comment by kousalik** [comment]
Can't reproduce. Most likely environmet specific. Can't see anything wrong with the file. @ahadas I would say we can reject this one.

**Comment by sskras** [comment]
In any case, that would indicate at least a small problem with the OS itself (not only with the app, if any).

**Comment by pskowronek** [comment]
Cannot produce, closing.
