### ISSUE TITLE
Need a refresh button and refresh right click menu item, or auto-refresh

### ISSUE THREAD

**Issue by Capri205** [mucommander/mucommander#200]
Hi. Very nice product except it needs a refresh button on the panel and on the right click menu for the panel. I know F9 is there but this isn't as convenient as working it through the mouse. Another nice feature would be to auto-detect changes to the files in the panel. I use Eclipse which updates the files and when I switch back to muCommander it would be really nice to see the files already refreshed.

Cheers!

**Comment by ahadas** [comment]
Hi @Capri205 , thanks for reporting this!
Regarding the button - did you notice the refresh button in the commands panel (at the bottom, below the panels)?
Refresh on the right-click menu can be nice, I agree.
Regarding the auto-detect changes - it should actually work. So you switch between to Eclipse, update files and when switching back to muCommander those files that appear on one of the panels are not updated? Are the files in a local folder?

**Comment by Capri205** [comment]
ah. ok. I didn't realize it's a button. That's perfect then! I found one
other things tripping me up was that a particular project in Eclipse
wouldn't update the timestamps on the jar files when it was rebuilt because
nothing had changed. So no amount of refreshing will change that timestamp.
Once I changed something and rebuilt I went back to muCommander but the it
hadn't auto-detected the changes. All local files. Not a problem though as
I always refresh and the refresh button fixed that, so all is good. Thanks
for the prompt responses!

**Comment by ahadas** [comment]
Alright, glad to see the button in the commands panel satisfies your needs :)

I'm interested to know why the changes were not reflected in muCommander though - do I understand currently that you've been in the `build` folder where the jars are created and you saw the jars with their previous modification time? On what operating system?

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
