### ISSUE TITLE
muCommander doesn't remember window placement and size

### ISSUE THREAD

**Issue by Hejsana** [mucommander/mucommander#201]
Hi everyone!

I have a problem with the placement and size of MuCommander window. Beginning from the version 0.9.2 it opens in its default size and location. When I try to resize it and change its location, after closing and running it again, it forgets my setting of placement and size. Is there any way to "teach" MuCommander to keep my way of placement and size? There was no such problem in previous versions (including 0.9.1).

Thanks in advance!

**Comment by ahadas** [comment]
Hi @Hejsana ,
Thanks for reporting this! That's funny as I've also noticed that yesterday.
I see that it doesn't work on the master branch but it works fine up to version 0.9.3 on my machine - what version do you run (it is presented in the About dialog) and on what operating system?

**Comment by Hejsana** [comment]
Hi,
Thanks for replying to my posting... Currently I run the latest version 0.9.3, build date: 2019/01/12, build number: df79168
Operating System: MacOS 10.13.6 High Sierra (fresh install couple days ago).
I don't want to return to version 0.9.1 :)

    On Thursday, April 25, 2019, 12:13:58 AM GMT+4, Arik Hadas <notifications@github.com> wrote:  
 
 
Hi @Hejsana ,
Thanks for reporting this! That's funny as I've also noticed that yesterday.
I see that it doesn't work on the master branch but it works fine up to version 0.9.3 on my machine - what version do you run (it is presented in the About dialog) and on what operating system?

**Comment by ahadas** [comment]
@Hejsana Can you please share the `preferences.xml` and `snapshot.xml` files that you'll find under `~/Library/Preferences/muCommander/`?

**Comment by Hejsana** [comment]
Sure, I can :)

    On Friday, April 26, 2019, 1:26:51 AM GMT+4, Arik Hadas <notifications@github.com> wrote:  
 
 
@Hejsana Can you please share the preferences.xml and snapshot.xml files that you'll find under ~/Library/Preferences/muCommander/?

**Comment by ahadas** [comment]
Great, that may shed more light on this since I cannot reproduce it with 0.9.3

**Comment by Hejsana** [comment]
I hop so... :) Thanks again for your kind help!
Regards,
David

    On Friday, April 26, 2019, 1:42:26 AM GMT+4, Arik Hadas <notifications@github.com> wrote:  
 
 
Great, that may shed more light on this since I cannot reproduce it with 0.9.3

**Comment by ahadas** [comment]
Sure, you can use upload them to this issue or using [FPaste](https://paste.fedoraproject.org) if you like

**Comment by ahadas** [comment]
@Hejsana ping, the preferences files?

**Comment by Hejsana** [comment]
Hi,

I apologize for replying so late... We have Easter Holidays in Georgia now and I was not able to get to my Mac. I was out of the city. I will upload them soon.

Thanks!

**Comment by Hejsana** [comment]
[Preferences & Snapshot.zip](https://github.com/mucommander/mucommander/files/3127484/Preferences.Snapshot.zip)

**Comment by ahadas** [comment]
@Hejsana, thanks for sharing those files.
Seems that the problem is caused by setting the starup folders to custom ones - the size and location is saved to `preferences.xml` but they are not restored because of that configuration (Imagine that you have several windows and then quit, it's not clear what size and location shoukd be used in that case, of which window).
Do you really need to set the startup folders to custom ones? Changing it to the last folders (via the preferences->folders dialog) is a possible workaround until we figure out how shoukd this work with custom startup folders

**Comment by Hejsana** [comment]
Hi again,
Thanks a lot for suggesting this perfect solution! It worked like a charm... The only thing is that after using this App, I will have to return manually to the root folder of my main drive (on both panels). That's it :)
Thanks again! You saved my nervous system :)

    On Tuesday, April 30, 2019, 1:27:25 PM GMT+4, Arik Hadas <notifications@github.com> wrote:  
 
 
@Hejsana, thanks for sharing those files.
Seems that the problem is caused by setting the starup folders to custom ones - the size and location is saved to preferences.xml but they are not restored because of that configuration (Imagine that you have several windows and then quit, it's not clear what size and location shoukd be used in that case, of which window).
Do you really need to set the startup folders to custom ones? Changing it to the last folders (via the preferences->folders dialog) is a possible workaround until we figure out how shoukd this work with custom startup folders

**Comment by ahadas** [comment]
Glad to see it helps :) keeping this open for now, we'll see if we can come up with some solution for custom folders

**Comment by Hejsana** [comment]
Sure! It will be great...
