### ISSUE TITLE
exe installer doesn't recognize already installed JDK

### ISSUE THREAD

**Issue by tikomir** [mucommander/mucommander#207]
If Java, eg. Open JDK 12 is being inslalled using zip distribution,
mucommander exe installer won't start at all saying that JDK is not installed,
despite the fact that JAVA_HOME environment variable is being set correctly.
It seems that the installer doesn't check for the existence of that variable at all.

**Comment by ahadas** [comment]
@tikomir Hi, the nickname sounded familiar - welcome back :)
Interesting... I would expect the installer not to require the development kit...
I'll look at this when adjusting the packaging for 0.9.4  - thanks for reporting this!

**Comment by tikomir** [comment]
Hi Arik. Thank you for your welcome.

Sorry, but I was wrong in a bit. It happened that I wrote the post by rote. In fact, installer works and on Win10 it installs mucommander in a path "C:\Program Files (x86)\muCommander". But, when I try to run it, it says "This application requires a Java Runtime Environment 1.8.0". Closing the dialog causes automatic opening of the web page "https://www.java.com/en/download/". Now, I remembered that the very same thing also happened with JEdit.
However, already installed MC should check for the existence of the JAVA_HOME variable as this variable is part of the standard and recommended way of Java installation. In fact, MC should check for the JAVA_HOME or JRE_HOME, as bot are valid environment variables regarding Java installation.

**Comment by ahadas** [comment]
@tikomir hi, as from 0.9.4 we'll have the JRE bundled with muCommander and that should prevent this issue. However, you made me think of the case where the user has a newer JRE than the bundled one. The posted PR #261 defines the bundled JRE as fallback but I'm afraid it makes the startup process significantly slower. So I wonder if searching for a newer JRE installed would worth it, what's your opinion on that?

**Comment by tikomir** [comment]
I'm against MC+JRE bundle but if you really want it, than the bundled version should be given as an optional download. Unbundled version should let the `mucommander.exe` check for the existence of the `JAVA_HOME\bin\java.exe` or `JRE_HOME\bin\java.exe` or `JDK_HOME\bin\java.exe` in that order. Whatever it finds first, it should start MC.jar using that finding otherwise an alert that JAVA_HOME is expected to be set should be shown.

p.s.
Bundling JRE with an app is not a common solution. The only application I can think of right now is the IDEA and its derivatives but JetBrains have sound reason for that.

**Comment by ahadas** [comment]
@tikomir , thanks for pointing this out. PR #278 enables to choose whether the Windows installer is bundled with the JRE or not and we will provide both options.
