### ISSUE TITLE
Locales not working on OS X 10.11.4 with Java 1.8.0_72

### ISSUE THREAD

**Issue by sebastian-lempert** [mucommander/mucommander#21]
I am using OS X 10.11.4 with Java 1.8.0_72. When building muCommander (head, checked out 5 minutes ago from https://github.com/mucommander/mucommander) with

`./gradlew createDmg`

the resulting binary contains strings / locales that are not working / that are not correctly displayed. I am using German / Deutsch, the corresponding translation should be contained in the file dictionary_de.properties but other languages seem to have the same problem.

Are the files that can be found at https://github.com/mucommander/mucommander/tree/master/src/main/resources still correct? When viewing these files in a browser (Firefox 45.0.2) they are not correctly displayed too (for example see https://github.com/mucommander/mucommander/blob/master/src/main/resources/dictionary_de.properties).

Maybe it is an issue with the corresponding file encoding? If so the following information might be useful: The terminal command

`file -I dictionary_de.properties `

gives

`dictionary_de.properties: text/plain; charset=unknown-8bit`

**Comment by ahadas** [comment]
Fixed
