### ISSUE TITLE
Reselection of previously selected files

### ISSUE THREAD

**Issue by tikomir** [mucommander/mucommander#210]
Don't like the behaviour where after copying the selected files, those files became unselected.
I would like to have them selected even after the action has been performed,
or at least to have a way to reselect them with a shortcut. Perhaps "Ctrl+NumPad *" would be appropriate?

**Comment by ahadas** [comment]
@tikomir , can you please provide a use-case in which it is useful? Would a setting like "keep current file selection" make sense?

**Comment by tikomir** [comment]
No, not the setting.  A menu item would fit my need.

Now, the use case. I don't use any of the backup software, but like to do it myself, and sometimes I use software for folder synchronization. So, when I copy items from one folder ina a left pane, I have to copy them on a various places in the right pane: another partition, external HD, FTP. That's why I like to have all selected items remain selected after copying.
Another use case is to check the size of the copied items volume. It happened that when I used Windows Explorer to copy items fro one partition to another, it reported that some items were not copied due to a too long path names. MC doesn't report such problem, but I like to retain selection to have an opportunity to check out the size of the selected and copied items.

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
