### ISSUE TITLE
Checking update not working

### ISSUE THREAD

**Issue by SGvagon** [mucommander/mucommander#215]
I can't check update after start MuCommander. There is only a message, that program can't get info about version. I am using the last version v0.9.3 on Windows 7 PRO x64bit.
Thank you in advance.

**Comment by ahadas** [comment]
@SGvagon Thanks for reporting this. It is caused by a recent change to the website that switched it from http to https. Apparently, muCommander was not prepared for such change.

**Comment by ahadas** [comment]
Disabled the `Enforce HTTPS` option on github so it should work now.
Needs to change the URL of version.xml to use HTTPS on 0.9.4

**Comment by SGvagon** [comment]
Yes, now it fixed :) . Thank you.
