### ISSUE TITLE
Opening a specific file via commandline only opens the files parent

### ISSUE THREAD

**Issue by hupfdule** [mucommander/mucommander#219]
When calling 

```
mucommander /etc/fstab
```

it opens the mucommander window (with the bug described in #218) with the directory `etc` opened.

However, since I have specified a specific file in that directory, it should actually additionally jump to and select that file.

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
