### ISSUE TITLE
SFTP Not Working in 0.9.3 on Windows 10 With Linux OpenSSH openssh-server-5.3p1-123 on Centos 6

### ISSUE THREAD

**Issue by johjeff** [mucommander/mucommander#228]
Password authentication is accepted by the OpenSSH server. I tried with login name / password and private SSH key and it doesn't work with either. FTP from muCommander works great. Command line SSH and SFTP works great. Filezilla works great using just login / password.

My Java Version:
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.3, JRE 11 Windows 10 amd64-64-Bit Compressed References 20190531_235 (JIT enabled, AOT enabled)
OpenJ9   - b8ab01656
OMR      - b56045d2
JCL      - dcdc97f9dc based on jdk-11.0.3+7)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
