### ISSUE TITLE
Development - Packaging tasks not working

### ISSUE THREAD

**Issue by sandreas** [mucommander/mucommander#232]
Hey,

I forked *mucommander* and applied some personal patches. Now, that I would like to use the latest improvements, I did not find a way to `build` or package an installable version of the code and there are no nightly builds.

As far as i see, none of the *official* readme packaging tasks is working atm (at least not on my system):

```
./gradlew shadowJar 
./gradlew createDmg
./gradlew createExe
./gradlew tgz
```

Some of the mentioned tasks are commented out in the `build.gradle`, but commenting them in leads to gradle errors (i think this is why they are commented out).

This is working:
```
 ./gradlew buildRpm
```
And with some modifications this is also working:
```
 ./gradlew buildDeb
```

What can I do to get a fully working version of mucommander out of the sourcecode?

**Comment by ahadas** [comment]
Yes, that's true, most of the packaging options were commented out during the transition to OSGi.
Well, now that the basic functionality works again, we can start fixing the packaging part.
What operating system do you test on?

**Comment by sandreas** [comment]
Oh, this was quick :-) Thank you. I work on Ubuntu 18.04 LTS with GNOME and MacOS.

**Comment by ahadas** [comment]
:)
So fixing the `deb` packaging should be easy as it is similar to `rpm` packaging.
Packaging MacOS's `app` would probably be more tricky, need to investigate the Gradle plugin we use

**Comment by ahadas** [comment]
@sandreas just to avoid duplicate work - would you like to work on fixing those packaging options? if so, which one?

**Comment by sandreas** [comment]
Well I'm not totally new to `gradle` but the osgi thing is nothing i worked with in the past. I already tried to fix some things, but i did not succeed.... (I got a working deb package, but mucommander did not start after installing). Anyhow I'm also busy in the next days, so if you would like to take a look, it would be great - I'm not in a hurry and in the next days i won't have the time to take a look / learn gradle with osgi.

I already mentioned the *hot-swap* thing, but i think it also belongs to this issue. This approach for OSGi looks promising and could possibly speed up development - see chapter 4:

https://sites.google.com/a/athaydes.com/renato-athaydes/posts/4freewaystohot-swapcodeonthejvm

For me coding atm is very time consuming because on every code change i have to:

```
# stop gradle manually in IntelliJ
./gradlew clean runOsgi # otherwise code changes are not detected
```

This takes pretty long for a recompile... If there is a better approach, i would love to see how its done, then i will document it in the readme.md develoment section...

**Comment by ahadas** [comment]
> Well I'm not totally new to `gradle` but the osgi thing is nothing i worked with in the past. I already tried to fix some things, but i did not succeed.... (I got a working deb package, but mucommander did not start after installing). Anyhow I'm also busy in the next days, so if you would like to take a look, it would be great - I'm not in a hurry and in the next days i won't have the time to take a look / learn gradle with osgi.

Just an update - the packaging for Debian/Ubuntu should work now.

**Comment by sandreas** [comment]
>Just an update - the packaging for Debian/Ubuntu should work now.

Thank you. Building now works, but running mucommander with the shell script, produces following error:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/share/mucommander/system-libs/org.apache.felix.main-6.0.3.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Unable to create cache directory: ./felix-cache
ERROR: Error creating bundle cache.
java.lang.RuntimeException: Unable to create cache directory.
        at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:135)
        at org.apache.felix.framework.Felix.init(Felix.java:703)
        at org.apache.felix.framework.Felix.init(Felix.java:641)
        at org.apache.felix.main.Main.main(Main.java:289)
Could not create framework: org.osgi.framework.BundleException: Error creating bundle cache.
org.osgi.framework.BundleException: Error creating bundle cache.
        at org.apache.felix.framework.Felix.init(Felix.java:708)
        at org.apache.felix.framework.Felix.init(Felix.java:641)
        at org.apache.felix.main.Main.main(Main.java:289)
Caused by: java.lang.RuntimeException: Unable to create cache directory.
        at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:135)
        at org.apache.felix.framework.Felix.init(Felix.java:703)
        ... 2 more

```

**Comment by ahadas** [comment]
@sandreas Thanks for let me know about this. Interestingly, it didn't happen to me (I wonder why..). It appears that I forgot to create that `felix-cache` directory as we do during the installation of RPMs.

Pushed a fix to the master branch, but it seems that the packaging would need to be further adjusted to enable packaging for MacOS and to resolve #237

**Comment by ahadas** [comment]
Closing, all packaging options should work now.
