### ISSUE TITLE
Can't duplicate a file

### ISSUE THREAD

**Issue by yaomtc** [mucommander/mucommander#238]
I want to copy a file and paste it into the same folder. In other file manager apps on MacOS I've tried, simply copying and pasting into the same folder works, and it adds "copy" to the name of the new file. In MuCommander, though, there is no Duplicate option or ability to copy a file into its own directory.

"Source and destination folders are the same

( Cancel ) ( Skip )"

I am using 0.9.3 on MacOS High Sierra (10.13.6)

**Comment by 5andi5** [comment]
@yaomtc try _Local Copy (Shift + F5)_

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
