### ISSUE TITLE
Future Releases' Java Version Requirements?

### ISSUE THREAD

**Issue by mkortkamp** [mucommander/mucommander#24]
The current code base needs at least Java 7.
At the same time I see git comments about assuring Java 6 compatibility and OSX App metadata specifying 1.6+ compatibility.

Are you going to drop 1.5 and 1.6 compatibility in the next release or is any current  1.7 dependency actually a bug that still needs to be fixed before the next release.

**Comment by ahadas** [comment]
Hi,
The next release should still be compatible with Java 6.
It would probably be the last one to preserve this compatibility, and future releases will be provided in 2 forms: with and without jre included.

So yeah, if the current code base is not compatible with Java 6 then it is a bug.

**Comment by ahadas** [comment]
The compatibility with Java 1.6 is fixed.
Note that 0.9.1rc is now available:
https://github.com/mucommander/mucommander/releases/tag/0.9.1rc
