### ISSUE TITLE
Cant attach to the taskbar

### ISSUE THREAD

**Issue by lxwulf** [mucommander/mucommander#258]
muCommander has no options to attach to the taskbar

**Comment by lxwulf** [comment]
> 
> 
> muCommander has no options to attach to the taskbar

![image](https://user-images.githubusercontent.com/44492381/71770709-23931980-2f30-11ea-8ce4-ecc54aa059c1.png)

okey interessting when i pin it via start and reboot it is in the taskbar but when i start it starts its own session in a new window 

![image](https://user-images.githubusercontent.com/44492381/71770717-3b6a9d80-2f30-11ea-9943-d071cf01c5bf.png)

**Comment by ahadas** [comment]
@lxwulf thanks for reporting this! the timing is good, while I'm working on Windows package (#259 ) :) I'll look at it soon

**Comment by lxwulf** [comment]
no problem everytime again =D

**Comment by ahadas** [comment]
@lxwulf would you be able to verify the fix?

**Comment by lxwulf** [comment]
yes i would do it asap 😁

**Comment by lxwulf** [comment]
> 
> 
> @lxwulf would you be able to verify the fix?
ehm yes but eh...do you have a finished binary file? 👉👈😅

**Comment by ahadas** [comment]
@lxwulf oh right, the installer can be downloaded from: https://tinyurl.com/yxx2r835

**Comment by lxwulf** [comment]
> `@lxwulf would you be able to verify the fix?`

![grafik](https://user-images.githubusercontent.com/44492381/72050031-7702c000-32c0-11ea-959b-728a0a30c395.png)

still no attach menu on windows 10 1903 🤔

**Comment by ahadas** [comment]
> > `@lxwulf would you be able to verify the fix?`
> 
> ![grafik](https://user-images.githubusercontent.com/44492381/72050031-7702c000-32c0-11ea-959b-728a0a30c395.png)
> 
> still no attach menu on windows 10 1903 thinking

Interesting, could you please copy the first two sections in the 'Version information' part of the 'About' dialog ("muCommander" and "Java")?

**Comment by lxwulf** [comment]
F* sry i forgot to compile it i just downloaded 0.9.3 😓 how can i compile it? for that i need a java envirement like eclipse or so right?

**Comment by ahadas** [comment]
No worry :)
You don't have to compile it, I've created a binary installer that can be downloaded from: https://tinyurl.com/yxx2r835

**Comment by ahadas** [comment]
@lxwulf  any update?

**Comment by lxwulf** [comment]
@ahadas sry had alot to do ^^

however i can just say: congratulation! it works now!

![grafik](https://user-images.githubusercontent.com/44492381/72143736-87d23500-3397-11ea-9125-efc244aa88f5.png)

now just only the scp implementation and this so far one of the best "file commanders" out there =D

**Comment by ahadas** [comment]
@lxwulf  cool, happy to hear. Thanks for the feedback :)

**Comment by lxwulf** [comment]
everytime again, ✌

**Comment by m4xence** [comment]
Just tested the fix, also works for me!
