### ISSUE TITLE
RFC: installing a newer version on Windows

### ISSUE THREAD

**Issue by sskras** [mucommander/mucommander#263]
Hey,

I am interested in a way to update the existing (non-portable) v0.9.3 to eg. [v0.9.4-testing](https://tinyurl.com/yxx2r835). Should I uninstall the older one at first, or should I just go with the newer installer and overwrite old files?

Wouldn't that mess the uninstall info?

**Comment by ahadas** [comment]
Hi @sskras ,
You can go with the newer installer that will override old files and registry entry, there's no need to uninstall the previous version.
