### ISSUE TITLE
Copy-remotely for SFTP

### ISSUE THREAD

**Issue by lxwulf** [mucommander/mucommander#265]
Wouldnt be nice to transport from server to server?

**Comment by ahadas** [comment]
@lxwulf Thanks for the suggestion. There's a support for server to server transmission already but only for certain protocols. For which protocol you mean?

**Comment by lxwulf** [comment]
for scp would be nice maybe im just blind 😅

**Comment by ahadas** [comment]
I see. Remote-copy is currently indeed [unsupported for SFTP](https://github.com/mucommander/mucommander/blob/master/mucommander-protocol-sftp/src/main/java/com/mucommander/commons/file/protocol/sftp/SFTPFile.java#L560) but apparently the library we use [supports it](https://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/ChannelSftp.html#get-java.lang.String-java.io.OutputStream-) so we can give it a try

**Comment by lxwulf** [comment]
nice when i habe time i would help you so far i can help im not the best and new to coding 😁✌🐺

**Comment by ahadas** [comment]
> I see. Remote-copy is currently indeed [unsupported for SFTP](https://github.com/mucommander/mucommander/blob/master/mucommander-protocol-sftp/src/main/java/com/mucommander/commons/file/protocol/sftp/SFTPFile.java#L560) but apparently the library we use [supports it](https://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/ChannelSftp.html#get-java.lang.String-java.io.OutputStream-) so we can give it a try

Actually, I was wrong - that API doesn't enable direct server to server communication. This seems to require setting authentication details for the target server at the source server, something that is beyond the scope of muCommander to do, or to introduce another protocol that supports this kind of communication, like [FXP](https://en.wikipedia.org/wiki/File_eXchange_Protocol) that doesn't seem to be so common. Need to see if there's a good alternative that provides this.

**Comment by ahadas** [comment]
Without a third-party tool/library that provides this, it is unlikely to be implemented in muCommander - closing
