### ISSUE TITLE
RFE: Option to close `Run command` dialog after command execution

### ISSUE THREAD

**Issue by mardukbp** [mucommander/mucommander#269]
In version 0.9.3 it is possible to execute a command in the current directory. However, it is desirable to be able to execute a command on the selected file, like `java -jar`.

**Comment by ahadas** [comment]
@mardukbp you mean in the `Run command` dialog, right? you'll need to provide the filename to the `java` command in your example, I don't see how we can avoid that. For this, one can use the copy path/name shortcut and then paste it in the dialog. Do you see a way to improve this?

**Comment by mardukbp** [comment]
Thanks Arik. That helps. It would be nice to have a checkbox to choose to automatically close the run command window after the execution. 

Am 10. Februar 2020 14:08:21 MEZ schrieb Arik Hadas <notifications@github.com>:

**Comment by ahadas** [comment]
@mardukbp yeah, that's something we can do :) thanks for the idea

**Comment by ahadas** [comment]
related to #661

**Comment by ahadas** [comment]
@mardukbp we integrated the operating system's terminal into the Run-command dialog so it would be possible to close the dialog after the command execution, not with a checkbox but rather with `<command>;exit` on Linux/macOS or `<command> & exit`

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)

**Comment by mardukbp** [comment]
@ahadas Perfect! Thanks!
