### ISSUE TITLE
When will there be a new release?

### ISSUE THREAD

**Issue by dlrourke** [mucommander/mucommander#272]
I realize that we are getting infinitely more than we paid for, but as of Feb. 17, 2020 there have been 279 commits.  Are there plans for a new release anytime soon?

Thanks in advance!

**Comment by ahadas** [comment]
Absolutely! wrapping up the packaging side these days and I think we will be good to go.

**Comment by dlrourke** [comment]
Thank you!!!  I'm sure I'm not the only one looking forward to this.  Thank you from all of us!

**Comment by sandreas** [comment]
I would suggest building specific tags/branches and nightlies with github actions... it might seem like a lot of work, but perhaps this is something that would solve a lot of problems and save much time in the long term having automatic builds for every system...

**Comment by aadrian** [comment]
@sandreas https://travis-ci.org/ is already been used by this project, see https://github.com/mucommander/mucommander/blob/master/.travis.yml  (no need to move to github actions)

So it's not a matter of employing a CI or not, but writing the pipeline steps to produce and publish the artifacts.

**Comment by ahadas** [comment]
@sandreas , @aadrian +1 on the need for automatic packaging for the various systems and generating nightly builds. And yes, need to find the best way to achieve this and specifically, where can we store those artifacts. I've read a post about someone replacing the artifacts through Github API which may be the way to go. I suggest we'll further discuss this on gitter and keep this issue for releasing v0.9.4.

**Comment by ahadas** [comment]
Version 0.9.4 has been released
