### ISSUE TITLE
Firewall issue

### ISSUE THREAD

**Issue by kennybroh** [mucommander/mucommander#281]
On the Mac, even though I enabled incoming connections, every time MUCommander starts up it asks me whether to allow or block.

**Comment by ahadas** [comment]
Hi @kennybroh , can you try to disable "Check for updates on startup" at the Preferences/Misc dialog? I suspect that the outgoing connection to the website is what triggers your firewall

**Comment by ahadas** [comment]
Closing, please feel free to reopen if needed.
