### ISSUE TITLE
Save settings issue

### ISSUE THREAD

**Issue by Chodec80** [mucommander/mucommander#286]
Hi,
version 0.9.4 ignores my settings regarding to Hidden files and Command bar. I disabled both of them but after restart the app are both settings active again (ie. I see hidden files and also I see Command bar). Version 0.9.3 doesn't have this issue.
I tried a clean install and also update (ie. "replace" during installation) from 0.9.3 but without any success.
(MacOs 10.15.3)

**Comment by ahadas** [comment]
Version 0.9.4-2 with the fix has been released
