### ISSUE TITLE
Native menu in Ubuntu

### ISSUE THREAD

**Issue by kachkaev** [mucommander/mucommander#30]
When mucommander is running on OSX, the menu is natively shown at the top of the screen:
![screen shot 2016-06-01 at 12 23 26](https://cloud.githubusercontent.com/assets/608862/15708179/f9b58972-27f4-11e6-9c11-4efca3a87d7d.png)

This is very convenient because of the consistency.

The same thing does not seem to happen on Ubuntu when the OSX-like menu is enabled system-wide:
![screenshot from 2016-06-01 12-30-29](https://cloud.githubusercontent.com/assets/608862/15708144/c6e388fa-27f4-11e6-95ab-ec1c80c1a30c.png)

It would be good if the menu component on Ubuntu could appear at the top of the screen as well. Native Ubuntu menu can be searched after pressing Alt, which is quite useful. This feature does not work now:
![screenshot from 2016-06-01 12-29-51](https://cloud.githubusercontent.com/assets/608862/15708149/cb97212c-27f4-11e6-9483-7dc478ccacc9.png)

Cheers!

**Comment by ahadas** [comment]
hi @kachkaev ,
it is not trivial to add because of the custom class loader we use in order to support extensions.
but if you didn't add extensions, you can easily achieve that by editing
/usr/bin/mucommander
and replacing the line that begins with JAVA_ARGS="-Djava.system..."
with: JAVA_ARGS="-javaagent:/usr/share/java/jayatanaag.jar"

**Comment by kachkaev** [comment]
Thanks! I'll have a look at this if find the current menu too annoying (not doing much with muc now, so a few shortcuts I remember are enough). Could this be made an option in future by a chance? A user puts a tick in settings and reboots. Done.

**Comment by ahadas** [comment]
sure, I'm keeping this issue open for a proper solution :)

**Comment by thomasuebel** [comment]
I would like to look into it, but Ubuntu will ship with Gnome3 starting with version 18.04. Will this still be worth the effort?

**Comment by ahadas** [comment]
@thomasuebel, Yeah.. I'm not sure that it worth the effort. If you wish to make some contribution then I would say that there are more important ones. But if you're interested specifically in this enhancement then that will also be welcome.

**Comment by ahadas** [comment]
We didn't do that and it doesn't make sense anymore
