### ISSUE TITLE
Quitting mucommander creates a ~/.osgiaas_cli_history file

### ISSUE THREAD

**Issue by biwqn** [mucommander/mucommander#303]
On macOS, quitting mucommander creates a blank file called .osgiaas_cli_history in the user's home directory. It would be nice to not have this file cluttering the home directory. Thanks!

**Comment by ahadas** [comment]
@biwqn thanks for reporting this! it is a side-effect of having the OSGi command line interface packaged with the other application components. The fix is to exclude it as it is not needed in packages intended for end-users.
