### ISSUE TITLE
v0.9.4 shows empty License window

### ISSUE THREAD

**Issue by sskras** [mucommander/mucommander#304]
I just have downloaded the latest version (v0.9.4) and installed it over the older one.
When I go to menu > Help > About > License, I get empty, narrow window:

![2020 03 26-18_52_44__muCommander_v0 9 4_exhibiting_bug_in_the_License_window](https://user-images.githubusercontent.com/7887758/77676114-87106e80-6f96-11ea-8a06-6f226706e3c0.gif)

(Black parts of the window titlebar and borders occur only in the captured video, not on my desktop)

**Comment by sskras** [comment]
> Version information
> 
> muCommander
> Version: 0.9.4
> Build date: 2020/03/08
> Build number: 8f24dfc
> 
> Java
> Runtime version: 11.0.4
> VM name: OpenJDK 64-Bit Server VM
> VM version: 11.0.4+11
> VM vendor: AdoptOpenJDK
> 
> OS
> Name: Windows 10
> Version: 10.0
> Architecture: amd64
> 
> Locale
> Language: en
> Country: US
> Encoding: Cp1257
>

**Comment by ahadas** [comment]
@sskras thanks for reporting this. It is a regression in 0.9.4 related to the switch to OSGi bundles.
