### ISSUE TITLE
Enhancement in handling of archives

### ISSUE THREAD

**Issue by alexey-lysiuk** [mucommander/mucommander#31]
It will be nice to have an ability to detect an archive (and to browse it like a regular directory) by its actual content, not just by its file extension.
Or at least, to have an ability to specify additional extensions for known archive types. Many applications and games use .zip's to store their assets but with different file extensions.

**Comment by ahadas** [comment]
Detecting the type of a file by examining its content rather than its extension is hard to do efficiently

The "Open as.." action that was added in Dec 2016 (sorry for now updating here before..) enables to do that - users can ask to open a file as a specific type regardless of its extension.
