### ISSUE TITLE
"One or more files could not be moved to Trash"

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#321]
I just updated to 0.9.4-2 on my Mac (Catalina), and  am now having a lot of trouble deleting files. Every time I try, I get the error message above. If I deselect "Move to Trash," permanent deletion from muCommander works fine, so it seems to be specifically a Trash issue.

**Comment by ahadas** [comment]
@rhstanton hi, did you use a previous version of muCommander before?

**Comment by rhstanton** [comment]
I did. The previous version worked fine.

**Comment by ahadas** [comment]
Can you try to execute `sudo tccutil reset All`?

**Comment by rhstanton** [comment]
Same error message afterwards, I’m afraid.

**Comment by ahadas** [comment]
I see, thanks for trying. I've noticed this on one of the machines of another user (it worked on one of his two machines but not on the other) and we currently don't have a solution for this. This seems like a rare bug that is not easy to fix. I would suggest trying to do what Andreas Hegenberg described [here](https://community.folivora.ai/t/bug-cant-add-btt-to-mojave-privacy-security-settings/6688) but I cannot guarantee that it'll solve it.

**Comment by ahadas** [comment]
Ah, maybe another check we can do to see if it's the same is to execute `/Applications/muCommander.app/Contents/MacOS/JavaAppLauncher` from the terminal and see if it's then possible to move files to the trash

**Comment by rhstanton** [comment]
That works.

**Comment by ahadas** [comment]
@rhstanton would you be willing to try an [unstable version](https://drive.google.com/open?id=1hZ0wl9SWGasD3vLl7mGbefo7rHDSYPkI) in which 'move to trash' is implemented with JNA rather than by calling to Finder?

**Comment by rhstanton** [comment]
Sure

**Comment by rhstanton** [comment]
Moving to trash now works fine. It still asks me to confirm allowing incoming network connections, even though I've manually added this to the Firewall rules.

**Comment by ahadas** [comment]
Great, thanks for the feedback!
As for the incoming network connections, let's discuss it on the other issue although it may be related to this one.

**Comment by dbogdanov** [comment]
I've got an SMB share mounted with `smbfs` and I now get the same issue on it after the 10.15.4 update. Deleting works fine on the local filesystem though. Any ideas?

**Comment by ahadas** [comment]
@dbogdanov hi, with what version of muCommander?

**Comment by dbogdanov** [comment]
The version is 0.9.5.

**Comment by ahadas** [comment]
@dbogdanov what happened in previous versions, did Finder move the files to Samba's trash?

**Comment by dbogdanov** [comment]
Yes, correct.

**Comment by dbogdanov** [comment]
For now, rolling back to 0.9.4-2 solved this for me.

**Comment by ahadas** [comment]
> For now, rolling back to 0.9.4-2 solved this for me.

@dbogdanov I think it's easy to solve, filed #361
