### ISSUE TITLE
issues while using a mouse

### ISSUE THREAD

**Issue by maiemi** [mucommander/mucommander#327]
using a mouse in mucommander has some issues.
macOC Catalina, 10.15.4

Using a mouse is not successful: 
you can mark the lines and klick the items, but change a directory by a double-click is not possible. The directory does not change to the selected one. Change by pressing the ENTER key at the keyboard is possible.

**Comment by ahadas** [comment]
Hi @maiemi , I can't reproduce it on my machine (installed with 10.15.5).
What version of muCommander do you use?

**Comment by maiemi** [comment]
Dear Adis Harak,

meanwhile I switched to the newest version of mu-commander . At this moment, I can not face the described issue.

Thank You very much for answering!
Stay healthy and have a nice weekend,

kind regards

maiemi

Von meinem iPad gesendet

**Comment by ahadas** [comment]
@maiemi thanks!
