### ISSUE TITLE
sftp not working with openssh server 6.7

### ISSUE THREAD

**Issue by balucha** [mucommander/mucommander#33]
no matching cipher found: client blowfis-cbc,.....

**Comment by ahadas** [comment]
Hi @balucha ,
What version of muCommander are you using?

**Comment by balucha** [comment]
I`m using 0.9.0 version installed on Debian Wheezy and I trying to connect on server with Debian Jessie.
With old Debian versions (Wheezy, Squeeze) connection working.

**Comment by ahadas** [comment]
ok, recently I replaced the library we use for sftp with jsch and I just verified that with it I managed to connect to openssh-server that runs on Debian Jessie. Soon (hopefully in couple of days) I will be able to publish a release candidate for 0.9.1. I will try to remember to update here, but the best way to track it is by following us on twitter (https://twitter.com/mucommander)

**Comment by balucha** [comment]
Ok. Thanks

**Comment by jhrom** [comment]
Hi, I checked 0.9.1 and I successfully connected to ssh server. 
Looking forward for 0.9.1 release. 

Thank you for your effort.

**Comment by ahadas** [comment]
@jhrom , thanks for the confirmation!
@balucha , I'm closing this issue, feel free to reopen if it still doesn't work for you

Note that I published the artifacts for 0.9.1rc - it would be great if you could try it and give feedback

**Comment by ahadas** [comment]
0.9.1rc is available here:
https://github.com/mucommander/mucommander/releases/tag/0.9.1rc

**Comment by alexzh16** [comment]
Hi, in Mac Os not working copy sftp. Connect its ok, but if i copy files, that nothing copyng. in older version all its ok.
I'm try copy files from Linux OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013 to mac os El Capitan.
