### ISSUE TITLE
debian install fails

### ISSUE THREAD

**Issue by psalty-dog** [mucommander/mucommander#332]
Using debian stretch (9), install of deb file fails.
 sudo gdebi mucommander_0.9.4-2_all.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done

a lightweight, cross-platform file manager
Do you want to install the software package? [y/N]:y
(Reading database ... 583174 files and directories currently installed.)
Preparing to unpack mucommander_0.9.4-2_all.deb ...
Unpacking mucommander (0.9.4-2) over (0.9.4-2) ...
Setting up mucommander (0.9.4-2) ...
chmod: cannot access '/usr/share/mucommander/felix-cache': No such file or directory
dpkg: error processing package mucommander (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for bamfdaemon (0.5.3-2) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-9) ...
Processing triggers for desktop-file-utils (0.23-1) ...
Processing triggers for mime-support (3.60) ...
Errors were encountered while processing:
 mucommander

Issue is the postinst file in the deb package.
I unpacked\edited\repacked and install worked ok.

postinst had:
:
ln -s /usr/share/mucommander/mucommander.sh /usr/bin/mucommander
chmod 777 /usr/share/mucommander/felix-cache
:

<< requires extra line to create the felix-cache >>
<< changed to >>
ln -s /usr/share/mucommander/mucommander.sh /usr/bin/mucommander
mkdir -p /usr/share/mucommander/felix-cache
chmod 777 /usr/share/mucommander/felix-cache

**Comment by ahadas** [comment]
@psalty-dog thanks for reporting this and proposing the fix, done :)
