### ISSUE TITLE
Use `command` (⌘) button as default modifier under macOS

### ISSUE THREAD

**Issue by sfuerte** [mucommander/mucommander#334]
Instead of default Windows `control` (^) button, `command` (⌘) button shall be used as default modifier under macOS, e.g.: not `^ + N` for new window but `⌘ + N`, etc.

**Comment by ahadas** [comment]
@sfuerte right, thanks for adding this. It is actually something that crossed my mind (I called it "Customize key bindings per operating system" [here](https://github.com/mucommander/mucommander/wiki/Roadmap)). Would be a nice addition indeed.

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
