### ISSUE TITLE
[Feature Request] calculate directory size by `F3`

### ISSUE THREAD

**Issue by sfuerte** [mucommander/mucommander#335]
Default action for `F3` is a file `View`. Would be great if it calculated a directory size when the cursor is on one. 
A very missed feature comparing to Far Manager (https://www.farmanager.com/) and this clone (https://github.com/trol73/mucommander)

**Comment by ahadas** [comment]
This is fixed in [v0.9.6](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)
