### ISSUE TITLE
Problems with finding Java on Windows

### ISSUE THREAD

**Issue by Forinil** [mucommander/mucommander#336]
Some time ago I installed muCommander and Oracle Java 8. It worked fine until one day, after an update, muComander requested 11. 

So I installed AdoptOpenJDK Java 11 (using installer) and it started working again.

A few days ago, Java 8 updated itself and suddenly muCommander stopped working and started requesting Java 11 again, despite `JAVA_HOME` being set to Java 11's path and Java 11 being first on `PATH`.

I believe this is related to the following launch4j issue:
[Check "JAVA_HOME" Environment Variable](https://sourceforge.net/p/launch4j/feature-requests/127/?page=0).

**Comment by ahadas** [comment]
@Forinil I would recommend on using [the version that comes with a bundled JRE](https://github.com/mucommander/mucommander/releases/download/0.9.4-2/mucommander-0.9.4-2-bundled.exe), would it work for you?

**Comment by Forinil** [comment]
@ahadas It probably would, but since I'd like to avoid bundled JRE, I've created desktop shortcut to `javaw -jar muCommander-0.9.4.jar`.

Now I just need to remember to update it every time I update muCommander .

**Comment by ahadas** [comment]
> Now I just need to remember to update it every time I update muCommander .

I've pushed a fix so hopefully as from v0.9.5 you won't need to :)
