### ISSUE TITLE
Copy from mac to windows sets read-only flag

### ISSUE THREAD

**Issue by Dan-Essin** [mucommander/mucommander#338]
Hello,
I copied a folder from a mac to a windows machine. When I tried to delete some of the files on the windows machine, the action was not allowed. It turns out that the folder and all its content were set to read-only. I was only able to remove the read-only flag by logging in as administrator and selecting the folder that contained the copied folder and then unchecking the read-only box in its properties dialog and then telling it to propagate the change to all the child items. Attempting to clear the read-only flag directly on the affect (copied) folder was not allowed, even to administrator.

If I do a similar copy with Finder, this does not happen.
I doubt that you intended to make copied items read-only so this is probably a bug.

Thank you

**Comment by ahadas** [comment]
Hi @Dan-Essin , thanks for reporting this. Can you please provide more details on how did you copy the files from the mac to windows?

**Comment by ahadas** [comment]
Closing, feel free to reopen if more information can be provided.
