### ISSUE TITLE
OS X 10.14.6 reports damaged file

### ISSUE THREAD

**Issue by Krea4** [mucommander/mucommander#344]
Cannot open mucommander-0.9.4-2.dmg file

**Comment by IANatCAMBIO** [comment]
I'm getting a similar issue. The DMG looked ok, but the app won't run on Mac 10.15.4.

I tried opening the .app and just running the .jar from CLI, and got the attached error.
[mucommanderError.txt](https://github.com/mucommander/mucommander/files/4732979/mucommanderError.txt)

**Comment by rhstanton** [comment]
I get the same, but running

xattr -cr /Applications/muCommander.App

allows it to install OK. I don't know if this causes any undesirable side-effects, though...

**Comment by IANatCAMBIO** [comment]
My xattr on Mac OS Catalina does not have -cr options.

**Comment by ahadas** [comment]
> I'm getting a similar issue. The DMG looked ok, but the app won't run on Mac 10.15.4.
> 
> I tried opening the .app and just running the .jar from CLI, and got the attached error.
> [mucommanderError.txt](https://github.com/mucommander/mucommander/files/4732979/mucommanderError.txt)

@IANatCAMBIO in order to run it from CLI you have to use Java 11.
Can you please check your Java version (`java --version`)?

**Comment by ahadas** [comment]
> Cannot open mucommander-0.9.4-2.dmg file

Probably due to the [known issue](https://github.com/mucommander/mucommander/blob/master/package/readme.txt#L58-L59) that was mentioned before
