### ISSUE TITLE
SFTP very slow (macOS Mojave, mucommander 0.9.4)

### ISSUE THREAD

**Issue by netjjordan** [mucommander/mucommander#345]
For some time, sftp on mucommander has been very slow on Mac. I'm getting less than 10KB / sec even on my home network machine-to-machine

The graph in "Advanced" shows a repeating pattern of a "peak" followed by several seconds of inactivity (see attached)

Mucommander has been this way with sftp for several versions now, thanks for looking into it

![Screenshot 2020-05-27 at 12 36 43](https://user-images.githubusercontent.com/26486800/83014549-d74b9180-a016-11ea-927c-fe2d320ecc74.png)

**Comment by ahadas** [comment]
Yeah, the SFTP library was replaced.
But can you provide more details on what files you tried to copy - how many, what was their size.

**Comment by JezevecCoM** [comment]
I have the same problem since I bought new Air. It's doing with any size of file, trying against Amazon ftp as well as against own server with Apache. Still same with newest version of MuCommander 0.9.5.

**Comment by Haneko** [comment]
I believe the issue could be due to the SFTPOutputStream class extending java.io.FilterOutputStream. In the FTPFile.java for FTP protocol, this has been updated to com.mucommander.commons.io.FilteredOutputStream. 

I've cloned the repo and built my own version with this update for SFTPFile.java, and the peak issue disappears.

**Comment by ahadas** [comment]
@Haneko thanks for the information, would you kindly post a patch to change that?

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
