### ISSUE TITLE
smb as guest issue

### ISSUE THREAD

**Issue by gnjmn** [mucommander/mucommander#346]
When trying to connect to smb as guest with the address "smb://xx.xx.xx.xx" i get this error message:

java.lang.RuntimeException: Failed to connect: 0.0.0.0<00>/xx.xx.xx.xx
 at com.mucommander.ui.event.LocationManager.setCurrentFolder(LocationManager.java:89)
 at com.mucommander.core.LocationChanger.setCurrentFolder(LocationChanger.java:341)
 at com.mucommander.core.LocationChanger.access$1300(LocationChanger.java:56)
 at com.mucommander.core.LocationChanger$ChangeFolderThread.run(LocationChanger.java:845)

version info:
muCommander
Version: 0.9.4
Build date: 2020/03/08
Build number: 8f24dfc

Java
Runtime version: 14.0.1
VM name: Java HotSpot(TM) 64-Bit Server VM
VM version: 14.0.1+7
VM vendor: Oracle Corporation

OS
Name: Windows 10
Version: 10.0
Architecture: amd64

how to get connected to smb as guest?

**Comment by ahadas** [comment]
Hi @gnjmn ,
Please try to follow the following recording:
https://youtu.be/4Ebwvabn6Cs

**Comment by gnjmn** [comment]
it's a client issue as a friend get connected but not me

**Comment by ahadas** [comment]
@gnjmn did your friend connect with mucommander or with another client? your friend might be using a client that supports a later version of smb than the one supported by mucommander at the moment (v1)

**Comment by ahadas** [comment]
Closing, feel free to reopen if needed

**Comment by gnjmn** [comment]
yes he did use mucommander

**Comment by ahadas** [comment]
> yes he did use mucommander
@gnjmn ok so I assume you try to connect to a different machine, right? can it be that your friend's machine enables SMBv1 and your not?
