### ISSUE TITLE
"Failed to read this folder" with MacOS Desktop and Downloads

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#348]
Using the latest version of muCommander (0.9.4, just downloaded from github) on MacOS 10.15.5, I'm no longer able to access either my Desktop or Downloads folders (this seems to be a fairly new problem). When I try to access either directory, I get the error message "Failed to read this folder." In principle, this can be handled in Security/Privacy -> Privacy -> Files and Folders, but muCommander is not one of the applications listed there, and I can't add an application manually (there's a + sign there, but it's greyed out).

**Comment by ahadas** [comment]
@rhstanton could you try to reset all the Security & Privacy settings for muCommander as described [in this wiki](https://github.com/mucommander/mucommander/wiki/Reset-Security-&-Privacy-Settings-on-macOS)?

**Comment by rhstanton** [comment]
That works. Thanks!

**Comment by ahadas** [comment]
Glad to hear :)
