### ISSUE TITLE
Free disk space updates lags sometimes

### ISSUE THREAD

**Issue by sskras** [mucommander/mucommander#349]
Sometimes muCommander refreshes the actual **free disk space** just when I activate the window (on my w10), but sometimes it shows the old value:
![image](https://user-images.githubusercontent.com/7887758/83974222-6d739780-a8f4-11ea-9ab6-bbedb933f4ed.png)

Sometimes hitting `Tab`,`Tab` is enough. But sometimes it's not.

I propose the free space value to be refreshed on a panel activation (at least after `Tab` was pressed).

**Comment by ahadas** [comment]
@sskras thanks for reporting this! indeed, the mechanism that updates the volume info (free/total space) in the status bar wasn't that great in terms of user experience. I'm going to do some changes to make in more efficient and to react better to events like switching to the application and panel activation. would you kindly give the nightly build a try and tell how you find it with those changes?

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)

**Comment by sskras** [comment]
Thanks!  Looks like it's in the commit de57ebd00d12e312e5452701b32179aeed7403b1.
