### ISSUE TITLE
Mac OS: Option+Arrow doesn't work from v0.9.4

### ISSUE THREAD

**Issue by collaborationgroup** [mucommander/mucommander#355]
It was in previous versions possible to jump between words separated by space or slash in modals such as "Move" (fn+F6) with the shortcut Option+Arrow. Same goes for Option+Delete. It's still possible in e.g. Finder in Mac OS so the problem is most likely with Mucommander.

Is there a workaround for this or can it be fixed in the next version? Thank you!

Mac OS Mojave 10.14.6
Mucommander 0.9.4

<img width="364" alt="Screenshot 2020-06-17 at 11 32 39" src="https://user-images.githubusercontent.com/8746755/84881543-4f452e80-b08e-11ea-802a-1b472a855897.png">

**Comment by ahadas** [comment]
hi @collaborationgroup , these dialogs have not been changed for quite some time and the functionality you describe works for me on macOS Catalina 10.15.5. What has changed in v0.9.4 is that on macOS we bundle the JRE and there might be an issue between the JVM and the operating system you're running. Could you check with [this version](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.5-snapshot.dmg)?

**Comment by collaborationgroup** [comment]
Thanks for answering @ahadas but the URL you provided results in a 404, can you please check the URL? Thank you!

**Comment by ahadas** [comment]
Right, I've uploaded it again (same [link](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.5-snapshot.dmg))

**Comment by collaborationgroup** [comment]
Thank you @ahadas the link worked but unfortunately the new version didn't fix the issue. If you don't have any I'll try updating to Catalina?

**Comment by ahadas** [comment]
@collaborationgroup ok, so apparently it has not been fixed in later versions of Java 11. I have no idea for what can cause it so yes, please try to update to Catalina
