### ISSUE TITLE
File search function works?

### ISSUE THREAD

**Issue by rg-software** [mucommander/mucommander#358]
Is file search functionality working?

I tried searching for "mu" inside muCommander folder (Windows 10), and it shows an empty panel with the title `find://C:\1\muCommander-0.9.5/mu`.

I also tried case-insensitive wildcard search (`find://C:\1\muCommander-0.9.5/*mu*?caseinsensitive=true`), but the result is the same.

**Comment by ahadas** [comment]
Hi @rg-software , 

> I tried searching for "mu" inside muCommander folder (Windows 10), and it shows an empty panel with the title `find://C:\1\muCommander-0.9.5/mu`.

Yes, that's because by default we look for an 'exact match'

> 
> I also tried case-insensitive wildcard search (`find://C:\1\muCommander-0.9.5/*mu*?caseinsensitive=true`), but the result is the same.

if you want to look for a regular expression you need to specify in 'the Java way' and explicitly tell that you wish to use a regexp, for instance:
find:///usr/share/mucommander/mu.*?regex=true

BTW, it's much easier to do it via the Find dialog

**Comment by rg-software** [comment]
Thank you. I confirm it works indeed. I must say it is rather unusual, though, as I's separate "regex search" from "ordinary search" that includes just ? and * wildcards.

**Comment by ahadas** [comment]
> Thank you. I confirm it works indeed. I must say it is rather unusual, though, as I's separate "regex search" from "ordinary search" that includes just ? and * wildcards.

The ? and *  wildcards are now ([v0.9.6-1](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)) supported the way you proposed - thanks!

**Comment by dandv** [comment]
Not sure if this is related, but the wiki says [you can't search for a specific file](https://github.com/mucommander/mucommander/wiki/FAQ#how-can-i-search-for-a-specific-file), however when I searched for "setup.md" in a directory that contained it, that file was found. Is that wiki section outdated, or does it need clarification?
