### ISSUE TITLE
v0.9.5 crashes after about one hour of work

### ISSUE THREAD

**Issue by abcdenis** [mucommander/mucommander#359]
Hi,
sample crash file attached.
If its openjdk issue it will be nice for muCommander to report of incompatible JDK on start.
Thank you.

[hs_err_pid52167.log](https://github.com/mucommander/mucommander/files/4854746/hs_err_pid52167.log)

**Comment by ahadas** [comment]
@abcdenis hi, it seems you run the application on macOS using the bundled JRE so it's not a JRE incompatibility issue. But it looks like a JRE issue. How reproducible is it on your machine? can you identify operations you've made using muCommander that may shed more light on how to reproduce it?

**Comment by mrserb** [comment]
This crash occurs when the user changes the keyboard language(in my case EN<-->RU).
But everything works fine if the next command is used
{same AdoptionJDK build}/java -jar /Applications/muCommander.app/Contents/Java/mucommander-0.9.5.jar

**Comment by mrserb** [comment]
The OpenJDK bug: https://bugs.openjdk.java.net/browse/JDK-8248532

**Comment by ahadas** [comment]
Thanks for pointing this out @mrserb ,
I thought about reverting the upgrade to 11.0.7 in the upcoming release but let's see how the handling of that bug goes

**Comment by desillusionist** [comment]
The same issue here :(

**Comment by elias137** [comment]
The same here. Although it crashes randomly too, with no any correlation to the issue mentioned above. 0.9.5 seems to be the most buggy release among all the rest ever released.

**Comment by elias137** [comment]
The same here. Although it crashes randomly too, with no any correlation to the issue mentioned above.

**Comment by ahadas** [comment]
This should be fixed in [v0.9.6](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)
