### ISSUE TITLE
muCommander V 0.9.5 hangs Viewing large text file on OS X High Sierra

### ISSUE THREAD

**Issue by adaongithub** [mucommander/mucommander#360]
Used the Command Bar to View a text file (size ~~ 330,000 bytes) with (suspiciously) NO newlines or CRLFs (it’s a very long pure ASCII text JSON database dump file).  MuCommander just hung (spinning beach ball & not responsive except for selecting windows) with a very long off-display-to-the-right single line window for the Viewed text file (window was empty - no text shown).  I couldn’t get muCommander to stop in any way but a Force Quit. 

Mac OS X - High Sierra
System Software Overview:
  System Version:	macOS 10.13.6 (17G13035)
  Kernel Version:	Darwin 17.7.0
  Boot Volume:	2017-07-10_IntHD
  Boot Mode:	Normal
Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro8,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	12 GB
__________________________________________________
muCommander
Version: 0.9.5
Build date: 2020/06/26
Build number: 147d0c8

Java
Runtime version: 11.0.7
VM name: OpenJDK 64-Bit Server VM
VM version: 11.0.7+10
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.13.6
Architecture: x86_64

Locale
Language: en
Country: US
Encoding: UTF-8

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
