### ISSUE TITLE
macOS: move to trash on SMB share

### ISSUE THREAD

**Issue by ahadas** [mucommander/mucommander#361]
The ability to move files on an SMB share to trash broke when we switched to use JNA for moving files to trash on macOS - #321  (Finder supports that while JNA not).

**Comment by ahadas** [comment]
Well, that method was introduced in Java 9 and we only recently separated out the macOS-specific code to a different bundle that compiles with Java 11 (it was compiled with Java 8 before).
I think we can use it instead of using JNA but we would still need to use Finder in order to move files on SMB shares to the trash

**Comment by mrserb** [comment]
Please note you can improve "moveToTrash()" by submitting the patch to the OpenJDK, if you wish.

**Comment by ahadas** [comment]
This is fixed in [v0.9.6](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)
