### ISSUE TITLE
Issue when deleting Android jar library file contents

### ISSUE THREAD

**Issue by TimYao18** [mucommander/mucommander#365]
When I entering and deleting Android jar file's content, the jar file won't be usable in Android studio. There will be something wrong .

Error message is as below.

Cannot read entry 'XXXXX.class' (offset: 1273623, size: 470) because it overlaps with 'XXXXX.class' (offset: 1272982, size: 653)

**Comment by ahadas** [comment]
Hi @TimYao18 , where do you see this error?

**Comment by TimYao18** [comment]
Hi,

I saw this error in Android Studio logcat when I building my project with
jar files. These jar files' contents are partly deleted in muCommander.


Arik Hadas <notifications@github.com> 於 2020年7月31日 週五 下午10:49 寫道：

**Comment by ahadas** [comment]
So can you please be more specific about what's the issue - if you delete (some of the content of) jar files using muCommander and it leads to issues in other applicatiins, what should be done differently by muCommander?

**Comment by TimYao18** [comment]
I don't know what caused this issue.
But delete some of the content of jar files in Double Commander, the result
jar files will be different with muCommander does. The Attachments are
screenshots show part of the different content of the jar file. Right hand
side is the jar file muCommander did, and Left hand-side is the jar file
Double Commander did.
I need the result by muCommander to be right.



Arik Hadas <notifications@github.com> 於 2020年8月1日 週六 下午4:37寫道：

**Comment by ahadas** [comment]
@TimYao18 I don't see the screenshot, can you please try to attach it again?

**Comment by TimYao18** [comment]
The attachments are screenshot that shows the jar file diff in hex.

Arik Hadas <notifications@github.com> 於 2020年8月9日 週日 上午12:16 寫道：

**Comment by ahadas** [comment]
@TimYao18 ok, I doubt it could explain what's wrong but if that's the only thing we have at hand - can you attach it?

**Comment by TimYao18** [comment]
It seems that attachments are still not seen.
I upload them to the image share space.

As below:
https://ibb.co/Tcxj8P3

https://ibb.co/CVn5503



Arik Hadas <notifications@github.com> 於 2020年8月9日 週日 上午2:42 寫道：

**Comment by ahadas** [comment]
@TimYao18  thanks for uploading the screenshots. It is actually the expected result - the removed content is supposed to be replaced with zero blocks.

**Comment by TimYao18** [comment]
Sorry my fault. I should snap the different from the content deleted.

This is the different from the content deleted screenshot.
Left one is content deleted by Double Commander. Right one is content deleted by muCommander.
![Screenshot 2020-08-12 16 38 27](https://user-images.githubusercontent.com/15173100/89994253-71d47c00-dcba-11ea-8775-b0a6c3babc9a.png)

This is the screenshot comparing the origin file and the file muCommander deleting the content.
![Screenshot 2020-08-12 16 42 14](https://user-images.githubusercontent.com/15173100/89994500-c8da5100-dcba-11ea-84cb-1a3d9432ae28.png)

Even If I use muCommander "run command"
_`zip -d sparkkernel_copy.jar /com/etencorp/kernel/serviceapi\*`_

The result jar file is usable in Android Studio that won't show the error message when building apk. 
But the screenshot seems useless.
Left: muCommander, Right: run command in muCommander to delete content in jar.
![Screenshot 2020-08-12 16 52 00](https://user-images.githubusercontent.com/15173100/89995582-3cc92900-dcbc-11ea-84e4-99a4cbd305e0.png)


The error message when building output: 
> _Cannot read entry 'com/etencorp/kernel/twstockservicedata/TRS_STRUCT_STOCK_CONCEPT.class' (offset: 2949993, size: 508) because it overlaps with 'com/etencorp/kernel/twstockservicedata/TRS_STRUCT_STOCK_CLASS.class' (offset: 2948888, size: 1117)_

I don't know why delete jar content in muCommander will make the file not usable in Android Studio. 
Maybe Android Studio have some bug that could not work with muCommander's result file.
