### ISSUE TITLE
Custom edit shortcut needs to be set on each start

### ISSUE THREAD

**Issue by KasperTA** [mucommander/mucommander#366]
Some versions ago, my custom setting for the edit file shortcut stopped working after opening muCommander (tested on macOS). It is only the edit shortcut, all other shortcuts work.

My edit settings in the preference files:
```
command_bar.xml:
    <command_bar modifier="SHIFT" version="0.9.5">
        <button action_id="Edit" alt_action_id="InternalEdit"/>

commands.xml
    <command alias="edit" value="open -a Sublime\ Text $f" type="system"/>

action_keymap.xml
    <action id="Edit" keystroke="meta E"/>
```

If i use the mouse to click on: bottom bar > edit button, then muCommander opens the external editor (Sublime).
But if i use the shortcut CMD+E i have set, then it opens the internal editor.

If i then open shortcut settings, change the shortcut for edit to something else and apply, and then change it back to CMD+E (meta E) and apply, then the shortcut works, until next time i close and open muCommander. Nothing seems to change in any preference files.

**Comment by ahadas** [comment]
I can't reproduce it on my machine.
I guess it wouldn't work with a different keystroke as well, right? did you try?

**Comment by KasperTA** [comment]
Problem is now gone, after latest upgrade to version 0.9.7.

**Comment by ahadas** [comment]
Happy to hear and thanks for the update @KasperTA !
