### ISSUE TITLE
Bug: Crashing after update to 0.9.5 from 0.9.1

### ISSUE THREAD

**Issue by AlexKalinin** [mucommander/mucommander#373]
[crash_report.txt](https://github.com/mucommander/mucommander/files/5112212/crash_report.txt)

( just wanted to rename folder )

**Comment by ahadas** [comment]
@alexey-lysiuk can you please check if that still happens with [v0.9.6-1](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)?

**Comment by ahadas** [comment]
Closing but feel free to reopen if it still happens with 0.9.6
