### ISSUE TITLE
Please add option to close all file windows

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#377]
With Finder on the Mac, pressing "Option" before clicking on the "File" menu item allows you to select "Close All" and close all open file-viewing windows. It would be very useful for muCommander to have this option (unless it's already there and I just didn't notice...), so people don't have to spend time closing a large number of file-view windows one at a time. Thanks!

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
