### ISSUE TITLE
mucommander Mac not compatible anymore with OS X <=10.10 (Yosemite and below) due to bundled Java jdk 11.0.4 :(

### ISSUE THREAD

**Issue by LeeBinder** [mucommander/mucommander#378]
Hi @ahadas , thank you for mucommander! I today fired up my 10.7.5 rig, opened mucommander 0.9.3-3 (with bundled Java 8 Update 161), followed the update notification because neither on your mucommander homepage nor here on github I saw any minimal macOS/ OS X system requirement, just to have mucommander 0.9.5-1 not launch anymore, finding out after some research that the minimal system requirement for JDK 11 is OS X 11.11 El Capitan as per [products-doc-jdk11certconfig.html#macos](https://www.oracle.com/java/technologies/javase/products-doc-jdk11certconfig.html#macos) and [overview-jdk-installation.html](https://docs.oracle.com/en/java/javase/11/install/overview-jdk-installation.html#GUID-8677A77F-231A-40F7-98B9-1FD0B48C346A).

I now have to requests to you:

1. Can you please indicate both here on github and on mc's homepage that (for now?) mc's current versions have a min. sys. requ. of OS X 11.11 El Capitan, + a link "Download mc 0.9.3-3 for OS X 10.7.3+ (Lion) and above" with the link to the 0.9.3-3 release? That would sure minimize confusion because I will not be the last one stumbling across this.

2. Can you please again issue a version which IS compatible with older OS X? I do think it would be most optimal to again bundle Java 8 Update 161 for highest reliability and compatibility (rather than having mc again use the JRE inside /Library/Internet Plug-Ins/JavaAppletPlugin.plugin because you cannot influence what users install).

I am positive no user of mc on an older Mac would mind if not all functions of current mc would make it into the 10.7.3+ port due to differences in Java 8 vs. 11.

To start some debugging, after copying the older Java 8/161 into mc 0.9.5-1, it does launch and work just fine in 10.7.5, just the Preferences are not present in the menu and also not accessible via ⌘, so I'd say there is hope 👍

**Comment by ahadas** [comment]
Hi @LeeBinder, thanks for reporting this.
Can you please give [this version](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg) a shot?

**Comment by LeeBinder** [comment]
that's what I call speedy 👍 but no, that mu 0.9.6 bundled with OpenJDK 8u265 does NOT launch in 10.7.5. When you look at 8u265's min sys requs for macOS you will see it's 11.8+:

https://bell-sw.com/pages/liberica-release-notes-8u265/

But good news: as soon as I copy Java HotSpot 8 Update 161 from mu 0.9.3-3 into 0.9.6 overwriting the one in there, it launches just fine in 10.7.5, and even Prefs work 🥇

Even for the oldest [OpenJDK 8 build 192](https://bell-sw.com/pages/downloads/?release=8u192&os=macOS), min sys requ. for macOS is 11.8+

https://bell-sw.com/pages/liberica-release-notes-8u192/

so it looks as if for OS X Lion, Java for mu is stuck at 8 Update161, which is better than nothing.

**Comment by ahadas** [comment]
Note that it's uses adoptopenjdk which is supposed to [support 10.10+](https://adoptopenjdk.net/supported_platforms.html).
I think 161 didn't work well on newer version but I'll give it another try

**Comment by LeeBinder** [comment]
ah I see (AdoptOpenJDK).

161 is too old and thus insecure to serve as default Java version for the current/ latest mu. I'm sure you have reasons why you upgraded Java to 11 LTS. I feel it will fully serve the purpose if you offer the Lion+ compatible version in addition to the main one, and simply label it that way (best 10.7.5+ because I can't test 10.7.3).

BTW, after replacing J_265 with J_161 in 0.9.6 snapshot, the app is quite bloated with 281,4 MB. I'm sure there is files from a higher Java 11 version in folders other than jre which are not required for 8u161 (or even 8u265).

**Comment by ahadas** [comment]
Yeah, another option is to provide both bundled and non bundled DMGs, as we do for Windows.

**Comment by LeeBinder** [comment]
sure, that would be option 3 and could/should be carefully labeled as "experimental/ on your own risk" in the filename to minimize impact in the issues section. But for OS X Lion 10.7.5, the last fully JRE was/is 8 Update 151. Versions 8.x beyond that until 241 install but the Java Control Panel does not launch. I tried 241 jre in mu 0.9.6 snapshot, but it does not launch with it. So again the Lion+ specific and fail-safe version I'd say would be bundled with Java HotSpot 8 Update 161 (because mu does not need to launch the Java CP) and purged of any higher Java leftovers.

**Comment by LeeBinder** [comment]
@ahadas here's a little script I just wrapped together. Description:

> This script will remove the Java JRE bundled into your muCommander app and instead link to your OS wide JRE install, then launch the modified app.

It'll work with both "editions" paths, ../macOS/.. and ../macOS8/.. inside the muCommander app and is helper tool to facilitate the process:

<details>
  <summary>click to expand</summary> 

  ```
#!/bin/bash
clear
echo "Have muCommander use your OS wide JavaAppletPlugin"
echo ==================================================
echo
echo "Pre-requisites check:"

simlink? () {
  test "$(readlink "${1}")";
}

info_plist=/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/info.plist

if simlink? "${info_plist}"; then echo "  ✓ compatible Java JRE found 👍"; else echo "No compatible Java JRE found 😞 - aborting." && echo && exit; fi

if [ ! -d "/Applications/muCommander.app" ]; then echo "No muCommander app found in your Applications folder 😞 - aborting." && exit; else echo "  ✓ muCommander app found in /Applications 👍"; fi
echo --------------------------------------------------
echo
echo "This script will remove the Java JRE bundled into your muCommander app and"
echo "instead link to your OS wide JRE install, then launch the modified app."
echo
read -p "Proceed now (y|n)? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
echo
if test -d /Applications/muCommander.app/Contents/PlugIns/macOS8; then var8="8"; fi

rm -Rf /Applications/muCommander.app/Contents/PlugIns/macOS$var8/Contents/Home/jre
rm -f /Applications/muCommander.app/Contents/PlugIns/macOS8/Contents/Info.plist
echo "  ✓ removed the Java bundle in the muCommander app 👍"

cp -a "$info_plist" /Applications/muCommander.app/Contents/PlugIns/macOS$var8/Contents
ln -s "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home" /Applications/muCommander.app/Contents/PlugIns/macOS$var8/Contents/Home/jre
echo "  ✓ placed SymLinks to your OS wide Java Plugin into your muCommander app 👍"
echo
echo "..launching the modified muCommander app now!"
open -n "/Applications/muCommander.app"
else echo
fi
echo
echo "This window will automatically close in 4 seconds..."
sleep 4
osascript -e 'tell app "Terminal"' -e 'close (every window whose name contains ".command")' -e 'if number of windows = 0 then quit' -e 'end tell' & exit;
  ```
</details>

[Have mC use installed JavaAppletPlugin.zip](https://github.com/mucommander/mucommander/files/5337301/Have.mC.use.installed.JavaAppletPlugin.zip)

I hope it can save you some time if wanted.

BTW, what is the diff between snapshot and snapshot-2.dmg?

**Comment by ahadas** [comment]
Thanks @LeeBinder, I'll look at it soon

> BTW, what is the diff between snapshot and snapshot-2.dmg?

Just [the fix for #381 ](https://github.com/mucommander/mucommander/commit/8d2cf917012f13a1c4af4dd309e8d46cc91d3ce7)

**Comment by ahadas** [comment]
Hi @LeeBinder , 
I like this solution as it enables to run muCommander on older versions without complicating the packaging for us.
The script looks good but a minor change is needed - I've pushed a PR that changes the bundled JRE on macOS to the latest version of Java 8 provided by adoptopenjdk (#382) instead of Java 11 (so no need to check the `macOS8` folder anymore).  

You can test it by commenting out `osgiRuntime project('mucommander-os-macos')` and remove the comment from `osgiRuntime project('mucommander-os-macos-java8')` in `build.gradle` and then execute `./gradlew clean run` followed by `./gradlew createDmg` to create the dmg file in the `build/distributions` folder.

Can you please adjust the script and submit a PR?
I will then follow up with the changes that are needed in order to include it with the dmg packaging.

**Comment by LeeBinder** [comment]
Great Arik that you have a use for it. I read #382 but it's not fully clear to me if the path is `/Applications/muCommander.app/Contents/PlugIns/macOS`

regarding compiling: I had to do a fundamental decision a while back to stop messing with XCode on my amateur level due to severe time restrictions, so feel free to create the dmg then attach it with your next posting and I'll test it.

**Comment by ahadas** [comment]
Ok, I merged the script after checking it on my machine where JavaAppletPlugin uses an older version of Java 8 than the bundled one. Once the CI creates an updated snapshot version, I'll upload the RPM there

**Comment by LeeBinder** [comment]
very cool. I'll test muC in the dmg then.

**Comment by ahadas** [comment]
@LeeBinder I've uploaded [the dmg file](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg). Note that the script will reside in `/Applications/muCommander.app/Contents/replace_jre.sh` - looking forward to your feedback :)

**Comment by LeeBinder** [comment]
hey Arik - I tested it - two questions:
- why inside the app and not on the root level of the (mounted) dmg right next to the ReadMe?
- why .sh = vs. .command not executable but has to be dragged inside Terminal to be executed?

this complicates replacement, doesn't it, and to me that appears unnecessary?

**Comment by ahadas** [comment]
Hi @LeeBinder ,
Thanks for the feedback!
Changed the script to be located within the root-level mountpoint of the dmg files as a `.command` file.
I placed it next to the `app` rather than next to the `readme.txt` file so it will be clearer that the app should be copied first (I know it's also part of validation the script does).
Could you please give [the updated dmg file](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg) a try?

**Comment by LeeBinder** [comment]
Yes Arik, that's much better, and I verified it's working. A few things:

1. `mucommander-os-macos-java8-0.9.6.jar` (from you previous snapshot nightly) must be present in `muCommander.app/Contents/Java/bundle` because otherwise the 'About muCommander' box will only be a tiny window without content:
![Screen Shot 2020-11-03 at 22 11 43](https://user-images.githubusercontent.com/39203497/98041060-9e171900-1e21-11eb-99ca-bea5aa8967c0.jpg)

2. I made an icon for the script. Do you like it :)? Also the .command extension can/ should be hidden because it's executable (and would otherwise only confuse most people):

![Screen Shot 2020-11-03 at 22 25 23](https://user-images.githubusercontent.com/39203497/98042273-9b1d2800-1e23-11eb-9e6f-fed60f17ab89.jpg)

Zip with iconized and extension-less script file: [change_jre.zip](https://github.com/mucommander/mucommander/files/5484140/change_jre.zip)

(if you want to fine-tune the icon, I could attach the Photoshop file on request)

**Comment by ahadas** [comment]
Hi @LeeBinder ,

Thanks for verifying and for the feedback!

No worry, the 'About' and 'Preferences' dialogs would be there in the stable releases which I'll build with Java 8 and include the `mucommander-os-macos-java8` bundle. The last dmg was created with Java 11 and therefore lacked that bundle.

Hiding the extension is a good idea - I also did that for the `license.txt` and `readme.txt` files.
The icon looks good but it's not that easy to set the item within the dmg with that, I have no objection to set it with the icon if you find how to do that but it's also ok to leave it without the icon - the default icon reveals that it's a shell script so there's also a benefit in having the macOS default icon.

**Comment by LeeBinder** [comment]
@ahadas I can finally reply when I'm back later tonite :)

**Comment by LeeBinder** [comment]
> The icon looks good but it's not that easy to set the item within the dmg with this icon. I have no objection to set it with the icon if you find how to do that

yes, it's different than for muC app's icon which is simply a icon.icns file in resources. For a file an icon is resource fork. I have no idea if github can handle that by now. I's easy for me however to apply it manually into a .dmg, see this one (I had sent you a screenshot of before): [muC dummy - script with icon.dmg.zip](https://github.com/mucommander/mucommander/files/5520779/muC.dummy.-.script.with.icon.dmg.zip)

> but it's also ok to leave it with the default icon that better reflects it is a shell script.

Unfortunately it did not display with the black command icon here indicating double-clickable/ executable as supposed, but with a white text file icon. That's why I created the icon :)

**Comment by ahadas** [comment]
I don't think it's related to github but to the gradle plugin we use to generate the dmg file (see [this](https://github.com/mucommander/mucommander/blob/master/build.gradle#L244-L269)).

Anyway, I've uploaded [an updated dmg](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg)  with the bundle for Java 8 bundle and hidden extensions. I think it's good enough but if I'll get contribution that integrates the icon, I'll gladly merge it. The uploaded dmg is opened like this:
<img width="453" alt="Screen Shot 2020-11-13 at 0 00 00" src="https://user-images.githubusercontent.com/6020068/99002347-ed0d2e80-2544-11eb-93d9-b6f6ee818bcf.png">

**Comment by LeeBinder** [comment]
ah, now I understand the process. I read fvarrui/ JavaPackager/ [README.md](https://github.com/fvarrui/JavaPackager/blob/master/README.md) and [macosx-specific-properties.md](https://github.com/fvarrui/JavaPackager/blob/master/docs/macosx-specific-properties.md): there is no gradle plugin command yet to assign an icon to *any* file inside a .dmg. Maybe in the future. So it's all good the way you do it right now.

So now all that seems to be left in this regard here would be a brief explanation in the readme?

**Comment by ahadas** [comment]
@LeeBinder hi, sorry for the late reply on this - sure, feel free to post an explanation for the readme file

**Comment by LeeBinder** [comment]
as long as I see you're alive & kickin' :)

sure, can do. Next week looks good once I'm back home.
