### ISSUE TITLE
Not possible to delete files under Big Sur

### ISSUE THREAD

**Issue by frankyxcs** [mucommander/mucommander#379]
Hi 

first thank you for all your work here and keeping mucommander alive !!!

0.9.4 is working fine so far under big sur latest beta but with 0.9.5.1 i cannot delete any files anymore

Would be nice if you can fix this

Frank

**Comment by ahadas** [comment]
Hi Frank,
What's the error you get?

**Comment by frankyxcs** [comment]
Hi 

no sorry i do not getting any error. I mark a zip file for example and then i click on delete. Then the delete window opens, goes to 100 % but nothing happens. 

Also the popup window does not close..I have to close is manually but the file is not deleted. So i went back to 0.9.4.2

**Comment by ahadas** [comment]
I see.
So we should probably first try to remove files with Apple script and only if that fails to fall back to JNA.
Can you please try with [this version](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot-2.dmg)?

**Comment by frankyxcs** [comment]
Hi ahadas, 

thank you for fixing it. I just tried it and now its working fine again with big sur. 
Greets Fran

**Comment by ahadas** [comment]
Thanks @frankyxcs

**Comment by spr-ru** [comment]
hi 
sorry, but link for 0.9.6 doesnt work. May i ask you to restore it?

**Comment by ahadas** [comment]
hi @spr-ru , I'm about to release 0.9.6 'officially' in the upcoming days

**Comment by ahadas** [comment]
This is fixed in [v0.9.6](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)
