### ISSUE TITLE
Add info on contribution process to README.MD

### ISSUE THREAD

**Issue by sdruskat** [mucommander/mucommander#38]
It'd be great to find some info on how to contribute in the main README.MD, i.e., which branch to create a pull request for mainly.

**Comment by ahadas** [comment]
You're right, this needs to be added there.
For the time being, pull requests need to be created for the 'master' branch. Significant fixes (like the one you reported with the deprecation of gnome-open) are backported for the release_0_9_1 branch.

**Comment by ahadas** [comment]
@sdruskat I added a 'contribution' section to the readme page with some basic information. If you think of a way to improve it - feel free to reopen or to submit a pull request
