### ISSUE TITLE
on OS X with OpenJDK 11:  nightly, 0.9.5,, 0.9.4-2, 0.9.4 view sort function keys don't reverse sort

### ISSUE THREAD

**Issue by jbbythebch** [mucommander/mucommander#383]
**Issue:**
A muCommander panel is sorted by Name.
Pressing ^+F6 changes the sort to Date.  Pressing ^+F6 again does **not** change the sort to reversed date.
Other function keys for sorting by name, etc., also fail to reverse the sort.

**Affects:**
b855f3abd4e2f243d1cfef63c42557ea mucommander-0.9.6-snapshot-portable.zip (from approx 2020-10-08)
0.9.5
0.9.4-2
0.9.4

However, muCommander 0.9.3 (Third Update) [edit, add: 0.9.3-3] opens and the sorting function keys work for sorting and for reverse sorting.

(muCommander 0.9.2 does not open using OpenJDK 11, so can't test it with this setup.)

(This problem does not exist on Windows 10, muCommander 0.9.5, AdoptOpenJDK's OpenJDK 11 JRE.)

**Tested on:**
OS X 10.13.6 (High Sierra), and 10.15.7 (Catalina);
using AdoptOpenJDK.net's OpenJDK 11, installed via MacPorts (openjdk11 @11.0.8_0);
with JAVA_HOME set in the environment to use OpenJDK 11.

This is not an urgent issue for my use, as using 0.9.3 is fine for now.

**Comment by jbbythebch** [comment]
I just noticed that 0.9.3-3 is using what appears to be a bundled Oracle JRE, and 0.9.5-1 is using the MacPorts installation of AdoptOpenJDK's OpenJDK 11.   (I'm guessing 0.9.4.x are also using OpenJDK 11, but didnt' check.)

**Comment by ahadas** [comment]
Hi @jbbythebch , thanks for reporting this.
Yeah, I've managed to reproduce it with 0.9.5.
I'm in the process of changing the bundled JRE on macOS to Java 8 again (#382) and that seems to resolve this issue (will be part of 0.9.6)

**Comment by jbbythebch** [comment]
You're welcome @ahadas, and thank you for all the work you do on this wonderful piece of software!!

I use it every day, all the time.

**Comment by ahadas** [comment]
This is fixed in [v0.9.6](https://github.com/mucommander/mucommander/releases/tag/0.9.6-1)
