### ISSUE TITLE
HDFS support... and bridge to Microsoft Azure AdlsGen2 storage accounts with scheme "abfss://" ?

### ISSUE THREAD

**Issue by Arnaud-Nauwynck** [mucommander/mucommander#387]
Hello muCommander developpers,

The home page documentation says 

> Here's a non-exhaustive list of what you'll find:
>  Virtual filesystem with support for local volumes, FTP, SFTP, SMB, NFS, HTTP, Amazon S3, Hadoop HDFS and Bonjour

but unfortunatly, I am not able to find documentations on how to configure "Hadoop HDFS", 
and not able to open dialog panel for configuring connection of type "Hadoop" (I do see ui panels for  SFTP, NFS, S3, ...) but none for "Hadoop HDFS"

Notice that in fact, I am interrested in the following things:
- browse Microsoft Azure AdlsGen2 storage accounts  (either using the java SDK of Azure  OR via the bridge to the Hadoop FileSystem API ... therefore my questions on HDFS)
- more precisely... I do need that the scheme "abfss://" be recognized ... maybe by Hadoop FileSystem bridge, or by Azure AdlsGen2 directly!  my files will not have urls starting with "hdfs://", even if Hadoop is able to handle them !! 
- I need a proxy to connect to microsoft site from corporate network (either http or SOCKS5 proxy... which I could do by overriding jvm arguments)
- have a cache of file/dirs metadata infos if possible, to avoid querying each time the remote storage accounts

- many files can be quite big: 1Go or more, as they are used for bigdata (parquet files read by Spark or Hadoop HDInsight cluster ).. Clearly, it is very slow/inneficient (and costly) to download the file contents, so it might be blocked for big files 
- some directories may contains thousands of files (for example 15 000 thousands for some directories... )
The UI should support paginating or simply truncating directory listing...
- doing a recursive search has almost 0% chance to finish quickly as they are more than 15 million files
... The main goal of the UI is to give access for checking file existence + file size + file modification date ... so mostly metadata on files, but not full data. So all big search/copy/delete operations may be blocked by a quota

There is already a file browser on the Azure portal, but it is unusable (because of proxy settings, and security authorizations restrictions... we can only browse our storage account using Azure Service Principal (clientID+credentials, not sharedKey), and we don't even have access to the Azure subscription that host the storage accounts! ) 
muCommander would be absolutly GREAT if it was usable as a replacement of the Azure file browser!

Regards,
Arnaud

**Comment by Arnaud-Nauwynck** [comment]
I have found that line 76 in build.gradle is commented:
https://github.com/mucommander/mucommander/blob/master/build.gradle#L76

I am not able to compile / run / debug anyway to investigate more

when trying to launch like "./gradlew runOsgi",  I get unknown property 'revision' :

> * Where:
> Build file 'D:\arn\downloadTools\hadoop\hdfs-explorers\mucommander\apache-bzip2\build.gradle' line: 16
> 
> * What went wrong:
> A problem occurred evaluating project ':apache-bzip2'.
> > Could not get unknown property 'revision' for task ':apache-bzip2:jar' of type org.gradle.api.tasks.bundling.Jar.

**Comment by ahadas** [comment]
hi @Arnaud-Nauwynck ,

As for the compilation issue, I replied to your message on gitter - it doesn't happen to me on Windows so I wonder about the versions of Java and Gradle that you're using.

You've identified the situation correctly - we've disabled Hadoop during the transition of OSGi and that's why you see it commented out in `build.gradle`. Note that we supported a relatively old version of Hadoop so there's a good chance that if wouldn't work for your use case anyway I'm afraid..

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
