### ISSUE TITLE
0.9.1rc Issue with Change permissions dialog

### ISSUE THREAD

**Issue by alexey-lysiuk** [mucommander/mucommander#39]
Change permissions dialog has Read and Execute settings swapped, i.e. changing read permissions modifies execute instead and vice versa.
I encountered this problem on macOS if it matters.

**Comment by ahadas** [comment]
@alexey-lysiuk , thank you for reporting this!
It is now fixed on the master branch and on the 0.9.1 branch so the fix will be available in the 0.9.1 release that is going to be published soon.
