### ISSUE TITLE
MacOS: can't delete to Bin

### ISSUE THREAD

**Issue by PDVJAM** [mucommander/mucommander#390]
Hey! I use Big Sur and 0.9.5 muCommander. When I try to delete anything to Bin it just stuck on "Deleting" window. Nothing is moved to Bin. Works fine if I remove without sending to Bin.

**Comment by ahadas** [comment]
Hi @PDVJAM , can you give [this](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg) a shot?

**Comment by DmitryYSmirnov** [comment]
@ahadas I had exactly the same problem with BigSur. 
Your update has helped resolve the problem. Thank you!

**Comment by orenifer** [comment]
> Hi @PDVJAM , can you give [this](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg) a shot?

Hey, can't seem to launch dmg. 

<img width="374" alt="Screen Shot 2020-11-26 at 23 06 26" src="https://user-images.githubusercontent.com/60127508/100391416-054c7580-303c-11eb-8615-77315f9c2373.png">

**Comment by PDVJAM** [comment]
Works!

**Comment by DmitryYSmirnov** [comment]
@ahadas  Wanted to install on another notebook but link not working now :-(

**Comment by ahadas** [comment]
uploaded it again [here](https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-0.9.6-snapshot.dmg)
