### ISSUE TITLE
ability to remove menu icon in macOS Big Sur

### ISSUE THREAD

**Issue by sfuerte** [mucommander/mucommander#392]
Not able to remove the subject icon from the menu. Would be great to have it configurable.

App version (as per `About muCommander):
```
muCommander
Version: 0.9.5
Build date: 2020/06/26
Build number: 147d0c8

Java
Runtime version: 11.0.7
VM name: OpenJDK 64-Bit Server VM
VM version: 11.0.7+10
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.16
Architecture: x86_64
```

OS Version: 11.0.1 on Apple M1

![image](https://user-images.githubusercontent.com/16941995/99855185-758e5f00-2b43-11eb-990d-4915b8b89e5c.png)

**Comment by ahadas** [comment]
Hi @sfuerte ,
Which menu icon?

**Comment by sfuerte** [comment]
@ahadas, the top right on the screenshot. 
Someone it isn't shown on Intel's laptop with Big Sur but it is there on M1-based one. 
No ability to disable it either via muCommander settings or system preferences.

**Comment by sfuerte** [comment]
See the attached screen recording (had to zip it as Github doesn't allow upload of MOV files).

[Screen Recording 2020-11-20 at 3.35.43 PM.zip](https://github.com/mucommander/mucommander/files/5576403/Screen.Recording.2020-11-20.at.3.35.43.PM.zip)

**Comment by ahadas** [comment]
@sfuerte I see, thanks. Looks similar to the menu icon on previous versions but this one can move. I'll need to upgrade my macOS to see more.

**Comment by sfuerte** [comment]
All menu icons can be moved, just press and hold Alt/Option button and then it's possible to move the icon to re-arrange the order or remove completely (after 13+ years on Mac, learned it myself just a few months ago, lol).

As for the muCommander's icon, I don't have that issue on Intel-based laptop, only on M1-based one. Both running macOS Big Sur. Potentially due to Rosetta translation on the latter.

**Comment by sfuerte** [comment]
I think I found the "problem": "enable system notification (system tray)" option is responsible for that. I guess it shall be renamed for better clarity.

![image](https://user-images.githubusercontent.com/16941995/100410576-64a28980-302c-11eb-84b0-6f38f0600a8a.png)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
