### ISSUE TITLE
MuCommander 0.9.6 Java SE8 *NIX -- Relocation of Felix's Cache Directory

### ISSUE THREAD

**Issue by mj162** [mucommander/mucommander#399]
Happy New Year, thank you for providing support.

Installed into this R/O hierarchy, for example, within /opt/local:-
```shell
$ ls -l mucommander-0.9.6
total 816
drwxr-xr-x 1 me ours     52 Jan  2 17:11 app
drwxr-xr-x 1 me ours   5686 Jan  2 17:11 bundle
-rw-r--r-- 1 me ours 831417 Jan  2 17:03 mucommander-0.9.6.jar
-rwxr-xr-x 1 me ours   1018 Oct 16 14:26 mucommander.sh
```
When run, it crashes having failed to create a `felix-cache` directory (below).  I was unable to find any reference to specifying and so relocating that cache directory in any of the `~/.mucommander` configuration/preference files.

```shell
$ /opt/local/mucommander-0.9.6/mucommander.sh
No config.properties found.
ERROR: Unable to create cache directory: /opt/local/mucommander-0.9.6/felix-cache
ERROR: Error creating bundle cache.
java.lang.RuntimeException: Unable to create cache directory.
        at org.apache.felix.framework.cache.BundleCache.<init>(BundleCache.java:135)
        at org.apache.felix.framework.Felix.init(Felix.java:703)
        at org.apache.felix.framework.Felix.init(Felix.java:641)
        at com.mucommander.main.muCommander.main(muCommander.java:319)
Could not create framework: org.osgi.framework.BundleException: Error creating bundle cache.
org.osgi.framework.BundleException: Error creating bundle cache.
...
```

Thanks in advance.

**Comment by mj162** [comment]
*SOLVED*

Empty directory `felix-cache` omitted from install location.

**Comment by mj162** [comment]
Sorry for chopping-and-changing.  I mistakenly thought that the issue had been resolved by creating the omitted `felix-cache` directory.  As I owned the installation directory (not root), I had write permission and MuCommander continued to write in into /opt.

Be grateful for direction how to make MuCommander work in multi-user environment with simultaneous instances of MuCommander and apps installation directory (obviously) write-locked.  Thanks.

**Comment by ahadas** [comment]
hi @mj162 , on what operating system? muCommander doesn't write by default to /opt - where did you get the installer from?

**Comment by mj162** [comment]
Hi there Ahadas, thanks for a quick reply.

Currently installed on::
* Solaris 11.3 SPARC
* Ubuntu 16.04 x86_64

Going-on to install on:
* OpenVMS V8.3

Got the installer from the website AND did check the MD5.

On both Solaris and Linux, it's only working when I have write permission to the installation directory.  Lock it off, and it complains, e.g.:

```shell
ERROR: Error creating bundle cache.
java.lang.Exception: Unable to create bundle cache lock file: java.io.FileNotFoundException: /media/shared/opt/mucommander-0.9.6-1/felix-cache/cache.lock (Permission denied)
```
Thanks Ahadas

Mike.

**Comment by mj162** [comment]
Specifically:

[https://github.com/mucommander/mucommander/releases/download/0.9.6-1/mucommander-0.9.6-1.tar.gz](https://github.com/mucommander/mucommander/releases/download/0.9.6-1/mucommander-0.9.6-1.tar.gz)

**Comment by mj162** [comment]
When first run with write permission, it's populating `felix-cache` with c. 100 `bundle`n directories.  How do I make it create the felix cache in the user's home directory and not within the directory hierarchy of where the app is installed please?

**Comment by mj162** [comment]
Launcher script is [here](https://pastebin.com/9iuTd2z5)

(I appreciate that the VMS version is for MuCommander 0.9.3 and provided by a third-party)

**Comment by mj162** [comment]
Hi Arik,

Thanks for helping.

I got the installer (yesterday) from the [https://www.mucommander.com/](https://www.mucommander.com/) website using the "Linux/Other" link:

https://github.com/mucommander/mucommander/releases/download/0.9.6-1/mucommander-0.9.6-1.tar.gz

The MD5 is correct:

```bash
$ ls -lrt /media/shared/archive/bin/java/mucommander*
-rw-r--r-- 1 me us 42180862 Jan  8 10:19 
/media/shared/archive/bin/java/mucommander-0.9.6-1.tar.gz

$ digest -a md5 /media/shared/archive/bin/java/mucommander-0.9.6-1.tar.gz
3a9ada5ff111a3a6b475701c2bf13d44
```
Kind regards

Mike

**Comment by ahadas** [comment]
I see, so you're not using an installer but unpack the tar.gz manually.
The rpm and deb installers [set write permissions to the `felix-cache` folder](https://github.com/mucommander/mucommander/blob/master/package/unix/postinst).
I recall that I thought about moving that folder to be under the user's home folder as a fix to the problem that were reported back then on debian/ubuntu but ended us placing it within the installation folder. That is not customizable at the moment.
@mj162 can you provide write permissions on that folder?

**Comment by mj162** [comment]
Hi Arik, many thanks.
I guess the bit I'm having difficulty in understanding is, separate from the OS -- VMS, Solaris, Linux -- why the app requires that the user have write permissions over the directory the app is installed in.  It does seem a surprising requirement:  As the app is stored on app storage on a filer used by many, that would effectively require the app directory to be world writable...

**Comment by ahadas** [comment]
muCommander doesn't use the cached content but we're obligated to store it because we use OSGi behind the scenes, see https://felix.apache.org/documentation/subprojects/apache-felix-framework/apache-felix-framework-bundle-cache.html

It could be a better idea to store it in ~/.muCommander but I need to see what lead me to store it with the application's folder before

**Comment by mj162** [comment]
Thanks Arik,

In the mean time I'll implement the launcher on *nix to copy into /tmp/$user and run it out of there.

Thanks for your prompt attention.  Take care.

Mike

**Comment by mj162** [comment]
Hi Ahadas,

Thanks for working this issue.

Great, does that mean that you solved the OSGi cacheing requirement and have placed the cache in /tmp?  I take it you have made it multi-user and perhaps multi-instance within muti-user by placing the cache in /tmp/$HOME/$instance ?

**Comment by ahadas** [comment]
> Great, does that mean that you solved the OSGi cacheing requirement and have placed the cache in /tmp? I take it you have made it multi-user and perhaps multi-instance within muti-user by placing the cache in /tmp/$HOME/$instance ?

The cache folder is now created in /tmp on Linux and named per-user so multi-user works now
It probably wouldn't work with multi-instance per user though. It's not that simple to remove the cache folder so I would prefer not to create a folder per instance and risk overloading /tmp. It also doesn't make much sense for users to start multiple instances as multi-tab and multi-window browsing can be used within a single instance of the application

**Comment by mj162** [comment]
Well done Ahadas.  Thanks, per-instance would have been nice but per-user is an acceptable practicable compromise.

Since discovering it, have been increasingly using muCommander as go-to file browser/manager and particularly like its cross-platform support Unix/Linux.  (Haven't been brave enough to try the non-manlined-VMS fork yet).  Was a little fearful at first -- press wrong button and wipe entire share -- but now have confidence in it.  Remote ssh -X performance is very good.
