### ISSUE TITLE
Problems after running muCommander as administrator

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#400]
On my Mac I often run muCommander as an administrator, to have permission to move/delete certain files that I can't move/delete when I run muCommander normally. I do this by navigating to  /Applications/muCommander.app/Contents/MacOS,  then running at the command line the command

sudo JavaAppLauncher

This works fine, but almost always once I've done this, muCommander fails to start normally (non-administrator) afterwards. I've found that I can get it to start again by deleting the directory /Applications/muCommander.app/Contents/Java/felix-cache and all subdirectories, but it would be nice not to have to do this. So I have two questions:

1) Is there a better way to get administrator privileges than the method I've been using?

2) If so (and if not), is there a way not to have to delete /Applications/muCommander.app/Contents/Java/felix-cache to get muCommander to start again?

Thanks!

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
