### ISSUE TITLE
hangs at startup

### ISSUE THREAD

**Issue by docgonzo2015** [mucommander/mucommander#401]
it starts, the small startup window pops up and then nothing happens.
Any idea?

**Comment by ahadas** [comment]
Can you share your `snapshot.xml` file (in  ~/Library/Preferences/muCommander/ on macOS or ~/.muCommander)?
Removing this file would probably fix it, but please back it up before removing it

**Comment by docgonzo2015** [comment]
of course:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<snapshot>
    <file_presenter>
        <text>
            <line_numbers>true</line_numbers>
            <line_wrap>false</line_wrap>
            <full_screen>false</full_screen>
        </text>
    </file_presenter>
    <screen>
        <width>2560</width>
        <height>1440</height>
    </screen>
    <windows>
        <selection>-1</selection>
        <count>0</count>
    </windows>
    <recent_locations>
        <count>0</count>
    </recent_locations>
</snapshot>
`

**Comment by ahadas** [comment]
Thanks, and does it start after removing this file?

**Comment by docgonzo2015** [comment]
no. i tried to reinstall it, the same behavior :(

**Comment by ahadas** [comment]
@docgonzo2015 how did you install muCommander? on what version of macOS?

**Comment by ahadas** [comment]
closing due to insufficient data
