### ISSUE TITLE
No message shown on error while opening a file

### ISSUE THREAD

**Issue by essobedo** [mucommander/mucommander#403]
Sometimes, when I try to open a file nothing occurs so I have no way to know what's wrong. The idea of this improvement is to provide the output message provided by the process launched.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/mucommander/mucommander/pull/404

**Comment by essobedo** [comment]
Hi @ahadas, what do you think of this ticket and PR?

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
