### ISSUE TITLE
Open the file with the viewer in case of error

### ISSUE THREAD

**Issue by essobedo** [mucommander/mucommander#405]
If we try to open a file that has an extension for which no editor has been affected, we get an error. The idea of this improvement is to give the opportunity to open the file with the viewer in case the file could not be opened natively.

**Comment by essobedo** [comment]
The corresponding PR https://github.com/mucommander/mucommander/pull/406

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
