### ISSUE TITLE
Set different Mucommander Icon!?

### ISSUE THREAD

**Issue by Drallas** [mucommander/mucommander#407]
Is it possible to set a different Mucommander Icon; the default icon looks a bit outdated and i prefer to chose one that is more modern. I know i can change them myself in macOS, but would be nice if the App came with some options.

**Comment by ahadas** [comment]
@Drallas the third-party tools we use to package mucommander for Windows and macOS support a single icon so we are not able to provide several options. and as you said, anyone can change the icon of the installed application so it's unlikely we'll invest time on this.
