### ISSUE TITLE
Run Command does not recognize shell alias

### ISSUE THREAD

**Issue by stef204** [mucommander/mucommander#409]
Is it possible to have the `Run Command` recognize shell aliases? Using zsh on Linux.
I have `zsh -c` as `custom shell` under `Preferences|Misc`.

muCommander
Version: 0.9.6
Build date: 2021/01/02
Build number: b64d056

Java
Runtime version: 11.0.10
VM name: OpenJDK 64-Bit Server VM
VM version: 11.0.10+9
VM vendor: Oracle Corporation

OS
Name: Linux

**Comment by ahadas** [comment]
related to #661

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
