### ISSUE TITLE
Add synchronize directories and file diff.

### ISSUE THREAD

**Issue by hermeslm** [mucommander/mucommander#41]
I think it is a good job, so thanks for your work. A useful functionality could be add synchronize directories and file diff.

Hope that my feedback helps you guys!

**Comment by aadrian** [comment]
+1 for file diff, but also please add the possibility to configure an external diff tool like SmartSync if the "internal" one does not do the job.

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
