### ISSUE TITLE
File copies to wrong directory + more errors...

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#410]
If you ask to copy a file but try to specify the destination directory (rather than accepting the default offering of the second pane's directory) problems occur with muCommander 0.9.6 under macOS. Here's an example:

1) With the two panes showing DIR1 and DIR2, select a file in DIR1 and press F5 to copy it. By default, it'll offer to copy to DIR2, keeping the file name the same. However, edit the offered file name in the "Copy" window that pops up and just type, say, "file.txt" then Enter. In old versions of this program (and all the way back to Norton commander), this would copy the file to a new file called file.txt in the ORIGINAL directory, DIR1. However, when you ask to copy the file, it appears in DIR2 not DIR1.

2) But that's not all. Now select the new file DIR2/file.txt, press F6 to move it to DIR1, and accept the default name/directory. Now you get an error popping up telling you the source and destination directory are the same, even though you're trying to move the file to a different directory. Note that if you select a different file in DIR2, moving it to DIR1 works just fine.

**Comment by rhstanton** [comment]
Note that in the copy operation in the first part of point above,  I completely delete the offered directory, so "file.txt" is the only thing visible as the target name.

**Comment by ahadas** [comment]
@rhstanton thanks for reporting this. the first part is indeed a regression that caused by the changes for supporting Google Drive. the second part is not an issue - you can choose to override the file and that would essentially "move" it to DIR1

**Comment by jamadam** [comment]
I have used the app long time and the issue no.2 is definitly an issue and is recent regression. Dialog pops even if DIR1 /file.txt don't exists.

**Comment by ahadas** [comment]
@jamadam thanks for the feedback. you both were right about the second issue that is a consequence of the first issue.

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
