### ISSUE TITLE
MuCommander creates dotfolders in $HOME

### ISSUE THREAD

**Issue by extrowerk** [mucommander/mucommander#412]
MuCommander should respect the xdg variables and create its config files accordingly.
On Haiku it is discuraged creating dotfiles and dotfolders everywhere, and most importantly in the $HOME.

XDG variables are available:

```
~> env | grep XDG
XDG_CONFIG_DIRS=/boot/system/settings
XDG_DATA_HOME=/boot/home/config/non-packaged/data
XDG_CONFIG_HOME=/boot/home/config/settings
XDG_CACHE_HOME=/boot/home/config/cache
XDG_DATA_DIRS=/boot/system/non-packaged/data:/boot/system/data
```

MuCommander should store its configs in /boot/home/config/settings/mucommander
Dotfolders and files are discuraged even here.

**Comment by ahadas** [comment]
@extrowerk thanks for pointing this out. But how should this work for configuration files that are per-user?

**Comment by extrowerk** [comment]
If mc respect the XDG env vars, it should be ok.

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)

**Comment by extrowerk** [comment]
Thank you!
