### ISSUE TITLE
Support trees to view files

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [mucommander/mucommander#415]
Tree view is really convenient for viewing files
 
![asdad](https://user-images.githubusercontent.com/57204004/107121652-9b1f3f00-68ce-11eb-95b7-9574a98012ea.png)

**Comment by ahadas** [comment]
hi @YU5Z8X2CvH1fv4ep , tree view is supported already - you can enable it with `View -> 'Show tree view'`
