### ISSUE TITLE
Symbolic links are not copied

### ISSUE THREAD

**Issue by alexey-lysiuk** [mucommander/mucommander#42]
Copying of symbolic links (pointing to files or to folders) seems to do nothing.
I think users are expecting that muCommander will do the same as `cp` shell command and so it will create copies of files/directories links are pointed to.
Tested with 0.9.1rc2 for macOS.

**Comment by ahadas** [comment]
thanks for reporting this.
indeed, seems like a bug (when copying a folder that contains symbolic links they are not copied on purpose, but when the top level file is a symbolic link it could have been resolved first).
+1 for making the copy operation in mucommander behave as cp.
yet, I prefer not to change this for 0.9.1 at this point. it will be addressed later as part of the changes planned for the handling of symbolic links.
