### ISSUE TITLE
Unreadable font of current tab in settings on macOS

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#425]
The font of the current tab in settings on macOS is almost unreadable. See attached screenshot.

<img width="640" alt="Bildschirmfoto 2021-02-28 um 12 00 12" src="https://user-images.githubusercontent.com/79788982/109416150-c3292c00-79bc-11eb-8dca-c90ef52ba595.png">

**Comment by ahadas** [comment]
@Andreas0602 this is not set by mucommander but by the underlying look and feel you choose - can you please provide the versions of mucommander, Java and macOS you use?

**Comment by Andreas0602** [comment]
Version information

muCommander
Version: 0.9.6
Build date: 2021/01/02
Build number: b64d056

Java
Runtime version: 1.8.0_265
VM name: OpenJDK 64-Bit Server VM
VM version: 25.265-b01
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.16
Architecture: x86_64

Locale
Language: de
Country: DE
Encoding: UTF-8

**Comment by ahadas** [comment]
@Andreas0602 thanks for the additional information. it doesn't happen for me on macOS 10.15.5 so maybe it's something specific for AdoptOpenJDK 1.8.0_265 on macOS 10.16

**Comment by Andreas0602** [comment]
Is there something that I can do about it as a user?

**Comment by ahadas** [comment]
It also happens to me on Big Sur.
It appears to [be fixed in Java 16](https://bugs.openjdk.java.net/browse/JDK-8251377) so you can give it a try (by changing the bundled JRE). I don't know at the moment when we'll update the bundled JRE to Java 16

**Comment by Andreas0602** [comment]
I guess I would need more detailed instructions how to change the bundled JRE (exact URL of the required download, exact names of files/directories to be replaced, ...)

What I tried: Download Java from [https://www.java.com/download/](https://www.java.com/download/) and install it, then manually started /Applications/muCommander.app/Contents/Java/mucommander-0.9.8.jar by double-click. After that, muCommander looked different than usual (for example, the menu bar was located at the upper edge of the application window), but the problem of the unreadable font was not solved.

I also downloaded the Java SDK from [https://www.oracle.com/java/technologies/javase-jdk16-downloads.html](https://www.oracle.com/java/technologies/javase-jdk16-downloads.html), but it didn't seem to contain the necessary files (updated versions of the files located in /Applications/muCommander.app/Contents/Java/bundle/).

After that, I gave up.

**Comment by Andreas0602** [comment]
Seems like updating the bundled JRE is a bit too complicated for me. I'm just a normal user. I'll wait for the next official version of muCommander.

**Comment by Andreas0602** [comment]
This problem is fixed with

muCommander
Version: 1.0.0-snapshot
Build date: 2022/03/12
Build number: 7b52eff

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.2
Architecture: x86_64

**Comment by ahadas** [comment]
Thanks for checking that with the latest nightly!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
