### ISSUE TITLE
Auto-refresh of directory content doesn't work for USB stick under macOS

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#426]
Under macOS, auto-refresh of directory content doesn't work for USB stick. You'll have to press F9 to see the changed directory content.

**Comment by ahadas** [comment]
@Andreas0602 this works well for me - can you please describe the flow you did?

**Comment by Andreas0602** [comment]
1. Plug-in an USB stick to your Mac computer
2. In muCommander, go to the root directory of the USB stick. In my case, it's /Volumes/SanDisk/
3. Open Finder, select any file, and press command-C
4. In Finder, go to the root directory of the USB stick, and press command-V. As a result, the file selected in step 3 will be copied into the root directory of the USB stick

Expected result: muCommander will show the file
Actual result: muCommander does not show the file

**Comment by ahadas** [comment]
@Andreas0602 thanks for the follow up!
I managed to reproduce it - apparently the modification date of the parent folder doesn't change and thus muCommander that relies on it to detect changes doesn't refresh the folder.
I think the better way to address this is by using `WatchService` for monitoring changes to the presented folder

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
