### ISSUE TITLE
"Invert selection" doesn't select folders

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#427]
"Invert selection" doesn't select folders.

muCommander should follow the standard, which is that "invert selection" also selects folders, not only files.

**Comment by ahadas** [comment]
@Andreas0602 thanks for reporting this!

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
