### ISSUE TITLE
Text search finds nothing when option caseinsensitive=true

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#431]
On macOS, text search finds nothing when option caseinsensitive=true

For example, when searching the source code of muCommander with

> find:///~/Downloads/*?caseinsensitive=true&text=toolbar&text-caseinsensitive=true

muCommander will find nothing.

**Comment by ahadas** [comment]
Hi @Andreas0602 , it works ok for me so please provide more information - do you have a file in the `Downloads` folder that includes the string `toolbar` (case-insensitive)? what does `find:///~/Downloads/*?caseinsensitive=true` returns?

**Comment by Andreas0602** [comment]
Hi @ahadas, I have the source code of muCommander in my Downloads folder. Go to https://github.com/mucommander/mucommander, press the green "Code" button, and select "Download ZIP". After the download, unpack the file mucommander-master.zip to the Download folder. After unpacking, delete the zip archive mucommander-master.zip, so that you'll only have the folder mucommander-master (and all of the files and sub-folders in it) in your Downloads folder.

> do you have a file in the Downloads folder that includes the string `toolbar` (case-insensitive)?

Yes, I have several such files in the Downloads folder, for example the file ~/Downloads/mucommander-master/package/readme.txt

> what does `find:///~/Downloads/*?caseinsensitive=true` returns?

It returns 3249 items: All files and sub-folders in the folder mucommander-master.

**Comment by ahadas** [comment]
I see, thanks for the quick follow up.
It's a consequence of https://github.com/tools4j/unix4j/pull/66.
I'll check with them when the fix for that is expected to be published but until it is published, a workaround for this is to set the `Matches Regexp` option for text search

**Comment by ahadas** [comment]
v0.9.7 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/0.9.7-1)
