### ISSUE TITLE
Big Sur click behaviour

### ISSUE THREAD

**Issue by frankyxcs** [mucommander/mucommander#444]
Hi first thanx for all your work here !! I really appreciate this ..

You know  in the commander (header line) i can sort if i click on   NAME.     SIZE.   DATE  in the header line 

but the click behaviour is very bad. sometimes it works fine and sometimes it does not work or only after clicking 8 -10 times for example on NAME .

Is there any way to improve this ? 

Greets

Frank

**Comment by ahadas** [comment]
@frankyxcs hi Frank, I see that here and there some clicks are not being recognized and this can be improved. But I can't reproduce the scenario you describe in which 8-10 clicks are not recognized so I won't be able to verify that the solution indeed fixes the issue you face, would you be able to give a shot to a nightly release?

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
