### ISSUE TITLE
Support for tar files in the pax format

### ISSUE THREAD

**Issue by elemongw** [mucommander/mucommander#452]
The inbuilt provider for tar files is missing support for the posix format as defined by the POSIX.1-2001 specification (pax format). Currently, when an archive in this format is opened by muCommander, additional PaxHeaders.* folders will be be displayed which contain files with the metadata that this format supports.

On the official documentation of GNU tar, there is information that this will be the default in a future release (current default is gnu format). This note seems to have been there for a while so "soon" is relative but at the least openSUSE has already set it as the default output file format which is how I came up with the issue (and seems to have had it for quite some time, I faced this issue even on some quite old archives). 

The latest commons-compress (which is a continuation of the tar code from ant that muCommander also uses) appears to have good-enough support for this specification. During some tests I run, TarArchiveEntry.getNextTarEntry (from commons-compress) would return the correct file list while TarEntry.getNextEntry (from mucommander) included the PaxHeaders folders and files in the resulting file list.

The pax support code could potentially be ported from commons-compress or mucommander-format-tar could be ported to use the upstream project directly. I saw there is an entry to improve handling of archive files on the roadmap so I guess there may already be plans affecting this. If not, what would be the prefered way of resolving this?

ref: https://www.gnu.org/software/tar/manual/html_section/Formats.html

**Comment by ahadas** [comment]
@elemongw thanks for reporting!
yeah, the `Improve handling of archive files` task on the roadmap is too generic - but I didn't have this in mind as I was not even aware of this issue :) this task is about not to create the entire tree of the archive when it's being inspected as this can take long time for large archives. I'll change that task and also update the roadmap that is a bit outdated.
but back to this issue, IIRC we used to depend on the upstream project and this has changed [during the transition to OSGi](https://github.com/mucommander/mucommander/commit/ebe2bbe8e1f5bd7f8458d082826cdb583ec50b92) - but I don't remember if there was an issue to convert the apache-ant to an OSGi module or I just wanted not to have the other content of this project that we don't use in muCommander.
I'd suggest to give it a try to use the upstream project (and maybe exclude some of the stuff that is not being used with appropriate settings in the gradle script) - I think it's better, what do you think?

**Comment by elemongw** [comment]
I agree, that sounds like the better option. I will give it a go when time permits and report back.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
