### ISSUE TITLE
Reveal in Finder/Explorer does not work

### ISSUE THREAD

**Issue by Bradeskojest** [mucommander/mucommander#455]
On MacOS, reveal in Finder button does nothing, on windows, the same button says "error".

**Comment by ahadas** [comment]
@Bradeskojest thanks for reporting this! the macOS part was fixed in #589

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
