### ISSUE TITLE
Directory bookmarks

### ISSUE THREAD

**Issue by pponec** [mucommander/mucommander#460]
Bookmarked directories should always contain the **current original path**. If the path contains a **symbolic link**, the saved path contains real directory linked from the symbolic name.  For example save a directory `/myHome` (created by the next staement) to MuCommander bookmarks:

```bash
ln -s $HOME /myHome
cd /myHome
```

Operating system: Ubuntu 20.04.2 LTS
MuCommander Version: 0.9.6
Java version 11

**Comment by ahadas** [comment]
@pponec  thanks for reporting this, makes sense

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
