### ISSUE TITLE
Can't launch mucommander after updating from 0.9.6 to 0.9.7 (Linux Mint 20.1 x86_64)

### ISSUE THREAD

**Issue by KorneevVitaly** [mucommander/mucommander#468]
After updating there is no muCommander in installed apps list or in terminal command, so I reverted back to 0.9.6.
I used mucommander_0.9.7-1_all.deb from releases page.

**Comment by ahadas** [comment]
@KorneevVitaly how did you install muCommander? I tried to reproduce this on Linux Mint but after executing `sudo dpkg -i mucommander_0.9.7-1_all.deb` it appears in the applications list and can be executed from the terminal

**Comment by KorneevVitaly** [comment]
I installed ith through gui by double clicking on deb packege. Right now i tried to do this by executing same command and it the same outcome with no available mucommander:
![2021-05-14_15-29](https://user-images.githubusercontent.com/47393025/118270932-56a4d000-b4c9-11eb-87b9-a7390d1b1dda.png)

**Comment by ahadas** [comment]
@KorneevVitaly and if you type `mucommander` in the terminal?

**Comment by KorneevVitaly** [comment]
@ahadas mucommander: command not found
![2021-05-14_17-03](https://user-images.githubusercontent.com/47393025/118281797-49daa900-b4d6-11eb-8438-e06ab42b48ff.png)

**Comment by ahadas** [comment]
@KorneevVitaly thanks for the quick follow-up! I managed to reproduce it by using GDebi Package Installer.
This seems like a regression in the 3rd party tool that is used to produce the `deb` file. Bumping the version of that tool to its latest version solves this.
In the meantime (until the next version is released) you can try the following the worked for me - execute `sudo apt-get remove mucommander` and then `sudo dpkg -i mucommander_0.9.7-1_all.deb`

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
