### ISSUE TITLE
Support RAR 5

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#469]
muCommander 0.9.7 under macOS Big Sur cannot unpack multi-volume RAR archives. Please find an example here: [Test.zip](https://github.com/mucommander/mucommander/files/6477345/Test.zip) (I had to zip it, because GitHub does not allow to upload RAR files.) Such archives are commonly used, for example, in the Usenet. Other file managers like Double Commander or ForkLift can unpack such archives with no trouble.

**Comment by ahadas** [comment]
@Andreas0602 thanks for reporting this. This is a [known issue](https://github.com/mucommander/mucommander/issues/469) that the library we use doesn't support RAR 5. Implementing a plugin for RAR 5 in Java is out of the scope of muCommander, but if there's a third party library that supports it, we can definitely check it out

**Comment by ahadas** [comment]
Actually [I've already checked it](https://github.com/mucommander/mucommander/issues/420#issuecomment-782372364) and didn't find a Java library that support RAR 5. So I'm closing this one, but if someone finds such a library or implement something that can we can use, please reopen

**Comment by Andreas0602** [comment]
muCommander cannot unpack multi-volume RAR archives in RAR4 format either.

**Comment by Andreas0602** [comment]
Anyway, RAR5 is definitely needed as well.

**Comment by Andreas0602** [comment]
@ahadas, According to [this post](https://board.jdownloader.org/showthread.php?p=471287), JDownloader (which is written in Java too) can unpack RAR5 archives.
