### ISSUE TITLE
Support RAR5

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#470]
Since I'm not allowed to reopen closed issues, I'm opening a new one.

According to [this post](https://board.jdownloader.org/showthread.php?p=471287), JDownloader (which is written in Java too) can unpack RAR5 archives. So maybe muCommander can do the same.

**Comment by ahadas** [comment]
Yeah, you indeed can't reopen closed github issues but you can keep commenting on them and I will reopen if needed
I took a look at JDownloader and it is indeed written in Java and it is open source but it seems that uses unRAR for this. Unfortunately, this approach would not be cross-platform and doesn't comply with the way files are handled in muCommander (which is stream-based)

Closing this one as duplicate of #469 , let's move the discussion on alternative options there

**Comment by Andreas0602** [comment]
Okay, thanks anyway for your time and effort spent on investigating this issue and also in general for your great work on muCommander!
