### ISSUE TITLE
MacOS: Drag&Drop from Finder to muCommander does now "copy" (not longer "move")

### ISSUE THREAD

**Issue by WolfgangFranke** [mucommander/mucommander#479]
The Drag & Drop of files or folders from MacOS Finder (e.g. desktop) into muCommander does now a "copy" in v0.9.7.  It did a "move" in earlier versions of muCommander (e.g. v0.9.3). 

How can I change the behaviour of Drag&Drop back to "move"? 
When using Drag&Drop from MacOS Finder almost only to "move" files into muCommander, it's not convenient to always have to press the "alt" button for every move of the mouse.

muCommander
Version: 0.9.7-1
Build date: 2021/05/08
Build number: 1729466

Java
Runtime version: 1.8.0_265
VM name: OpenJDK 64-Bit Server VM
VM version: 25.265-b01
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.15.7  and  11.4
Architecture: x86_64

**Comment by ahadas** [comment]
Yeah, the default changed to "copy" in 0.9.4 to align it with the default of internal (i.e., in-app) drag and drop (see #255 ). @WolfgangFranke so you'd like to have it configurable?

**Comment by WolfgangFranke** [comment]
@ahadas  yes, I would like to have it configurable , but no UI or Menu entry required,  just somehow configurable in deep settings would be ok for me.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)

**Comment by WolfgangFranke** [comment]
Congratulations to version 1.0!
The new 'Set default file drag and drop action to COPY' checkbox works like a charm, thank you!
