### ISSUE TITLE
File associations under Linux

### ISSUE THREAD

**Issue by yosaba** [mucommander/mucommander#48]
I have used (and loved) muCommander for years.  In the most recent, 0.9.1 release (and its release candidate), launching files no longer uses the native Linux file associations.  For example, using Nautilus, I set the application I want to be used to open mp3 files to  be VLC.   In previous versions of muCommander, this always resulted in mp3 files actually being opened by VLC (when I pressed enter or right arrow in muCommander).  

In 0.9.1, however, muCommander hands the file off to Firefox to open.

I have not tested this under other operating systems.

**Comment by ahadas** [comment]
@yosaba can you please check if 'gnome-open <mp3 file>' or 'gvfs-open <mp3 file>' opens the file using VLC while 'xdg-open <mp3 file>' opens it with firefox?

**Comment by yosaba** [comment]
If I can just answer by replying to this email, gnome-open and gvfs-open 
launch "I.ifo" files in VLC while xdg-open send them to Firefox.

(All three open MP4 files in VLC.)
