### ISSUE TITLE
Please make muCommander remember editor and viewer window position

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#481]
Please make muCommander remember the width, height, and position of the window of the in-built editor and viewer between sessions.

**Comment by ahadas** [comment]
Hi @Andreas0602, does it mean you prefer the window to be set with the same dimensions and position regardless of the content of the file?

**Comment by Andreas0602** [comment]
Yes, I prefer the window to be set with the same dimensions and position regardless of the content of the file -- as long as it's a text file. The automatic mechanism to determine the dimensions and position does not work satisfactorily for me in the case of text files.

In the case of photos, the automatic mechanism to determine the dimensions of the window makes sense and should be kept. By the way, unfortunately, the built-in photo viewer is useless for me as long as the issue #424 is not fixed.

**Comment by ahadas** [comment]
I see. yeah, I guess some would find it better this way but I really don't want to put too much effort into the built-in viewer/editor. would you be able to achieve this with a third-party text editor (like, e.g., Notepad++ on Windows)? There's a way to [configure a custom command to let mucommander open files with third-party apps](https://github.com/mucommander/mucommander/wiki/Custom-Commands) which I would recommend, if applicable, rather than introducing yet another configuration to the built-in text editor/viewer

**Comment by Andreas0602** [comment]
Sure, using third-party tools is an option, although I would prefer using muCommander's built-in tools. They have some advantages: They start faster than external programs, they are faster to exit (just press ESC), and they save you the trouble of installing additional programs.

**Comment by Andreas0602** [comment]
By the way, the built-in text viewer of Total Commander works well together with the built-in search function: In the list of search results, press F3 to open a file from the list, then press F3 again to jump to the first occurrence of the search string, then press F3 again to jump to the next occurrence, and so on. It would be great if this would also be possible with muCommander!

**Comment by Andreas0602** [comment]
So, frankly, I dislike hearing that you don't want to put much effort into the built-in viewer/editor.

**Comment by ahadas** [comment]
> By the way, the built-in text viewer of Total Commander works well together with the built-in search function: In the list of search results, press F3 to open a file from the list, then press F3 again to jump to the first occurrence of the search string, then press F3 again to jump to the next occurrence, and so on. It would be great if this would also be possible with muCommander!

Hehe, I didn't think about this use case :) yeah, that's a benefit of modeling the search results as files in a folder

**Comment by ahadas** [comment]
> So, frankly, I dislike hearing that you don't want to put much effort into the built-in viewer/editor.

I'm not saying that I wouldn't accept it as a contribution or do it myself if I see that there's a demand for this. But I think that the focus should be on other things at this point.
Let's keep this one open for now.

**Comment by jamazurak** [comment]
+1 to store the viewer / editor panel size.

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
