### ISSUE TITLE
Cannot search for zip files

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#493]
Steps to reproduce the issue:

1. Under macOS, in muCommander, go to File -> Find...
2. In the Find dialog, in the Filenames field, enter: *.zip 
3. Leave the other fields in the Find dialog unchanged.
4. Press the Find button.

Result: Error message "Folder access error: This folder doesn't exist or is not available."

The error occurs irrespective of the folder in which you do the search.

The error will not occur when you search e.g. for txt files.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
