### ISSUE TITLE
Fragmented caret when renaming a file

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#497]
When you select a file, press Shift+F6, and then move the caret, the caret will be fragmented. See the attached screenshot. In the screenshot, you can see a vertical line between the letters "n" and "d" (the real position of the caret) and also a fragmented vertical line between the letters "e" and "r" (the original position of the caret before being moved).

<img width="154" alt="screenshot" src="https://user-images.githubusercontent.com/79788982/125189305-b30d3d00-e237-11eb-95f3-b6d97bd92ac3.png">

The problem occurs with muCommander v0.9.7 under macOS Big Sur with "Mac OS X" look & feel. The problem is independent of the font.

**Comment by Andreas0602** [comment]
This problem is **not** fixed with

muCommander
Version: 1.0.0-snapshot
Build date: 2022/03/12
Build number: 7b52eff

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.2
Architecture: x86_64

**Comment by Andreas0602** [comment]
I'll close this issue, because the issue does not occur when using the FlatLaf look and feel, and FlatLaf now comes together with muCommander.

**Comment by ahadas** [comment]
yeah, see #651

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
