### ISSUE TITLE
Dynamic FileTypes

### ISSUE THREAD

**Issue by zotona** [mucommander/mucommander#5]
I am waiting it for a years! After Frigate and Dos Navigator, its is very usefull.
For example:
    <GROUP order="1" color="R;G;B" name="Multimedia" mask="mp3;wav;as;cda;mid;mjf;it;xm;s3m;stm;mod;dsm;far;ult;mtm;669;mp;mp1;voc;wma;m3u;pls;ogg;ape;apl;mpc;flac;m4a;aac;aiff;" />
    <GROUP order="2" color="R;G;B" name="Images" mask="bmp;ico;gif;jpg;wmf;pcx;jpeg;cur;ani;tga;psd;emf;tif;tiff;cdr;png;pbm;" />
    <GROUP order="2" color="R;G;B" name="Program source" mask="pas;c;cpp;asm;dpk;dpr;dfm;sql;h;hpp;inc;bas;bpg;js;vbs;" />

For each group we assigned color, and order. 
Order, its for advanced sorting in FolderPanel

i could make it, but i dont know how. if you give me a path i could try!

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
