### ISSUE TITLE
Automatic refresh of file panel contents sometimes doesn't happen

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#500]
Automatic refresh of the file panel contents (i.e. of the list of files) sometimes does not happen. You have to manually press F9 in these cases. Unfortunately I cannot give precise instructions how to reproduce the problem. It happens sometimes after copying files, or deleting files, or renaming files.

I'm using the latest version of muCommander on macOS Big Sur.

**Comment by Andreas0602** [comment]
Two more observations: When the problem occurs, then
1. there is a sometimes blue veil over the field with the path (encircled in red in the screenshot below)
2. the button "stop folder change" (marked with a red arrow in the screenshot below) is sometimes active

<img width="783" alt="screenshot" src="https://user-images.githubusercontent.com/79788982/129711824-d9cb9e6e-0106-4a06-a22d-edc0a74c4221.png">

**Comment by Andreas0602** [comment]
I've managed to make the problem disappear by downloading the [Flat Look & Feel](https://www.formdev.com/flatlaf/) and importing it via Preferences > Appearance > Look & Feel > Import into muCommander. By the way, this also made the problems #425 and #497 go away.

So, the Mac OS X Look & Feel coming with muCommander seems to be outdated and cause various problems. It would be good if it would be updated soon.

Unfortunately, the [Flat Look & Feel](https://www.formdev.com/flatlaf/) isn't the perfect solution either. It has some other minor issues, but at the moment — as long as muCommander's built-in Mac OS X Look & Feel isn't updated — it's the best solution for macOS users in my opinion.

**Comment by Andreas0602** [comment]
This problem is **not** fixed with

muCommander
Version: 1.0.0-snapshot
Build date: 2022/03/12
Build number: https://github.com/mucommander/mucommander/commit/7b52eff20563d88e2a8c91eb820cf592e50b7f20

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.2
Architecture: x86_64

**Comment by Andreas0602** [comment]
I'll close this issue, because the issue does not occur when using the FlatLaf look and feel, and FlatLaf now comes together with muCommander.

**Comment by ahadas** [comment]
see #651

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
