### ISSUE TITLE
Cannot change date of files in search results list

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#507]
Steps to reproduce the issue:

1. In an empty folder, create the files a.txt and b.txt
2. In the same folder, execute a file search (via menu item File > Find) for the filenames *.txt
3. Execute Mark > Mark all to select a.txt and b.txt in the list of found files
4. Execute File > Change date

As a result, the button "Change" in the "Change date" dialog will be grayed out.

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
