### ISSUE TITLE
Security issue on mucommander 

### ISSUE THREAD

**Issue by b1nslashsh** [mucommander/mucommander#508]
Hey, 

I have two disclosed two security issue on mucommander 
https://www.huntr.dev/bounties/1-other-mucommander/
https://www.huntr.dev/bounties/1625335746525-mucommander/mucommander/

Please have a look and let me know updates 

Regards,
Muhaimin

**Comment by ahadas** [comment]
Hi @b1nslashsh ,
Thanks for reporting this.
This reminds me that there was a PR for handling this (#467) that looks ok but didn't get in, I'll polish it a bit and get the fix in

**Comment by b1nslashsh** [comment]
hey @ahadas ,
That's cool, thanks for your response if you think that's a valid bug feel free to validate that 

regards,
muahimin

**Comment by ahadas** [comment]
> That's cool, thanks for your response if you think that's a valid bug feel free to validate that

Sure, validated the first one. What's the difference between the first disclosure and the second disclosure?

**Comment by b1nslashsh** [comment]
I thought two functions are separate and fix will be different , if you think they are no different that's fine 🙌

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
