### ISSUE TITLE
Mkdir autoname

### ISSUE THREAD

**Issue by klayman** [mucommander/mucommander#51]
Please, bring back the autofill feature for the make file/dir dialogs (the same as the "mkdir autoname" in mc). It was enabled by default in the older versions of mucommander and is very handy in some workflows.  In my opinion, this feature has absolutely no drawbacks - anyone can type the new filename immediately or edit the suggested template.

**Comment by ahadas** [comment]
Thanks for reporting this. We removed this feature long ago since we didn't think it is useful, but if you find it useful then I see no reason not to bring it back.

**Comment by klayman** [comment]
Great! Thank you very much!
