### ISSUE TITLE
Graphical issue when renaming files with certian look and feels: GTK+ or Nimbus 

### ISSUE THREAD

**Issue by Rykarix** [mucommander/mucommander#515]
Hi folks - Thanks for providing a great tool

Before trying to rename:
![image](https://user-images.githubusercontent.com/8267553/135748582-5b68fb59-ad75-4a47-a2b7-50df58f01538.png)

This is what happens when trying to rename:
![image](https://user-images.githubusercontent.com/8267553/135748588-35b281f6-3eec-45d3-b580-be00e57ebc77.png)

By the looks of this particular issue the font size is being decreased

If I swap to CDE or Metal it doesn't happen:
![image](https://user-images.githubusercontent.com/8267553/135748604-802b9211-5348-445f-844c-88ba584766ae.png)
![image](https://user-images.githubusercontent.com/8267553/135748613-fc611b69-80dd-4c97-823f-636bc392f1a9.png)

Also happens a bit in Nimbus:
![image](https://user-images.githubusercontent.com/8267553/135748627-200515f4-7e6b-4bf6-8bb8-7d6f9f311936.png)

The issue here seems to be that the 'embossing' effect of the rename box is clipping into the text?

Hope this is useful. Please let me know if I can help provide anything else

**Comment by ahadas** [comment]
@Rykarix thanks for reporting this! I merged a fix that sets the text area with an empty border for fix that

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
