### ISSUE TITLE
File that copied from 7-zip archive have zero bytes size (mac os Big Sur)

### ISSUE THREAD

**Issue by al-u-m** [mucommander/mucommander#521]
Archive was created by 7-zip utility on Windows 10. 
On mac os Big Sur i can explore it's folders and files. But when i try to copy a file from the archive, it is empty and has 0 bytes size.

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
