### ISSUE TITLE
0.9.7-1_all.deb does not install properly 

### ISSUE THREAD

**Issue by KogentaTiger** [mucommander/mucommander#523]
"a179aaba49a805936415750c6cba0f20 mucommander_0.9.7-1_all.deb", does not install properly. 

After install there is no content in "/usr/share/mucommander/" and no icon appears in the menu.

Uninstall not working properly either. (("sh: 0: getcwd() failed: No such file or directory"))

Workaround for me : "uninstall" mucommander ignore the error and install
1dff46d9be24d3d1e2addb4325b47788 mucommander_0.9.6-1_all.deb.

**Comment by ahadas** [comment]
@KogentaTiger thanks for reporting this, on what operating system?

**Comment by KogentaTiger** [comment]
> 

Linux(Mint)

**Comment by ahadas** [comment]
Works fine on Linux Mint 20.3 "Una"
