### ISSUE TITLE
font size: way tooo small

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mucommander/mucommander#524]
There is no option to increase the font size in appearance < preferences. So, i am having huuuge inconvenience in navigating the menu items.

![javaw_sjSGbErXEo](https://user-images.githubusercontent.com/19423063/139525526-d54d6640-9ed1-4f3b-8ec6-cb0f38d4fd66.png)

![image](https://user-images.githubusercontent.com/19423063/139525356-9c6d6f75-92c1-40fe-b835-c4d1297e1b90.png)

### System info:
- muCommander Version: 0.9.7-1
- OS: Windows 10 20H2
- 1920*1080 px display with system wide scaling of 125%

**Comment by yashpalgoyal1304** [comment]
duplicate 🔍 : [small](https://github.com/mucommander/mucommander/issues?q=is:issue+is:open+small)

no, #77 is not a duplicate

**Comment by ahadas** [comment]
@yashpalgoyal1304 is the font still too small with v1.0.0?

**Comment by yashpalgoyal1304** [comment]
@ahadas havent tested yet, will check in some time (read: ~10-20 days on average)

**Comment by yashpalgoyal1304** [comment]
yes, it's fixed on v1.0.1-1

**Comment by yashpalgoyal1304** [comment]
hey @ahadas so, i used the mucommander for some time, and:
* it takes so long to start
* is there any way that i can copy the addresses in the Unix format, i.e. choose forward slashes `/` instead of the windows' stupid backslashes `\` ??
* the way it functions and designed, it feels like it is more intended to be an app for accomplishing some specific tasks and not a general replacement for the default explorer - am i right? if yes, then why so? 
* i'd love to be able to use this as a full replacement and not having to rely on windows explorer
