### ISSUE TITLE
Windows 10 - right click to local text editor

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#529]
Hello
on Windows 10
I would like to open text files in my text editor (EditPad Pro) with a direct right click. Without opening the Windows file explorer to access the system shell.
Is this possible?
Looking forward to your return,
best regards,
Nico

**Comment by ahadas** [comment]
Hi @nico92GitHub , 
You can add a custom command as explained [here](https://github.com/mucommander/mucommander/wiki/Custom-Commands). You'll need to point to the exe file of EditPad Pro and provide it an alias that will appear in the 'open with..' option of the file context menu

**Comment by nico92GitHub** [comment]
Thank so much Arik!

I'm not very comfortable with documentation...
First, I did not find a file "commands.xml" in arborescence:
C:\Users\Administrateur\.mucommander
C:\Program Files (x86)\muCommander
I created this file "commands.xml" in my admin directory. Here is the contents of the file:

<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="openEXE" type="system" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe"/>
</commands>

As you can see from the attachments, this does not work.
Can you tell me how to do this more precisely?

Waiting for your return,
best regards,
Nico

![ScreenShot_002](https://user-images.githubusercontent.com/22394276/146147976-67b0bdbf-e425-418a-a231-d434c9ecf2c4.jpg)
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/146147980-f702185f-bd8c-4848-aaa5-455b39cdda1e.jpg)

**Comment by ahadas** [comment]
@nico92GitHub you didn't add the content of the file

**Comment by nico92GitHub** [comment]
Oops! Sorry

<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="openEXE" type="system" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe"/>
</commands>

[commands-XML.txt](https://github.com/mucommander/mucommander/files/7725004/commands-XML.txt)

**Comment by ahadas** [comment]
OK, so the problem is that `type="system"`, that's why [the command is invisible](https://github.com/mucommander/mucommander/blob/0.9.7-1/mucommander-command/src/main/java/com/mucommander/command/Command.java#L35-L36). You need to drop that part, and it's better not to name it `openEXE`, so you can replace it with something like:
```xml
<commands>
    <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe"/>
</commands>
```

**Comment by nico92GitHub** [comment]
Well, it's coming along...





with this command file:



By replacing the "\" with "/":
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="EditPadPro7" value="C:/Program Files/Just Great Software/EditPad Pro 7/EditPadPro7.exe"/>
</commands>


EditpadPro opens correctly but it has not loaded the pointed document.

Is there a parameter to indicate the transmitted file(s), like in regedit or under dos "...EditPadPro7.exe" "%1"


In the meantime your precious return...
Nico




OK, so the problem is that `type="system"`, that's why [the command is invisible](https://github.com/mucommander/mucommander/blob/0.9.7-1/mucommander-command/src/main/java/com/mucommander/command/Command.java#L35-L36). You need to drop that part, and it's better not to name it `openEXE`, so you can replace it with something like:
```xml
<commands>
   <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe"/>
</commands>
```

**Comment by ahadas** [comment]
ah right right, missing the `$f`:
```xml
<commands>
   <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe $f"/>
</commands>
```

**Comment by nico92GitHub** [comment]
Super génial Arik :) ça marche très bien avec cette syntaxe:
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="EditPadPro7" value="C:/Program Files/Just Great Software/EditPad Pro 7/EditPadPro7.exe $f"/>
</commands>



But...
I still have one last question that I can't solve: How to create multiple entries that point to external softwares?

I tried these syntaxes without success:

<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="EditPadPro7" value="C:/Program Files/Just Great Software/EditPad Pro 7/EditPadPro7.exe $f"/>
</commands>

<commands>
    <command alias="PSPad" value="E:\Program Files\PSPad\PSPad.exe $f"/>
</commands>

Here, the "EditPad Pro" entry works and the "PSPAD" entry appears but makes an error (execution error during the task):
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="PSPad" value="E:\Program Files\PSPad\PSPad.exe $f"/>
    <command alias="PSPad" value="E:\Program Files\PSPad\PSPad.exe $f"/>
</commands>



Is this possible?

Thank you in advance,
Nico


ah right right, missing the `$f`:
```xml
<commands>
  <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe $f"/>
</commands>
```

**Comment by nico92GitHub** [comment]
Oops, oops, I am a donkey!!
If I do not put slash everywhere ...


The redirection to the 3 text editors works perfectly.
However, the following syntax (for compare_md5.bat) does not make any mistake, but do not make anything (What is more enigmatic!).
Also with this syntax "    <command alias="COMPARE_MD5" value="COMPARE_MD5.bat $f"/>"



The batch "COMPARE_MD5.bat" takes the name of the file to be processed in the parameter %1% and calculates the MD5 of this file


If you have an idea to launch a batch script, I'm interested :)
Nico



ah right right, missing the `$f`:
```xml
<commands>
  <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe $f"/>
</commands>
```

**Comment by nico92GitHub** [comment]
For the entry compare_md5.bat, it works but indirectly:

<command alias="COMPARE_MD5" value="E:/Program Files/ConEmuPack_Portable/ConEmu64.exe -run {COMPARE_MD5.bat} $f"/>

What do you think?
Nico








Ceci est un message transf�r�
De : n.f mirkov ***@***.***>
� : mucommander/mucommander ***@***.***>
Date : vendredi 17 d�cembre 2021, 11:31:12
Objet : [mucommander/mucommander] Windows 10 - right click to local text editor (Issue #529)

===8<============== Message d'origine ===============


Oops, oops, I am a donkey!!
If I do not put slash everywhere ...


The redirection to the 3 text editors works perfectly.
However, the following syntax (for compare_md5.bat) does not make any mistake, but do not make anything (What is more enigmatic!).
Also with this syntax "    <command alias="COMPARE_MD5" value="COMPARE_MD5.bat $f"/>"



The batch "COMPARE_MD5.bat" takes the name of the file to be processed in the parameter %1% and calculates the MD5 of this file


If you have an idea to launch a batch script, I'm interested :)
Nico



ah right right, missing the `$f`:
```xml
<commands>
  <command alias="EditPadPro7" value="C:\Program Files\Just Great Software\EditPad Pro 7\EditPadPro7.exe $f"/>
</commands>
```

--
Reply to this email directly or view it on GitHub:
https://github.com/mucommander/mucommander/issues/529#issuecomment-995985689
You are receiving this because you were mentioned.

Message ID: ***@***.***> 

===8<=========== Fin du message d'origine ===========

**Comment by ahadas** [comment]
Did you try a full path to the script?
And btw, I see that previously you added two `commands` elements to the file - you shoikd have added a single one and multiple `command` elements inside it

**Comment by nico92GitHub** [comment]
Thanks to your various information, my script is now functional:
<?xml version="1.0" encoding="UTF-8"?>
<commands>
    <command alias="COMPARE_MD5" value="E:/Program Files/ConEmuPack_Portable/ConEmu64.exe -run COMPARE_MD5.bat $f"/>
    <command alias="EditPadPro7" value="C:/Program Files/Just Great Software/EditPad Pro 7/EditPadPro7.exe $f"/>
    <command alias="HxD R-W" value="C:/Program Files/HxD/HxD.exe $f"/>
    <command alias="PilotEdit" value="E:/Program Files/PilotEdit x64/PilotEdit.exe $f"/>
    <command alias="PhotoFiltre" value="C:/Program Files (x86)/PhotoFiltre/PhotoFiltre.exe $f"/>
    <command alias="PSPad" value="E:/Program Files/PSPad/PSPad.exe $f"/>
    <command alias="QMMP" value="E:/Program Files (x86)/Qt-based Multimedia Player/qmmp.exe $f"/>
    <command alias="SMPlayer" value="E:/Program Files/SMPlayer/smplayer.exe $f"/>
    <command alias="Wavosaur" value="E:/Program Files/Wavosaur/Wavosaur.exe $f"/>
</commands>
-------------------------------------------------------------------------------------------------------------------------------
Now, just a note about locked tabs.
I thought a locked tab kept "in absolute" the path it contains.
But if I navigate in the tree of an tab, then I click on another tab and I come back on the first tab, it comes back on the last displayed location, but not on the initial location of the tab.
Is there a way to assign to a tab the path it contains unconditionally?

Looking forward to your return,
Nico

**Comment by nico92GitHub** [comment]
[commands-xml.txt](https://github.com/mucommander/mucommander/files/7739887/commands-xml.txt)

Oops, attached is my script that works great.
Nico

**Comment by ahadas** [comment]
Great to hear custom commands work for you now
I filed a separate issue on the tab locking part - the location of a locked tab shouldn't change, even from the tree view

**Comment by nico92GitHub** [comment]
Thank you so much :)

I'm afraid there a problem in addition to the problems with tabs.
I just understood that Mucommander does not like file names with some characters.
Example: Double clicking on "Slideshow(3).exe" does not make a mistake but opens the next file in directory.
While, a double click on "Slideshow3.exe" opens this executable.

Still work to do ;-)
Nico

**Comment by nico92GitHub** [comment]
Just a clarification on the rejected character issue. Screenshot in attachments:

The screenshot 1 shows that "Diaporama(3b).exe" generates an error that "Diaporama" is not recognized by the system. The interpretation of the characters of the file name has stopped just before the character "(".

The screenshot 2, more problematic, shows that by double clicking on "Diaporama(3b).exe", there is no error but it is "Diaporama.exe" which is executed!

I let you see this quietly ...
regards,
Nico

![ScreenShot_002](https://user-images.githubusercontent.com/22394276/146689105-af99b9bf-2007-40e0-9e96-b60660c37098.jpg)
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/146689107-a581b6ee-19fa-4913-9099-1d1169927cdf.jpg)

**Comment by nico92GitHub** [comment]
reOops!
I misplaced the top arrow (double clic). The arrow should show Diaporama(3).exe.
Désolé... Sorry...
Nico

**Comment by nico92GitHub** [comment]
MSG:
"Diaporama[3b].exe"  The characters "[" "]" do not block. This executable starts normally.
Nico

**Comment by ahadas** [comment]
@nico92GitHub thanks for reporting this, can you please file a different issue? I'm afraid the information here will be missed

**Comment by nico92GitHub** [comment]
I hope I did the right thing on github by creating a new issue from our last exchanges(github of course)...
Nico




@nico92GitHub thanks for reporting this, can you please file a different issue? I'm afraid the information here will be missed
