### ISSUE TITLE
Viewer/Editor find shortcuts on macOS

### ISSUE THREAD

**Issue by alexey-lysiuk** [mucommander/mucommander#53]
Viewer and Editor find shortcuts are not native to macOS: `Ctrl+F` instead of `Command+F`, `F3` instead of `Command+G` and `Shift+F3` instead of `Shift+Command+G`.
And there is no way to customize these shortcuts.

Moreover `Ctrl+F` doesn't work, need to select Find option from menu to make the corresponding window appear.

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
