### ISSUE TITLE
Characters "(" ")" Not recognized in File Name Executable in Win10

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#532]
Just a clarification on the rejected character issue. Screenshot in attachments:

The screenshot 1 shows that "Diaporama(3b).exe" generates an error that "Diaporama" is not recognized by the system. The interpretation of the characters of the file name has stopped just before the character "(".

The screenshot 2, more problematic, shows that by double clicking on "Diaporama(3b).exe", there is no error but it is "Diaporama.exe" which is executed!

I let you see this quietly ...
regards,
Nico

![ScreenShot_002](https://user-images.githubusercontent.com/22394276/146689105-af99b9bf-2007-40e0-9e96-b60660c37098.jpg)
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/146689107-a581b6ee-19fa-4913-9099-1d1169927cdf.jpg)

_Originally posted by @nico92GitHub in https://github.com/mucommander/mucommander/issues/529#issuecomment-997453367_

**Comment by ahadas** [comment]
@nico92GitHub  thanks for reporting this, will be fixed in v0.9.8

**Comment by nico92GitHub** [comment]
OK :)
Do you have an idea when will the v0.9.8 come out?

I am waiting for the resolution of 2 problems, which we have already talked about:
(1) After browsing, a tab does not display its initial location.
(2) Certain characters not recognized in the names of file.
Nico

**Comment by nico92GitHub** [comment]
re...
add_characters not recognized(1):
It is likely that it will be solved globally, but I prefer to tell you another problem with a directory whose name contains the characters "(" ")".
Indeed, MuCommander can enter in the "E:\TEMP01\TEMPE\TEMPDEV(1)" directory, but it will make an error (see attachment) to open an executable(.exe) file.
However, it will successfully open .mp4, .jpg or .txt files in the same "TEMPDEV(1)" directory.

Good reception,
Nico

![ScreenShot_001](https://user-images.githubusercontent.com/22394276/147403842-6e90b832-ba6e-491f-9276-74bf48b39d30.jpg)

**Comment by ahadas** [comment]
@nico92GitHub  There's no release date yet. It depends on how long it will take to try upgrading the integrated JRE - I think it will be the last thing to do before releasing v0.9.8 and the other pending changes will be pushed out to the next release

About the second issue, would you mind testing if it works with [the nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly)?

**Comment by nico92GitHub** [comment]
Hello Ahadas!
With the nightly build v0.9.8-snapshot, problems (1) and (2) seem to be solved !:)
I haven't tested it thoroughly, but the tabs keep their original location and the "(" ")" are accepted in file and directory names. Cool!
While waiting for the new official version, I keep this "nightly". Thanks a lot :))
Nico

**Comment by ahadas** [comment]
great to hear,
just note that while using the "nightly" version you won't get a notification that a new stable version was released - I'll try to remember to update the relevant github issues but it is also recommended to check one in a while just in case that I miss

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
