### ISSUE TITLE
Focus lost after Move/Copy operation on MacOS (multiple versions)

### ISSUE THREAD

**Issue by aobszyns** [mucommander/mucommander#536]
When moving or copying files progress window closes - there is no way to use arrow keys any longer.
Quickest is just doing alt+tab or similar app switch and then everything is fine.
I have the same behaviour with multiple macos versions.

There is another related issue. 
After coping/moving files ie. from left panel to the right one. When operation finishes if I will try to click to open folder on the right panel... action will be done for the left one highlighted item.

It is hard to demonstrate, I can thing of making short video if needed.
Reproduction is very easy. i.e. copy file from left to right and then double click on this already copied file.
Action will happen for item in source panel.

Tested today with "mucommander-0.9.7-1.dmg" still the same.

Regards.

**Comment by Andreas0602** [comment]
For what it's worth, both issues  don't occur for me. I'm using the latest available nightly build (before the [link](https://github.com/mucommander/mucommander/releases/tag/nightly) to the nightly builds got broken) plus [FlatLaf](https://www.formdev.com/flatlaf/). The look & feel and Java bundled with muCommander 0.9.7 seems quite outdated and has a number of issues.

**Comment by ahadas** [comment]
> For what it's worth, both issues don't occur for me. I'm using the latest available nightly build (before the [link](https://github.com/mucommander/mucommander/releases/tag/nightly) to the nightly builds got broken)

Seems the jenkins job that published the nightly build is not stable at the moment, I'll check it

**Comment by ahadas** [comment]
> > For what it's worth, both issues don't occur for me. I'm using the latest available nightly build (before the [link](https://github.com/mucommander/mucommander/releases/tag/nightly) to the nightly builds got broken)
> 
> Seems the jenkins job that published the nightly build is not stable at the moment, I'll check it

Looks like it works now, I'll check to see if it reproduces again

**Comment by ahadas** [comment]
@aobszyns Yes, please upload a video that demonstrates it because I can't reproduce these issues

**Comment by aobszyns** [comment]
Small recording.
2 panels, left is empty, on the right few directories
creating new directory and clicking on the left panel.... do directory change on the right where last focus were after directory creation.

https://user-images.githubusercontent.com/31958328/147513135-62c45a50-2210-4903-a554-ca3bbd81bc85.mov

**Comment by Andreas0602** [comment]
Just out of curiosity: How did you manage to get the menu bar (File  Mark  View ...) inside the window of muCommander?

For me, the menu bar is at the upper edge of the desktop. Also, for me, the leftmost dropdown menu is the Apple menu (with the Apple icon), and the second leftmost dropdown menu is the muCommander menu.

**Comment by ahadas** [comment]
@aobszyns can you please add the Java and OS information from the `About` dialog? it indeed seems weird that the menu bar is set that way as @Andreas0602 wrote and the reason for this issue might be related to the underlying Java platform so it's interesting to see how it looks like from the application's point of view

**Comment by aobszyns** [comment]
Visual part can be some settings / tunings from the past. I'm using it since many years.
I opened this issue after I tried muccmd on my wife macos and there was not this focus issue...

About details:
muCommander
Version: 0.9.7-1
Build date: 2021/05/08
Build number: 1729466

Java
Runtime version: 1.8.0_265
VM name: OpenJDK 64-Bit Server VM
VM version: 25.265-b01
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.15.7
Architecture: x86_64

Locale
Language: en
Country: PL
Encoding: UTF-8

**Comment by aobszyns** [comment]
Portable (jar) reports only: Version 1.0 (1.8.0_311)

**Comment by ahadas** [comment]
The Java version seems correct, @aobszyns what type of look and feel do you use (`Preferences -> Appearance -> Look & Feel`)?

**Comment by aobszyns** [comment]
![image](https://user-images.githubusercontent.com/31958328/147784065-358efe3e-6954-49c6-ab0c-b5f223f03fc7.png)

Mac OS X
Themes  / Native
system icons / For apps only
Sizes all 100%

**Comment by ahadas** [comment]
Thanks @aobszyns ,can you check [this version](https://github.com/mucommander/mucommander/releases/download/nightly/arik-1.0.dmg) that is bundled with Java 17?

**Comment by aobszyns** [comment]
App installation fails with message broken app.
Running natively .jar from its content works with the same focus issue :-(

**Comment by aobszyns** [comment]
After playing with xattr, mu as arik.app works just fine. No more focus issue.

**Comment by ahadas** [comment]
@aobszyns thanks for checking that. I think it's about time to upgrade the version of Java that is bundled for macOS, so I'll give a try to Java 17

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
