### ISSUE TITLE
Please add menu item "Show in Enclosing Folder"

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#543]
Please add item "Show in Enclosing Folder" to right-click menu (context menu) of file/folder in search results.

When the user selects this item, muCommander should open a new tab, and in that tab, show the folder containing the selected file/folder, and put the blue bar (selection mark) onto that file/folder.

Other file managers, e.g. ForkLift, have this feature too. It is missing in muCommander.

**Comment by Andreas0602** [comment]
Thank you very much for implementing this, @ahadas. I read your message on #542 saying you open the new tab in the inactive panel. That sounds a bit odd at first. The expected behavior would be that the tab will be opened in the same panel as the search results. At least that's what other file managers do. But after a little thought I figure that opening the tab in the inactive panel would also okay, or maybe even better, because then the search results remains visible.

I'd really like to try it out, but unfortunately the automatic release of the nightly build doesn't seem to have worked. At least it didn't happen at the usual time of the day.

**Comment by Andreas0602** [comment]
Another solution might be not to open a new tab, but to go directly to the selected file/folder in the existing tab with the search results. In fact, this is the most common approach in other file managers. But the downside is that there's no way back: If you want to see the search results again, you'll have to repeat the search. That's the reason why I suggested to open a new tab.

**Comment by ahadas** [comment]
@Andreas0602  yeah, the build failed earlier. I fixed it and published a [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly) with this change that you can check

**Comment by Andreas0602** [comment]
Thank you very much again,@ahadas! I've checked the latest nightly build. It works fine. From my point of view, file search is really in a good shape now.

Just one little thing: I'm not so happy that "case sensitive" is active by default. It means extra mouse clicks for me to deactivate it in most cases. Any chance to change the default of that option (for file name and search text) to not active? Anyway, it's not a big thing, and also it's a matter of taste for sure.

**Comment by ahadas** [comment]
> Just one little thing: I'm not so happy that "case sensitive" is active by default. It means extra mouse clicks for me to deactivate it in most cases. Any chance to change the default of that option (for file name and search text) to not active? Anyway, it's not a big thing, and also it's a matter of taste for sure.

Yeah, it was implemented this way because case sensitivity is set by default when comparing strings in Java but I agree that it makes sense to change it - done in #573

**Comment by Andreas0602** [comment]
Perfect! Thank you very much!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
