### ISSUE TITLE
v0.9.8-snapshot - File access problem in MuCommander directory

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#544]
Hello Ahadas

In the MuCommander directory:
PB-01: [Double-click] on a file (.text for example) generates an error.
PB-02: [Open with] opens the called program, but not the selected file. 

As you can see in the attachments, when I [Right Click - Open with - EditPad pro] on a file located in the MC directory tree, Editpad Pro opens but empty. A priori, there is a problem with spaces that are displayed with the "^" character.
The screen view shows the error after double-clicking the readme.txt file.

To make [Open with] work with the Diffinity program, I worked around (bypassed) this problem as you can see in my attached .bat script. In MC, START__Diffinity_LEFT-bat.TXT on one file then then START__Diffinity_RIGHT-bat.TXT on another file works correctly.

This problem is a special case, but ultimately computer science is a series of endless special cases... :)
Nico

[START__Diffinity_LEFT-bat.TXT](https://github.com/mucommander/mucommander/files/7798686/START__Diffinity_LEFT-bat.TXT)

![tilt_mc_directory_open_txt_file](https://user-images.githubusercontent.com/22394276/147868351-3ad489e2-07f7-47b7-9155-cc2caef54541.jpg)
[commands-xml.TXT](https://github.com/mucommander/mucommander/files/7798680/commands-xml.TXT)

**Comment by ahadas** [comment]
@nico92GitHub thanks for reporting this, can you please give the [latest nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly) a try?

**Comment by nico92GitHub** [comment]
It's okay, the 2 issues are solved with the [latest nightly build] :)
Thanks Ahadas.
I'm still testing. There are a few changes to be made to improve the ergonomics of our excellent muCommander. I will try to group these few proposals together...
Nico

**Comment by ahadas** [comment]
Thanks Nico

**Comment by nico92GitHub** [comment]
Thank you Arik, I'm happy to participate modestly in your project.

For now, here are 2 proposals that I think could improve MuCommander:

1/ In attachment:
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/149199682-059a407d-93f6-487c-a41f-6fbdebc3e262.jpg)
The arrow shows the button you have to press many times to get to the first tab (when there are several tabs, which is my case).
---> I propose a maintained click to get the same result, it would be simpler.

2/ I searched without success how to copy a file in the same directory to itself in order to quickly get a copy of the same file.
What Windows does by renaming the copied file to:
"file - Copy.txt", then "file - Copy (2).txt" for example.
---> A right click on a file could contain the choice "Duplicate file here".

What do you think?
Nico

**Comment by ahadas** [comment]
> 1/ In attachment: ![ScreenShot_001](https://user-images.githubusercontent.com/22394276/149199682-059a407d-93f6-487c-a41f-6fbdebc3e262.jpg) The arrow shows the button you have to press many times to get to the first tab (when there are several tabs, which is my case). ---> I propose a maintained click to get the same result, it would be simpler.

That's a widget of Java so it requires checking if/how it can be customized
Please file a different issue for this
 
> 2/ I searched without success how to copy a file in the same directory to itself in order to quickly get a copy of the same file. What Windows does by renaming the copied file to: "file - Copy.txt", then "file - Copy (2).txt" for example. ---> A right click on a file could contain the choice "Duplicate file here".

See #238

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)

**Comment by nico92GitHub** [comment]
Thank you for your messages.
In the new version 1.0.0-1, my remark 1/ does not work.
Unless I am mistaken, there is no change to my comment 2/. Copying a file to itself does not offer to automatically rename the file. As in version 0.9.7(8 snapshot)-1 you have to rename the file manually.
What information do you have about these 2 remarks?

**Comment by ahadas** [comment]
Hi @nico92GitHub , yeah - the fix I mentioned above that is included in v1.0.0 addresses the original problem you reported (generally, it's a good practice not to mix multiple problems within the same github issue).
I see that you filed a separate issue for the tabs navigation - good, thanks, it will be considered for a future release.
About duplicating a file, as I wrote above - we have #238 already, please check it out and comment there if needed
