### ISSUE TITLE
chdir to /var/root ( /private/var/root ) allowed?

### ISSUE THREAD

**Issue by devZer0** [mucommander/mucommander#55]
i`m running mucommander as ordinary user.

i can navigate to /var/root and mucommander shows an empty directory instead of telling "access denied" (what i would expect)

i`m curious if this is intenionally or if this is a bug. for me, this is a bug.

if i navigate to /var/root and then use "open in finder" icon, i`m getting a message that there is an error, but it doesn´t tell what error.   i also would expect "permission denied" here

**Comment by ahadas** [comment]
I agree, the current behavior seems confusing and should be treated as a bug.

**Comment by ahadas** [comment]
This fix solves it for local folders only for now.
Thanks for reporting this!
