### ISSUE TITLE
Export saved passwords for FTP connections

### ISSUE THREAD

**Issue by stepannemejc** [mucommander/mucommander#550]
It would be perfect if passwords could be exportable so I can import them to another machine with muCommander.

**Comment by ahadas** [comment]
@stepannemejc You can simply copy the configuration file `credentials.xml` to the second machine.  More information about the configuration files can be found [here](https://github.com/mucommander/mucommander/wiki/Preference-Files)
Feel free to reopen this issue if it doesn't work for you
