### ISSUE TITLE
under win10 pro - Click and hold on the [<][>] button of the tabs

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#554]
Hello dev

In attachment:
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/149292852-7a11f0a0-377c-42da-97ce-dcc7f7a748c7.jpg)
the arrow shows the button you have to press many times to get to the first tab (when there are several tabs, which is my 
case).
---> I propose a maintained click to get the same result, it would be simpler.

Regards,
Nico

**Comment by ahadas** [comment]
Duplicate of #621
