### ISSUE TITLE
under win10pro - (on file) Right Clic [ctr][c] = [alt][cap][c] = fullpath\file.ext

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#555]
Hello Dev

![ScreenShot_001](https://user-images.githubusercontent.com/22394276/149396376-d3f0be02-fe76-4498-9a72-f6cbf358ef08.jpg)

The attached screenshot shows you 2 choices in a right click on a file that do the same thing: Copies the "fullpath\file.ext" of the selected file to the clipboard.

Regards,
Nico

**Comment by ahadas** [comment]
Hi @nico92GitHub ,
The first copies the source file while the second copies its path
It depends on where you paste - if you paste them at, e.g., a terminal it will appear as they do the same thing because you get the file path in both cases
But the first option allows you to copy the source file to a different folder

**Comment by nico92GitHub** [comment]
I take your explanation, however, I think these 2 options do the same thing, as you will see in the attached video.
My ClipMagic software saves all the copies in the clipboard WITHOUT creating duplicates.
Tell me your analysis, please.
Nico

https://user-images.githubusercontent.com/22394276/149843352-5a6f99ca-66ad-4e0f-82ea-dacc5ad1aca0.mp4

**Comment by nico92GitHub** [comment]
Sorry, I'm coming back to change my point of view which was a bit heavy, it's true ;(
I think the wording of these options could be clearer, in particular:
"Copier chemin(s) Alt+Maj+C"
which could be:
"Copier chemin(s) **complet(s)** Alt+Maj+C".

Which seems to mean that this block is about "editing" paths and files but not about making real copies.

There is surely something I don't understand, but I regret that in a Right Click there is no option to PASTE.  Why?

Looking forward to your return,
Nico

**Comment by ahadas** [comment]
@nico92GitHub I don't think it's a matter of path vs. "complete path" but rather "file vs. path" so that part seems ok to me

about not having "paste" in the right click menu - that can be easily added

**Comment by ahadas** [comment]
> about not having "paste" in the right click menu - that can be easily added

added in #655
