### ISSUE TITLE
under win10pro - proposal for improvement display free space disk at the bottom right

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#556]
Hello dev

My machine has 2 hard drives. The top panel displays one disc, the other panel displays the other disc.
Whatever the selected disk, the free disk space display always show the disc C:
My proposal: At the bottom right, the free disk space displayed is that of the selected disk.
![ScreenShot_003](https://user-images.githubusercontent.com/22394276/149576338-d8db0762-f8a4-4f55-aab2-1432d37c7cbb.jpg)

Regards,
Nico

**Comment by ahadas** [comment]
Hi Nico,
It should work the way you describe - does the path in the status bar (below the file table) changes properly?  Can you record a video that demonstrate the issue?

**Comment by nico92GitHub** [comment]
Oops, sorry, I was in the moon ;( Because I tested my second disk which is a clone of the first one, so with about the same sizes.
You can close this issue, with apologies...

Regards,
Nico



Hi Nico,
It should work the way you describe - does the path in the status bar (below the file table) changes properly?  Can you record a video that demonstrate the issue?
