### ISSUE TITLE
File search unreliable

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#558]
On macOS Monterey, file search with muCommander 0.9.8 nightly build of 2022-01-16 is unreliable. To reproduce the issue, follow these steps:

1. Go to a directory containing one single file
2. Execute File > Find... (or press control+F) and then click the "Find" button in order to do a file search with the default settings
3. Press F9 repeatedly in order to refresh and thereby repeat the file search

**Expected result:** File search will always find the file.

**Actual result:** In most cases, File search will find the file, but sometimes (after pressing F9 ten or twenty times in a row), File search will not find the file.

**Comment by ahadas** [comment]
@Andreas0602 thanks for reporting this, can you please give the [updated nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly) a try?

**Comment by Andreas0602** [comment]
@ahadas I've tested the updated nightly build -- it has fixed the problem for me. Thank you very much!
