### ISSUE TITLE
Wrong rounding of small file sizes

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#559]
To reproduce the issue, activate the option "Round displayed file sizes" and create a small file in the current directory, for example by running the following command in the terminal (under macOS): echo -n 123 > test

**Expected result:** muCommander will show "3 B" in the SIZE column of the file.
**Actual result:** muCommander will show "1 KB" in the SIZE column of the file.

I've tested a few other file managers under macOS, including Finder, ForkLift, and Commander One, and all of them show "3 B", "3 bytes" or something similar. Note that those file managers also do rounding. For example, a file with 1450050021 bytes will be shown with a size of "1,45 GB" or "1.5 GB" or something similar. So, those other file managers do rounding properly, but muCommander does it wrong.

**Comment by ahadas** [comment]
This should be easy to fix but it seems it was set this way intentionally, need to dig into the log to see what was the reason for using ROUND_TO_KB [here](https://github.com/mucommander/mucommander/blob/1.0.0/mucommander-core/src/main/java/com/mucommander/ui/main/table/FileTableModel.java#L128) as it seems that [there was a regression which caused file size less than 1KB to be rounded to 1KB in the past](https://github.com/mucommander/mucommander/commit/55156ac65867b6a669d86879709a79f31b535ffe)
