### ISSUE TITLE
no file change notification

### ISSUE THREAD

**Issue by devZer0** [mucommander/mucommander#56]
when i write to a samba share mapped in mucommander from another system (or another user does), mucommander does not automatically refresh the directory contents when a file or directory is added or removed, like windows explorer or apple finder do.

apparently (like in apple finder) there is not even a button / hotkey for manually refreshing the directory contents (did i miss that?), so the only thing you can do is to  leave the directory and re-enter.

i like mucommander, but i think that`s really a missing feature for serious administrative use, as you cannot "lively" whatch to what´s happening in a directory

same goes for lokal file access, with a minor difference: if you select any file/folder in mucommander, the changed/added/remove files/dirs appear/disappear, so there is some easy way for manual refresh - but no automatic refresh, either

not sure if it`s a java limitation, but i think it`s some feature which can be expected from a flle manager in 2016

**Comment by ahadas** [comment]
@devZer0 actually there is a way to manually refresh the current folder. By default it is mapped to F9 and there is also a button for that in the command bar (the lowest bar).

Regarding automatic refresh, I agree it can be useful. Today we automatically refresh the presented folder when one switches to an open instance of muCommander. It can be extended with a background job that monitors changes in the currently presented folder.

**Comment by ahadas** [comment]
Closing, @devZer0 feel free to reopen if the issue still exists.
