### ISSUE TITLE
Add commandline option to specify config folder (instead of ~/.mucommander)

### ISSUE THREAD

**Issue by thevpc** [mucommander/mucommander#560]
Hi,
Thank you for your amazing app.  My concern is that we want to be using a commandline switch in your app to specify the config folder (changing ~/.mucommander elsewhere) by I'm failing to find how; something like `mucommander --settings=/my-other-config/folder`

By the way, I'm trying to make mucommander available out of the box using nuts package manager (a new open source package manager we are working on https://github.com/thevpc/nuts). The Idea is to use a simple command like `nuts install mucommander` and voilà!

**Comment by ahadas** [comment]
Hi @thevpc ,
I'll respond on #561 where you also mentioned the nuts package manager but generally speaking, sounds good. muCommander was recently added to winget-pkg (#528) and it's also in brew for macOS - package managers can significantly ease the deployment so the better they are, the better it is for application developers :)

As for the preferences folder, [it's already configurable](https://github.com/mucommander/mucommander/blob/master/src/main/java/com/mucommander/main/Configuration.java#L63-L65). You can set with the -p or --preferences arguments, e.g. : `mucommander --preferences /tmp/test`
