### ISSUE TITLE
muCommander issue with MacOS accessibility zoom option

### ISSUE THREAD

**Issue by rgerrits** [mucommander/mucommander#563]
How to reproduce:

Enable Accessibility -> Zoom -> Use keyboard shortcuts to zoom
Start the zoom by pressing alt+cmd+8

Now start using muCommander. 
Select some files and copy, move or delete them. (probably any action that gives a popup dialog) 
Once that action is done, muCommander doesn't properly respond to keyboard and mouse anymore.

cannot use keyboard to "change the selection" (move the blue bar up and down)
cannot use mouse to switch the focus to the other pane
can only use the mouse to move the blue bar in pane that already had focus before the copy/move/delete action

After switching to a different program on the Mac and then switching back to muCommander, then controls are back until the next copy/move/delete action.

If I disable zoom again (by again pressing alt+cmd+8) then this behaviour does not occur.

Version information:

muCommander
Version: 0.9.7-1
Build date: 2021/05/08
Build number: 1729466

Java
Runtime version: 1.8.0_265
VM name: OpenJDK 64-Bit Server VM
VM version: 25.265-b01
VM vendor: AdoptOpenJDK

OS
Name: Mac OS X
Version: 10.16 (actually muCommander is detecting this wrong, I'm running Monterey 12.1 (on Intel)
Architecture: x86_64

**Comment by ahadas** [comment]
Thanks for reporting this, sounds similar to #536 - maybe upgrading the Java version would solve this as well

**Comment by ahadas** [comment]
Yeah, I think the other issue reproduced with latest version of Java 8 but didn't occur with Java 14

**Comment by ahadas** [comment]
@rgerrits could you please give a try to [this nightly version](https://github.com/mucommander/mucommander/releases/download/nightly/muCommander-1.0.0.dmg) that runs with Java 17?

**Comment by rgerrits** [comment]
> @rgerrits could you please give a try to [this nightly version](https://github.com/mucommander/mucommander/releases/download/nightly/muCommander-1.0.0.dmg) that runs with Java 17?

After copying the app to /Applications, I initially couldn't start it. It gave error:
 “muCommander” is damaged and can’t be opened. You should eject the disk image.

I fixed this by running:
sudo xattr -cr /Applications/muCommander.app

But I can confirm that my original issue is solved with this nightly build.

**Comment by ahadas** [comment]
Thanks for the confirmation!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
