### ISSUE TITLE
Search without entering search text twice

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#566]
Currently, when you're searching for a keyword in a couple of files, you'll have to follow these steps:

1. Press ctrl-f
2. Enter the search text
3. In the list of search results, select a file and press F3
4. In muCommander's built-in text viewer, press F3
5. Enter the search text and press OK to jump to the first occurrence

In the above procedure, you have to enter the same search text twice: in step 2 and in step 5. It would be better if you would need to enter the search text only once: in step 2. When you press F3 in step 4, the viewer should directly jump to the first occurrence. So, you wouldn't have to perform step 5.

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
