### ISSUE TITLE
HiDPI Scaling Problems!

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#57]
It looks like HiDPI scaling is still not working properly:
 - the installer doesn't seem to detect it, to chose a Native LF (instead of Metal LF that does no scaling at all)
 - when using a Native LF, than some parts of the UI are scaled, others are not. E.g. 
    - Icons in Toolbar (but almost everywhere)
    - content of the Viewer, 
    - content of the Editor
    - default size of most dialogs

**Comment by mrserb** [comment]
HiDPI is unsupported by jdk8, did you try jdk9+? (for example jdk11 or jdk12)

**Comment by aadrian** [comment]
@mrserb as you can see, the issue is quite old. HiDPI works with JDK 8 too, since other products based on Java managed to solve it.

**Comment by mrserb** [comment]
On windows and linux it works for some other products like jetBrains Idea, because they use custom runtime of jdk8.
But in the pure jdk it works on jdk9+ as it was implemented in http://openjdk.java.net/jeps/263
BTW I think on macOS it was implemented earlier, probably in jdk7+

**Comment by ahadas** [comment]
Version 0.9.4 works with Java 9+ that should solve HiDPI issues.

**Comment by apws** [comment]
in ubuntu 20.04lts with fractional scaling to 125%, muCommander is tiny (temporarily solved by 24pt fonts, but dialogs are small)
