### ISSUE TITLE
Feature request: Modifier for executing rename - "consecutive rename"

### ISSUE THREAD

**Issue by illettante** [mucommander/mucommander#575]
Possibly a niche feature but:
Similar to the behaviour of Windows' File Explorer (yes, i know), in which once you're renaming a file, you can press Tab instead of Enter and it will execute the rename, move to the next consecutive file, and open that filename for editing.
Comes in handy for speeding up the processing of files with multiple naming issues that batch processing isn't appropriate for.

**Comment by ahadas** [comment]
@illettante I didn't know about that feature in Windows' file-explorer, thanks for the suggestion

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)

**Comment by illettante** [comment]
Awesome!
