### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Object

### ISSUE THREAD

**Issue by rgoubet** [mucommander/mucommander#577]
What is the status with this error? I know it has already been reported, but all related issues were closed while the issue is, as far as I can tell, not resolved (0.9.7 is still the latest release).

I'm running Ubuntu 21.10.

**Comment by ahadas** [comment]
Yeah, it was fixed in #465 but v0.9.8 wasn't released yet
In the meantime, muCommander won't work with a recent version of Java but should work fine with Java 11

**Comment by rgoubet** [comment]
OK. Strange that the issues are being closed even though the fix hasn't been released.
