### ISSUE TITLE
Online Documentation 404

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#58]
The "Help -> Online Documentation" menu item points to a **404** page: http://www.mucommander.com/documentation/ with version 0.9.1 .

Maybe it would be easier to host the help pages with GitHub Pages?

**Comment by ahadas** [comment]
@aadrian thanks for reporting this.
I added a redirection from http://www.mucommander.com/documentation/  to the wiki on github. This at least prevents the 404 page. Generating an informative wiki is something that would take some time though, any help with this would be appreciated :)

**Comment by aadrian** [comment]
> Generating an informative wiki is something that would take some time though

I can't find the (very) old docs mucommander html pages. Do you have a backup of them, to convert them to Markdown, in order to have a starting point?

**Comment by ahadas** [comment]
@m4xence do we have a backup of the pages that used to be on Trac?

**Comment by sdruskat** [comment]
You could try http://web.archive.org. Plenty of snapshots for the site...

**Comment by ahadas** [comment]
@sdruskat thanks a lot!
Seems that a snapshot of the previous wiki pages from 2014 is found at:
http://web.archive.org/web/20140707015438/http://trac.mucommander.com/wiki/TitleIndex
