### ISSUE TITLE
Search for part of filename by default

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#587]
In the file search dialog, it would be convenient if you could search for a part of the filename by default. For example, when you have a file named `beta.txt` and you type `eta` in the filename field of the search dialog, muCommander will find that file. At the moment, you'll have to type `*eta*` to find that file.

Other file managers, e.g. Total Commander, also behave like that.

**Comment by ahadas** [comment]
@Andreas0602 thanks for suggesting this. I wouldn't change the default to behave this way though - first, because I find it counter intuitive (that the search behaves as `grep` rather than `find`), and second, because it would make the comparison less efficient.
