### ISSUE TITLE
"Reveal in Finder" selects nothing in Finder

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#589]
Under macOS, when you select a file in muCommander and then execute `Reveal in Finder`, the directory containing the selected file will be opened in Finder (which is fine), but the file itself will not be selected in Finder. This is a bug. The file should be selected in Finder. At least that's how other file managers on macOS behave, for example ForkLift and Commander One, which also have a `Reveal in Finder` function.

I do have the following entry in commands.xml, as described in the [Wiki](https://github.com/mucommander/mucommander/wiki/Custom-Commands):

`<command alias="openFM" type="system" value="open -a Finder $f" display="Finder"/>`

**Comment by Andreas0602** [comment]
As I workaround, I've added to following entry to my commands.xml:

`<command alias="Finder" value="open -R $f"/>`

This works as desired. But anyway, it's just a workaround. The root cause of the problem needs to be fixed in muCommander.

**Comment by ahadas** [comment]
thanks for reporting this @Andreas0602 !

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
