### ISSUE TITLE
English language is not English, but system default

### ISSUE THREAD

**Issue by Forkest** [mucommander/mucommander#59]
Had to switch to British English to really use English.

OS: Windows XP
Version: 0.9.1

**Comment by ahadas** [comment]
@Forkest hi, can you please elaborate a bit?
What is the primary language of your system?
When you select British English and then switch to English, in what language does muCommander start with?

**Comment by Forkest** [comment]
Sorry, I already deleted it, muCommander turned out to be not feature-rich enough for me, I am looking for something on par with Total Commander. As far as I remember, after the switch to British English and back to English it became the system default (not English) again.

**Comment by ahadas** [comment]
@Forkest what is the system default?

And sorry to hear that you didn't find muCommander suitable for your needs. I really appreciate that you filed issues and being responsive although you don't use muCommander. What features in muCommander do you think are missing the most?

**Comment by Forkest** [comment]
Russian is the system language, although I thought it hardly matters.

As for the features, my personal faves are file comparison, directory comparison (not only selection, but by files date or content, including subdirectories, this is called "Synchronize directories" in TC) and the custom button toolbar where I can drop executables so they become shortcuts and I can drag-and-drop files onto them. And of course search (I was surprised not to find it), including search in the archives. Maybe I am missing something else, but these are off the top of my head. For example, is muCommander able to try to open an archive without the correct extension or browse contents of an exe file such as a self-extracting archive (Ctrl+PageDown in TC)?

**Comment by ahadas** [comment]
@Forkest thanks, I'll try to reproduce it.

Search functionality is surely one of top features that are still missing, I agree.
In the next release, muCommander will provide the ability to execute operations in the background. This, together with tabbed browsing and search functionality have been the most wanted features in muCommander for a long time. Hopefully, I'll be able to release the next version soon and search functionality will be the next big feature to tackle.
As for opening an archive without the correct extension or browse contents of an exe - no, these are missing. Another issue was opened for automatically detecting file formats, but until this will be available we can consider to add the ability for doing this manually (browse as..).
You're invited to follow us on twitter, we'll update on such changes there.

**Comment by Forkest** [comment]
I should also note that the OS is not English-based and localized via MUI, but is localized from the start. I don't know if this does matter something for user programs, but there are internal differences in these versions.

I was talking only about the manual opening as an archive, not expecting automatic detection. I'm not even sure if I would appreciate automatic detection, wouldn't it load the hdd too much?

Glad to see that the project is in development, I'll check back once in a while then.

**Comment by ahadas** [comment]
@Forkest I added a menu that allows one to open a file as an archive of type that is selected manually. Would you like to give it a try?

**Comment by mainzelM** [comment]
Looking at the title, I think this I've experienced the same problem, but as clear steps to reproduce are missing so far, I feel free to add them here:

1. I'm using Windows 7, my system language is German, so muCommander UI starts in German by default
2. In muCommander -> settings -> general -> set language to "English"
3. Restart muCommander
Error: muCommander UI is still German, not English

Workaround: set language to "British English"

**Comment by ahadas** [comment]
@Forkest , @mainzelM thanks!
The suggested workaround of selecting 'British English' is alright - there is only a slight difference between that translation and the non-British translation. A proper fix will be introduced in the next release.
