### ISSUE TITLE
Copying of file never finishes -- stuck at 100 %

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#592]
When copying a file to another directory, the copy operation never finishes. It's stuck at 100% with a transfer speed of 0b/s.

This never happened with previous versions of muCommander.

muCommander
Version: 1.0.0-snapshot
Build date: 2022/03/12
Build number: https://github.com/mucommander/mucommander/commit/7b52eff20563d88e2a8c91eb820cf592e50b7f20

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.2
Architecture: x86_64

<img width="410" alt="Bildschirmfoto 2022-03-13 um 21 15 18" src="https://user-images.githubusercontent.com/79788982/158077620-e26e636e-d024-4b0d-a45e-9574383ad5e0.png">

**Comment by ahadas** [comment]
@Andreas0602 thanks for reporting this! indeed it's a regression that happened due to the transition to Java 17. I updated the dmg that is attached to the [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly) to include the fix, could you please try it?

**Comment by Andreas0602** [comment]
I confirm that the problem is fixed. Thank you!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
