### ISSUE TITLE
Problems with browsing ISO files

### ISSUE THREAD

**Issue by Forkest** [mucommander/mucommander#60]
Some ISOs are shown as empty, some other list files almost normally except for the size of some large .bin files, which are shown as a question mark. They are also not viewable. Perhaps the library that responds for ISO browsing should be updated.

OS: Windows XP
Version: 0.9.1

**Comment by ahadas** [comment]
Thanks for reporting this.
We don't use a third-party library for browsing ISO archives. It could be that there is a bug in our code but I don't see the reported issues with the ISO files I have.
If there's a concrete example that it happens with, please reopen and share it with us.
