### ISSUE TITLE
First letter of search result not shown when searching from root directory

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#604]
On Mac, when you go to the root directory "/" and search for something, e.g. for the file "Finder.app", then muCommander will omit the first letter of the search result. For example, muCommander will show "ystem/library/CoreServices/Finder.app".

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
