### ISSUE TITLE
Can't open muCommander 1.0.0 on 10.13.6

### ISSUE THREAD

**Issue by elias137** [mucommander/mucommander#614]
Hi. I've downloaded dmg twice, but each time I run muCommander either from within the image itself or from /Applications it says that file is damaged and can't be opened. Mac OS High Sierra 10.13.6
![Screen Shot 2022-04-19 at 17 48 07](https://user-images.githubusercontent.com/5212070/164031745-2a01f5f5-68c6-431a-b22a-7e66d3ec65cb.png)

**Comment by mvveelen** [comment]
Same problem here. And I decided this time to NOT keep both versions. I regret this decision now.

**Comment by mvveelen** [comment]
Yes, that helped!

Using sudo xattr -cr /Applications/muCommander.app after the installation did the trick.

**Comment by ahadas** [comment]
> Yes, that helped!

Great to hear!
