### ISSUE TITLE
"“muCommander.app” is damaged and can’t be opened." on macos Catalina

### ISSUE THREAD

**Issue by C0br4** [mucommander/mucommander#615]
I just upgraded mucommander to the latest version (1.0.0-1) via brew and it won't launch with a generic error message. I removed it from my system completely and tried to install it via the provided dmg image from the mucommander website with the exact same result
![Screenshot 2022-04-20 at 11 38 29](https://user-images.githubusercontent.com/3701591/164200230-88e969f2-0c9b-4465-9799-b39f1a81de19.png)

**Comment by thawn** [comment]
I had the exact same issue. I was able to work around it by running the following command in a terminal:
```
sudo xattr -cr /Applications/muCommander.app
```

**Comment by thawn** [comment]
I think this issue should stay open until it is fixed by the developers. I am sure, we are not the only two mac users who run into it ;-). Most mac users probably won't find this issue here - even less will find it once it is closed.

**Comment by C0br4** [comment]
Considering how bad the finder is for basic jobs, there must be a lot of us ;)

**Comment by ahadas** [comment]
Note that there's a discussion on this already - #613 , I'll reply to the things that were mentioned here there
