### ISSUE TITLE
customize widget of Java

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#621]
Sorry, I just saw your comment "in" my initial message. I answer here...

ME: In attachment, The arrow shows the button you have to press many times to get to the first tab (when there are several tabs, which is my case). ---> I propose a maintained click to get the same result, it would be simpler.

YOU: That's a widget of Java so it requires checking if/how it can be customized
Please file a different issue for this.

Waiting for you, please.
![mucommander-1 0 0-1_customize_WidgetJava](https://user-images.githubusercontent.com/22394276/164758974-4c8abcc7-0c8b-4a92-9c88-3d7086b00a02.jpg)

**Comment by ahadas** [comment]
hi @nico92GitHub , I looked at this and saw that different L&Fs (looks and feels) behave differently when it comes to those widgets, and therefore I don't think we should try to modify this for a particular one. however, the next release will include few more L&Fs and some of them have better widgets for the header of the file tables that enable to pick a tab that is not visible more easily.
