### ISSUE TITLE
Mac OS 12.3 (Monterey) security prevents start of muCommander 1.0.0-1

### ISSUE THREAD

**Issue by WolfgangFranke** [mucommander/mucommander#622]
The Mac OS 12.3.1 (Monterey) App Security prevents start of muCommander 1.0.0-1
- Install into the Applications folder runs fine
- but when starting muCommander, MacOS says something like "App is damaged, can't be open, recommend move to trash"

MacOS Security setting:
- Allow Apps from App-Store and Verified Developers

![Bildschirmfoto 2022-04-22 um 20 21 55](https://user-images.githubusercontent.com/49641989/164772485-30c42b0c-7883-406d-9527-34f0e367ac6f.jpg)

![Bildschirmfoto 2022-04-22 um 20 22 48](https://user-images.githubusercontent.com/49641989/164772622-52b4b0c2-b1d5-4aa5-9414-5a9cfea4373c.jpg)

fyi: in Mac OS 10.15 (Catalina) with same Security settings, muCommander 1.0.0-1 starts as expected

**Comment by ahadas** [comment]
Thanks for reporting this, please see #613
