### ISSUE TITLE
[docs] macOS: muCommander damaged and cannot be opened

### ISSUE THREAD

**Issue by sfuerte** [mucommander/mucommander#625]
It would be nice to move documentation for the subject message from the known issues in a release `readme.txt` (https://raw.githubusercontent.com/mucommander/mucommander/1.0.0-1/package/readme.txt) to either the repo's `README` or Github release description so it's visible at once, or both. 

> macOS: "muCommander damaged and cannot be opened" may appear after downloading muCommander from the browser. This
  can be solved by executing: xattr -d com.apple.quarantine <jar_name>.jar

Also the command needs to be updated to:
```sh
sudo xattr -r -d com.apple.quarantine /Applications/muCommander.app
```

Because the whole package get quarantined:
```sh
$ xattr -lr /Applications/muCommander.app/
/Applications/muCommander.app//Contents/MacOS/muCommander: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/MacOS: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/app/app/mucommander-core-1.0.0.jar: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/app/app: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/app/bundle/jaxws-api-2.2.12.jar: com.apple.quarantine: ...
...
/Applications/muCommander.app//Contents/runtime/Contents/Info.plist: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/runtime/Contents: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/runtime: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/readme.txt: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/license.txt: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/Info.plist: com.apple.quarantine: ...
/Applications/muCommander.app//Contents/PkgInfo: com.apple.quarantine: ...
/Applications/muCommander.app//Contents: com.apple.quarantine: ...
/Applications/muCommander.app/: com.apple.quarantine: ...
```

OS: 
```sh
$ sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
```

**Comment by tomasMizera** [comment]
I have the same issue on macOS 11.5

**Comment by ahadas** [comment]
Documenting it as proposed makes sense
See #613 for the discussion about it

**Comment by freebrowser1** [comment]
Same issue here with macOS 12.3.1 on Mac M1.
But after doing `sudo xattr -r -d com.apple.quarantine /Applications/muCommander.app` it did work, but very slowly. 
The 'Activity Monitor' shows Intel, so it is not ported to ARM yet.

**Comment by ahadas** [comment]
> The 'Activity Monitor' shows Intel, so it is not ported to ARM yet.

Right, it's not packaged to ARM yet
