### ISSUE TITLE
Google drive - need to auth each time I start muCommander to use it

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#630]
Each time I start muCommander and want to access Google drive I need to give access to it via Google auth, this also produces email with notification etc. I saw in the code that the token is being written to muCommander/google/ - was it meant to be used to remember the access token between restartsof muCommander? 

Observed on muCommander version 1.0.0-1, macOS 10.15.7.

BTW, it would be nice to have a repository UI for such things - like, multiple google drives plus a possibility to choose which GDrive to use.

**Comment by pskowronek** [comment]
Oh yes, Bookmarking does the job.

"maybe it would be nice to suggest the user to create a bookmark when connecting as suggested there" - yes, also I was thinking about it, or even force displaying 'Bookmark form' after successful connection for the first time? This could be driven by Dialog box as whether one would like to bookmark it to hassle free access in the future?

**Comment by ahadas** [comment]
I would try to avoid showing another form/dialog - it's nice at the beginning, to be aware of this option (to create a bookmark) but let's say that you don't want to do that, then it may be annoying to have another form/dialog that you need to cancel every time. I'd prefer to integrate it within the connection dialog
