### ISSUE TITLE
An error prevented muCommander from starting.

### ISSUE THREAD

**Issue by craue** [mucommander/mucommander#632]
muCommander 1.0.0-1-portable
OS: Windows 10 x64
Java: Oracle OpenJDK 18.0.1 x64

I just became aware of this project and was eager to take a look, but after downloading, extracting, launching `mucommander.exe` I get (repeatedly, not only on first launch):

```
java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.SubstituteLogger is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @14c53f9d; ch.qos.logback.classic.Logger is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @47f6c52e)
 at com.mucommander.utils.MuLogging.configureLogging(MuLogging.java:144)
 at com.mucommander.Application.run(Application.java:289)
 at com.mucommander.Application.run(Application.java:495)
 at com.mucommander.Activator.start(Activator.java:102)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
 at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ahadas** [comment]
@craue thanks for reporting this, you encountered this with the portable version, right?

**Comment by craue** [comment]
Yes, @ahadas.

**Comment by ahadas** [comment]
OK, thanks. It seems that the `exe` file is not prepared for recent Java versions, need to see how it looks like on the [launch4j](https://sourceforge.net/projects/launch4j/) side. In the meantime, I'd suggest to use the [Windows installer](https://github.com/mucommander/mucommander/releases/download/1.0.0-1/muCommander-1.0.0-1.msi) instead

**Comment by craue** [comment]
True, using the installed version works.
It's packaged with a Java runtime version 17.0.2. Before running muCommander portable with Oracle OpenJDK 18.0.1 x64, I also tried with Oracle OpenJDK 17.0.2 x64 resulting in the same error message so it indeed seems to be a portable-specific issue.

**Comment by ahadas** [comment]
Thanks for the follow up @craue. I may just add a `bat` file that works with recent version of Java then

**Comment by ahadas** [comment]
The portable version has been updated with a fixed `exe`

**Comment by craue** [comment]
👍🏻 I confirm it's now working as expected. Thank you, @ahadas.

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
