### ISSUE TITLE
macOS: Starting from version 1.0.0 the command Open in Finder doesn't work anymore as expected

### ISSUE THREAD

**Issue by sebastian-lempert** [mucommander/mucommander#633]
When right-clicking on any file in a directory and selecting the **Open in Finder** command, muCommander opened a new Finder window up to version 0.9.7 and displayed the above directory in it. Unfortunately, since version 1.0.0 the above mentioned file is opened instead of a new Finder window. However, this should only be opened when the commands **Open** or **Open with** are selected.

**Comment by Andreas0602** [comment]
I was able to solve this issue by removing the line with "openFM" from my commands.xml file.

**Comment by sebastian-lempert** [comment]
@Andreas0602: Thanks a lot!

I just removed the following line from my **commands.xml** file located at **~/Library/Preferences/muCommander**:

`<command alias="openFM"  value="open -a Finder $f"  type="system" display="Finder"/>`

After restarting muCommander version 1.0.0 using the now modified commands.xml the old behavior was restored. However, the question remains why this change was necessary from version 1.0.0 and whether this is so intentional?

Following [1] the above line is among the default custom commands for macOS. Furthermore at [1] it says "If this command is not defined, the Reveal in Desk[t]op action will be disabled". Here the question remains, what is meant by the "Reveal in Desk[t]op action"?

Best, Sebastian

[1] https://github.com/mucommander/mucommander/wiki/Custom-Commands

**Comment by ahadas** [comment]
@sebastian-lempert thanks for reporting this!
The command has changed from `open -a Finder $f` to `open -R $f` in order to address #589 in v1.0.0
For some reason it didn't happen on my machine, but yeah - if you had the former command in commands.xml then there's a change in behavior since it is now invoked with the selected file rather than the folder that is currently presented.
I updated https://github.com/mucommander/mucommander/wiki/Custom-Commands with the new command.
We should probably convert the old command to the new one automatically when upgrading muCommander to prevent this

**Comment by sebastian-lempert** [comment]
@ahadas: Thanks for your fast reply and incredibly good work on this project!

Using

`<command alias="openFM"  value="open -R $f" type="system" display="Finder"/>`

instead of the old command in commands.xml is almost restoring the old behaviour. I like the fact that the selected file is now selected in the opening FInder windows as well.

But what is now missing is the following: If in muCommander no file is selected or if only the two dots ".." are selected, then now Finder window will be opened using Open in Finder that is executing the command mentioned above. Sometimes you don't care about selecting a file from within a folder, you just want to open that folder within Finder. Is there a way to support this too?

Best, Sebastian

**Comment by ahadas** [comment]
> @ahadas: Thanks for your fast reply and incredibly good work on this project!

Thanks!

> Using
> 
> `<command alias="openFM" value="open -R $f" type="system" display="Finder"/>`
> 
> instead of the old command in commands.xml is almost restoring the old behaviour. I like the fact that the selected file is now selected in the opening FInder windows as well.

Great :)

> But what is now missing is the following: If in muCommander no file is selected or if only the two dots ".." are selected, then now Finder window will be opened using Open in Finder that is executing the command mentioned above. Sometimes you don't care about selecting a file from within a folder, you just want to open that folder within Finder. Is there a way to support this too?

Yeah, actually this should be fixed in the next version by #631

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
