### ISSUE TITLE
“muCommander.app” is damaged and can’t be opened. You should move it to the Trash

### ISSUE THREAD

**Issue by stefek99** [mucommander/mucommander#64]
1. Download https://github.com/mucommander/mucommander/releases/download/0.9.1/mucommander-0.9.1-apple-java.dmg

2. Install Legacy ```javaforosx.dmg```

3. Authorise unidentified developers

Getting: **“muCommander.app” is damaged and can’t be opened. You should move it to the Trash**

System:

```MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)```

**Comment by ahadas** [comment]
@stefek99 did you disable gatekeeper?
Here are instructions for how to do this:
https://www.yourkit.com/download/mountain_lion.html

**Comment by ahadas** [comment]
Closing. Feel free to reopen if disabling the gatekeeper during the installation doesn't solve it.

**Comment by stefek99** [comment]
There is no such option.

What I've noticed: I have to run the app first, then the option appears to run that specific app.

_(and it doesn't help with muCommander)_

<img width="780" alt="screen shot 2016-12-26 at 17 12 25" src="https://cloud.githubusercontent.com/assets/249703/21484673/a63387ca-cb8e-11e6-9c6a-f8ee915d5675.png">

**Comment by alexey-lysiuk** [comment]
Download `.dmg` but before mounting it do
`xattr -d com.apple.quarantine mucommander-0.9.1.dmg`
in Terminal (adjusting a path to file accordingly of course).
Then mount, copy and run as usual.

Also it's better to avoid outdated and potentially insecure Apple's Java.
Install latest Oracle's JDK to run muCommander.

**Comment by stefek99** [comment]
> Also it's better to avoid outdated and potentially insecure Apple's Java.

I think - with the other version I couldn't even get that far...

**Comment by stefek99** [comment]
<img width="758" alt="screen shot 2016-12-31 at 14 55 09" src="https://cloud.githubusercontent.com/assets/249703/21578036/2e926ad6-cf69-11e6-857d-fbf8e4a538e1.png">

**Comment by ahadas** [comment]
@stefek99 what version of Java is currently being used on your machine?

**Comment by stefek99** [comment]
Cannot tell, returned computer to the Apple Store.

**Comment by stefek99** [comment]
```
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

**Comment by marisphg** [comment]
Hello,
Still have the problem of "muCommander is damaged and can't be opened..." message.
![screenshot 2017-07-17 15 48 24](https://user-images.githubusercontent.com/30178291/28268555-61098cc6-6b07-11e7-9ff9-7acfe1f4c82f.png)

I used without problems 0.85 version then I updated to 0.92 and it started. Can't use it anymore. Tried solutions that are given above, did not work.

Any suggestions?
See my specs in images.

<img width="624" alt="screenshot 2017-07-17 15 45 34" src="https://user-images.githubusercontent.com/30178291/28268448-fd203e62-6b06-11e7-9008-19fb2b59204d.png">
![screenshot 2017-07-17 15 44 03](https://user-images.githubusercontent.com/30178291/28268426-edd05334-6b06-11e7-9f36-d992edb617b8.png)
<img width="487" alt="screenshot 2017-07-17 15 44 41" src="https://user-images.githubusercontent.com/30178291/28268427-edd2eb9e-6b06-11e7-8f27-4d3b0acf084f.png">
<img width="433" alt="screenshot 2017-07-17 15 44 56" src="https://user-images.githubusercontent.com/30178291/28268428-edd392e2-6b06-11e7-9da1-c94b98f7337d.png">

**Comment by ahadas** [comment]
@marisphg , I believe the only solution for this, other than signing the application with Apple's Developer ID or publishing it on the App Store, is described [here](https://www.imore.com/how-open-apps-unidentified-developers-mac).

**Comment by stefek99** [comment]
Small internet, finding the same issue as the other day.

My main machine is being serviced, installing MuCommander on a new Mac.

`mucommander-0.9.1-apple-java.dmg`

Installed `javaforosx.dmg`

Same error as a year ago... I don't remember how I fixed it the last time, quite probably let it go...

Tried #81 workaround, also doesn't help.

**Comment by stefek99** [comment]
Installed latest Java SDK from Oracle website.

# Works for me

**Comment by superbonaci** [comment]
https://github.com/mucommander/mucommander/issues/850

**Comment by superbonaci** [comment]
New instructions here: https://github.com/mucommander/mucommander/issues/850
