### ISSUE TITLE
symlinks in zip archive

### ISSUE THREAD

**Issue by ulianitski** [mucommander/mucommander#660]
mucommander breaks symbolic links whilst extracting from a zip archive (MacOS Monterey, OpenJDK version 11.0.15)

**Comment by ahadas** [comment]
@ulianitski what does it mean `breaks symbolic links`?

**Comment by ulianitski** [comment]
a zip archive can store symbolic links; when the archive is extracted by mucommander the symbolic links are not re-created: they become ordinary text files.

**Comment by ahadas** [comment]
@ulianitski what's the version you tried this with? this seems similar to #76 that was handled in v1.0.0

**Comment by ahadas** [comment]
ah no, that one was for tar entries, the information about symlinks in zip entries seems to be missing, ok

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
