### ISSUE TITLE
Cannot delete folder from search result

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#669]
- Inside of an empty directory, create a sub-directory X
- Search for  filename *
- In the search results, select X and press F8
- Press Enter to confirm deletion

As a result, muCommander will infinitely remain in the delete dialog and will not delete X.

**Comment by ahadas** [comment]
Version 1.0.1 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
