### ISSUE TITLE
Freezed selected element in files list

### ISSUE THREAD

**Issue by zlobme** [mucommander/mucommander#672]
Floating bug, can't reproduce it. See it on almost all version of muCommander, Java and macos that I have had.

After some time of running app, navigation in files list is freeze with 2 cases:
* There is selected element (line with blues background), but pressing on up/down arrow has no effect because selected element change position according to arrow direction and then goes back to original position
* Same as previous case but selected element goes full way down to last element.

Feel free to ask additional info.

**Comment by ahadas** [comment]
This sounds like #643 but too general - please try to find a pattern that lead to that state or monitor the resource consumption (if everything is frozen, not just the file table) or provide log that covers the time it happens and what happened before. Until then we cannot do much as long as it doesn't reproduce elsewhere

**Comment by ahadas** [comment]
closing, if there's more information that can help us with this, please reopen
