### ISSUE TITLE
Apple Silicon M1 broken

### ISSUE THREAD

**Issue by vsigler** [mucommander/mucommander#673]
Hello, I found a closed ticket about Apple M1 support, but neither of the current releases for mac - 1.0.0 as well as 0.9.1 - seem to work.

With both I get system error saying that the application is corrupted and cannot be opened.

Is there anything special I need to do to get it to work? I did not try building from scratch yet as I'd rather use releases for "production" mode.

**Comment by uandco** [comment]
It's not just on M1 Macs, it also fails on Intel

<img width="372" alt="image" src="https://user-images.githubusercontent.com/26996169/174058555-2f4bffda-6be6-44bc-999e-77468a0a777b.png">

**Comment by vsigler** [comment]
The workaround works, thanks a million! I was used to the "unidentified developer" message, but I wonder why it downright crashes like this here.
