### ISSUE TITLE
Preference setting then [OK] impossible, frozen. win10pro x64

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#675]
rehello Arik

Following the problem with my all_progs directory, I wanted to reset all my settings.
With my portable version, in "C:\Program Files (x86)\muCommander", I deleted the ".mucommander" directory, then quit and restarted MUC.
Then I did my general settings, then in the preferences, clicked [Apply], then [OK].
Then the window did not close. The [OK] and [Apply] buttons were ghosted, only [Cancel] was possible.
After clicking [Cancel], I went back into the preferences and my settings were saved.
Here is a little anomaly and a screen view...
![tilt_muc_après_paramétrage_ok_est_figé](https://user-images.githubusercontent.com/22394276/174974715-35d14ef5-ff8b-455c-9f8a-dfb0a94f6bac.jpg)

**Comment by ahadas** [comment]
@nico92GitHub hi, that's expected - the 'apply' and 'ok' buttons are enabled only when there's a change in the dialog that was not "committed" yet (before pressing 'apply' or 'ok')
