### ISSUE TITLE
win10 x64 - Insufficient memory resources at the end of a DOS batch

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#678]
Hello Dev

I double clicked on my .bat script, which on Windows exits with no system error, stating that this batch was not started via shell right click.
But within MUC...:
The message below says "There are insufficient memory resources to process this command.":
![tilt_muc_start_bat](https://user-images.githubusercontent.com/22394276/175874681-141c64e0-3f5a-48e7-bf5a-ad6616e28702.jpg)
One of the few positive components on my machine is the memory:
![tilt_muc_start_bat--02](https://user-images.githubusercontent.com/22394276/175875690-d1726416-69a0-47a0-be69-bad8f5fe2945.jpg)

Note that my .bat script ends with EXIT /B and therefore closes its window when it ends. But you can see that this is not the case in the view above.
Looking forward to your return,
Nico

**Comment by pskowronek** [comment]
Is it still an issue?

**Comment by nico92GitHub** [comment]
Sorry, no, that's all right.
