### ISSUE TITLE
Can't install V1.0.0

### ISSUE THREAD

**Issue by SurfingFinger** [mucommander/mucommander#679]
I love this app - thank you!

I just tried to update to the V1.0.0. It looks like it's getting installed, but then when I try to open the application, I get a message saying that it's damaged and I should trash it. Tried a couple of times/a couple of downloads with no luck. Reinstalling my previously-downloaded Version: 0.9.7-1 works for using the older version.

I'm on a 2020 M1 Mac, running Monterey (Version 12.4).

**Comment by ahadas** [comment]
@SurfingFinger this has been resolved in [1.0.1 that was released today](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1)
