### ISSUE TITLE
press and hold = scroll through all tabs

### ISSUE THREAD

**Issue by nico92GitHub** [mucommander/mucommander#684]
Hello
In the tab bar, it's quite stressful to have to click x times there are tabs to shift the tabs left or right.
So I propose a sustained press on these buttons which will have the same result without stressing the user :)
![ScreenShot_001](https://user-images.githubusercontent.com/22394276/176989373-11ef9596-ab0e-47dc-a655-26ed188033db.jpg)

**Comment by ahadas** [comment]
@nico92GitHub this part is not controlled by muCommander but by the look and feel you use.
you can check the FlatLaf looks and feels that were added in v1.0.1 and have the proposed functionality

**Comment by nico92GitHub** [comment]
Thank you, but... how to adjust this feature in "FlatLaf looks and feels" that I don't know and don't know where to look where it is?

**Comment by ahadas** [comment]
ok, in the 'Preferences' dialog go to the 'Appearance' tab and you'll see 'Look & Feel' at the top

**Comment by nico92GitHub** [comment]
Sorry to come back, but it looks like it changes the look. But I would like to have this functionality WITH the Current appearance.
![TILT_MUC_feels_n_look](https://user-images.githubusercontent.com/22394276/178149006-03ac411b-47d3-4a3a-af67-48c9fbef4266.jpg)

As I understand it, this is not possible???

**Comment by nico92GitHub** [comment]
Or my request could be:
Is it possible to add the functionality of a sustained click in the METAL look & feem with the NATIVE theme?

**Comment by nico92GitHub** [comment]
(feel, of course)

**Comment by ahadas** [comment]
It will then need to be filed to openjdk but the likelihood of that to be fixed is not so high

**Comment by nico92GitHub** [comment]
Thanks. So more likely that this feature will not be retained ;-( While it seems to me as user-friendly as it is basic.
Java is Java, isn't it?

**Comment by ahadas** [comment]
> Thanks. So more likely that this feature will not be retained ;-( While it seems to me as user-friendly as it is basic.

well, that's debatable - I mean, looking at common browsers, they just squeeze the tabs as much as possible to show all of them without a scroll bar but that doesn't fit for us
there is an alternative method you can try - the 'open tabs' quick list. you invoke it from the 'Go' menu -> 'Quick lists' -> 'Open tabs' (its shortcut defaults to ALT+6) and it shows you the tabs you have in the selected folder pane. then you can start typing the name of the tab and it would filter out items that don't match what you type

> Java is Java, isn't it?

There are many advantages to Java but there are also some downsides in its swing-based UI, definitely

**Comment by nico92GitHub** [comment]
Of course, there are other ways to achieve the result I want. But I still hope that this functionality (which exists in other programs of the same kind) will be implemented :) "L'espoir fait vivre" Hope makes people live, they say in France...
