### ISSUE TITLE
Copying of file never finishes -- stuck at 100 %

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#685]
On macOS, the problem #592 is back in muCommander 1.0.1-1 (the official Release version). Since copying of files is one of the most fundamental functions of a file manager, this problem makes muCommander 1.0.1-1 more or less useless, at least on macOS.

**Comment by Andreas0602** [comment]
The same problem occurs when copying to an external USB flash drive.

**Comment by Andreas0602** [comment]
Even copying from one local directory into another local directory does not work.

So, it looks like this problem is not only similar to #592, but it's identical.

**Comment by ahadas** [comment]
@Andreas0602 thanks for reporting this, it is indeed similar to #592 but different, this time it is related to the signing of the dmg. I managed to reproduce this. I can provide a way to workaround that but let's see if I can come up with a proper solution first

**Comment by WolfgangFranke** [comment]
@ahadas, thanks for your answers ^^ .
Additionally, **Move** (Verschieben) behaves incorrect too:
- "File Move" within same Volume work as expected,
- "File Move" between different Volumes never finishes (stuck at 100%) , and after hitting "Stop" and "reloading the target directory", the target file is there, but also the source file is still there. So yep, looks like the hang is with "Copy".

The issue with **Copy** I confirm under Mac OS 12.4 and 10.15.7 
for copy on same volume and between different volumes.

**Comment by ahadas** [comment]
@Andreas0602 @WolfgangFranke can you please give [this version](https://github.com/mucommander/mucommander/releases/download/1.0.1-1/muCommander-1.0.1-test.dmg) a try?

**Comment by rhstanton** [comment]
I was about to report the same bug when I saw this thread. The new version seems to copy fine.

**Comment by ahadas** [comment]
@rhstanton thanks for the confirmation, in that case I think it would be better to release a new build for 1.0.1 where all the inner components are signed as in that version but this would require an additional change so the new version won't falsely report that there's a new version available

**Comment by WolfgangFranke** [comment]
@ahadas yes, this version executes "Copy" and "Move"  as expected, tested Mac OS 12.4 and 10.15.7

**Comment by Andreas0602** [comment]
@ahadas, I too can confirm that the version you posted above solves the problem.

After installing the new version, I got the following message when starting the program:

<img width="297" alt="Bildschirmfoto 2022-07-06 um 18 55 35" src="https://user-images.githubusercontent.com/79788982/177605029-9a2126b9-acad-433f-b655-2acca667a316.png">

Translation: muCommander is damaged and cannot be opened. It is recommended to move the object into trash.

Running the following command fixed the problem: `sudo xattr -cr /Applications/muCommander.app`

So, in my opinion, this version should **not** be released. Instead, a version should be released which fixes the copy/move problem without re-introducing the old problem of "damaged" app.

Another point: When starting the app, the following message pops up:

<img width="320" alt="Bildschirmfoto 2022-07-06 um 18 57 31" src="https://user-images.githubusercontent.com/79788982/177605880-846fa004-3e47-4951-af5d-ae2bc6439fab.png">

Translation: A new version of muCommander is available.

That's a bit strange. I would have expected the test version to be the newest available version.

**Comment by ahadas** [comment]
uploaded a new dmg to [v1.0.1](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1), please check it out

**Comment by Andreas0602** [comment]
Just a minor issue: The macOS version shown in "About muCommander" is wrong.

<img width="653" alt="Bildschirmfoto 2022-07-06 um 22 02 57" src="https://user-images.githubusercontent.com/79788982/177634079-6c29edd0-fa8d-43a4-918f-e64fe48f3f3c.png">

**Comment by ahadas** [comment]
> Just a minor issue: The macOS version shown in "About muCommander" is wrong.
> 
> <img alt="Bildschirmfoto 2022-07-06 um 22 02 57" width="653" src="https://user-images.githubusercontent.com/79788982/177634079-6c29edd0-fa8d-43a4-918f-e64fe48f3f3c.png">

yeah, that's what Java detects - maybe it will be fixed by upgrading Java but that's too much of an effort for that

**Comment by WolfgangFranke** [comment]
@ahadas I just realized the following action still is affected:
- the Drag&Drop "Move" from e.g. Desktop into MC still get stuck at 100%.
fyi: Drag&Drop "Copy" works fine.

**Comment by ahadas** [comment]
@WolfgangFranke it's unrelated to this issue, please file another one

**Comment by ahadas** [comment]
> @WolfgangFranke it's unrelated to this issue, please file another one

For me:
```
Exception in thread "com.mucommander.job.impl.MoveJob" java.lang.NullPointerException: Cannot invoke "com.mucommander.commons.file.AbstractFile.getURL()" because "this.baseSourceFolder" is null
	at com.mucommander.job.impl.FileJob.getBaseSourceFolder(FileJob.java:679)
	at com.mucommander.job.impl.MoveJob.jobCompleted(MoveJob.java:288)
	at com.mucommander.job.impl.FileJob.run(FileJob.java:733)
	at java.base/java.lang.Thread.run(Unknown Source)
```
