### ISSUE TITLE
Drag&Drop "Move" never finishes -- stuck at 100 %

### ISSUE THREAD

**Issue by WolfgangFranke** [mucommander/mucommander#688]
The Drag&Drop "Move" from e.g. Desktop into the muCommander window get stuck at 100%.
fyi: Drag&Drop "Copy" works fine.
Found on:  Mac OS 12.4 and 10.15.7

Exception in thread: https://github.com/mucommander/mucommander/issues/685#issuecomment-1177075760

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
