### ISSUE TITLE
renaming of files/folders partially broken with muCommander-1.0.1-1 on MacOS

### ISSUE THREAD

**Issue by rgerrits** [mucommander/mucommander#695]
to reproduce, select a file or folder, so that it is blue.
then shift + F6 (or slow double click), so that it is white.

Then normally, you could use the keyboard or mouse to place the cursor at the correct place to make modifications. I.e. only insert or delete a few characters. 
But with version 1.0.1-1, using keyboard or mouse to place the cursor, actually exits the renaming, so the entry gets blue again.
The only option to rename is to actually start typing and thus replacing the entire old name.

I also checked version 1.0.0-1 -> here everything still works fine.

Version with the issue:
muCommander
Version: 1.0.1
Build date: 2022/07/06
Build number: f49e48b

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.4
Architecture: x86_64

**Comment by ahadas** [comment]
Sounds like #680, @rgerrits can you please take a look at [the video here](https://github.com/mucommander/mucommander/issues/680#issuecomment-1170382497) and upload a similar one that demonstrates the issue?

**Comment by rgerrits** [comment]
https://user-images.githubusercontent.com/1229091/180611710-02656fa2-5760-416e-ae1f-1fc4d5ced32b.mov


https://user-images.githubusercontent.com/1229091/180611715-651935d7-bf46-4246-8ff4-7efed6ebba7f.mov

**Comment by rgerrits** [comment]
now that I relook the video of the bad situation, it seems the issue is indeed that the color of the field during renaming is the same as the color of the entire line and I didn't see that small black cursor -> my conclusion was that it had exitted the renaming

**Comment by rgerrits** [comment]
So if I look a little better, then yes I can still rename files with 1.0.1. But I rather prefer the way that 1.0.0 was working.
https://user-images.githubusercontent.com/1229091/180612005-9bf1ecb6-65ac-4ccc-883f-a66925aeec3e.mov

**Comment by ahadas** [comment]
@rgerrits @Andreas0602  thanks for the feedback on this, your comments made me realize that with the changes that were introduced in v1.0.1 this can be confusing when there is no text selected so I changed the rendering to improve that. I suspect @Andreas0602  won't find it ideal because it's not the same as what other file managers do (and as I wrote before, we don't have to align with what other tools do) but I think it would be better

**Comment by ahadas** [comment]
The fix is included in the [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly), it would be great if you can check it out before the next version is released

**Comment by Andreas0602** [comment]
Thank you, @ahadas, the new behavior is clearly better than the old one, in my opinion. It's more logical.

By the way, in the Theme editor, under Folder pane --> Inactive, I've made the color of the background and the border a bit lighter. See screenshot below. I think that does improve things even a bit more, not only when renaming, but also in general, because you can easily see whether the program window is active or inactive.

<img width="477" alt="Bildschirmfoto 2022-07-31 um 10 23 03" src="https://user-images.githubusercontent.com/79788982/182017874-e523382a-0a4f-4054-8ac2-4e821eab5155.png">

By the way, with today's nightly build, the bug with the never ending copy operation is back. That makes today's nightly build unusable for me. It would be good if you could release the next version soon where this bug is fixed.

**Comment by rgerrits** [comment]
I don’t see any macOS version of the nightly, so cannot test.
(And going on vacation tomorrow)

**Comment by ahadas** [comment]
> I don’t see any macOS version of the nightly, so cannot test. (And going on vacation tomorrow)

yes, the nightly build is not packaged as DMG but it has a `sh` script that you can use to run the app on macOS

**Comment by rgerrits** [comment]
Quickly tried that, but it throws this error:

java.lang.IllegalAccessError: superclass access check failed: class com.mucommander.ui.macos.TabbedPaneUICustomizer$CompactAquaTabbedPaneUI (in unnamed module @0x576875c9) cannot access class com.apple.laf.AquaTabbedPaneUI (in module java.desktop) because module java.desktop does not export com.apple.laf to unnamed module @0x576875c9
 at java.base/java.lang.ClassLoader.defineClass1(Native Method)
 at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
 at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2332)
 at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClassParallel(BundleWiringImpl.java:2150)
 at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2084)
 at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)
 at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
 at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
 at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
 at com.mucommander.desktop.macos.OSXDesktopAdapter.getTabbedPaneCustomizer(OSXDesktopAdapter.java:133)
 at com.mucommander.core.desktop.DesktopManager.init(DesktopManager.java:220)
 at com.mucommander.Application.run(Application.java:327)
 at com.mucommander.Application.run(Application.java:495)
 at com.mucommander.Activator.start(Activator.java:102)
 at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
 at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
 at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
 at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
 at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
 at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ahadas** [comment]
@rgerrits oh, I see - the recent changes broke the portable version on macOS then, thanks for checking

**Comment by ahadas** [comment]
> Thank you, @ahadas, the new behavior is clearly better than the old one, in my opinion. It's more logical.

thanks for the confirmation!
 
> By the way, in the Theme editor, under Folder pane --> Inactive, I've made the color of the background and the border a bit lighter. See screenshot below. I think that does improve things even a bit more, not only when renaming, but also in general, because you can easily see whether the program window is active or inactive.

cool, I don't was to change the native theme but if you make a custom theme that would be useful for others as well, please share and I'll add it
 
> By the way, with today's nightly build, the bug with the never ending copy operation is back. That makes today's nightly build unusable for me. It would be good if you could release the next version soon where this bug is fixed. Or, if you don't want to make a release soon, at least provide a dmg file on the nightly build page which contains all the latest changes, including the fix of this severe bug.

yeah, the nightly build is not signed and as I see that running using the script doesn't work, I guess you copied the jars to the app, right? if so, it makes sense that issue that was solved by signing the app would reappear

**Comment by Andreas0602** [comment]
Yes, I copied the jars to the app directory and manually updated muCommander.cfg. It was quite a lot of work. Therefore, I'd prefer ready-to-use dmg files being provided on the nightly build page.

**Comment by ahadas** [comment]
> Yes, I copied the jars to the app directory and manually updated muCommander.cfg. It was quite a lot of work. Therefore, I'd prefer ready-to-use dmg files being provided on the nightly build page.

it shouldn't be too complex to fix the portable version, I just wasn't aware of this issue.. building a nightly dmg is much more complex

**Comment by ahadas** [comment]
@Andreas0602 can you please check the latest nightly?

**Comment by Andreas0602** [comment]
@ahadas, I checked the latest nightly, and it has the same problem as the previous nightly: After copying the jars to the app directory and manually updating muCommander.cfg, the problem with the never ending copy operation occurred.

**Comment by ahadas** [comment]
Right, but that's expected. The question is whether you're able to start the app with the `mucommander.sh` script

**Comment by Andreas0602** [comment]
> Right, but that's expected. The question is whether you're able to start the app with the `mucommander.sh` script

The answer is no.

>% ./mucommander.sh
>The operation couldn’t be completed. Unable to locate a Java Runtime.
>Please visit http://www.java.com for information on installing Java.

I also tried to set the JAVA environmant variable to the path of the java binary that comes with muCommander, but that didn't work either:

>% export JAVA_HOME=/Applications/muCommander.app/Contents/runtime/Contents/Home
>% ./mucommander.sh
>Fehler: Hauptklasse com.mucommander.main.muCommander konnte nicht gefunden oder geladen werden
>Ursache: java.lang.ClassNotFoundException: com.mucommander.main.muCommander

After that, I gave up.

**Comment by Andreas0602** [comment]
Okay, I tried another thing: Simply unpacking the zip file from the nightly build page into a temporary directory, set JAVA_HOME as described above, and then run mucommander.sh from the temporary directory. That did work! Only one small issue: The icon shown in the dock is the java duke logo, not the muCommander icon.

**Comment by ahadas** [comment]
> Okay, I tried another thing: Simply unpacking the zip file from the nightly build page into a temporary directory, set JAVA_HOME as described above, and then run mucommander.sh from the temporary directory. That did work! However, the icon shown in the dock is the Java Duke logo, not the muCommander icon. And when you hover the mouse pointer over it, it will show "java" instead of "muCommander" as the program name.

Ok, good! It was possible to copy the jars from the portable version when the dmg was unsigned but now that it's signed, the portable version should be used this way. As for the icon and seeing 'java' instead of 'mucommander' - that's also expected to happen with the portable version. I found couple of issues in the process of fixing the portable version though, I'll need to take a deeper look at those..

**Comment by Andreas0602** [comment]
@ahadas, I have created an Automator program to execute mucommander.sh from the nightly build, and I've put that Automator program into the dock. As a result, when I click on that Automator program in the dock, it will launch muCommander as another program having the Java Duke icon and the name "java". So, you will have two icons in the dock: the Automator program and "java". And when you want to switch from another program to muCommander, you'll have to click on the Java Duke icon in the dock.

This is not a good solution, but unfortunately I didn't find a better one. I guess no Mac owner will be willing to use muCommander that way. So, at the moment, the nightly build of muCommander is practically not usable in daily life for Mac owners (except for experimental purposes).

It would be good if you could provide a convenient solution for Mac owners to use the nightly build of muCommander.

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
