### ISSUE TITLE
Is this the new issue tracking for mucommander?

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#7]
Is this (github) now the new issue tracking for mucommander? the other old one seems down.

thanks.

**Comment by ahadas** [comment]
no, the new issue tracker is: http://mucommander.atlassian.net/

**Comment by aadrian** [comment]
OK, thanks.

I asked this because the official site still points to a Trac error page:
  http://trac.mucommander.com/query

Since the "forums" from the official page are also down, is there maybe an alternative one in use (just like JIRA) ?
