### ISSUE TITLE
Last release doesn't work on MacOS

### ISSUE THREAD

**Issue by s8fabord** [mucommander/mucommander#702]
I just installed the last release and it won't open, because "muCommander can't be opened because Apple isn't allowed to search for malware in it"...

Have no more muCommander as I replaced the old one...

<img width="293" alt="Bildschirmfoto 2022-07-28 um 14 15 34" src="https://user-images.githubusercontent.com/96500012/181502956-368a1472-c84f-40bd-a6c3-9b867af6d47b.png">

**Comment by ahadas** [comment]
@s8fabord I don't remember a report on this before and I can't reproduce it on my machine - what's the macOS version you use? did you enable some setting that is not set by default on macOS?

**Comment by ahadas** [comment]
Without more information on how to reproduce, there's not much we can do
