### ISSUE TITLE
mac os copy files from external sources

### ISSUE THREAD

**Issue by czosnkowy666** [mucommander/mucommander#709]
After upgrade to version 1.0.1 I have issue with coping files from external sources like sd card or external hard drive. It start and stales and says it will take forever. First file is actually copied but somehow mucommnader is not able to detect this and move to next file or close copy dialog

**Comment by gentisle** [comment]
Yes, I am also unable to copy. MacOS 10.15.7 with a 2022-06 update, MacBook Pro from late 2020/early 2021. I tried to uninstall and go back to an earlier version, but those would not run. Copy speed is listed as 1kb. Doesn't matter whether I copy/move to a USB stick or another directory on HDD. Thanks.

***
muCommander
Version: 1.0.1-1
Build date: 2022/06/29
Build number: 23a87f5

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 10.15.7
Architecture: x86_64
***

**Comment by kles4enko** [comment]
Having MacOS Monterey, same issue. Downgraded to `1.0.0-1`
The issue with network resource too. I have SMB/AFP resource on my local NAS. I can't copy something on it using mucommander `1.0.1-1`.

**Comment by ahadas** [comment]
seems like #711, please try the updated dmg in [v1.0.1](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1) (build f49e48b). I wonder how did you still get the previous build - how did you install muCommaner?

**Comment by kles4enko** [comment]
@ahadas updated dmg is working properly. I've got notification about new release (I've subscribed). Downloaded the dmg file from github release page :)

**Comment by ahadas** [comment]
thanks for the confirmation @kles4enko !

**Comment by czosnkowy666** [comment]
great job :) it is working now, thanks
