### ISSUE TITLE
muCommander does not start on Debian

### ISSUE THREAD

**Issue by demetriuzz** [mucommander/mucommander#710]
Good day!

`muCommander` does not start.
The error log is attached:
[muCommander_hs_err_pid1891.log](https://github.com/mucommander/mucommander/files/9247892/muCommander_hs_err_pid1891.log)
[muCommander_hs_err_pid1941.log](https://github.com/mucommander/mucommander/files/9247893/muCommander_hs_err_pid1941.log)

**System**:
Linux Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux

**JRE**:
On system installed:
```
$ java --version 
openjdk 17.0.4 2022-07-19
OpenJDK Runtime Environment (build 17.0.4+8-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.4+8-Debian-1deb11u1, mixed mode, sharing)
```
but `muCommander` used embedded:
`JRE version: Java(TM) SE Runtime Environment (17.0.2+8) (build 17.0.2+8-LTS-86)`

**Assumption**:
It _started_ after the update Linux Debian `SECURITY`.
I can't say for sure, but I think after that: `[DSA 5196-1] libpgjava security update`

**Comment by demetriuzz** [comment]
The situation is _strange_.
It starts the first time, then only the third time.
_Unstable_.

**Comment by ahadas** [comment]
@demetriuzz thanks for reporting this, as it will take me some time to look at that, I'd recommend to use the portable version in the meanwhile

**Comment by ahadas** [comment]
@demetriuzz I played with Debian Linux 11.5 while working on #771 and didn't notice this issue - does it still happen to you?

**Comment by demetriuzz** [comment]
Good day!
Every update is a bit of a _surprise_.
For the current version `muCommander 1.1.0`, this is not happening yet.
Let's see _what_ happens next.
Until the next Debian update :)

**Comment by ahadas** [comment]
ack, so closing this for now and let's reopen if it happens again
