### ISSUE TITLE
Copying files hangs AFTer the first file has finished

### ISSUE THREAD

**Issue by andrastokes-redk** [mucommander/mucommander#711]
Hi all,
I've started experiencing an odd issue with muC after installing it on a new m1 chip mac with Monterey 12.4 on it.
Whenever I try copying any files the 'Copying files' status window just stays on the screen without ever proceeding to the next file or closing. It's a very odd behaviour and totally defeats the purpose of having this neat app.
Can someone please advise how to resolve this?
Thanks,
Andras

**Comment by andrastokes-redk** [comment]
Hi Arik,

Here’s my version information:

muCommander
Version: 1.0.1-1
Build date: 2022/06/29
Build number: 23a87f5

Java
Runtime version: 17.0.1
VM name: OpenJDK 64-Bit Server VM
VM version: 17.0.1+12
VM vendor: Eclipse Adoptium

OS
Name: Mac OS X
Version: 11.5
Architecture: x86_64

Locale
Language: en
Country: GB
Encoding: UTF-8

I have also attached the log to this email.

--
Kind regards,
András Tőkés
Solution Architect

From: Arik Hadas ***@***.***>
Date: Wednesday, 3 August 2022 at 17:55
To: mucommander/mucommander ***@***.***>
Cc: András Tőkés ***@***.***>, Mention ***@***.***>
Subject: Re: [mucommander/mucommander] Copying files hangs AFTer the first file has finished (Issue #711)
WARNING The e-mail below is from an external source. Please exercise caution before opening attachments or clicking links

@andrastokes-redk<https://github.com/andrastokes-redk> what version do you use? can you share the log within ~/Library/Preferences/muCommander/logs?

**Comment by ahadas** [comment]
Ack, thanks, please try the updated dmg in [v1.0.1](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1) (build f49e48b)

**Comment by andrastokes-redk** [comment]
Hi Arik,
Cheers, this one is working properly.

Andras



From: Arik Hadas ***@***.***>
Date: Thursday, 4 August 2022 at 16:47
To: mucommander/mucommander ***@***.***>
Cc: András Tőkés ***@***.***>, Mention ***@***.***>
Subject: Re: [mucommander/mucommander] Copying files hangs AFTer the first file has finished (Issue #711)
WARNING The e-mail below is from an external source. Please exercise caution before opening attachments or clicking links

Ack, thanks, please try the updated dmg in v1.0.1<https://github.com/mucommander/mucommander/releases/tag/1.0.1-1> (build f49e48b)

**Comment by kles4enko** [comment]
> Ack, thanks, please try the updated dmg in [v1.0.1](https://github.com/mucommander/mucommander/releases/tag/1.0.1-1) (build f49e48b)

@ahadas updated build works good, thank you!
