### ISSUE TITLE
[Bug] Versions discrepancy between About and .exe 

### ISSUE THREAD

**Issue by Ygarr** [mucommander/mucommander#719]
Such discrepancy

![minibug2022-08-16_17-53](https://user-images.githubusercontent.com/14309871/184911328-7efb3ae9-7598-484e-8b77-691146be993e.png)
![minibug2022-08-16_17-54](https://user-images.githubusercontent.com/14309871/184911334-7b436a9c-5933-4ce8-b483-aa2d8d87055a.png)

**Comment by pskowronek** [comment]
@ahadas any thoughts?

**Comment by hajdam** [comment]
I believe exe is created via launch4j, so maybe it's just missing versionInfo properties in gradle launch4j section. https://launch4j.sourceforge.net/docs.html

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
