### ISSUE TITLE
Can not start muCommander after upgrade to 0.9.1

### ISSUE THREAD

**Issue by onaydenov** [mucommander/mucommander#72]
MacOS 10.12.2
After software replacement OS says "files are broken". Tried to install previous version again - same result, it is not working any more.

**Comment by ahadas** [comment]
@onaydenov did you disable 'gatekeeper'?

**Comment by onaydenov** [comment]
I have no option to start programs from "any" developer. Just 2 lines - from Appstore or form Approved Developers. Please advise how to manage the issue.

**Comment by onaydenov** [comment]
Ok, found this: sudo spctl --master-disable
It works and now muCommander works.
Thanks for your prompt help.

**Comment by ahadas** [comment]
Glad that it works for you now and thanks for specifying your resolution.

**Comment by stefek99** [comment]
```sudo spctl --master-disable``` 

Clever http://osxdaily.com/2015/05/04/disable-gatekeeper-command-line-mac-osx/

Solves #64
