### ISSUE TITLE
Keep directory timestamp when moving between different mountpoints

### ISSUE THREAD

**Issue by mfilser** [mucommander/mucommander#720]
Hello,
i have an issue when moving a directory to another directory which is in another mountpoint. The timestamp is the current one and not the original one. When i move files, the timestamp keeps the same. This is what "i" expect for directories too.

Here's a short bash script to create directories and 1 file:
```bash
#!/bin/bash

_dir="2020-08-15_080000"
test -d "$_dir"  &&  rm -r "$_dir"
mkdir -p "$_dir/test"
touch --date="2020-08-15 08:00:00" "$_dir/test/test3"
touch --date="2020-08-15 08:00:00" "$_dir/test"
touch --date="2020-08-15 08:00:00" "$_dir"
```

I tested it at the latest commit hash 6b85a0f1e. I opened muCommander, created the directories by the script above in `/tmp` and then moved it to `/data` which is on a different mountpoint (partition).

Is there a way to keep directory timestamp while using the "Move" option ? At the "Copy" option, the timestamps are kept.

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
