### ISSUE TITLE
Get rid of message "The default interactive shell is now zsh..." when starting terminal

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#728]
On macOS, when your default shell is zsh and you start the terminal, the message "The default interactive shell is now zsh..." appears. This should not happen. Apple's Terminal.app does not do this either.

The reason for this problem is probably here: https://github.com/mucommander/mucommander/blob/master/mucommander-core/src/main/java/com/mucommander/ui/action/impl/TerminalWindow.java#L74

<img width="893" alt="Bildschirmfoto 2022-09-12 um 08 27 03" src="https://user-images.githubusercontent.com/79788982/189587302-391fcef9-e7b2-41e1-84ab-f9a332b538a9.png">

**Comment by pskowronek** [comment]
The fix is to get a default shell for a current user under macOS (only), idea taken from: https://stackoverflow.com/a/41553295/1715521

For other OSes it uses a hardcoded shells (cmd, /bin/bash).

**Comment by Andreas0602** [comment]
Okay, from a formal point of view, this change addresses my original request to get rid of the message. But it doesn't really solve the underlying problem, it just hides it. The real solution should be to start the user's default login shell. On my Mac, both `dscl . -read ~/ UserShell` and `echo $SHELL` return the correct result, which is `UserShell: /bin/zsh` or `/bin/zsh` respectively in my case. @ahadas wrote [here](https://github.com/mucommander/mucommander/pull/733#issuecomment-1250040955) that `dscl . -read ~/ UserShell` doesn't work for him, so what about reading `$SHELL`?

**Comment by ahadas** [comment]
@Andreas0602 I believe that using `dscl . -read ~/ UserShell` is the right way to go, it returned /bin/bash because that's the terminal that is configured on my machine. the idea behind #733 is good, just need to align it with the other configuration for the terminal, and maybe also make use of Unix4j to get the output from this command to save a few lines. feel free to chime in the thread there
