### ISSUE TITLE
Get rid of sound for 'invalid key pressed' when closing terminal

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#729]
On macOS, when you have configured F10 to toggle the terminal and the terminal is open and you press F10, the terminal will be closed (that's fine) and you will hear a short sound as if you'd pressed an invalid key. That's not okay -- there should be no such sound.

Also, when you open the terminal again, there will be the text "1~" in the command line. That's not okay either.

<img width="828" alt="Bildschirmfoto 2022-09-12 um 08 36 10" src="https://user-images.githubusercontent.com/79788982/189588738-1ce4969d-2089-4a7d-986b-42b0b6cbe68a.png">

**Comment by ahadas** [comment]
@pskowronek hi, could you look at this? also happened to me but it's not always reproducible

**Comment by pskowronek** [comment]
The PR contains:
- fix for this issue
  - the custom key listener didn't mark the key event as `consumed`
  - however, JediTerm doesn't check if the event was consumed (I've created a bug and PR for it: https://github.com/JetBrains/jediterm/issues/251), and in the meantime, I've committed a workaround to muC to fix that
- some code clean up
- found that Cmd-O/Ctrl-O is also used to 'open in other tab' action - changed that default key configuration to Cmd-Alt-Shift-O/Ctrl-Alt-Shift-O so Terminal could be opened with well known/used combination Cmd-O/Ctrl-O.

@ahadas, BTW, I'm having problems importing muC to Idea - strangely, the library produced by `jetbrains-jediterm` subsystem is not recognized for core subsystem :/

**Comment by ahadas** [comment]
@pskowronek thanks! all but the changing the default key shortcut for 'open in other tab' looks good to me - commented on the PR
about Idea - I have no idea :) I don't use IntelliJ, maybe it uses some generated configuration from the gradle one that needs to be refreshed? things like apache-bzip2 and sevenzipjbindings are recognized well?
