### ISSUE TITLE
sftp is not working with the newest version

### ISSUE THREAD

**Issue by harpo2017** [mucommander/mucommander#73]
used to work with version 0.90 and was able to use sftp to my server.
with the newest vesion (same settings as 0.90) doesnt work anymore.

Is there a way to fix this??

Thanks in advance
Ben Harpo

**Comment by ahadas** [comment]
Hi Ben,
In 0.9.1 the library j2ssh was replaced with jsch.
It works well with my servers, better than the previous one.
Can't you login to your server?
Can you please attach a log with the failure?

**Comment by harpo2017** [comment]
Hi ahadas,
I get the following message

![grafik](https://cloud.githubusercontent.com/assets/25395222/22440638/a73294e2-e734-11e6-9936-4c58699bafd5.png)

and the Debugger says
--------------------------------------------------------------------
	•	[2017-01-30 21:30:15.994] INFO ConnectionPool.java#getConnectionHandler,108 adding new ConnectionHandler com.mucommander.commons.file.impl.sftp.SFTPConnectionHandler@5b6800e0, realm = sftp://xxx.xxx.xxx.xxx:51222/ 
	•	[2017-01-30 21:30:15.994] INFO ConnectionPool.java#getConnectionHandler,115 starting monitor thread 
	•	[2017-01-30 21:30:15.994] INFO ConnectionHandler.java#checkConnection,109 not connected, starting connection, this=com.mucommander.commons.file.impl.sftp.SFTPConnectionHandler@5b6800e0 
	•	[2017-01-30 21:30:15.994] INFO SFTPConnectionHandler.java#startConnection,62 starting connection to sftp://xxx.xxx.xxx.xxx:51222/ 
	•	[2017-01-30 21:30:15.994] FINEST SFTPConnectionHandler.java#startConnection,73 creating SshClient 
	•	[2017-01-30 21:30:16.264] INFO SFTPConnectionHandler.java#startConnection,110 Caught exception while authenticating 
	•	[2017-01-30 21:30:16.264] INFO FileFactory.java#getFile,396 Caught an exception 
	•	[2017-01-30 21:30:16.264] FINE LocationChanger.java#run,851 Caught exception 
	•	[2017-01-30 21:30:16.267] FINEST CredentialsManager.java#findMatches,384 returning matches=[] 
	•	[2017-01-30 21:30:16.267] FINEST CredentialsManager.java#findMatches,384 returning matches=[root sftp://xxx.xxx.xxx.xxx:51222/] 
	•	[2017-01-30 21:30:16.328] FINEST FocusDialog.java#windowActivated,229 requesting focus on initial focus component 
	•	[2017-01-30 21:30:16.328] FINEST FocusDialog.java#windowActivated,237 requestFocusInWindow failed, calling requestFocus 
	•	[2017-01-30 21:30:16.394] FINE FocusRequester.java#run,103 focus requested on javax.swing.JTextField 
	•	[2017-01-30 21:30:16.877] FINEST RecordReaper.java#run,53 RecordReaper(MYSERVER.local.).run() JmDNS reaping cache 
	•	[2017-01-30 21:30:16.995] INFO ConnectionPool.java#run,174 Removing unconnected ConnectionHandler com.mucommander.commons.file.impl.sftp.SFTPConnectionHandler@5b6800e0 
	•	[2017-01-30 21:30:16.995] INFO ConnectionPool.java#run,217 No more ConnectionHandler, stopping monitor thread 
--------------------------------------------------------------------

Do you see why i cant login to myserver!
Thanks in advanceBen Harpo

**Comment by ahadas** [comment]
Unfortunately, the log doesn't specify the reason of the failure.
Could you please try with a development build?
You can either build it from source or download the jar file from [here](https://github.com/mucommander/mucommander/releases/download/0.9.2/mucommander-0.9.2-nightly-20170204.jar) and execute it from the command line:
'''
java -cp mucommander-0.9.2-nightly-20170204.jar com.mucommander.muCommander
'''
Then, you'll find a log message like:
INFO SFTPConnectionHandler.java#startConnection,110 Caught exception while authenticating: <reason. e.g., timeout: socket is not established>

**Comment by harpo2017** [comment]
Hi ahadas,
I downloaded the file and tried to execute (just coppied and pasted).
However it wont start. It throws. 
"Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mucommander/muCommander"

Dont know how to fix that

Thanks
harpo

**Comment by ahadas** [comment]
@harpo2017  what version of Java do you have?

**Comment by harpo2017** [comment]
Version 8 Update 121 (Build 1.8.0_121-b13)
and maybe another important information. I am using OSX 10.12.3

**Comment by ahadas** [comment]
@harpo2017 that's weird, it should work properly with Java 8. are you sure that's what is used when invoking 'java' from the command line? (the output of 'java -version')

**Comment by harpo2017** [comment]
Hi ahadas,
 checked and found an second installation of Java.
Now thats the output of mucommander
----------------- snipp --------- 

[2017-02-07 21:19:58.788] INFO ConnectionPool.java#run,174 Removing unconnected ConnectionHandler com.mucommander.commons.file.protocol.sftp.SFTPConnectionHandler@e350b40
[2017-02-07 21:19:58.788] INFO ConnectionPool.java#run,217 No more ConnectionHandler, stopping monitor thread
[2017-02-07 21:20:02.514] FINEST RecordReaper.java#run,53 RecordReaper(MY-COMPUTER-NAME.).run() JmDNS reaping cache
[2017-02-07 21:20:03.915] FINE StatusBar.java#updateVolumeInfo,316 Cache hit!
[2017-02-07 21:20:09.917] FINE StatusBar.java#updateVolumeInfo,316 Cache hit!
[2017-02-07 21:20:11.743] INFO DefaultSchemeParser.java#parse,297 Warning: path should not be empty, url=sftp://MY-SERVER-IP/etc
[2017-02-07 21:20:11.743] FINE LocationChanger.java#tryChangeCurrentFolder,274 folderURL=sftp://MY-SERVER-IP/etc
[2017-02-07 21:20:11.747] FINE LocationChanger.java#run,626 starting folder change...
[2017-02-07 21:20:11.754] FINEST CredentialsManager.java#findMatches,384 returning matches=[]
[2017-02-07 21:20:11.754] FINEST CredentialsManager.java#findMatches,384 returning matches=[root sftp://MY-SERVER-IP/]
[2017-02-07 21:20:11.754] FINEST CredentialsManager.java#getBestMatchIndex,454 returning bestMatchIndex=0
[2017-02-07 21:20:11.846] FINEST FocusDialog.java#windowActivated,229 requesting focus on initial focus component
[2017-02-07 21:20:11.847] FINEST FocusDialog.java#windowActivated,237 requestFocusInWindow failed, calling requestFocus
[2017-02-07 21:20:11.921] FINE FocusRequester.java#run,103 focus requested on javax.swing.JTextField
[2017-02-07 21:20:12.515] FINEST RecordReaper.java#run,53 RecordReaper(MY-COMPUTER-NAME.).run() JmDNS reaping cache
[2017-02-07 21:20:13.368] INFO ConnectionPool.java#getConnectionHandler,108 adding new ConnectionHandler com.mucommander.commons.file.protocol.sftp.SFTPConnectionHandler@3f1b7914, realm = sftp://MY-SERVER-IP/
[2017-02-07 21:20:13.368] INFO ConnectionPool.java#getConnectionHandler,115 starting monitor thread
[2017-02-07 21:20:13.368] INFO ConnectionHandler.java#checkConnection,109 not connected, starting connection, this=com.mucommander.commons.file.protocol.sftp.SFTPConnectionHandler@3f1b7914
[2017-02-07 21:20:13.368] INFO SFTPConnectionHandler.java#startConnection,62 starting connection to sftp://MY-SERVER-IP/
[2017-02-07 21:20:13.368] FINEST SFTPConnectionHandler.java#startConnection,73 creating SshClient
[2017-02-07 21:20:14.406] INFO SFTPConnectionHandler.java#startConnection,110 Caught exception while authenticating: Auth fail
[2017-02-07 21:20:14.407] FINE SFTPConnectionHandler.java#startConnection,111 Exception:
[2017-02-07 21:20:14.407] INFO FileFactory.java#getFile,400 Caught an exception
[2017-02-07 21:20:14.407] FINE LocationChanger.java#run,868 Caught exception
[2017-02-07 21:20:14.430] FINEST CredentialsManager.java#findMatches,384 returning matches=[]
[2017-02-07 21:20:14.430] FINEST CredentialsManager.java#findMatches,384 returning matches=[root sftp://MY-SERVER-IP/]
[2017-02-07 21:20:14.547] FINEST FocusDialog.java#windowActivated,229 requesting focus on initial focus component
[2017-02-07 21:20:14.548] FINEST FocusDialog.java#windowActivated,237 requestFocusInWindow failed, calling requestFocus
[2017-02-07 21:20:14.607] FINE FocusRequester.java#run,103 focus requested on javax.swing.JTextField
[2017-02-07 21:20:15.374] INFO ConnectionPool.java#run,174 Removing unconnected ConnectionHandler com.mucommander.commons.file.protocol.sftp.SFTPConnectionHandler@3f1b7914
[2017-02-07 21:20:15.374] INFO ConnectionPool.java#run,217 No more ConnectionHandler, stopping monitor thread
[2017-02-07 21:20:22.517] FINEST RecordReaper.java#run,53 RecordReaper(MY-COMPUTER-NAME.).run() JmDNS reaping cache

------------- snipp --------

and its still not authenticating

thanks in advance 

harpo

**Comment by ahadas** [comment]
ok, can you please share your /etc/ssh/sshd_config file?

**Comment by harpo2017** [comment]
Here it comes ;-)
--------------------------------------------
Host *
        SendEnv LANG LC_*

# Host *
#   ForwardAgent no
#   ForwardX11 no
#   RhostsRSAAuthentication no
#   RSAAuthentication yes
#   PasswordAuthentication yes
#   HostbasedAuthentication no
#   GSSAPIAuthentication no
#   GSSAPIDelegateCredentials no
#   BatchMode no
#   CheckHostIP yes
#   AddressFamily any
#   ConnectTimeout 0
#   StrictHostKeyChecking ask
#   IdentityFile ~/.ssh/identity
#   IdentityFile ~/.ssh/id_rsa
#   IdentityFile ~/.ssh/id_dsa
#   IdentityFile ~/.ssh/id_ecdsa
#   IdentityFile ~/.ssh/id_ed25519
#   Port 22
#   Protocol 2
#   Cipher 3des
#   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc
#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160
#   EscapeChar ~
#   Tunnel no
#   TunnelDevice any:any
#   PermitLocalCommand no
#   VisualHostKey no
#   ProxyCommand ssh -q -W %h:%p gateway.example.com
#   RekeyLimit 1G 1h

# XAuthLocation added by XQuartz (http://www.xquartz.org)
Host *
    XAuthLocation /opt/X11/bin/xauth
-----------------------------------------------

**Comment by ahadas** [comment]
Thanks, and just to make sure - that's the file on the server you're connecting to, right? what operating system is installed there?

**Comment by harpo2017** [comment]
`#	$OpenBSD: sshd_config,v 1.98 2016/02/17 05:29:04 djm Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

# The default requires explicit activation of protocol 1
#Protocol 2

# HostKey for protocol version 1
#HostKey /etc/ssh/ssh_host_key
# HostKeys for protocol version 2
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_dsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key

# Lifetime and size of ephemeral version 1 server key
#KeyRegenerationInterval 1h
#ServerKeyBits 1024

# Ciphers and keying
#RekeyLimit default none

# Logging
# obsoletes QuietMode and FascistLogging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#RSAAuthentication yes
#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts
#RhostsRSAAuthentication no
# similar for protocol version 2
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# RhostsRSAAuthentication and HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to no to disable s/key passwords
#ChallengeResponseAuthentication yes

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#KerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#X11Forwarding no
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#UsePrivilegeSeparation sandbox
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# pass locale information
AcceptEnv LANG LC_*

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	/usr/libexec/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	X11Forwarding no
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

# XAuthLocation added by XQuartz (http://xquartz.macosforge.org)
XAuthLocation /opt/X11/bin/xauth`

**Comment by harpo2017** [comment]
no actually this is the sshd file on my local computer.
 just now I dont have the right credentials to see the sshd.config file on the server

**Comment by ahadas** [comment]
I suspect that the password authentication is disabled on the server that you're connecting to and that is the reason for jsch's authentication failure. that's why I wanted to examine the ssh-config on the server. let me try to reproduce it with my server then.

**Comment by ahadas** [comment]
@harpo2017 did you use to provide the private key in the 'connect to server' dialog?

**Comment by harpo2017** [comment]
Hi ahadas,
to your post:
>I suspect that the password authentication is disabled on the server that you're connecting to and >that is the reason for jsch's authentication failure. that's why I wanted to examine the ssh-config >on the server. let me try to reproduce it with my server then.
If that would be true then I shoudnt be able to authenticate with the previous version of mucommander

**Comment by harpo2017** [comment]
regarding your post
>did you use to provide the private key in the 'connect to server' dialog?

No I did not. Is it necessary to provide one and again why dit id work with the previous version

**Comment by ahadas** [comment]
Hi Ben,
You said it works fine with version 0.9.0. Could you please connect to your host using that version and share what kind of authentication is used? You'll find a log in the form:
"Using <method> authentication method"
I suspect that the answer would be either "publickey" or "keyboard-interactive".
Thanks for your responsiveness!

**Comment by ahadas** [comment]
Seems that SLES 11 comes with ```PasswordAuthentication no``` by default and thus when no private key is provided, keyboard-interactive authentication is used. However, when j2ssh was replaced with jsch, the keyboard-interactive authentication was not implemented.

@harpo2017 , you can either change this setting of PasswordAuthentication to 'yes' (in /etc/ssh/sshd_config) if you like to use the 0.9.1 version or switch to a development build of 0.9.2 that will be available, hopefully, soon. Please feel free to reopen this issue if needed.
