### ISSUE TITLE
ftp connetion problem with Java

### ISSUE THREAD

**Issue by patty4m** [mucommander/mucommander#730]
HI,
 I am not able to connect to ftp servers, new innstallation 1.0.1 wil least JAva : OpenJDK17U-jdk_x64_mac_hotspot_17.0.4.1_1.
Mac OS 10.15.7

Older installation of MCU on another computer with same MAC OX connect to server correctly.
here is a log 

Anny idea?

Network firewal for MCU is Allowed.

![Snímek obrazovky 2022-09-12 v 9 38 22](https://user-images.githubusercontent.com/74317343/189602059-58734913-8132-4d82-8fcd-9f5f77cd34a9.png)

**Comment by pskowronek** [comment]
Problem with ipv6? Can you try to disable ipv6 in your network preferences? Unless you use ipv6 intentionally.

**Comment by patty4m** [comment]
I try disabled ip v6, same result. It looks like Java problem.... froma same place, second computer with aslo MAC Catalina can acces to ftp server. but older version of mucommander.

**Comment by pskowronek** [comment]
Can you try to set env variable as described here: https://superuser.com/a/453329

You may want to relogin or restart your macbook to make sure this env is really set.

**Comment by pskowronek** [comment]
Any feedback?

**Comment by patty4m** [comment]
HI, Piotr,

finally I was reinstall OSX to Monterey, 
I was install last update of mucommander an it works now.
I do not know exactly, what happened in preview installation.
Thank you for patience.
Best.
Patrik


On 25 Dec 2022, at 23:35, Piotr Skowronek ***@***.***> wrote:


Any feedback?

**Comment by pskowronek** [comment]
Thanks
