### ISSUE TITLE
Encrypted/secure https download for jnlp web start, to improve security and avoid Java warnings

### ISSUE THREAD

**Issue by n-a-b-s-t-e-r** [mucommander/mucommander#74]
Hi,

muCommander via web start is useful on computers which do not allow native installation of software.

Java recommends that web start software is downloaded from https and not http links.

This makes sense, since files obtained over http could be manipulated during transmission, thereby making end users vulnerable to malicious code alterations.

I'd therefore like to request a https site for muCommander.

Thanks for writing this userful software!

**Comment by pskowronek** [comment]
If it is still an issue please re-open.

**Comment by n-a-b-s-t-e-r** [comment]
Thank you!

*From: *Piotr Skowronek ***@***.***>
*To: *mucommander/mucommander ***@***.***>
*CC: *n-a-b-s-t-e-r ***@***.***>; Author ***@***.***>
*Date: *9 Jun 2023 23:22:11
*Subject: *Re: [mucommander/mucommander] Encrypted/secure https download for jnlp web start, to improve security and avoid Java warnings (#74)
