### ISSUE TITLE
MUCommander 1.01 Copy Overwrite if older Not Skipping Existing Older Files

### ISSUE THREAD

**Issue by MattKHK** [mucommander/mucommander#740]
When copying files from one folder to another and setting "Overwrite if older" MU copies all files even if the target destination files are of the same date as the source files.  I believe it should skip all files of same name that are same age or newer and only overwrite older files.  Actually it overwrites each and every file regardless of age of the files in the target folder.

**Comment by pskowronek** [comment]
Please provide:
- version of muC and the OS and its version
- exact steps to reproduce 

On mac I cannot reproduce this (version 1.0.1-1).

**Comment by MattKHK** [comment]
Hi,

I'm on MU version 1.0.1 and MacOS 12.6

When I copy a directory from one drive to another drive with the same
directory name which contains some files with the same date/time, MU
Commander now ignores the instruction to overwrite a file ONLY if it is
older.  In the previous versions going back to 0.99 MU would skip files of
the same date/time and only copy newer files.

Attached to this email are screenshots to clarify what I am saying.

[image: Mu Commander Copy Directory to Directory on Another Drive.jpg]

[image: MU Commander Overwrite if older.png]

[image: MU Commander overwriting files of same date:time.jpg]

This is not a huge problem, but I find it strange that previous versions
obeyed the instruction to overwrite only if the target file is older than
the source file, but the latest version ignores the instruction and
proceeds to copy over every file from the source to the target regardless
of the date/time of the two files.

I hope that this clarifies what I am having difficulty with.

In any case, I have been a happy user of MU Commander for many years and
want to thank you all for developing this app.

Matt

**Comment by Andreas0602** [comment]
Just guessing, since different drives are involved, maybe the different granularity of time stamps plays a role here. For example, if I remember correctly, the resolution of time stamps in a FAT file system is two seconds.

By the way, the screenshots are not visible on the GitHub web page.

**Comment by MattKHK** [comment]
Andreas,

You may have a point there.  One of the drives is APFS and the other is
NTFS.  MU Commander once handled this without problem but no longer.

Anyway, don't worry about it.  I can live with this!  Thanks for your help
and sorry that the screenshots were not able to be seen.

Matt
