### ISSUE TITLE
status line free space does not update

### ISSUE THREAD

**Issue by JamesOlvertone** [mucommander/mucommander#743]
mucommander Version: 1.0.1-1 (portable version)
OS: Linux
Java: 17.04 open-jdk

Initial situation:
left panel drive x, right panel drive y. x and y are real different drives.

active panel is left, status bar shows free space of drive x. no switch to right panel with tab-key and move around in the directory of drive y, status bar does not update to free space of drive y, it still shows free space of drive x. sometimes it changes to drive y after a while.

Suggestion: Status bar should show for left and right panel free space all the time. Updates after completed copy/move tasks.

**Comment by ahadas** [comment]
@JamesOlvertone it sounds like the type of the file system of drive y is not recognized, and thus its free space is not retrieved when the active panel changes but only "sometimes" (that is after a minute that the panel that shows drive y is active). can you please confirm that the file system type is not included in [this list of 'known' file system types](https://github.com/mucommander/mucommander/blob/1.1.0/mucommander-commons-file/src/main/java/com/mucommander/commons/file/protocol/local/LocalFile.java#L159-L162)? (my guess is that it's either ext4 or btrfs)

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
