### ISSUE TITLE
German umlauts not shown correctly in new terminal

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#750]
German umlauts are not shown correctly in the new terminal. Steps to reproduce:

1. In muCommander, Press F7 to create a new directory, and enter `Löwe` as the name of the new directory.
2. Press F12 to switch to the new terminal.
3. In the terminal, enter the command `ls`.

Expected result: `Löwe`
Actual result: `L??we`

By the way, in Apples Terminal.app, the correct name `Löwe` is shown.

**Comment by ahadas** [comment]
@pskowronek can you please take a look at this? could be related to https://github.com/JetBrains/jediterm/issues/140

**Comment by pskowronek** [comment]
@Andreas0602 what's the operating system? macOS?

What's the value of env variable `LC_ALL` (and other LC_*) for your user in the system? (`env | grep LC_`)

I've got `export LC_ALL=en_US.UTF-8` set in `~/.profile` and diacritcs work no problem including umlauts in 'Löwe'.

**Comment by Andreas0602** [comment]
My OS is macOS. My default shell is zsh. But when I press F12, I get bash.

`env | grep LC_` returns nothing.

I have no file `~/.profile`. Anyway, for testing purposes, I just created that file and wrote the line `export LC_ALL=en_US.UTF-8` into it. That solved the problem.

In my opinion, a solution is needed for users not having the file `~/.profile`, and that solution should also work when zsh is used.

**Comment by pskowronek** [comment]
What about `LANG`?

For macOS Terminal app, what do you have over there: https://apple.stackexchange.com/a/21107 ?

**Comment by Andreas0602** [comment]
`env | grep LANG` returns nothing.

<img width="731" alt="Bildschirmfoto 2022-09-25 um 13 31 52" src="https://user-images.githubusercontent.com/79788982/192141312-e4ab5876-c477-4eee-8cef-5ae3ec142168.png">

**Comment by pskowronek** [comment]
Can you copy and run the first code sample from: https://www.geeksforgeeks.org/locale-getdefault-method-in-java/
and paste the result? You may want to modify the code to print also these values: https://stackoverflow.com/a/25865153/1715521

I'm wondering how precisely java env knows the correct lang and encoding in your system when no LC_*/LANG is set.

**Comment by Andreas0602** [comment]
The code from the first web page prints the following output: `de_DE`

For the values from the second web page, please provide complete code how to print them.

**Comment by pskowronek** [comment]
Add these lines at the end of `main` method from above sample.
```
System.out.println("file enc" + System.getProperty("file.encoding"));
System.out.println("charset" +  java.nio.Charset.defaultCharset());
System.out.println("IS reader" + java.io.InputStreamReader.getEncoding());
```

**Comment by Andreas0602** [comment]
Does not compile.

```
GfG.java:20: error: cannot find symbol
        System.out.println("charset" +  java.nio.Charset.defaultCharset());
                                                ^
  symbol:   class Charset
  location: package java.nio
GfG.java:21: error: non-static method getEncoding() cannot be referenced from a static context
        System.out.println("IS reader" + java.io.InputStreamReader.getEncoding());
                                                                  ^
2 errors
```

**Comment by pskowronek** [comment]
@Andreas0602 oops, I've updated the code above.

**Comment by Andreas0602** [comment]
Output of the program:

```
de_DE
file encUTF-8
charsetUTF-8
```

**Comment by pskowronek** [comment]
Fix proposal provided in PR #733. @Andreas0602 can you check it?

**Comment by Andreas0602** [comment]
> Fix proposal provided in PR #733. @Andreas0602 can you check it?

With that version, when I press F12, the terminal starts and the following message is displayed in the terminal:

`zsh: string expected after -c`

Then the terminal hangs and accepts no input via keyboard.

**Comment by pskowronek** [comment]
Probably you have set `zsh -c` in Preferences. As stated in #733 the shell command and its parameters provided there must be now for 'interactive' mode, i.e. w/o `-c`. BTW, if you switch to default then you should have `zsh` chosen automatically.

**Comment by Andreas0602** [comment]
Yes, please ignore my previous message. With the default setting, everything is fine!

<img width="580" alt="Bildschirmfoto 2022-09-25 um 19 53 39" src="https://user-images.githubusercontent.com/79788982/192157883-88b6d542-7bf4-405a-9247-723d3fdcba9c.png">

**Comment by pskowronek** [comment]
but, still this backward incompatibility may surprise people. The question is how to tell people to fix what they placed there in previous versions..... @ahadas , @Andreas0602 ? Any thoughts?

**Comment by Andreas0602** [comment]
True. Would it be possible to enforce the default setting on first start after upgrade?

**Comment by pskowronek** [comment]
Does muC has something like migration scripts or something? Alternatively, we may change the preference key name (and probably for custom shell too)

**Comment by ahadas** [comment]
> Does muC have something like migration scripts or something? Alternatively, we may change the preference key name (and probably for custom shell too)

there're no migration scripts but we used to convert values when reading the configuration file, like [this](https://github.com/mucommander/mucommander/blob/release_0_9_1/src/main/java/com/mucommander/conf/MuPreferences.java#L399-L406) - maybe we should rename the variable to make it easier?

**Comment by pskowronek** [comment]
> > Does muC have something like migration scripts or something? Alternatively, we may change the preference key name (and probably for custom shell too)
> 
> there're no migration scripts but we used to make adaptations when reading the configuration file, like [this](https://github.com/mucommander/mucommander/blob/release_0_9_1/src/main/java/com/mucommander/conf/MuPreferences.java#L399-L406) - maybe we should rename the variable to make it easier?

I would try to avoid such things in the code (i.e. a migration script/code - fine, but in the production code it makes it cluttered. In future, we could come up with migration functionality, but for this case, let's rename it?

I can do it when everything related is merged into master.

**Comment by ahadas** [comment]
> > > Does muC have something like migration scripts or something? Alternatively, we may change the preference key name (and probably for custom shell too)
> > 
> > 
> > there're no migration scripts but we used to make adaptations when reading the configuration file, like [this](https://github.com/mucommander/mucommander/blob/release_0_9_1/src/main/java/com/mucommander/conf/MuPreferences.java#L399-L406) - maybe we should rename the variable to make it easier?
> 
> I would try to avoid such things in the code (i.e. a migration script/code - fine, but in the production code it makes it cluttered. In future, we could come up with migration functionality, but for this case, let's rename it?

yes, let's rename to something that better reflects we talk about interactive shell
 
> I can do it when everything related is merged into master.

merged :)

**Comment by pskowronek** [comment]
@ahadas pushed here #763

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
