### ISSUE TITLE
Bonjour does not detect smb drive

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#751]
On my Mac, I have installed Parallels Desktop. When I start a virtual machine (Windows), I can see the root drive of that virtual machine under Finder and MaxCommander, but not under muCommander.

Finder:
<img width="258" alt="Bildschirmfoto 2022-09-24 um 20 45 39" src="https://user-images.githubusercontent.com/79788982/192114285-91f7b2ab-ba52-47a3-ae2a-b2c1da729f3b.png">

Bonjour Browser of MaxCommander:
<img width="759" alt="Bildschirmfoto 2022-09-24 um 20 46 24" src="https://user-images.githubusercontent.com/79788982/192114290-7b7366e6-3083-49e6-afa1-b31fa2e8e107.png">

muCommander:
<img width="917" alt="Bildschirmfoto 2022-09-24 um 20 48 16" src="https://user-images.githubusercontent.com/79788982/192114295-a5d6c88a-65ea-4d8d-9779-2ee7c84a7dd8.png">

"Nokia VM 2019-11-06" is the name of the virtual machine.

I don't think that this is a new problem in muCommander v1.1.0. This feature has never worked as desired for me in muCommander.

**Comment by Andreas0602** [comment]
Okay, with the very latest muCommander build, this issue is resolved. The root drive of the virtual machine is still not listed under Bonjour services, but it's directly listed in the list of mounted volumes and special directories, and it can be used without any problems.

I'll close this ticket.

**Comment by ahadas** [comment]
Yeah, resolved by #749

**Comment by ahadas** [comment]
Version 1.1.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)
