### ISSUE TITLE
Moving files on NAS via FTP

### ISSUE THREAD

**Issue by mvveelen** [mucommander/mucommander#757]
With the latest version I suddenly have a problem with moving files on my Synology NAS. The shares are connected via FTP.

In the past it was done in seconds. Now it first copies the whole file to the destination and when done, MuCommander deletes the file from the source.

Version: 1.0.1-1
Build date: 2022/06/29
Build number: 23a87f5

**Comment by mvveelen** [comment]
With this build:

Version: 1.1.0
Build date: 2022/10/09
Build number: 6fb2c42

I have the same issue. What has changed and how can I fix it, because this is a big step backwards.

**Comment by ahadas** [comment]
@mvveelen I don't see any change in the last 2-3 years that could explain this, we barely touch the ftp protocol. do you remember which version worked well for you? if so, could you maybe give this version a try again to eliminate the possibility that something that is unrelated to mucommander causes this?

**Comment by ahadas** [comment]
@mvveelen I've upgraded 'commons-net' to v3.8.0 (#780) but the 'rename' functionality that you described above seems to work for me also with the previous version of 'commons-net' (v3.6) so I don't know if that would solve the issue for you, could you please try that with tomorrow's nightly build and provide the log in case it fails?

**Comment by mvveelen** [comment]
I'm not sure how I can retrieve and test the 'nightly build' you refer to, so that's a roadblock for me. Not sure what version worked for me, in the meanwhile I've updated twice if I remember correctly.
I indeed connect via FTP and the moving of files on the Synology NAS suddenly stopped working in seconds, it now copies the file to the new location and after that it removes the file from the old location (i.e. moving ...).
I would gladly test, but need to know the steps I should take, sorry.

**Comment by mvveelen** [comment]
I found older versions (0.9.7 and 0.9.4) and they have the same problem I'm experiencing. So I think it has nothing to do with Mucommander. Perhaps it's something that has changed on the Synology or the MacBook Pro, so this case can be closed. I have to figure out what has changed on these devices.

**Comment by ahadas** [comment]
> I would gladly test, but need to know the steps I should take, sorry.

Sorry, I overlooked this part - the nightly build, in portable form (which means you need to extract the zip and execute mucommander.sh/mucommander.exe, is available [here](https://github.com/mucommander/mucommander/releases/tag/nightly)

**Comment by mvveelen** [comment]
I found out that it probably has to do with the filesystem I now use on my Synology (Btrfs) because on another (remote) Synology with ext4 I can move big files in seconds. So it's probably nothing to do with MuCommander, I'm sorry.
