### ISSUE TITLE
Please make right-click menu "Services" available on macOS

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#758]
On macOS, please make available the right-click menu item Services (like in Finder).

I'm aware that it's possible to customize commands.xml. That's better than nothing, but it's not a full replacement of the "real" Services menu, particularly because you have to do it manually, while the "real" Services menu is automatically populated by the system. I'm also aware that this might be difficult to implement in Java, but on the other hand I believe it's worth to spend some effort for this, because it's an important feature for a file manager.

**Comment by ahadas** [comment]
that's similar to #759 - it's not a bad idea, on the contrary, but implementing something like this is out of the scope of mucommander
