### ISSUE TITLE
Failure to unpack symbolic links properly

### ISSUE THREAD

**Issue by yosaba** [mucommander/mucommander#76]
This may relate to issue 42 "Symbolic links are not copied ".

I tried to unpack (control-P) this  .bz2 file:
https://dronedata.dl.sourceforge.net/project/liteide/X30.3/liteidex30.3.linux64-qt4.tar.bz2

In the lib directory inside the archive, each file has a set of other files linked to it.  For example
libliteapp.so.1.0.0
libliteapp.so.1.0
libliteapp.so.1
libliteapp.so

In typical development, the first of these (libliteapp.so.1.0.0) is the real file and the rest at linked to it.  When I unpacked this archive with MuCommander, the last three files all had length zero.

When I unpacked it using tar from the bash command line,  all four files in each set had the same non-zero length.

**Comment by yosaba** [comment]
Thank you!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
