### ISSUE TITLE
muCommander's pop-up window progress bar stands still during file operations

### ISSUE THREAD

**Issue by nightknight-int** [mucommander/mucommander#761]
macOS Monterey 12.1. During file operations (copy, move, delete) muCommander's pop-up window progress bar stands still and the operation won't end until interrupted by pressing Stop button.

**Comment by ahadas** [comment]
@nightknight-int I can't reproduce it, can you please try with [v1.1.0](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1)?

**Comment by nightknight-int** [comment]
Issue resolved in https://github.com/mucommander/mucommander/releases/tag/1.1.0-1
You can close the issue. Thank you!
