### ISSUE TITLE
deb: unknown compression

### ISSUE THREAD

**Issue by demetriuzz** [mucommander/mucommander#771]
## Description
When install DEB package, I get an **error**:

```
sudo dpkg -i mucommander_1.1.0-1_amd64.deb 
dpkg-deb: error: archive 'mucommander_1.1.0-1_amd64.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive mucommander_1.1.0-1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 mucommander_1.1.0-1_amd64.deb
```
## Release
Version 1.1.0-1

## System
Linux Debian 11.5
Kernel 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

**Comment by ahadas** [comment]
@demetriuzz on which operating system?

**Comment by ahadas** [comment]
@demetriuzz thanks for reporting this. apparently, it's a known issue that [Debian’s dpkg package doesn’t support zstd compression](https://bugs.debian.org/892664). I've updated `mucommander_1.1.0-1_amd64.deb`, can you please check now?

**Comment by demetriuzz** [comment]
Good day!
Updated `mucommander_1.1.0-1_amd64.deb` is work!
**Good work!**
_Thank you so much for your promptness._

I didn't know about this bug: [Debian’s dpkg package doesn’t support zstd compression](https://bugs.debian.org/892664)
I _hope_ that the specified compression method will be added in the next version of `dpkg`.
But at the moment, in the current version of `dpkg 1.20.12`, it is as it is.

**Comment by ahadas** [comment]
thanks for the confirmation!

**Comment by jlschwartz** [comment]
I am getting the same error when trying to install mucommander 1.30 in Debian.  It does not recognize the zst compression.  How can this be corrected.   Thanks.

**Comment by ahadas** [comment]
@jlschwartz yeah, it makes sense as version 1.3.0 was built using github-actions on Ubuntu as I did before (this issue was solved by building the `deb` file on Debian). you can try to repack the package [as explain here](https://unix.stackexchange.com/questions/669004/zst-compression-not-supported-by-apt-dpkg) but it would be better to upgrade to Debian 12 if you can, I verified the `deb` file can be installed on Debian 12
