### ISSUE TITLE
Feature: render file or directory name differently if read only

### ISSUE THREAD

**Issue by fr43nk** [mucommander/mucommander#773]
Hi,

in the theme editor I can modify the font color of different file states (hidden,  symbolic link, normal). Is it possible to add a additional value to files and directories with attribute set to *read only*?

Best,
Frank

**Comment by ahadas** [comment]
@fr43nk thanks for filing this, sounds possible :)

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
