### ISSUE TITLE
Add ability to change timeout of filter invalidation

### ISSUE THREAD

**Issue by tomasMizera** [mucommander/mucommander#775]
Hi all,

I am having a hard time using the filtering feature (typing letters in a directory to jump over files that match the string, see video).

The default timeout to invalidate the search is too quick for me. When I search for a file without knowing the exact name, the search invalidates while reading the file name and I need to type it in again (it even jumps to the first entry again!) 🙃 

I was wondering if we could have an option in settings to make the search permanent (do not invalidate after a few seconds) or have some variable to manipulate the timeout. Thanks for the good work!

https://user-images.githubusercontent.com/22449698/196433709-a4f0e8d7-7ff3-4c65-b1d2-8db1346ec3b6.mp4

**Comment by ahadas** [comment]
@tomasMizera thanks for reporting this, yeah, [it's hard coded to 2 seconds](https://github.com/mucommander/mucommander/blob/1.1.0/mucommander-core/src/main/java/com/mucommander/ui/quicksearch/QuickSearch.java#L50). I think it's a good idea to make it configurable as you suggest

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)

**Comment by tomasMizera** [comment]
Marvellous!
