### ISSUE TITLE
Open native not working - Open is always read-only

### ISSUE THREAD

**Issue by lanthale** [mucommander/mucommander#78]
Version 0.9.1
On windows if I open a file on a network drive e.g. a ppt than the PPT is opened in read-only mode. If I use the function "open native" no operation is executed.

**Comment by lanthale** [comment]
Here is the error log:
[2017-02-24 13:02:24.026] INFO DefaultSchemeParser.java#parse,296 Warning: path should not be empty, url=file://nvgm387.itar.net/documents

**Comment by lanthale** [comment]
This is always happening if I open a file on a network path (SMB)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.
