### ISSUE TITLE
Mark/unmark (+/-) don't work on macOS unless using full KB with numpad or alternative shortcut

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#782]
Mark/unmark (+/-) actions don't work on macOS with small keyboard without num-keys. It works only when using +/- from numpad of full layout keyboard. To make it work on small keyboard I had to add alternative shortcut "+" and "-".

I've got two questions:
1) what is the character in the screenshot below?
2) where default shortcuts for these actions are being defined in the project (code)? I don't see them on Action handlers.

![obraz](https://user-images.githubusercontent.com/360665/197396808-f386d4cb-e1f6-4ca5-ae4c-5a138eda467a.png)

**Comment by ahadas** [comment]
> 1. what is the character in the screenshot below?

it's not a character, it's the representation of "NumPad" on macOS - so this thingie with '+' means 'NumPad +'

> 2. where default shortcuts for these actions are being defined in the project (code)? I don't see them on Action handlers.

[here](https://github.com/mucommander/mucommander/blob/master/mucommander-os-api/src/main/java/com/mucommander/desktop/ActionShortcuts.java) is the default ones, and [here](https://github.com/mucommander/mucommander/blob/master/mucommander-os-macos/src/main/java/com/mucommander/desktop/macos/ActionShortcuts.java) we override things for macOS

**Comment by pskowronek** [comment]
> > 1. what is the character in the screenshot below?
> 
> it's not a character, it's the representation of "NumPad" on macOS - so this thingie with '+' means 'NumPad +'

Interesting..... not very intuitive I must say :)

> 
> > 2. where default shortcuts for these actions are being defined in the project (code)? I don't see them on Action handlers.
> 
> [here](https://github.com/mucommander/mucommander/blob/master/mucommander-os-api/src/main/java/com/mucommander/desktop/ActionShortcuts.java) is the default ones, and [here](https://github.com/mucommander/mucommander/blob/master/mucommander-os-macos/src/main/java/com/mucommander/desktop/macos/ActionShortcuts.java) we override things for macOS

Any objections to add "normal" + and - to alternative shortcuts (as default ones)?
