### ISSUE TITLE
Ubuntu internal error when running muCommander

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#783]
I just installed muCommander on a newly installed Ubuntu 22.04 machine. Now when I boot up the Linux machine, I get an error telling me "Sorry, Ubuntu 22.04 has experienced an internal error." When I ask for more information, it tells me the problem is a crash with SIGABRT from executable file /opt/mucommander/bin/mucommander.

Any thoughts on what to do next...?

Thanks.

**Comment by pskowronek** [comment]
Pls dig thru logs (`/var/log/syslog`?) and see if there's anything helpful to move on with the investigation. When you run `/opt/mucommander/bin/mucommander` from terminal do you see any errors?

**Comment by rhstanton** [comment]
Nothing obvious. And it seems to have stopped reporting any problems after a reboot. I'll report back if I see anything else.
