### ISSUE TITLE
"Search in hidden files" should be enabled by default

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#789]
"Search in hidden files" should be enabled by default. Rationale: With the current default setting, where this option is disabled, normal files within hidden directories are not found. For example, the normal file ~/.config/xnviewmp/xnview.ini is not found, because it is located in the hidden directory .config. This is probably unexpected and undesired behavior to most users. It is also somehow inconsequent that "Search **for** hidden files" is enabled by default whereas "Search **in** hidden files" is disabled.

Furthermore, it would improve clearness to rename the option to "Search in hidden files **and directories**". One might argue that a directory is also a file (?), but it's more user-friendly to avoid potential misunderstandings in the first place.

**Comment by ahadas** [comment]
> "Search in hidden files" should be enabled by default. Rationale: With the current default setting, where this option is disabled, normal files within hidden directories are not found. For example, the normal file ~/.config/xnviewmp/xnview.ini is not found, because it is located in the hidden directory .config. This is probably unexpected and undesired behavior to most users. It is also somehow inconsequent that "Search **for** hidden files" is enabled by default whereas "Search **in** hidden files" is disabled.

I wonder, how did you configure the 'Show hidden files' setting - is it enabled or disabled? I think that you have a point in what you wrote above but the default should rather be derived from that setting - if this setting is disabled, that means you don't wish to see hidden files, and by default we shouldn't search for or search in hidden files. However, if this setting is enabled then we should both search for and search in hidden files. A combination in which one is enabled and the other is disabled would then only be set manually, and we wouldn't need to assume what users expect to get by default. @Andreas0602 What do you think?
 
> One might argue that a directory is also a file (?) ...

Yeah, at this point it's pretty much assumed the user understands folders are kind of files in various place - the aforementioned 'Show hidden files' setting, the 'File operations' category for actions in the keyboard shortcuts dialog, 'Mark files', etc. For consistency, I'd leave it this way

**Comment by Andreas0602** [comment]
@ahadas, I have disabled the setting 'Show hidden files'. Anyway, xnview.ini is not a hidden file. Therefore, the search function should find it. IMHO it's generally better to find more results than less. You can get rid of undesired results, if any, in a second search run with different settings. But not finding an existing file is quite a serious issue.

Your idea to derive the default search settings from the setting of 'Show hidden files' sounds over-complicated to me. Generally, the behavior should be straight-forward. Settings which change other settings behind the scenes are not straight-forward.

**Comment by Andreas0602** [comment]
I think I already answered the question why I want to find xnview.ini with the default settings: Because it's a normal file.

I don't want this to become an endless discussion. I think the arguments are clear now. There's no point in repeating them again and again.

I agree that the behavior of the search function should not be changed. I haven't requested such a change anyway. I only requested to change the default value of one search parameter - pretty easy and straight-forward. It's your decision whether you want to follow that request or not.

**Comment by ahadas** [comment]
@Andreas0602 it's not yet clear to me why would anyone care about it that much so I tried to see if there's a scenario I don't think of but that's ok, if you wish not to discuss it further then I guess you also don't care about this that much.

After a bit more thinking I tend to think that the reason we argue about the default settings of the search reveal a different issue - that the search properties are not persistent. Had the search properties been saved and restored the same way on future searches, we would have cared about the default value as they are used only for the very first search.

So I think we can improve the current situation by doing the following:
1. Save the previously used settings for file searches in the snapshot.xml and so we'd restore them on startup.
2. For the very first the search in hidden files and search for hidden files would match the setting of 'show hidden files'. By default, the latter is false and so both search options would be disabled. If the user enables 'show hidden files', that would be an indication that hidden files are interesting for the user and we'll enable both search options.

**Comment by Andreas0602** [comment]
Meanwhile I had the same idea: The real issue is not the question why a user prefers this or that setting, but the real issue is that the settings are not sticky. So, I fully agree with your new proposal – with one possible reservation. You mentioned to save the search settings in the snapshot.xml. This reminds me of issue #689. The settings for "Line wrap" and "Line numbers" also seem to be stored in snapshot.xml. And here we have a problem: After some time, muCommander forgets the settings and reverts to some defaults. I don't know which specific event makes muComander forget these settings, but it definitely happens, and it's annoying.

Regarding the settings of "Line wrap" and "Line numbers", we have in principle the same situation as with the search settings. I don't want endless discussions about the reasons why I prefer certain defaults. I would already be satisfied if the settings I make would persist, reliable and permanent.

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
