### ISSUE TITLE
Sort based on column should not group items by type

### ISSUE THREAD

**Issue by tomasMizera** [mucommander/mucommander#793]
Hello,

not sure if this is intentional, however, when I click on `date` to sort items by date, I always see all the folders first (despite they are not recent) and need to scroll down below folders in order to get to files.

You can see it on the image below:
<img width="902" alt="Screenshot 2022-11-15 at 15 40 46" src="https://user-images.githubusercontent.com/22449698/201947629-b7cd3087-b541-4633-8e95-9a272a8be707.png">

I tried to reach the just downloaded `.tar.gz` packages, but instead I got all the folders first (even some `.app` files were listed first). Is it intentional to group all the folders first? Are there other types that are grouped like this? Why are the `.app` files between folders 🤔 

Thanks for your hard work 💪!!

**Comment by Andreas0602** [comment]
Did you try the check/uncheck the option View > Show folders first?

.app files are actually folders on macOS.

**Comment by tomasMizera** [comment]
Thanks!
