### ISSUE TITLE
Can't set up cygwin shell on win8 x64

### ISSUE THREAD

**Issue by kuzp** [mucommander/mucommander#8]
I've tried to use cygwin shell instead of cmd.exe :
C:\cygwin64\bin\bash.exe -l -c
(this path exists)
After C-R and type any command I have message: 
"An error has occurred while performing the requested operation."
Also I checked that I will see the same message if I set any shell path that doesn't exist
Tested both on 0.9 and last nightly (http://www.mucommander.com/download/nightly/mucommander-current-setup.exe)
On windows 7 x64 everything is fine 
Thanks

**Comment by sskras** [comment]
I think the title should be fixed into something like:
"Can't use Cygwin as a custom shell on ..."

**Comment by ahadas** [comment]
Newer Windows versions now have built-in Linux bash shell that renders this redundant
