### ISSUE TITLE
Selected text practically unreadable

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#806]
With the new editor, selected text is difficult to read. To fix this issue, selected text should be white (as it was in the old editor) so that there is a strong contrast to the dark blue background of the selection.
<img width="679" alt="Screenshot" src="https://user-images.githubusercontent.com/79788982/208238342-ff68b4fc-27b4-489c-b456-0cf77631e705.png">

**Comment by ahadas** [comment]
@pskowronek what do you think?

**Comment by pskowronek** [comment]
hmmm, on my mac I've got:

![obraz](https://user-images.githubusercontent.com/360665/208267947-000957b2-4d5f-49b9-9ffe-0918e2faa1b5.png)

@Andreas0602 what Theme and L&F do you have?

**Comment by Andreas0602** [comment]
I have the Native theme and FlatLaf Light L&F.

**Comment by pskowronek** [comment]
I've got Mac OS X theme and SolarizedDark and it looks good.

I've checked L&Fs:
- FlatLaf Light L&F makes this selection unreadable, and btw all other FlatLaf variants too
- Nimbus, VAqua are totally broken - no selection is visible, plus some text not so visible 
- Metal is OK (of course :P)
- Motif is OK

So, for FlatLaf variants (and I'm not sure how those L&F work in muC i.e. how they are defined) - would it be possible to set alpha channel for selection? Or replicate the color for selection as for SolarizedDark/Metal? @ahadas any suggestion?

**Comment by pskowronek** [comment]
If we do not explicitly set selectedTextColor and selectionColor in TextEditoImpl leaving defaults then:

![obraz](https://user-images.githubusercontent.com/360665/208269652-b69c7998-78b0-4443-8804-61ef2ebb00dc.png)

As it comes to Nimbus, VAqua - are they still we should care about? I mean, maybe it's time to mark them as `legacy`?

**Comment by ahadas** [comment]
@pskowronek for how FlatLaf is defined see #651 
Vaqua was added not long ago (#654) and I remember users commenting that they use it (@Andreas0602 was it you? I really can't recall) so better to make it work but Nimbus.. I don't know how many people use it, I also saw other things that didn't look so well with Nimbus L&F, I don't think we should pay too much attention to that

**Comment by Andreas0602** [comment]
IMHO it would be good if VAqua would remain supported. I slightly prefer FlatLaf over VAqua, but nevertheless VAqua is a good, modern L&F. If I remember correctly, I mentioned VAqua in a discussion about some issue and provided a link to it. Regarding Nimbus, I can say that I never used it, and I wouldn't care if it wouldn't be supported in the future.

**Comment by pskowronek** [comment]
A fix proposal for all L&Fs as it comes to selection. 

However, for Nimbus - still its color settings are not so visible in the editor with syntax.

As it comes to VAqua - apparently, I'm having a problem setting it:
```
AquaNativeSupport: Unable to load library libvaqua.dylib: /private/var/folders/9p/n_68mkh91bdfhvddkxntw3bm0000gp/T/libvaqua17663141656312094888.dylib: dlopen(/private/var/folders/9p/n_68mkh91bdfhvddkxntw3bm0000gp/T/libvaqua17663141656312094888.dylib, 1): Library not loaded: @rpath/JavaNativeFoundation.framework/Versions/A/JavaNativeFoundation
  Referenced from: /private/var/folders/9p/n_68mkh91bdfhvddkxntw3bm0000gp/T/libvaqua17663141656312094888.dylib
  Reason: image not found
Exception in thread "Thread-7" java.lang.IndexOutOfBoundsException: len=-4
        at java.desktop/sun.font.FontDesignMetrics.charsWidth(FontDesignMetrics.java:498)
        at org.fife.ui.rsyntaxtextarea.TokenImpl.getWidthUpTo(TokenImpl.java:601)
```

**Comment by Andreas0602** [comment]
For what it's worth, VAqua does work on my Mac, and the selection is okay. So, no further work or fixes are needed for VAqua from my point of view.
