### ISSUE TITLE
Replace ICEpdf with better / maintained library

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#810]
On macOS, muCommander's built-in PDF viewer does not work. To reproduce the issue, select any PDF file and press F3. The PDF viewer will start, but all pages of the PDF document will be empty.

**Comment by ahadas** [comment]
yeah, the library we use (ICEpdf) is not perfect and doesn't seem to be maintained anymore but it works well with my pdf files. could you please share the pdf for which it fails for you?

**Comment by Andreas0602** [comment]
Here is a example which does not work for me.
[hdd2,5_external_core_30.pdf](https://github.com/mucommander/mucommander/files/10297288/hdd2.5_external_core_30.pdf)

**Comment by Andreas0602** [comment]
Viewing PDF files is not an important feature for a file manager. If it does not work, I'd suggest to simply remove that feature.

**Comment by ahadas** [comment]
seems to work well for me on macOS Monterey:
<img width="1032" alt="Screen Shot 2022-12-23 at 22 57 19" src="https://user-images.githubusercontent.com/6020068/209404899-b001e23a-f711-428a-80ac-850ebb98deb2.png">

> Viewing PDF files is not an important feature for a file manager. If it does not work, I'd suggest to simply remove that feature.

yeah, I'd agree if it's completely broken but if it works, even if not perfectly, and can serve others, I don't think we should remove it but rather find a better library to use, maybe [this](https://mvnrepository.com/artifact/com.github.pcorless.icepdf/icepdf-viewer)

**Comment by Andreas0602** [comment]
This is how it looks for me (under macOS Ventura -- unfortunately I never tested it under Monterey):

<img width="850" alt="Screenshot_2022-12-23_22-06-47" src="https://user-images.githubusercontent.com/79788982/209405670-a205d0f2-9449-4cfd-8063-e0533073f7eb.png">

**Comment by ahadas** [comment]
@Andreas0602 can you please check if it's better with the nightly build?

**Comment by Andreas0602** [comment]
It works fine with the nightly build. Thank you very much, @ahadas!

I'll close this issue.

<img width="754" alt="Screenshot_2022-12-24_18-56-24" src="https://user-images.githubusercontent.com/79788982/209446816-aa83c6be-a844-40bc-8ed5-27f294dfb68e.png">
