### ISSUE TITLE
Opening links from viewer/editor does not work reliably

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#811]
On macOS Ventura, opening links from the new viewer/editor does not work reliably. In rare cases, clicking on a link like www.google.com while pressing the command key will open the link in Safari, but in ~ 95% of all attempts nothing will happen.

**Comment by ahadas** [comment]
it doesn't reproduce for me on macOS Monterey (on the contrary, the link seems to open too quick - on mouseover after clicking the command key, before clicking the link). @pskowronek can you please look into this?

**Comment by Andreas0602** [comment]
Yes, sometimes the link even opens after pressing and releasing the command key, without a mouse click. But in most of the cases, it doesn't do anything at all.

**Comment by pskowronek** [comment]
> it doesn't reproduce for me on macOS Monterey (on the contrary, the link seems to open too quick - on mouseover after clicking the command key, before clicking the link). @pskowronek can you please look into this?

as it comes "too quick" - I have this, too, but I thought it is by design in RSyntaxTextArea - I will check in their vanilla example how it behaves.

>  but in ~ 95% of all attempts nothing will happen

I don't have Ventura anywhere :/ Can somebody verify on Ventura if it is the problem?

**Comment by pskowronek** [comment]
btw, @Andreas0602 - for opening links I've used muC existing code - can you check if in AboutDialog clicking `Go to website` opens browser reliably?

**Comment by Andreas0602** [comment]
Clicking `Go to website` in the About dialog does open the browser reliably.

**Comment by pskowronek** [comment]
I've just pushed PR
- @ahadas - pls check key sequence
- @Andreas0602 - pls check reliability of opening the links

**Comment by Andreas0602** [comment]
@pskowronek, I tested your change. I still need several attempts to open a link, but apparently fewer than before. After opening the link, the mouse cursor will change from an arrow to a pointing hand, and it's not possible to change it back except by closing the window. So, the behavior has slightly improved, but it's still not okay.

**Comment by Andreas0602** [comment]
Okay, opening a link does work reliably now if I do it the following way:

step 1: place the mouse cursor over the link
step 2: press the command key and keep it pressed
step 3: slightly move the mouse cursor -- as a result, the mouse cursor will change from an arrow to a pointing hand
step 4: left mouse click

It doesn't work without step 3.
But it should work without step 3.

**Comment by pskowronek** [comment]
@Andreas0602 - I cannot reproduce this on my mac (Catalina) :/

**Comment by Andreas0602** [comment]
Okay, this issue is not a major one. Overall, the new syntax highlighting feature is a great improvement. Thank you very much for it, @pskowronek! Too bad that we don't have more users to test it in different environments, so that we know whether the issue is somehow related to macOS Ventura.

**Comment by ahadas** [comment]
> Okay, opening a link does work reliably now if I do it the following way:
> 
> step 1: place the mouse cursor over the link step 2: press the command key and keep it pressed step 3: slightly move the mouse cursor -- as a result, the mouse cursor will change from an arrow to a pointing hand step 4: left mouse click
> 
> It doesn't work without step 3. But it should work without step 3.

that happened on my machine, posted #817 to address that - @pskowronek I've added you as code owner of `mucommander-viewer-text/` so you'd be automatically added to review PR that touch this code, please take a look.

note that there're two things I left out of this PR:
1. something doesn't work properly with the initial focus still, so you need to press on the text and only then this functionality works
2. the cursor is always changed back to Cursor.TEXT_CURSOR, even when opening the text file with `view` but I see that it's hard coded in RSyntaxTextArea, @pskowronek would you like to address that?

**Comment by pskowronek** [comment]
> 2\. the cursor is always changed back to Cursor.TEXT_CURSOR, even when opening the text file with `view` but I see that it's hard coded in RSyntaxTextArea, @pskowronek would you like to address that?

Hm, is Cursor.TEXT_CURSOR wrong for `view` mode? I can still may want to copy a text and such a cursor type is OK.

If we really want to return to DEFAULT_CURSOR (arrow) then this might be a good workaround:
```
@@ -110,6 +114,16 @@ class TextEditorImpl implements ThemeListener {
                             LOGGER.error("Error opening link in a browser", e);
                         }
                     });
+                    textArea.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
+                }
+            });
+            textArea.addMouseMotionListener(new MouseAdapter() {
+                Cursor textCursor = Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR);
+                @Override
+                public void mouseMoved(MouseEvent e) {
+                    if (textArea.getCursor() == textCursor) {
+                        textArea.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
+                    }
                 }
             });
             textArea.setHyperlinksEnabled(true);
```

However, what I would suggest is to set Cursor.TEXT_CURSOR as a default for textArea (in init phase).
What do you think? @ahadas , @Andreas0602

**Comment by ahadas** [comment]
@pskowronek that's a good point, I think it makes sense to set TEXT_CURSOR as the default cursor for text viewer as well

**Comment by pskowronek** [comment]
> @pskowronek that's a good point, I think it makes sense to set TEXT_CURSOR as the default cursor for text viewer as well

PR created - still most of the time on initial open a default 'arrow' cursor is set (moving to line-number panel and back to editor it shows TEXT_CURSOR properly). Another magic required as for the focus, @ahadas ? :)
