### ISSUE TITLE
Automatic detection of iso-8859-1 encoding does not work with new text viewer/editor

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#824]
Automatic detection of iso-8859-1 encoding does not work with the new text viewer/editor. See the file "iso-8859-1.txt" in the attached zip file. That file contains a sentence with an umlaut, which is incorrectly displayed. The same file is displayed correctly with the viewer of muCommander v1.1.0.

[test.zip](https://github.com/mucommander/mucommander/files/10325060/test.zip)

**Comment by pskowronek** [comment]
I've checked this file, and I see that iso-8859-1 has umlauts etc in its charset (https://www.fileformat.info/info/charset/ISO-8859-1/list.htm)... The quick fix (#821) to treat iso-8859-1 as utf-8 was not so great. Checking if `EncodingDetector` can give us more options.

**Comment by pskowronek** [comment]
I have commented out the code committed in #821 - need to re-think how to switch from 7-bit iso-8859-2 (w/o umlauts etc) to utf-8

**Comment by pskowronek** [comment]
PR updated - I've created a proxy `InputStream` to snoop whether bytes used by `EncodingDetector` (or rather `CharsetDetector`) had 8th bit set, if not then UTF-8 will be used as default.
