### ISSUE TITLE
macOs says mucommander-snapshot.dmg is damaged

### ISSUE THREAD

**Issue by superbonaci** [mucommander/mucommander#826]
Download and drag to Applications:
https://github.com/mucommander/mucommander/releases/download/nightly/mucommander-snapshot.dmg

macOs 13 says:
```
"muCommander" is damaged and can't be opened. You should move it to the Bin.
This file was downloaded on an unknown date.
Move to Bin / Cancel
```
Stable version works fine:
https://github.com/mucommander/mucommander/releases/download/1.1.0-1/muCommander-1.1.0-1.dmg

**Comment by ahadas** [comment]
@superbonaci thanks for reporting this - it's a ['known issue'](https://github.com/mucommander/mucommander/discussions/716) that the nightly version is not signed. this shouldn't happen with stable versions, the latest is [v1.1.0](https://github.com/mucommander/mucommander/releases/tag/1.1.0-1). you can also check if [the solution that worked for previous versions](https://github.com/mucommander/mucommander/discussions/613) also works on macOS 13

**Comment by superbonaci** [comment]
Thank you. `sudo xattr -cr mucommander-snapshot.dmg` worked.
