### ISSUE TITLE
muCommander 1.1.0-1 does not rename files in Google Drive

### ISSUE THREAD

**Issue by superbonaci** [mucommander/mucommander#827]
Try to rename a file in GDrive and fails:

![](https://i.imgur.com/H4NY9bY.gif)

Version muCommander-1.1.0-1.dmg

**Comment by ahadas** [comment]
yeah, I can reproduce it, thanks for reporting this

**Comment by superbonaci** [comment]
Thank you, will test with latest nightly.

**Comment by superbonaci** [comment]
@ahadas ok then release stable version I think there are more bugs...

**Comment by ahadas** [comment]
@superbonaci FYI, I've fixed the integration with Google Drive in nightly versions - you can go ahead and check it with the nightly version that was published

**Comment by superbonaci** [comment]
Thank you!

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)

**Comment by superbonaci** [comment]
Thank you I confirm it works!
