### ISSUE TITLE
I can t see "my phone"

### ISSUE THREAD

**Issue by Ol6464** [mucommander/mucommander#828]
Hi, 
I can t see "my phone" in the explorer, I can t see "My computer", Maybe it is the same problem.

I only see classical drive, but if I use Freecommander, it s working.

Do you have a solution ?
Thanks in advance.
Olivier

technical detail :
Version information

muCommander
Version: 1.1.0
Build date: 2022/10/09
Build number: 6fb2c42

Java
Runtime version: 17.0.2
VM name: Java HotSpot(TM) 64-Bit Server VM
VM version: 17.0.2+8-LTS-86
VM vendor: Oracle Corporation

OS
Name: Windows 10
Version: 10.0
Architecture: amd64

Locale
Language: fr
Country: FR
Encoding: Cp1252

**Comment by ahadas** [comment]
hi @Ol6464 , `My Computer` is not shown as it's not a partition but your phone should be identified, can you press the button to the left of the text field that holds the current location (in the tab) and share what you get?

**Comment by pskowronek** [comment]
Please re-open if it is still an issue.
