### ISSUE TITLE
Trojan detection in portable package .zip

### ISSUE THREAD

**Issue by elalewen** [mucommander/mucommander#829]
Hello, I usually scan package before installation, execution or unzip it. VirusTotal detects a Trojan : 
![image](https://user-images.githubusercontent.com/25105768/210253140-ba907526-8289-48f5-b175-39307c6b0fc2.png)
Is there a risk ? Security problem ?

**Comment by pskowronek** [comment]
I've run the scan and nothing was found (see [here](https://www.virustotal.com/gui/url/a48d886660606a055e70dea3728da57cb755d0e26475c4b02314636745455792)).

However, on the list of vendors I don't see Jiangmin and NANO-Antivirus

**Comment by ahadas** [comment]
interesting, Jiangmin seems to be missing when I upload the snapshot-portable version but NANO-Antivirus and what it detects (Trojan.Win32.Adwind.jtlhdj) is there

**Comment by pskowronek** [comment]
Please re-open if it is still an issue.
