### ISSUE TITLE
Umlauts cause wrong line-wrap 

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#833]
In today's nightly build, muCommander's internal text viewer wraps words with umlauts in the middle of the word. See screenshot below:

<img width="500" alt="with muCommander 1 2 0" src="https://user-images.githubusercontent.com/79788982/210540447-f8782d9d-4de4-44fb-bbb0-8b20b4693e5e.png">

To reproduce the issue, enable line wrap and disable line numbers, then download the attached file [unnötig.txt](https://github.com/mucommander/mucommander/files/10343427/unnotig.txt), select it, and press F3.

This problem did not occur with with muCommander 1.1.0. See screenshot below:

<img width="500" alt="with muCommander 1 1 0" src="https://user-images.githubusercontent.com/79788982/210541196-8bb31806-196f-4876-af62-01aed6d058e8.png">

**Comment by pskowronek** [comment]
I can reproduce this. When you change syntax style from None to any other then problem is gone.

I've reproduced this in demo app provided by `RSyntaxTextArea` - I've reported a bug for it: https://github.com/bobbylight/RSyntaxTextArea/issues/483
It is not only limited to Umlauts but also to other national diacritics.

**Comment by pskowronek** [comment]
It's been fixed in master of RSyntaxTextArea - awaiting a new release of the library.

**Comment by pskowronek** [comment]
PR provided

**Comment by ahadas** [comment]
great job @pskowronek !
