### ISSUE TITLE
Text editor should create utf-8 files without BOM by default

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#835]
When you create a shell script and try to run it, you'll get an error like "command not found". To reproduce the issue, follow these steps:

1. Press Shift+F7 and create a new file named "test".
2. Select the file "test" and press F4. This will open the file in the internal editor.
3. In the internal editor, enter the text "echo Hello world"
4. Press ESC. When prompted, press "Save" to save the file.
5. Press F12 to open the terminal.
6. Execute the following command: sh ./test

To fix this issue, the text editor should create utf-8 files without BOM by default.

**Comment by pskowronek** [comment]
I confirm, will take a look.

**Comment by pskowronek** [comment]
This behavior was also present in muC Version: 1.1.0 (when UTF-8 was set as encoding).

**Comment by pskowronek** [comment]
Since BOM for UTF-8 is not required and in the wild is uncommon, plus having [this](https://unicode.org/faq/utf_bom.html#utf8-2) information I decided to override BOMWriter#bomWriteChecked init value so it will avoid writing BOM for UTF-8.

See upcoming PR

**Comment by pskowronek** [comment]
PR provided #836

**Comment by ahadas** [comment]
I have a vague memory of a thread on dropping BOM, which didn't make sense back then, but for specifically for UTF-8 it sounds ok - so this approach is fine by me, I'll comment on implementation details in the PR
