### ISSUE TITLE
SFTP server's certificate is not checked

### ISSUE THREAD

**Issue by magicgoose** [mucommander/mucommander#84]
mucommander seems to blindly connect to any SFTP server without certificate checks. therefore a MitM (some other server pretending to be the server we want to connect) won't be detected…

the right way is to check server certificate fingerprint against a whitelist, and if it's not there, prompt the user. all of this BEFORE sending password to the server (in case of password-based authentication)

**Comment by pskowronek** [comment]
If it is still an issue please re-open.

**Comment by magicgoose** [comment]
> If it is still an issue please re-open.

Why wouldn't it be, did anyone make any relevant changes?

**Comment by pskowronek** [comment]
6 years of fixes, library changes and their updates.... Can you simply check the newest version and confirm if it is still an issue? BTW, PRs are welcomed, too :)

**Comment by magicgoose** [comment]
Oops haven't noticed it's been so long :)
