### ISSUE TITLE
Korean characters are broken in a statusbar

### ISSUE THREAD

**Issue by binmaker** [mucommander/mucommander#85]
![default](https://cloud.githubusercontent.com/assets/26684152/24328931/23392006-1232-11e7-8156-94264b253fd4.png)

**Comment by ahadas** [comment]
I can't reproduce it, unfortunately (see the screenshot below).
@binmaker  Did you modify the dictionary file with the Korean translation?
<img width="758" alt="korean" src="https://cloud.githubusercontent.com/assets/6020068/25305633/d6b44c22-2787-11e7-82be-9bb4899ae22f.png">
