### ISSUE TITLE
nightly dmg is damaged

### ISSUE THREAD

**Issue by superbonaci** [mucommander/mucommander#850]
macOS keeps saying "muCommander" is damaged and can't be opened. You should move it to the Bin.
Doesn't happen with stable release.

**Comment by ahadas** [comment]
that's a known issue - the nightly build is not signed, see https://github.com/mucommander/mucommander/discussions/613 for how to install that dmg

**Comment by superbonaci** [comment]
The `sudo xattr -cr /Applications/muCommander.app` doesn't work anymore with macOS 13.1. You must go to System Settings - Privacy & Security - "muCommander" was blocked from use because it is not from an identified developer. Open Anyway. Then it works.

**Comment by superbonaci** [comment]
If you had Settings opened just close it and reopen so "Open Anyway" appears.

**Comment by superbonaci** [comment]
Update: you must `sudo xattr -cr /Applications/muCommander.app`, until you do this you can't unblock it from Systems Settings because doesn't appear.

 Then go to System Settings - Privacy & Security - "muCommander" was blocked from use because it is not from an identified developer. Open Anyway.

Then it works.

**Comment by georgjaehnig** [comment]
@superbonaci When trying `sudo xattr -cr /Applications/muCommander.app`, I get many lines with

    [...]
    xattr: [Errno 1] Operation not permitted: '/Applications/muCommander.app/Contents/PkgInfo'
    xattr: [Errno 1] Operation not permitted: '/Applications/muCommander.app/Contents'
    xattr: [Errno 1] Operation not permitted: '/Applications/muCommander.app'

Also tried `chflags -R nouchg /Applications/muCommander.app` from [here](https://superuser.com/a/40754).

**Comment by pskowronek** [comment]
@georgjaehnig 
Try this `` as described here: https://stackoverflow.com/q/64842819/1715521

If that doesn't help, try this: https://stackoverflow.com/a/64985297/1715521

Let us know which one helped.

**Comment by georgjaehnig** [comment]
@pskowronek So I tried:

    $ sudo xattr -rd com.apple.quarantine /Applications/muCommander.app
    ...
    xattr: [Errno 1] Operation not permitted: '/Applications/muCommander.app/Contents'
    xattr: [Errno 1] Operation not permitted: '/Applications/muCommander.app'

Then:

    $ codesign --force --deep --sign - /Applications/muCommander.app
    /Applications/muCommander.app: replacing existing signature
    /Applications/muCommander.app: Operation not permitted
    In subcomponent: /Applications/muCommander.app/Contents/readme.txt

Also:

    $ sudo chmod -R 755 /Applications/muCommander.app
    ....
    chmod: Unable to change file mode on /Applications/muCommander.app/Contents/Info.plist: Operation not permitted
    chmod: Unable to change file mode on /Applications/muCommander.app/Contents/PkgInfo: Operation not permitted

**Comment by pskowronek** [comment]
Try this this https://stackoverflow.com/a/65372659/1715521 and give us feedback.

BTW, as last resort you may want to reboot to Recovery mode and try those commands, or temporarily disable SIP (https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).

**Comment by pskowronek** [comment]
btw, again - are you on mac silicon? What macOS version?

**Comment by georgjaehnig** [comment]
> Try this this https://stackoverflow.com/a/65372659/1715521 and give us feedback.

    $ pkgutil --check-signature /Applications/muCommander.app
    Package "muCommander":
       Status: package is invalid (checksum did not verify)

>  btw, again - are you on mac silicon? What macOS version?

maOS Ventura 13.4.1 (c) with Apple M1 chip

**Comment by pskowronek** [comment]
@georgjaehnig  remove the whole app and re-download again?

**Comment by georgjaehnig** [comment]
Already did that a few times: Installed and removed with `brew`, also via [direct download](https://www.mucommander.com/#download). Always the same.

**Comment by pskowronek** [comment]
What about this:
> BTW, as last resort you may want to reboot to Recovery mode and try those commands, or temporarily disable SIP (https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection).

**Comment by georgjaehnig** [comment]
@Andreas0602 This one helped!

Then, I only needed to open it one time from Finder with right click -> Open. 

Thanks!

**Comment by superbonaci** [comment]
You may need to cycle through several of those commands and settings to get it working. Those not wanting to bother can use brew.sh botthe:
https://formulae.brew.sh/cask/mucommander
