### ISSUE TITLE
Trashed files in Google Drive still appear in previous location

### ISSUE THREAD

**Issue by superbonaci** [mucommander/mucommander#852]
Create any file in your gdrive account, in any folder. Then go to it from a web browser (https://drive.google.com/drive/folders/xxxx), select the file and right click with mouse then Remove. It will be sent to Trash (https://drive.google.com/drive/trash).

![](https://i.stack.imgur.com/jN4PU.jpg)

However in muCommander will still appear in folder like not Trashed.

How it works is, gdrive does not actually "remove" files from there, they just add a mark to indicate that they are trashed, but they still belong to "previous" parent. muCommander should either not display them (and have the Trash section like other file managers), or have any special color or column to indicate that the file is trashed and marked for deletion after 30 days.

**Comment by ahadas** [comment]
@superbonaci thanks for reporting this - a fix will be available in tomorrow's [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly)

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)

**Comment by superbonaci** [comment]
Thanks a lot.
