### ISSUE TITLE
NFS 2GB file size limit

### ISSUE THREAD

**Issue by vkcska** [mucommander/mucommander#855]
Files larger than 2GB cannot be copied via NFS. Copying the file works fine up to 2.0 GB, but then the speed drops to 0 and the file size does not increase. The result is the same for V2 and V3 NFS mounts.

![image](https://user-images.githubusercontent.com/70227088/213736366-9553d566-c966-43ce-b9a1-9dedc9caf8b4.png)

**Comment by ahadas** [comment]
@vkcska thanks for reporting this - it required updating the version of the 'yanfs' library we use and patching it in order to allow writing files bigger than 2GB. the fix will be available tomorrow in the [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly)

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
