### ISSUE TITLE
“muCommander.app” is damaged and can’t be opened. You should move it to the Trash

### ISSUE THREAD

**Issue by freebrowser1** [mucommander/mucommander#856]
This issue appears again.
I have mucommander 1.1.0 and issues this message.
I completely removed mucommander and reinstallled it but it persists.
After updating Java from 'System settings' the issue persists.
And the command `sudo xattr -cr /Applications/muCommander.app` does not help either.

I am running macOS Ventura 13.01 on an Intel Macbook Pro 2018.

The weird thing is that I have another Macbook Pro 2021 M1 14", also Ventura 13.01 where it runs flawlessly.

Is this app M1 / ARM64 only ?

**Comment by ahadas** [comment]
> Is this app M1 / ARM64 only ?

Nope, actually we only bundle it with Java for x64
There is [a discussion on this topic](https://github.com/mucommander/mucommander/discussions/613) so I'm closing this issue, please check that thread and comment there if it still doesn't work for you

**Comment by freebrowser1** [comment]
I uninstalled mucommander again and reinstalled it and ran 
`sudo xattr -cr /Applications/muCommander.app` 
and now it did run.

So you can close this ticket.
