### ISSUE TITLE
Preview of PDF File(s) not functional

### ISSUE THREAD

**Issue by maiemi** [mucommander/mucommander#858]
Hi there,  pre viewing a PDF File with F3 is not functional. By pressing the F3 Key, the preview is starting but the preview shows only a blanc formula. The PDF file is PDF version 1.4 with embedded graphics. The graphics are JPEG format.
Operating System is MacOS 13.2 (Ventura), muCommander is running on a MacBook Pro with Apple Silicon Chip (M1). muCommander Version is 1.1.0 build number 6fb2c42, build date 2022/10/09

**Comment by ahadas** [comment]
@maiemi thanks for reporting this. we use [icepdf](https://github.com/pcorless/icepdf) behind the scenes - can you please check the [nightly version](https://github.com/mucommander/mucommander/releases/tag/nightly) that includes an upgraded version of icepdf?

**Comment by maiemi** [comment]
hi there,please excuse my late response.Today, I was able to download the nightly build of muc.I am running a Silicon macbook pro with macOS 13.2.When I am starting muc (nightly), I get a message that the  App is broken and cannot be opened Am 04.02.2023 um 21:59 schrieb Arik Hadas ***@***.***>:﻿
@maiemi thanks for reporting this. we use icepdf behind the scenes - can you please check the nightly version that includes an upgraded version of icepdf?

**Comment by ahadas** [comment]
@maiemi ah yeah, the nightly build is not signed so you'll need to follow the steps described in [this thread](https://github.com/mucommander/mucommander/discussions/613) to install it

**Comment by ahadas** [comment]
@maiemi please check [version 1.2.0](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1) and let us know if you still see this issue
