### ISSUE TITLE
Add mucommander to awesome-mac tooling

### ISSUE THREAD

**Issue by davsclaus** [mucommander/mucommander#86]
This site has a list of great tooling for mac.

I have been using mu commander on my mac since I switched from windows many years ago, and I love it. 

I suggest maybe you can try to get it on that awesome list
https://github.com/jaywcjlove/awesome-mac

There is not many norton commander like tools anymore, and mu commander is a real time saver when working with the file system. Love that it can easily browse inside zip / tar files etc as well.

**Comment by ahadas** [comment]
Good idea!
Submitted a [pull-request](https://github.com/jaywcjlove/awesome-mac/pull/252)

**Comment by thomasuebel** [comment]
The pull request has been accepted. This issue can be closed, I take it?

**Comment by ahadas** [comment]
Right, closing.
