### ISSUE TITLE
Undo/redo functionality in text editor

### ISSUE THREAD

**Issue by d0vgan** [mucommander/mucommander#862]
I've been following this wonderful project for a long time, and I'm very glad it is getting better and better!
I have two issues regarding the editor:
1) I remember it was possible to configure an external editor for muCommander, however I don't see such ability neither in the Preferences nor in the current documentation. Could you update the documentation with detailed instruction about setting up an external editor?
2) Basically, the most significant reason for me to use an external editor for is the absence of Undo and Redo functionality in the built-in editor. Seriously, the Undo and Redo functionality is so essential and common that I could not even imagine it may be absent. Please add this to the built-in editor and it will be complete!

**Comment by pskowronek** [comment]
> 2\. Basically, the most significant reason for me to use an external editor for is the absence of Undo and Redo functionality in the built-in editor. Seriously, the Undo and Redo functionality is so essential and common that I could not even imagine it may be absent. Please add this to the built-in editor and it will be complete!

With #787 PR which brought syntax highlighting the Undo and Redo functionality has been also incorporated. It is not however visible in the menu, however it works from keyboard. Please try-out nightly and tell us what do you think.

**Comment by ahadas** [comment]
> I've been following this wonderful project for a long time, and I'm very glad it is getting better and better!

Thanks for the feedback! that's possible thanks to @pskowronek and other contributors that keep fixing the enhancing muCommander :)
 
> 1. I remember it was possible to configure an external editor for muCommander, however I don't see such ability neither in the Preferences nor in the current documentation. Could you update the documentation with detailed instruction about setting up an external editor?

Did you check out [this wiki](https://github.com/mucommander/mucommander/wiki/Custom-Commands)? just to see that this provides the information you were looking for - I don't suggest to configure an external viewer/editor with the changes that were contributed recently in that area

**Comment by d0vgan** [comment]
Yes, I saw the wiki page describing the custom commands. What I'd like to see, however, is an explicit example of setting up an external editor. For example, something like the following:
`To set up an external editor that will be invoked by pressing F4, open your file "commands.xml" and add the following section there:
 ...`
Why some explicit examples will be important is because they can show how to integrate some widely used text editors. For example, exact commands may be mentioned for such editors as `jEdit` and `VS Code`. Also, in case of Windows, `Notepad++` can be mentioned and this example should include a situation where the path to the executable contains spaces - such as `C:\Program Files\Notepad++\notepad++.exe`.

Regarding the nightly build, the updated editor is indeed very promising! I tested it with a few text files in different encodings, as well as with a few big .cpp files (200 - 300 kB). Seems to be very good!
What I did not understand, though, is why the editor proposes to save a file after the file's encoding is changed (for example, when viewing files with text in IBM866 encoding)? I mean, file encoding relates to _viewing_, it does not change the file content, so why proposing to save? And even when I press the "Save" the file, its content remains unchanged.

**Comment by pskowronek** [comment]
> It is not however visible in the menu

#863 PR provided to address this.

**Comment by d0vgan** [comment]
> > It is not however visible in the menu
> 
> #863 PR provided to address this.

I've also discovered `Ctrl+[` that goes to the matching bracket or brace. Probably there are other interesting key shortcuts to discover.

**Comment by pskowronek** [comment]
> Probably there are other interesting key shortcuts to discover.

https://github.com/bobbylight/RSyntaxTextArea/wiki/Keyboard-Shortcut-List - take a look here :)

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
