### ISSUE TITLE
Properties

### ISSUE THREAD

**Issue by Pavel00x** [mucommander/mucommander#867]
Hello,
I have a request please.
When I have information about the folder (Properties), the number contains hidden files.
Regardless of whether the display of hidden files is on or off.
Could this number contain only visible files?
Or depending on whether the display of hidden files is turned on or off.
Thank you

![Properties](https://user-images.githubusercontent.com/124076032/218055655-f36cab32-6ce7-4645-b03d-14b6fc720337.png)

**Comment by ahadas** [comment]
@Pavel00x thanks for reporting this

> Or depending on whether the display of hidden files is turned on or off. Thank you

yeah, I had a similar thought when [thinking about the default properties for file search](https://github.com/mucommander/mucommander/issues/789#issuecomment-1343477669) - I think it makes sense, this change would be available in tomorrow's [nightly build](https://github.com/mucommander/mucommander/releases/tag/nightly)

**Comment by Pavel00x** [comment]
Ahadas, thanks for your willingness.

**Comment by ahadas** [comment]
Version 1.2.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.2.0-1)
