### ISSUE TITLE
'Replace' in new editor

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#876]
Suggestion for future improvement of new text editor: Support of Replace functionality including 'replace all', 'replace current', 'find next'.

**Comment by ahadas** [comment]
@pskowronek WDYT?

**Comment by pskowronek** [comment]
I will take a look in #879

**Comment by pskowronek** [comment]
PR provided

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
