### ISSUE TITLE
Search options in new editor

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#879]
Suggestion for future improvement of new text editor: Search options, for example like in the internal editor of Double Commander.
<img width="497" alt="Search Options in Double Commander" src="https://user-images.githubusercontent.com/79788982/221508112-c6fe87b1-1503-4e66-b2ab-f6b43e3e78e9.png">

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
