### ISSUE TITLE
Cannot unpack password-protected RAR file

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#883]
muCommander does not handle password-protected files correctly. There are two different errors. It's difficult to predict which one will occur when, but one of them will always occur. Both errors have the same result: You won't get the password-protected content.

Here's a password-protected RAR file to demonstrate the error (I had to zip it, because GitHub doesn't allow the upload of RAR files): [Test.rar.zip](https://github.com/mucommander/mucommander/files/10887912/Test.rar.zip) The password is: 123

When you try to unpack the RAR file, one of the following errors will occur:

### Error 1:

muCommander will unpack the file without asking for a password. The unpacked file will have a size of 0 bytes.

### Error 2:

muCommander will show the dialog below. When you enter the correct password, muCommander will show the same dialog again, and so on.
<img width="612" alt="dialog" src="https://user-images.githubusercontent.com/79788982/222890169-96210a49-9682-4323-91e6-2fd296edea46.png">
When you press Cancel, muCommander will show the following error:
<img width="472" alt="error" src="https://user-images.githubusercontent.com/79788982/222890203-6f86a31d-6da6-44e0-a3d7-39bbeaa0acb4.png">

**Comment by ahadas** [comment]
@Andreas0602 extraction of password protected archives was added to the nightly build of v1.2.0 but it's limited to 7z or RAR v5 where also the file headers are encrypted. encryption of RAR archives can come in two forms: headers encryption and entries encryption. if you encrypt the header, you cannot browse the file without a password. if you encrypt the entries, you cannot extract the data without a password. if you encrypt both the headers and the entries you need to provide the password both for browsing and for extracting the file entries.

I looked at the file you've attached - it's a RAR v5 file in which the entry is encrypted. so you can browse the file and yeah, the data cannot be extracted without the password so the output is empty. currently, mucommander asks for a password when failing to browse the file and that password is used when browsing and extracting the file. it doesn't ask for the password when being able to browse the fail. so it seems that with the attache file you face the first error and that's the reason for it.

about the second issue, could it be that you use a RAR with lower version? I just noticed that the junrar library we use added supported for password-protected files so I can easily add it and let's see if it solves that issue? did you keep the file you saw this with?

**Comment by ahadas** [comment]
> > about the second issue, could it be that you use a RAR with lower version?
> 
> No, it‘s the newest version.
> 
> > did you keep the file you saw this with?

RAR v5?

> 
> It's the file Test.rar that I provided in my previous posting.
> 
> I can reproduce both Error 1 and Error 2 with the same file Test.rar (but not at the same time). I cannot control which of these errors will occur. It seems to be random. Error 1 occurs more often than Error 2.

yeah, that's weird

**Comment by ahadas** [comment]
ack, thanks.
I'm not exactly sure how this could happen then but I found few issues with the current mechanism for indicating that the archive is password-protected and asking for the password, so maybe by fixing those issues I'll also touch on this flow

**Comment by ahadas** [comment]
@Andreas0602 ok, if the flow involved copying the rar then the fix I merged would probably solve it - just triggered the action to create a nightly build, could you please check it out once it's ready?

**Comment by ahadas** [comment]
@Andreas0602 yes, that's a "known" issue - the current implementation handles password-protected files under the assumption that the "file headers" are also protected. It would need to be enhanced to handle such files in which entries are encrypted but the file headers are not encrypted

**Comment by ahadas** [comment]
@Andreas0602 could you please file another issue? the second error is an important one that I wanted to address before releasing 1.2.0. this feature of supporting archives in which the entries are encrypted but the headers are not encrypted is a bit more complicated and it will take me some time to get to it
