### ISSUE TITLE
When renaming a folder (or file?) over smb, to same name, but small letters, the folder is removed

### ISSUE THREAD

**Issue by soder82** [mucommander/mucommander#89]
I'm using muCommander on OSX, 10.12.4. When I'm connected to a samba share, and try to rename that folder, from like "ABC" to "abc" the folder and all it's content is getting removed.

Check this video. https://youtu.be/6dj_CugRqiQ

/Söder

**Comment by ahadas** [comment]
@soder82 thanks for reporting this! (btw, the video demonstrates this really nice)
