### ISSUE TITLE
Correct alphabetical order CZ

### ISSUE THREAD

**Issue by Pavel00x** [mucommander/mucommander#890]
Hi, I have a request.
muCommander does not sort folders (files) with the Czech alphabet correctly.
It is the same whether I have muCommnader language set to English or Czech.
See screenprints - comparison of correct alphabetical sorting from Mac Finder and wrong one from muCommander.
Is there a solution to this please?
Thanks a lot
Pavel

![alphabetical order](https://user-images.githubusercontent.com/124076032/223671704-609f204d-0a38-4b72-bad2-63d6b5c52e0b.JPG)

**Comment by ahadas** [comment]
@Pavel00x thanks for this report. yeah, we should have used [Collator](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/text/Collator.html) when sorting by file names so it would look as in file explorers in the major operating systems. it's not specific to the Czech language though so I'm taking this one - I already have a branch with few changes in this area. I'm thinking about adding another option in the preferences for a locale that will be used for this as the sorting is locale-specific (and I can imagine using English for the display and sorting by the cz locale).

and as a side note, I know we have code contributors from the Czech Republic, it's great to see more users from the Czech Republic!

**Comment by Pavel00x** [comment]
Hi Ahadas,
thanks so much for your reply and your efforts in muCommander.

**Comment by Pavel00x** [comment]
Many thanks once again.
Pavel

**Comment by Pavel00x** [comment]
Hi, I have a question about this.
Should I replace the 14 .java files (that you refer here) inside muCommander?
Or will it be from you in a future version of muCommander?
"make filenames comparing locale-sensitive"
Or am I understanding it all wrong...
Thank you

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)

**Comment by ahadas** [comment]
> Hi, I have a question about this.
> Should I replace the 14 .java files (that you refer here) inside muCommander?
> Or will it be from you in a future version of muCommander?
> "make filenames comparing locale-sensitive"
> Or am I understanding it all wrong...
> Thank you

sorry @Pavel00x , I missed that comment.. it's challenging to modify an existing version of muCommander as you described above so the right thing was to wait for version 1.3.0, and as the previous comment says - it's now available :)
