### ISSUE TITLE
muCommander Version: 1.2.0 (Portable) - artifacts on screen

### ISSUE THREAD

**Issue by anthonyrpitts** [mucommander/mucommander#895]
When using mucommander either trying to rename multiple files, it appears I am getting screen artifacts.
Different menus overlapping artifacts to various parts of the screen.

I have been able to replicate this several times. I have included my systems specs and version of Java 

**muCommander**
Version: **1.2.0 (Portable)**
Build date: **2023/03/11**
Build number: **a394a33**

**Java**
Runtime version: **17.0.6**
VM name: **OpenJDK 64-Bit Server VM**
VM version: 17.0.6+10
VM vendor: Eclipse Adoptium

OS
Name: **Windows 11**
Version: 10.0
Architecture: amd64

 **![mucommander](https://user-images.githubusercontent.com/95981408/226175539-0d8843ca-5a25-4222-a2b7-470242427843.png)**

**Comment by ahadas** [comment]
@anthonyrpitts thanks for reporting this. unfortunately, I don't have Windows 11 and this issue doesn't happen on my machine with Windows 10 so I can't change it myself - so could you try to see if this issue is specific to a L&F/Theme? you can change those in the Preferences -> Appearance tab

**Comment by pskowronek** [comment]
@ anthonyrpitts ?

**Comment by ahadas** [comment]
the version of Java that is bundled with muCommander on Windows [was upgraded to 20.0.1+9](https://github.com/mucommander/JRE/commit/f4299bd34f3ccd5f7cd1b716c9b8d268b1d373a7) in [v1.3.0](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1). there's a chance that it fixes this issue which is unlikely to be a bug in our code base but as we have not heard back from the reporter for quite some time, I'm closing this issue - feel free to reopen if it still happens with the latest version of muCommander
