### ISSUE TITLE
Symlink on sftp not working

### ISSUE THREAD

**Issue by freebrowser1** [mucommander/mucommander#904]
When I connect to an SSH server (e.g. Raspberry Pi) on which are symbolic links to folders, the folders don't open. An error appears.
I can reproduce it on any Linux server.

<img width="843" alt="Screenshot 2023-04-17 at 19 56 31" src="https://user-images.githubusercontent.com/26625141/232570482-cefeb6db-2b56-46a6-b815-038f8a9a7b0e.png">

**Comment by ahadas** [comment]
@freebrowser1 I can't reproduce this with version 1.2.0 - I'm able to browse symlinks to folders on an SSH server (installed with centos stream 8) well. it makes sense that the copy action fails on your server - looking at the icon of the links `Videos` and `Music`, it shows that muCommander thinks those links are broken. which version do you use? can you share more information on how to reproduce it, do the links behave well from the command line?
