### ISSUE TITLE
feature request : panel to quickly access bookmarks

### ISSUE THREAD

**Issue by olduh29** [mucommander/mucommander#909]
Hello,

Could it be possible to add a panel (on the left side maybe) with the list of bookmarks. i personally find boring to have to move the mouse to menu then bookmarks then my mark. A panel with the list may be easier and quicker to access.
this is my personal state of cours. feel free to reject.

thanks for this tools,

Olivier

**Comment by ahadas** [comment]
@olduh29 hi, did you check the quick-list of bookmarks? its keyboard shortcut defaults to ALT+4

**Comment by olduh29** [comment]
thanks for your answer. this answers to my need.
