### ISSUE TITLE
Error: private method `download_name' called

### ISSUE THREAD

**Issue by georgjaehnig** [mucommander/mucommander#918]
I'm trying to install with Homebrew

    brew install --cask mucommander

and get

    Error: private method `download_name' called for #<Cask::Download:0x000000010326e270>
    Did you mean?  downloader
    Do not report this issue until you've run `brew update` and tried again.
    /opt/homebrew/Library/Homebrew/exceptions.rb:612:in `initialize'
    /opt/homebrew/Library/Homebrew/downloadable.rb:89:in `new'
    /opt/homebrew/Library/Homebrew/downloadable.rb:89:in `rescue in fetch'
    /opt/homebrew/Library/Homebrew/downloadable.rb:86:in `fetch'
    /opt/homebrew/Library/Homebrew/cask/download.rb:51:in `fetch'
    /opt/homebrew/Library/Homebrew/cask/installer.rb:174:in `download'
    /opt/homebrew/Library/Homebrew/cask/installer.rb:69:in `fetch'
    /opt/homebrew/Library/Homebrew/cask/installer.rb:100:in `install'
    /opt/homebrew/Library/Homebrew/cmd/install.rb:237:in `block in install'
    /opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `each'
    /opt/homebrew/Library/Homebrew/cmd/install.rb:228:in `install'
    /opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'

(Yes, I also tried `brew update`. No change afterwards.)

**Comment by pskowronek** [comment]
Shouldn't be reported to homebrew?
Other apps install well via homebrew?

**Comment by georgjaehnig** [comment]
> Shouldn't be reported to homebrew?

Ah true, possibly. :)

> Other apps install well via homebrew?

Yes.

Just noticed, Homebrew seems to have an [issue with mucommanders versioning](https://github.com/Homebrew/homebrew-cask/pull/144970).

**Comment by ahadas** [comment]
Yeah, another reason to release 1.3.0 soon :)

**Comment by ahadas** [comment]
Apparently it was already resolved for v1.2.0 in Homebrew by https://github.com/Homebrew/homebrew-cask/pull/148555 and it's also fixed now for v.1.3.0 by https://github.com/Homebrew/homebrew-cask/pull/150626
