### ISSUE TITLE
Remove obsolete code!

### ISSUE THREAD

**Issue by aadrian** [mucommander/mucommander#92]
Please remove the obsolete code: there seems to be allot of hacks and functionality for old OSes (e.g. Win95 or old OSX versions) that's not required anymore.

Thank you.

**Comment by aadrian** [comment]
Also please remove old Java code (and checking), since mucommander now requires Java8.

**Comment by ahadas** [comment]
Good idea. The master branch has been cleaned from code for Java < 8 and for unsupported operating systems (the `compile.txt` file was already replaced by more up-to-date resources). Thanks for reporting this!

**Comment by ahadas** [comment]
Version 1.0.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.0.0-1)
