### ISSUE TITLE
I have completed the Korean translation of the dictionary in Zanata.

### ISSUE THREAD

**Issue by yi-yunseok** [mucommander/mucommander#923]
When it is applied, I will re-work again to complete the Korean translation asap.

**Comment by ahadas** [comment]
thanks @yi-yunseok, I'm afraid that the translations in Zanata are not up to date, sorry about that - I should have updated the documentation. could you please check the [translation file](https://github.com/mucommander/mucommander/blob/master/mucommander-translator/src/main/resources/dictionary_ko.properties) and change it directly instead?
