### ISSUE TITLE
Cannot enter 'pipe' and other symbols in terminal on Mac with German keyboard

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#933]
I cannot enter the 'pipe' symbol `|` in the built-in terminal on a Mac with German keyboard. When I go to the terminal by pressing F12 and then press `Option + 7`, nothing will happen. In Apple's Terminal.app, it does work. Also, it does work in muCommander in the 'Find' dialog or when renaming a file, but it does not work in muCommander's terminal. The following symbols don't work either: `{`, `}`, `[`, `]`. This severely limits the usefulness of muCommander's terminal.

<img width="572" alt="Screenshot_2023-05-14_11-53-25" src="https://github.com/mucommander/mucommander/assets/79788982/c09629b3-d3d3-47fc-8d3a-10e9599789d6">

**Comment by pskowronek** [comment]
Can you try cloning this repo https://github.com/JetBrains/jediterm and run `./jediterm.sh` - are you able to reproduce the problem in their terminal?

**Comment by pskowronek** [comment]
hmm, I've switched input to German and yes, I can reproduce the problem in muC, but also in jeditem master:

![obraz](https://github.com/mucommander/mucommander/assets/360665/801ee1f3-fc22-4a44-b654-64f24fac1e00)

This what happens when I hit `Option + 7` either via keyboard or virtual keyboard on the screen.

**Comment by pskowronek** [comment]
In Idea the had similar problems (umlauts, pipes etc): https://youtrack.jetbrains.com/issue/IDEA-115276 - JDK update apparently fixed the problem there.

**Comment by pskowronek** [comment]
btw, I can this behavior on macOS Terminal when I turn on `Use Option as Meta key` in terminal preferences (see https://osxdaily.com/2013/02/01/use-option-as-meta-key-in-mac-os-x-terminal/)

**Comment by pskowronek** [comment]
`Arg 7` shows only on `bash` imho, on `zsh` is not shown - but the effect is the same (letter multiplied 7 times).

As it comes to my setup - mac laptop with built-in keyboard, right Option works always when it comes to pipe and DE.

**Comment by pskowronek** [comment]
btw, do you use German or German Standard layout?

**Comment by pskowronek** [comment]
![obraz](https://github.com/mucommander/mucommander/assets/360665/9135153f-2950-4bc1-b5b4-07dd2a72dd04)

But I guess it is `German` - only there option-7 should produce pipe

**Comment by pskowronek** [comment]
There must be sth in mac preferences for adding keyboard input sources (i don't have Ventura near by to check where it is exactly).

**Comment by pskowronek** [comment]
And, on mac 2, do you have this problem with Terminal opened via F12 or via `Run Command` (CMD+R)?

**Comment by pskowronek** [comment]
In IntelliJ IDEA they applied 'workaround' ("Use Option as Meta key" option) this way: https://github.com/JetBrains/intellij-community/blob/305571a6286b419ac4e255bf47dce00280cbc837/plugins/terminal/src/org/jetbrains/plugins/terminal/exp/TerminalEventsHandler.kt#L85

**Comment by pskowronek** [comment]
@Andreas0602 can you check if it fixes the problem on your both macs? PR: https://github.com/mucommander/mucommander/pull/935

If all those umlauts, pipes work for you (using both Option/alt keys)?

**Comment by pskowronek** [comment]
Great to hear that.

However, we need to introduce a new preference option then :/ Just like they did in Intellij IDEA - see last comment [here](https://youtrack.jetbrains.com/issue/IDEA-274617/Typing-Option-digit-in-Terminal-doesnt-show-alternate-character).

Any thoughts, objections? @Andreas0602 , @ahadas ?

**Comment by pskowronek** [comment]
> @pskowronek, your fix does work on my 1st and 2nd Mac, with both left and right Option key. Also other "difficult" characters like ~äöüÄÖÜß^\ work fine. Thank you, well done!

hmm, strange - tried umlauts and they don't work for me...  and what's even worse, I cannot enter any Polish diacritics - with and without a fix. I'm lost :)

**Comment by pskowronek** [comment]
ok, so, a proper LC_ALL env variable matters! 
If I run muC with LC_ALL set to `de_DE.UTF-8` then it works for DE and PL with a fix.

**Comment by pskowronek** [comment]
so, on my env if LC_ALL is not set the following one is being produced by muC for terminal: `LC_ALL=en_PL.UTF-8` - this breaks Polish diacritics.  I will take a look at that later.

For now in a moment I will provide a final PR for DE issue - @Andreas0602, can you test it thoroughly?
I set this preference to false by default, that means it changes the behavior from previous muC version. I hope this is OK.

**Comment by pskowronek** [comment]
> 2\. For example, instead of `ä`, `a ̈` will be shown. In Apple's Terminal.app, filenames with German umlauts are shown correctly.

I observed something similar with Polish diacritics when I was navigating through volume that was mounted from bundle spares, on regular macOS volume it worked well. Something tells me that it might be related to #898.

**Comment by pskowronek** [comment]
> > 2. When executing the "ls" command in a directory containing files whose names contain German umlauts, two combined characters will be shown instead of the correct one. For example, instead of `ä`, `a ̈` will be shown. In Apple's Terminal.app, filenames with German umlauts are shown correctly.
> 
> > By the way, muCommander's internal editor also has problems with such filenames.
> 
> Unfortunately, both problems still exist with macOS 13.4.

can you create a separate bug for it?

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
