### ISSUE TITLE
[macOS] Internal terminal displays filenames with German umlauts incorrectly

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#940]
On macOS, when executing the `ls` command in a directory containing files whose names contain German umlauts, two combined characters will be shown instead of the correct one.

Example:

- In the Finder, create a new folder with the name `München`.
- In muCommander's internal terminal, run the command `ls`.

Result:

<img width="72" alt="Screenshot_2023-05-18_22-19-59" src="https://github.com/mucommander/mucommander/assets/79788982/bf1b8fba-e627-43f7-9611-964eb76044dd">

**Comment by pskowronek** [comment]
> files whose names contain German umlauts, two combined characters will be shown instead of the correct one

On the newest macOS version and on Catalina while using `sparse bundles`.

**Comment by pskowronek** [comment]
https://github.com/mucommander/mucommander/issues/941#issuecomment-1555274496

**Comment by pskowronek** [comment]
@Andreas0602, PR provided: https://github.com/mucommander/mucommander/pull/944 - can you check it?
I've built it with java 20 and all those files displayed correctly in terminal via vim/cat: a.txt and ls.txt, plus `ls` works OK (on my special volume where I kinda reproduced the problem with diacritics)

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
