### ISSUE TITLE
[macOS] "Home", "End", "Page Up", "Page Down" keys do not work in terminal

### ISSUE THREAD

**Issue by ghost** [mucommander/mucommander#942]
On macOS, in muCommander's internal terminal, the keys "Home", "End", "Page Up", "Page Down" do not work. In Apple's Terminal.app, they do work.

**Comment by pskowronek** [comment]
@Andreas0602 please check if this problem is still there in this PR: #944

**Comment by pskowronek** [comment]
@Andreas0602  - pls re-check with this PR: #946

**Comment by pskowronek** [comment]
@Andreas0602 Tested with apple extended (i.e. with num keys) keyboard and it works. PgUp and PgDwn - but you have to press shift, Home/End no problem. Kb layout looks like this:
![obraz](https://github.com/mucommander/mucommander/assets/360665/ac09386f-259f-44c9-af9f-b157761b0a60)

Tested on PL and DE keyboard settings.

Can you tell me what keyboard you're exactly using and what key combination (if required)?

**Comment by pskowronek** [comment]
what about iTerm2?

**Comment by pskowronek** [comment]
So, what I would suggest is to propose such a feature - close this bug and in this feature reference it (to have a clarity and concentrate on that feature).
