### ISSUE TITLE
Font preferences for Shell not used in Terminal

### ISSUE THREAD

**Issue by pskowronek** [mucommander/mucommander#945]
The following Font preferences for Shell not used in Terminal:
![obraz](https://github.com/mucommander/mucommander/assets/360665/fb377219-1025-41f2-9619-1c8fadf4a23d)

And I guess shell history is gone when JediTerm was integrated as Run command replacement?

**Comment by pskowronek** [comment]
@Andreas0602 can you confirm that?

**Comment by pskowronek** [comment]
PR provided

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
