### ISSUE TITLE
[macOS] Faulty behavior of the terminal after pasting

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#947]
The terminal behaves faulty after something has been pasted from the clipboard.

Steps to reproduce:

1. Copy the following command into the clipboard (i.e. select the whole line and press command+C):
`git clone --recurse-submodules git@github.com:mucommander/mucommander.git && cd mucommander && ./gradlew dmg`
2. In muCommander, open the terminal (F12) and press command+V. Note that the text you've just pasted is selected/highlighted.
3. Try to replace the word "dmg" at the end of the command with the word "run".

**Expected behavior:** You can normally edit the command (e.g like in Apple's terminal).

**Actual behavior:** When you press the "cursor left" key, you'll get two versions of the command: The first one is selected/highlighted, the second one is normal. The second one partly overwrites the first one.

Please see the video below:

https://github.com/mucommander/mucommander/assets/79788982/c84500ac-18c2-4f8b-a55a-1e288b07837f

**Comment by pskowronek** [comment]
I guess the bumped version of JediTerm 3.17 is either broken or it is not correctly embedded in muC.

The following problems I found:
1. when you extend the width of the term window and press space then at some point (way before reaching the length of the window) the cursor returns back without moving to a new line - this problem cause the problem with pasting (at least for me, when using `bash` and cmd+V)
2. when you press a letter, like `u` or `z` it doesn't repeat but a suggestion for diacritics appear.... (maybe a feature or a bug? to be investigated).

**Comment by pskowronek** [comment]
> > 2. when you press a letter, like `u` or `z` it doesn't repeat but a suggestion for diacritics appear.... (maybe a feature or a bug? to be investigated).
> 
> I don't have that problem.

try to switch to `Polish Pro` and retry in muC?


> When you build and run JediTerm 3.17 by means of the command
> 
> `git clone --recurse-submodules git@github.com:JetBrains/jediterm.git && cd jediterm && ./jediterm.sh`
> 
> then there are no problems with pasting.

yup, I will investigate this.

**Comment by pskowronek** [comment]
PR #946  updated to address this problem. @Andreas0602  pls check.

**Comment by pskowronek** [comment]
> > try to switch to Polish Pro and retry in muC?
> 
> I just tried it, but I still don't have that problem.

FYI, it is macOS setting: https://stackoverflow.com/questions/15107321/intellij-idea-auto-repetition-of-letter-keys
One can disable this behavior globally with: `defaults write -g ApplePressAndHoldEnabled -bool false`
Just in case if somebody was to stamp on it.

**Comment by ahadas** [comment]
regression in 1.3.0 build
