### ISSUE TITLE
[macOS] "Run command" does not launch the terminal

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#948]
Please see the video below:

https://github.com/mucommander/mucommander/assets/79788982/9d546082-b612-4350-86c4-b4203b6e5add

**Comment by pskowronek** [comment]
good catch, that happened after bumping to the newest JediTerm. Fix is coming, probably will be done to #946

**Comment by pskowronek** [comment]
PR updated with fix to this issue

**Comment by ahadas** [comment]
regression in 1.3.0 build
