### ISSUE TITLE
Google Drive: Feature request: Please add support for "Shared with me" files

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#949]
I just noticed that muCommander allows me to mount and access my files on Google Drive as though they were local. Very nice! However, it does not show files and directories that others have shared with me. Other tools, like CloudMounter, do provide this functionality (though they're not muCommander...), so can I put in a request for adding this functionality to muCommander? Then I'll never need to use the Web interface again!

Thanks!

Richard Stanton

**Comment by ahadas** [comment]
thanks for reporting this @rhstanton!

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
