### ISSUE TITLE
Google drive: Cannot see Google-specific files

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#950]
When I access my Google Drive account from mu Commander, I can see most of my files, but *not* Google-specific files like those with extensions .gdoc, .gslides, and .gsheet. Could these be made visible? Thanks!

**Comment by ahadas** [comment]
@rhstanton yeah, they were filtered out because they cannot be downloaded like ordinary files - but now (in v1.3.0 and as from tomorrow's nightly build) they will be visible and downloaded in their corresponding OpenDocument format (odt, ods or odp, respectively)

**Comment by ahadas** [comment]
> Excellent! Thanks a lot. I assume this is not bidirectional, right?

right, the other way around wasn't implemented - it's more complicated since one may want to keep the original format of the file (e.g., odp) when uploading it, but we can think about it a bit more, please file an issue if you're interested in this

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
