### ISSUE TITLE
Please provide key mapping capabilities for terminal like in iTerm2

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#952]
It would be great if muCommander's internal terminal had the same key mapping capabilities as iTerm2. This would, for example, solve the issue #942, and it would also be useful for other purposes.

**Screenshots from iTerm2:**
<img width="897" alt="1" src="https://github.com/mucommander/mucommander/assets/79788982/e6463747-9075-4d5e-9c50-1e1519c6e029">
<img width="897" alt="2" src="https://github.com/mucommander/mucommander/assets/79788982/142f1d56-48fa-4088-8f9f-b814b13158f6">
<img width="897" alt="3" src="https://github.com/mucommander/mucommander/assets/79788982/010e3bc5-54df-48b8-ba0c-4dc21c37f7ed">
<img width="897" alt="4" src="https://github.com/mucommander/mucommander/assets/79788982/be7ae70d-c994-4301-8ead-d2352a16b6d7">

**Comment by pskowronek** [comment]
So, the question if it should be added the existing `Preferences -> Shortcuts` or a new separate place?
For the former, some 'shortcuts' aka key combinations can conflict with existing ones - we would need to ignore that for Terminal - and I don't like that. I would be more into the latter solution (partially reusing the Shortcuts form if possible).

**Comment by ahadas** [comment]
@pskowronek I find it confusing to have two different dialogs for shortcuts - it makes it look like the terminal is not really well integrated into muCommander. I'd rather prefer to have it in the existing shortcuts dialog under a new category, and yeah - we'll need to figure out how to ignore conflicts with non-terminal actions

**Comment by pskowronek** [comment]
What about a separate preference tab "Terminal" where all the possible things could be configured there, like the recent Option as Alt, bell on/off, color inversion for selection etc ... and finally key bindings - and in case of Terminal, these aren't shortcuts per se, these are more key bindings for its actions like PgUp.

When it comes to colors - we already have it under Theme, so we could have a "link" to switch to Theme pref -> Terminal if "inverse colors" is off.

Just thinking out loud - right now I don't have preference between these two alternatives.

**Comment by ahadas** [comment]
@pskowronek yeah, there're also arguments for having a separate tab for the terminal but I think that if we go with this approach, it makes the UI more cumbersome. in my opinion, having a category of terminal shortcuts in the preferences->shotcuts tab is equivalent to the Terminal tab we have in the Theme editor dialog

**Comment by pskowronek** [comment]
Yes, I meant to implement that. But so far so good, right?

**Comment by pskowronek** [comment]
> does not fit well into the existing Shortcuts panel.

what do you mean? That only 5 actions can be redefined (JediTerm I think doesn't allow for more just like that).

**Comment by pskowronek** [comment]
> 



> Following these orders means to put the modifiers into the Shortcuts dialog, right? I guess it could be done technically, but is it good logically? Is it good to put items of different kind into the same dialog?

yup, "in my opinion, having a category of terminal shortcuts in the preferences->shotcuts tab is equivalent to the Terminal tab we have in the Theme editor dialog" - there was no more discussion/argue about it, then 'the order was sealed' :)

**Comment by pskowronek** [comment]
> However, the problem is that theses keys have stopped working in muCommander's file panel. Pressing them has no effect, except that the following error message occurs in the terminal in which muCommander has been compiled and run:

PR updated

**Comment by pskowronek** [comment]
Strange, I cannot reproduce this....

**Comment by pskowronek** [comment]
Ok, I can reproduce - you need to close Prefs and re-open to see that shortcut disappeared.

**Comment by pskowronek** [comment]
PR updated. @Andreas0602  - pls check. I guess it could have been slightly randomish to reproduce (depending on the order returned by Map).

**Comment by pskowronek** [comment]
done via  #967

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
