### ISSUE TITLE
[Bug] Wrong architecture in About muCommander dialog

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#962]
### Description

Wrong architecture shown in About muCommander dialog. See details below.

### Steps to reproduce

On an iMac with Apple M1 chip, open the About muCommander dialog.

### Expected behavior

"Architecture: Apple M1" or something similar is shown.

### Actual behavior

"Architecture: x86_64" is shown.

### Screenshots?

<img width="1047" alt="snagit" src="https://github.com/mucommander/mucommander/assets/79788982/efc21ad7-54e6-4932-b015-ef394de34694">

### muCommander version

muCommander
Version: 1.3.0
Build date: 2023/05/26
Build number: c57a8d6

### Java version

Java
Runtime version: 20
VM name: OpenJDK 64-Bit Server VM
VM version: 20+36
VM vendor: Eclipse Adoptium

### Operating System type and version

OS
Name: Mac OS X
Version: 13.4
Architecture: x86_64   // Wrong!

**Comment by ahadas** [comment]
@Andreas0602 that's something we get from the JVM so it's probably a result of using the x64 version of the JDK. unfortunately, I don't have a machine to sign the dmg for aarch64 on. I can create an unsigned nightly version with Java for aarch64 but would you use it?

**Comment by pskowronek** [comment]
I don't have Apple silicon either. Do you have logs of "but the app terminated itself within less than one second after starting"?  Maybe try running with `./gradlew clean run` and send us the console output.

**Comment by ahadas** [comment]
@Andreas0602 yeah, you can find the bundled Java versions [here](https://github.com/mucommander/JRE)

**Comment by ahadas** [comment]
@Andreas0602 can you give mucommander-1.4.0-snapshot-aarch64.dmg from [here](https://github.com/mucommander/mucommander/actions/runs/8498773909) a try please?

**Comment by ahadas** [comment]
@Andreas0602 ack, thanks
I was about to make another change and saw that [macos-latest changed yesterday to macOS 14](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/) (that runs on M1), can you please check the dmg for aarch64 from [here](https://github.com/mucommander/mucommander/actions/runs/8515709555)?

**Comment by ahadas** [comment]
@Andreas0602 and the one from [here](https://github.com/mucommander/mucommander/actions/runs/8520258708)?

**Comment by ahadas** [comment]
> > @Andreas0602 and the one from [here](https://github.com/mucommander/mucommander/actions/runs/8520258708)?
> 
> @ahadas, @pskowronek, that works much better. It starts and works well.

great!

> However, there's one issue: In the "Open with" dialog, there's an entry "Enable apps here?" I do have installed the duti tool properly on my system. When I type `duti -h` in the terminal, the duti tool is properly started and shows its usage hints. But muCommander doesn't seem to find the duti tool. mucommander.log also contains the following errors:
> 
> 2024-04-02 11:37:20.573 [WT-EventQueue-0] ERROR c.m.desktop.macos.OSXDesktopAdapter:264 - Error finding default shell for user, going to use a default one 2024-04-02 11:37:20.573 [WT-EventQueue-0] ERROR c.m.desktop.macos.OSXDesktopAdapter:495 - Error executing command: /bin/bash. Error msg: Cannot run program "/bin/bash": error=0, posix_spawn failed java.io.IOException: Cannot run program "/bin/bash": error=0, posix_spawn failed
> 
> [mucommander.log](https://github.com/mucommander/mucommander/files/14834589/mucommander.log)

@pskowronek can you please take a look at this?

> Yet another problem: When I double-click a dmg file in muCommander, I get this error: <img alt="Bildschirmfoto 2024-04-02 um 12 05 13" width="472" src="https://private-user-images.githubusercontent.com/79788982/318735829-7170f8e5-0e05-4977-aca8-2017903e599e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTI2ODksIm5iZiI6MTcxMjA1MjM4OSwicGF0aCI6Ii83OTc4ODk4Mi8zMTg3MzU4MjktNzE3MGY4ZTUtMGUwNS00OTc3LWFjYTgtMjAxNzkwM2U1OTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEwMDYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmNDkyZTQyODc1ZjczYTk0OTZiY2NjMGQ5ZTFiY2I5NjczMmE0NDMyNjE4MDAxZTE2MWFiYTE3Y2Q3NDY2YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.257Jt2O9gQhKQf6nb0Le1QkYv95LDC1reyWvcyQCGOg">

this could be a consequence of not signing the dmg, I plan to release 1.4 with a signed dmg so we'll check it then

**Comment by ahadas** [comment]
@Andreas0602 could you please attach the log?

**Comment by pskowronek** [comment]
@ahadas / @Andreas0602  - leaving you for 12h and all the problems appear!

However, in both logs (the one for duti and double-click) I see this:
```
2024-04-02 11:37:18.346 [WT-EventQueue-0] INFO  c.m.commons.file.CachedFile:170 - Error while allowing access to java.io.FileSystem
java.lang.NoSuchFieldException: fs
        at java.base/java.lang.Class.getDeclaredField(Unknown Source)
        at com.mucommander.commons.file.CachedFile.<clinit>(CachedFile.java:151)
        at com.mucommander.ui.main.table.FileTableModel.setCurrentFolder(FileTableModel.java:229)
        at com.mucommander.ui.main.table.FileTable$FolderChangeThread.run(FileTable.java:1864)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
       .... cut
```

As you mentioned @ahadas, it might be related to unsigned app.

@Andreas0602 - can you check in muC terminal what shell was used? I dunno, `ps -p $$` and `echo "$SHELL"`? I think it started with bash, hence you see 'bash' errors (due to security reasons behind unsigned app?). Additionally in log I see:
`2024-04-02 11:37:20.573 [WT-EventQueue-0] ERROR c.m.desktop.macos.OSXDesktopAdapter:264 - Error finding default shell for user, going to use a default one`. Probably due to sec reasons muC was unable to probe `zsh` or whatever you set as favorite shell.

@ahadas - can you try to sign the app, release something like pre-alpha? I could ask friends to check on Apple Silicon (my macbooks are still intel only).

**Comment by ahadas** [comment]
> @ahadas / @Andreas0602 - leaving you alone for 12h and all the problems appear!

:laughing: 

> > @ahadas - can you try to sign the app, release something like pre-alpha? I could ask friends to check on Apple Silicon (my macbooks are still intel only).
> 
> After installing the muCommander snapshot, I was able to execute it without running `sudo xattr -cr /Applications/muCommander.app` beforehand. Therefore I guess the app was already signed. @ahadas please correct me if I'm wrong.

that's interesting, no - the dmg is not signed at this point

> @ahadas, here is the log after double-clicking a png file:
> 
> [mucommander.log](https://github.com/mucommander/mucommander/files/14835363/mucommander.log)

thanks, ok, I think I see what's going on - [File#fs was renamed to File$FS](https://github.com/mucommander/jdk/commit/079255e312a60584d748babcd320eacec99c5a02), I'll post a fix

**Comment by pskowronek** [comment]
> When I execute `echo $PATH` in the muC terminal, the path does **not** contain `/opt/homebrew/bin:/opt/homebrew/sbin`. Therefore, I guess that the muC terminal uses bash, not zsh.

yup, it used `bash` because there was a problem executing anything to check if `zsh` exists, the or `duti` :)

**Comment by ahadas** [comment]
> > @ahadas, here is the log after double-clicking a png file:
> > [mucommander.log](https://github.com/mucommander/mucommander/files/14835363/mucommander.log)
> 
> thanks, ok, I think I see what's going on - [File#fs was renamed to File$FS](https://github.com/mucommander/jdk/commit/079255e312a60584d748babcd320eacec99c5a02), I'll post a fix

@Andreas0602 can you try the dmg from [here](
https://github.com/mucommander/mucommander/actions/runs/8577381796) please?

**Comment by ahadas** [comment]
> > > > @ahadas, here is the log after double-clicking a png file:
> > > > [mucommander.log](https://github.com/mucommander/mucommander/files/14835363/mucommander.log)
> > > 
> > > 
> > > thanks, ok, I think I see what's going on - [File#fs was renamed to File$FS](https://github.com/mucommander/jdk/commit/079255e312a60584d748babcd320eacec99c5a02), I'll post a fix
> > 
> > 
> > @Andreas0602 can you try the dmg from [here](https://github.com/mucommander/mucommander/actions/runs/8577381796) please?
> 
> @ahadas, the same problem still exists. Here is the log after double-clicking a txt file: [mucommander.log](https://github.com/mucommander/mucommander/files/14892850/mucommander.log)

ack, I merged [a fix for that error](https://github.com/mucommander/mucommander/pull/1142) but while testing it now on my (x64) machine, I encountered a different error - I'll take a look at it later

**Comment by ahadas** [comment]
ok, I fixed the aforementioned issue, @Andreas0602 can you please check the dmg from [here](https://github.com/mucommander/mucommander/actions/runs/8582104776)?

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
