### ISSUE TITLE
[Enhancement] Rename "Run command"

### ISSUE THREAD

**Issue by ghost** [mucommander/mucommander#974]
### Description

I would suggest to rename "Run command".

<img width="192" alt="Bildschirmfoto 2023-06-08 um 08 42 34" src="https://github.com/mucommander/mucommander/assets/79788982/d51f3908-66a6-4ba8-9d98-46a61e3cf5e2">

It doesn't run just a single command. It opens a separate terminal window, so "Open Terminal window" would be more appropriate in my opinion.

**Comment by pskowronek** [comment]
However, @Andreas0602 , the point is still sound - the naming should be probably changed?
