### ISSUE TITLE
[Enhancement] Use Menlo instead of Lucida Grande as default font in Terminal on macOS

### ISSUE THREAD

**Issue by Andreas0602** [mucommander/mucommander#976]
### Description

On macOS, Lucida Grande looks odd in the terminal, probably because it's proportional, not monospaced. Menlo should be used instead as default font.

### Lucida Grande:

<img width="1191" alt="Lucida Grande" src="https://github.com/mucommander/mucommander/assets/79788982/dc859bc0-d3fd-4ed9-b31c-0e2cfda824d3">

### Menlo:

<img width="1191" alt="Menlo" src="https://github.com/mucommander/mucommander/assets/79788982/a6ad4b93-8f7d-4c1c-823b-ef82bbbc664e">

**Comment by pskowronek** [comment]
PR provided (#978)

**Comment by pskowronek** [comment]
Any chance to check it on Windows/Linux? @Andreas0602 ?

**Comment by pskowronek** [comment]
I have a problem building MSI :/

**Comment by ahadas** [comment]
> I have a problem building MSI :/

yeah, easier to let the automated action do that

**Comment by ahadas** [comment]
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)
