### ISSUE TITLE
license.txt missing

### ISSUE THREAD

**Issue by Marzona** [mucommander/mucommander#98]
Hello,

in Readme.md it is mentioned that the tool is released under GPL and there is written to check license.txt bundled with the program, but I can't find license.txt file.

Will you be so kind to add this file to the package?

**Comment by ahadas** [comment]
Hi @Marzona ,
The license is supposed to be in every package of muCommander already, may I ask which package are you using? for which operating system?

**Comment by Marzona** [comment]
ah I found it in the package folder, thanks. From the readme.md file I was expecting to find it in the root of the repo.

I am fine now, thanks for the support.

**Comment by ahadas** [comment]
Cool. I also added a link to that file in README.md to make it easier to find.
