### ISSUE TITLE
macOS install: "muCommander" is damaged and can't be opened

### ISSUE THREAD

**Issue by rhstanton** [mucommander/mucommander#999]
### Description

I just installed the new version, 1.3.0-1, on my Mac, and when I try to run it I get the error message

"muCommander" is damaged and can't be opened. You should move it to the Trash

This used to happen all the time in the past, but I thought it had gone away with recent versions.

### Steps to reproduce

Install muCommander 1.3.0-1 on macOS, then try to run it.

### Expected behavior

It should run.

### Actual behavior

I get the error message listed above.

### muCommander version

1.3.0-1

### Java version

I can't run muCommander to get this output, but I don't think it's Java-related.

### Operating System type and version

macOS 12.6.7

**Comment by ahadas** [comment]
ah right, I should have written it as a known issue but I found that I won't be able to sign the dmg too late in the release process - so version 1.3.0 cannot be installed like the last few versions. I don't have a machine that I can try this on but there's [this user guide](https://support.apple.com/lv-lv/guide/mac-help/mh40616/mac) that should help with installing an app from unidentified developer on macOS Ventura

**Comment by rhstanton** [comment]
Those instructions don't work for me, I'm afraid. After installing, I then need to run the command

sudo xattr -cr /Applications/muCommander

Then muCommander works fine.

**Comment by ahadas** [comment]
> Those instructions don't work for me, I'm afraid. After installing, I then need to run the command
> 
> sudo xattr -cr /Applications/muCommander
> 
> Then muCommander works fine.

thanks for the follow up @rhstanton, could you please share what's the version of your operating system?

**Comment by ahadas** [comment]
> > Those instructions don't work for me, I'm afraid. After installing, I then need to run the command
> > sudo xattr -cr /Applications/muCommander
> > Then muCommander works fine.
> 
> thanks for the follow up @rhstanton, could you please share what's the version of your operating system?

ok, I asked this because it didn't work for another user - but apparently what blocked him is that there was no permissions for the terminal to access files in /Applications/muCommander.app
I'll document this procedure then

**Comment by andrus-k** [comment]
"muCommander" is damaged and can't be opened. You should move it to the Trash
12.6.7
?

**Comment by sebastian-lempert** [comment]
Same for me on macOS Ventura 13.4.1 (22F82).

In the past [this guide](https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat) helped me when encountering this problem, but unfortunately with muCommander version 1.3.0-1 it doesn't work anymore.

The same applies for the tip of @rhstanton, so using `sudo xattr -cr /Applications/muCommander` doesn't work for me either.

**Comment by ahadas** [comment]
@sebastian-lempert it worked for @danielerez with 13.4.1 (22F82) - does it fail for you on `xattr: [Errno 1] Operation not permitted`? if so, please make sure that the terminal has permission on these files

**Comment by sebastian-lempert** [comment]
> @sebastian-lempert it worked for @danielerez with 13.4.1 (22F82) - does it fail for you on `xattr: [Errno 1] Operation not permitted`? if so, please make sure that the terminal has permission on these files

No, I have granted the needed permissions to Terminal as described in this [guide](https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update), so this is not the problem.

**Comment by sebastian-lempert** [comment]
> > "muCommander" is damaged and can't be opened. You should move it to the Trash
> > 12.6.7
> > ?
> 
> that's the version I have, it worked for me with: `xattr -dr com.apple.quarantine /Applications/muCommander.app`

The command `sudo xattr -rd com.apple.quarantine /Applications/muCommander.app` is part of the first guide that I referenced in my first post. This one didn't work for me as well (although it worked for versions < 1.3.0-1).

**Comment by ahadas** [comment]
> > @sebastian-lempert it worked for @danielerez with 13.4.1 (22F82) - does it fail for you on `xattr: [Errno 1] Operation not permitted`? if so, please make sure that the terminal has permission on these files
> 
> No, I have granted the needed permissions to Terminal as described in this [guide](https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update), so this is not the problem.

@danielerez did you do any other magic to make it work on 13.4.1 (22F82)?

**Comment by danielerez** [comment]
> > > @sebastian-lempert it worked for @danielerez with 13.4.1 (22F82) - does it fail for you on `xattr: [Errno 1] Operation not permitted`? if so, please make sure that the terminal has permission on these files
> > 
> > 
> > No, I have granted the needed permissions to Terminal as described in this [guide](https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update), so this is not the problem.
> 
> @danielerez did you do any other magic to make it work on 13.4.1 (22F82)?

So I've just added the Terminal under Settings>Privacy & Security>App Management.
Restarted the Terminal, and then: sudo xattr -cr /Applications/muCommander.app

**Comment by mu-citizen** [comment]
> So I've just added the Terminal under Settings>Privacy & Security>App Management. Restarted the Terminal, and then: sudo xattr -cr /Applications/muCommander.app

I had the same problem as sebastian-lempert, but thanks, it helped me!

Just a quick question, how can I use the "Open with..." command? I've never could use it (it was grayed out), now this new version says "Enable apps here" and "The "duti" tool must be present on PATH...".
I'm not a coder... is is so hard to write it in the Settings, or somewhere, where I could connect extensions with programs? Or take the same "Open with" as in Finder?

**Comment by pskowronek** [comment]
> I'm not a coder... is it so hard to write it in the Settings, or somewhere, where I could connect extensions with programs? Or take the same "Open with" as in Finder?

The info states as follows:
```The "duti" tool must be present on PATH
It can be installed via homebrew, macports, fink, etc. ```

You don't need to be coder - there's enough information to let you google it out. Just install `duti` using either homebrew, macports or fink. 

> Or take the same "Open with" as in Finder?

This is what `duti` is being used for - to get the list of apps for extensions :)

Try it out - you'll be happy :)

**Comment by ahadas** [comment]
> > So I've just added the Terminal under Settings>Privacy & Security>App Management. Restarted the Terminal, and then: sudo xattr -cr /Applications/muCommander.app
> 
> I had the same problem as sebastian-lempert, but thanks, it helped me!

thanks for the feedback @mu-citizen! (nice nickname btw :) )
@freebrowser1 FYI ^

**Comment by mu-citizen** [comment]
> 

Maybe I'm just too lame, but it's too complicated... what should I dl, how should I install it, what should I type in Terminal or somewhere else... ehhh, I didn't buy a Mac to be more complicated than having a Linux (and yes, I tried to google it, but I could find just complicated things, no simple advice or instruction, what to download and do).

**Comment by mu-citizen** [comment]
> You don't need to be coder - there's enough information to let you google it out. Just install `duti` using either homebrew, macports or fink.

Maybe I'm just too lame, but it's too complicated... what should I dl, how should I install it, what should I type in Terminal or somewhere else... ehhh, I didn't buy a Mac to be more complicated than having a Linux (and yes, I tried to google it, but I could find just complicated things, no simple advice or instruction, what to download and do).

**Comment by mu-citizen** [comment]
> > how should I install it, what should I type in Terminal or somewhere else
> 
> 1. In muCommander, press F12 to start the terminal.
> 2. In the terminal, install Homebrew by running the install command given here: https://brew.sh
> 3. Install the `duti` tool by running the install command given here: https://formulae.brew.sh/formula/duti
> 4. Restart muCommander.

Thanks so much! This is exactly what I was looking for, now "Open with..." works the same as in Finder. Now I'm feel like a hacker. ;) :DDD

**Comment by pskowronek** [comment]
true hacker indeed! :) glad that it worked finally.

**Comment by freebrowser1** [comment]
In Privacy&Security I added that I would run mucommander anyway, so that worked.

And logging in to an sftp server with a private key worked as well !

**Comment by ahadas** [comment]
@freebrowser1 great, good to hear this

**Comment by GH20223** [comment]
Hi,

just wanted to add something.
I followed the instructions from @danielerez :
**So I've just added the Terminal under Settings>Privacy & Security>App Management.
Restarted the Terminal, and then: sudo xattr -cr /Applications/muCommander.app**

After that I had to allow opening mucommander again under:
![Bildschirmfoto 2023-07-11 um 22 27 39](https://github.com/mucommander/mucommander/assets/115704197/61be57b4-95d0-446f-a660-104a61e4437a)


Thanks all for the great tool and support :-)

**Comment by sebastian-lempert** [comment]
> Hi,
> 
> just wanted to add something. I followed the instructions from @danielerez : **So I've just added the Terminal under Settings>Privacy & Security>App Management. Restarted the Terminal, and then: sudo xattr -cr /Applications/muCommander.app**
> 
> After that I had to allow opening mucommander again under: ![Bildschirmfoto 2023-07-11 um 22 27 39](https://user-images.githubusercontent.com/115704197/252790067-61be57b4-95d0-446f-a660-104a61e4437a.png)
> 
> Thanks all for the great tool and support :-)

Unfortunately I don't have this option **Dennoch öffnen** (English: open anyway):

![Bildschirmfoto 2023-07-11 um 22 47 30](https://github.com/mucommander/mucommander/assets/18451267/1a80d7bd-199d-4316-a825-0658197d8b75)

Also (again) I would like to point out that I am on macOS Ventura 13.4.1 (22F82) and if you look at my **Datenschutz & Sicherheit** (English: Privacy & Security) settings than you can see that there is an additional option **Überall** (English: Anywhere) in the section **Apps erlauben, die geladen wurden von** (English: Allow applications downloaded from). My guess is that this option was added in macOS Ventura and that this option probably is used in order to replace the above mentioned option **Dennoch öffnen**?

Another thing that might be worth to be mentioned is the fact that my MacBook is a work computer, which is administered by my employer. This is the reason why the whole section **Apps erlauben, die geladen wurden von** is grayed out (see screenshot above). Nevertheless, since there the option **Überall** is selected everything should be fine I guess. Furthermore I am able to use sudo and to gain administrator rights for a certain period of time. But I am not able to change these grayed out options.

**Comment by GH20223** [comment]
Maybe this video may help you:

https://www.dropbox.com/s/udg8ev1234z32p8/mucommander.mp4?dl=0

**Comment by ahadas** [comment]
> Another thing that might be worth to be mentioned is the fact that my MacBook is a work computer, which is administered by my employer.

that's also the case with @danielerez 's machine

> This is the reason why the whole section **Apps erlauben, die geladen wurden von** is grayed out (see screenshot above).

@danielerez is it the same for you?

**Comment by mrserb** [comment]
You can workaround the problem by using the wget instead of browser to download the file, in that case the "com.apple.quarantine" will not be set.

**Comment by ahadas** [comment]
Documented the post-installation actions that were discussed in this thread in the [readme file](https://github.com/mucommander/mucommander/blob/master/package/readme.txt)

**Comment by czosnkowy666** [comment]
but in general there is plan to have mac os release that is installing without any issues? or it is direction for future to do some hacks to install mucommander?

**Comment by ahadas** [comment]
> but in general there is plan to have mac os release that is installing without any issues? or it is direction for future to do some hacks to install mucommander?

as I [commented elsewhere](https://github.com/mucommander/mucommander/issues/984#issuecomment-1629577576), technically it's possible to sign the dmg as we did before but this requires a developer account and I don't think it is worth its cost. however, if you find it important, you're invited [to sponsor the project](https://github.com/sponsors/mucommander) and when it covers the cost of a developer account, I'd gladly sign the application

**Comment by xenorama** [comment]
> Same for me on macOS Ventura 13.4.1 (22F82).
> 
> In the past [this guide](https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat) helped me when encountering this problem, but unfortunately with muCommander version 1.3.0-1 it doesn't work anymore.
> 
> The same applies for the tip of @rhstanton, so using `sudo xattr -cr /Applications/muCommander` doesn't work for me either.

if you strip the app-path and manually drag/drop the file into the terminal line instead, you'll find that the file suffix '.app' is added to the path, which is when it finally worked for me after initially not working — so feel free to add the suffix and retry

**Comment by pskowronek** [comment]
re-opening to have this bug more visible for people searching a solution.

If you read this - please become Sponsor so we could sign DMG via apple.

**Comment by sebastian-lempert** [comment]
> re-opening to have this bug more visible for people searching a solution.
> 
> If you read this - please become Sponsor so we could sign DMG via apple.

Done, just sponsored $30. 💖 I'm sponsoring mucommander because I am a passionate muCommander user, the muCommander team has been doing a fantastic job for years, and because I want to enable this team to sign the installer for macOS.

**Comment by ahadas** [comment]
thanks @sebastian-lempert and @Andreas0602 for your kind sponsorship!

**Comment by maiemi** [comment]
"my" solution is to press control and klick on muCommander.app. After that, a menu will appear and you can click on "open".This will open the muCommander. Afterwards, the app can be opened with a "normal" double-click as any other app, too. I am running macOS 14.0

**Comment by maciejmiklas** [comment]
What worked for me on Ventura: 13.5.2 

1. Settings -> Privacy & Security -> Full Disk Access: add Terminal here
2. sudo xattr -cr /Applications/muCommander.app

**Comment by sebastian-lempert** [comment]
> "my" solution is to press control and click on muCommander.app. After that, a menu will appear and you can click on "open".This will open the muCommander. This is only necessary at the first time, when you're running muCommander after the installation. Afterwards, the app can be opened with a "normal" double-click as any other app, too. I am running macOS 14.0

In my case, unfortunately, this does not help. As described [earlier](https://github.com/mucommander/mucommander/issues/999#issuecomment-1631517636) my MacBook is a company computer, for which my employer automatically issues policies stating that only signed apps can be launched. I can temporarily get local admin rights, i.e. use sudo, but I still can't override the above mentioned policies. So the only solution for me is to wait for a signed version of muCommander, hence my [donation](https://github.com/mucommander/mucommander/issues/999#issuecomment-1732294958).

**Comment by sebastian-lempert** [comment]
> What worked for me on Ventura: 13.5.2
> 
>     1. Settings -> Privacy & Security -> Full Disk Access: add Terminal here
> 
>     2. sudo xattr -cr /Applications/muCommander.app

Both steps have been reported in this discussion for some users to be working before:

- Step 1 was described [here](https://github.com/mucommander/mucommander/issues/999#issuecomment-1631477235)
- Step 2 was described [here](https://github.com/mucommander/mucommander/issues/999#issuecomment-1628131810)

In my case, unfortunately, this does not help. As described [earlier](https://github.com/mucommander/mucommander/issues/999#issuecomment-1631517636) my MacBook is a company computer, for which my employer automatically issues policies stating that only signed apps can be launched. I can temporarily get local admin rights, i.e. use sudo, but I still can't override the above mentioned policies. So the only solution for me is to wait for a signed version of muCommander, hence my [donation](https://github.com/mucommander/mucommander/issues/999#issuecomment-1732294958).

**Comment by sebastian-lempert** [comment]
> > Same for me on macOS Ventura 13.4.1 (22F82).
> > In the past [this guide](https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat) helped me when encountering this problem, but unfortunately with muCommander version 1.3.0-1 it doesn't work anymore.
> > The same applies for the tip of @rhstanton, so using `sudo xattr -cr /Applications/muCommander` doesn't work for me either.
> 
> if you strip the app-path and manually drag/drop the file into the terminal line instead, you'll find that the file suffix '.app' is added to the path, which is when it finally worked for me after initially not working — so feel free to add the suffix and retry

True, you have to append the file suffix *.app. Of course this is what I did when I tested the above command, but I did not mention it in my posting here.

**Comment by dmetcalfe-work** [comment]
I think I'm having a similar issue to @sebastian-lempert 
I'm running MacOS Sonoma 14.3.1, and I cannot get muCommander to work on my company issued device.

I have tried several different methods of installing, and ran the following commands:
- sudo xattr -cr /Applications/muCommander.app
- sudo xattr -rd com.apple.quarantine /Applications/muCommander.app
- sudo spctl --master-disable (I think this "should" set the system to allow from Everywhere)

However, I still get "muCommander is damaged". My options are not greyed out and I get a password prompt when I click launch here, but it still doesn't work:
![image](https://github.com/mucommander/mucommander/assets/76944419/3a1005d5-8e8f-4820-93bf-c5ef2978b96c)

**Comment by ffays** [comment]
The version 1.3.0-1 is x86_64 only, would it be possible to create an arm64 version as well?

Cf.
```zsh
% lipo -archs /Applications/muCommander.app/Contents/MacOS/muCommander 
x86_64
```

**Comment by ffays** [comment]
Here are the build instructions for Apple Mac silicon with arm64 CPU architecture (assuming you already have JDK 17 installed):

```zsh
git clone --depth 1 https://github.com/mucommander/mucommander.git
cd mucommander
export JAVA_HOME=$(/usr/libexec/java_home -v 17 | head -1)
jlink --add-modules $(java --list-modules | cut -d '@' -f 1 | tr '\n' ',' | sed 's/,$//') --output jre/macOS/$(uname -m) --compress=2
./gradlew -Parch=$(uname -m) dmg
open ./build/distributions/muCommander-*.dmg
```

**Comment by jonelo** [comment]
I also got the error message "macOS install: "muCommander" is damaged and can't be opened" on a x64 Mac running Sonoma 14.4.1. As a workaround I installed the JDK 21 LTS from [adoptium.net ](https://adoptium.net/), opened a terminal and simply entered

```
java -jar /Applications/muCommander.app/Contents/app/mucommander-1.3.0.jar
```
to make it running. A JRE is also fine, but make sure to select the correct binaries for your architecture. Select aarch64 if you use an Apple silicon, select x64 if you use an Intel Mac.

**Comment by ahadas** [comment]
@ffays the [nightly builds](https://github.com/mucommander/mucommander/actions/workflows/nightly.yml) already produce a dmg for aarch64, version 1.4.0 will also include it

**Comment by sebastian-lempert** [comment]
@ahadas: Thank you very much for this fix. I just went to the [nightly builds](https://github.com/mucommander/mucommander/actions/runs/8871665605) and downloaded the most recent version [mucommander-1.5.0-snapshot-x86_64.dmg](https://github.com/mucommander/mucommander/actions/runs/8871665605/artifacts/1455103232): I could install and run it by just opening the *.dmg file and extract the muCommander.app to the applications folder and afterwards by simply running it on my MacBook, which is a company computer, for which my employer automatically issues policies stating that only signed apps can be launched! Thus, with your new fix that creates signed *.dmg files no additional settings / workarounds / command line arguments were needed in order to install and run muCommander!

**Comment by ahadas** [comment]
@sebastian-lempert great to read this, thanks for the confirmation! just note that by using a nightly version you won't get updates when new versions are released so I'd recommend to install v1.4.0 once it's released

**Comment by sebastian-lempert** [comment]
@ahadas: Thanks for your above information regarding v1.4.0. I just downloaded this official release including the fixes that were already included in the nightly build mentioned above and can confirm that it works as well without a hassle! Again: thank you very much for this fix!

**Comment by ahadas** [comment]
Version 1.4.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.4.0-1)
